[dino.bin 로또 미션 1단계 PR입니다.]
NewKrew2021/java-lotto-kakao pull request #1
Opened 2021-01-07 09:54 UTC by kommadot

## 요약
- LottoNumber는 팩토리 메서드 패턴으로 만들어져 있는 번호들을 Lotto가 관리합니다.
- Lottos는 Lotto들을 관리하는 일급컬렉션으로 사용되며, 로또 번호 추첨 및 결과 반환을 담당합니다.
- WinningNumber는 사용자가 입력한 당첨번호를 저장하는 클래스로 사용됩니다.
- Statistics는 로또 결과를 전달받아 통계를 구성하는 역할을 합니다.

## 질문
1. 추첨기능이 엮여있는 클래스가 많아서 구현에 복잡함이 많았습니다. 일급컬렉션에 getter를 최대한 지양하려다보니 많이 돌아가게 되었는데 효율적인 방법이 있을까요?
2. 상수같은 경우 Static final 필드로 선언을 지향했는데 어느정도 선까지 변경을 해야하나요? lottos 클래스의 getRank부분에 상수가 들어가는데 이부분도 상수 필드로 변경해야할까요?
3. 라이브러리를 사용하다보니 리턴타입이 원하는 타입이 아니라 강제형변환을 몇번 사용하였는데, 클린코드적으로 문제가 없을까요?
4. 함수명 네이밍에 꽤 많은 고민을 하게되는데 꿀팁이 있을까요?

2021-01-07 11:00 UTC, javajigi commented on src/main/java/lotto/domain/Lotto.java
> +    public Lotto() {
`this(new RandomNumberGenerator());`와 같이 구현해 중복을 제거하는 것은 어떨까?

2021-01-07 13:37 UTC, dongjoon1251 requested changes
안녕하세요. 로또 미션 리뷰를 맡게 된 제노스입니다.
미션을 수행하시면서 열심히 고민하신 흔적들이 많이 보이네요 👍 
질문에 대한 답변은 아래와 같습니다. 제가 남긴 리뷰 코멘트도 같이 확인 부탁드려요 :)

1. 추첨기능이 엮여있는 클래스가 많아서 구현에 복잡함이 많았습니다. 일급컬렉션에 getter를 최대한 지양하려다보니 많이 돌아가게 되었는데 효율적인 방법이 있을까요?
- 말씀하신 코드의 복잡도를 줄여나가기 위해서 리팩토링을 수행하게 됩니다. 리팩토링을 하다보면 꼭 필요한 클래스만 남고 필요 없는 클래스들이 삭제 되면서 전보다 더 깔끔해질 수 있습니다. 한번에 깔끔한 코드를 만드는 방법은 없습니다. 동료들과의 토론과 지속적인 리팩토링을 통해서 좀더 나은 코드를 작성한다고 생각해주시면 좋을 것 같습니다 :)

2. 상수같은 경우 Static final 필드로 선언을 지향했는데 어느정도 선까지 변경을 해야하나요? lottos 클래스의 getRank부분에 상수가 들어가는데 이부분도 상수 필드로 변경해야할까요?
- getRank에 관한 로직을 Rank 클래스로 옮기고, Rank 클래스 내의 rank 변수처럼,  count, bonusCount 등을 변수로 가지도록 수정해보면 어떨까요?

3. 라이브러리를 사용하다보니 리턴타입이 원하는 타입이 아니라 강제형변환을 몇번 사용하였는데, 클린코드적으로 문제가 없을까요?
- 외부에서 필요한 DTO 형태로 변환하는 것은 변수를 그대로 넘겨주는 getter 메소드를 지양하기 위해서 필요한 부분이라고 생각됩니다. 크게 문제가 되는것으로 보이진 않습니다. 

4. 함수명 네이밍에 꽤 많은 고민을 하게되는데 꿀팁이 있을까요?
- 꿀팁이 있다면 저도 알고싶네요ㅎㅎ 항상 어려운 문제 같습니다. '클린 코드'책에 보면 메소드는 동사, 변수는 명사로 지정하도록 대략적인 가이드가 나와 있긴 합니다. 네이밍은 해당 도메인에 대한 지식을 쌓아가면서 점점 더 능숙해지는 것 같습니다. 네이밍에 대한 고민을 해주신것이 코드에서 보입니다. 지금처럼 단순히 get, set 등으로 표현하기 보다 최대한 메소드의 의미를 고민해서 미션을 수행하시다보면 마음에 드는 네이밍을 찾을 수 있어 보입니다. :)

2021-01-07 13:37 UTC, dongjoon1251 commented on README
> +# 로또
TODO list를 잘 작성해주셨네요 :)
다만, README.md 만 있는게 어떨까요?

2021-01-07 13:37 UTC, dongjoon1251 commented on src/main/java/lotto/LottoMain.java
> +    public static void main(String[] args) {
main 함수가 LottoController 내부에 있으면 별도로 LottoController를 생성하지 않아도 되지 않을까요?

2021-01-07 13:37 UTC, dongjoon1251 commented on src/main/java/lotto/controller/LottoController.java
> +        lottoNumberGenerator = new RandomNumberGenerator();
둘다 멤버 변수를 파라미터로 받을 필요가 없다면 객체 생성없이 static method를 호출해서 사용하면 어떨까요?

2021-01-07 13:37 UTC, dongjoon1251 commented on src/main/java/lotto/controller/LottoController.java
> +    private Money money;
해당 클래스로 객체를 생성할 때 파라미터로 받지 않는다면 그냥 로컬 변수로 사용하는게 어떨까요?

2021-01-07 13:37 UTC, dongjoon1251 commented on src/main/java/lotto/util/RandomNumberGenerator.java
> +            numbers.add(random.nextInt(RANGE) + 1);
정말 운이 없다면 무한루프가 될 수 있을 것 같습니다. 미션수행 조건에 나와있듯이 '로또 자동 생성은 Collections.shuffle() 메소드 활용한다.'를 염두에 두고 다시 작성해보면 어떨까요?

2021-01-07 13:37 UTC, dongjoon1251 commented on src/main/java/lotto/util/LottoNumberGenerator.java
> +public interface LottoNumberGenerator {
인터페이스로 꼭 나누어야 하는지는 의문이 있습니다.

2021-01-07 13:37 UTC, dongjoon1251 commented on src/main/java/lotto/util/FixNumberGenerator.java
> +    @Override
이부분은 코드에서 사용되지 않는 것 같습니다. 사용되지 않는 코드는 삭제해주세요 :)

2021-01-07 13:37 UTC, dongjoon1251 commented on src/main/java/lotto/controller/LottoController.java
> +        List<Lotto> listLottos = new ArrayList<>();
Lottos 생성자로 Money를 전달받는것이 어떨까요?

2021-01-07 13:37 UTC, dongjoon1251 commented on src/main/java/lotto/controller/LottoController.java
> +    }
winningNumberText, bonusNumber를 LotteryMachine을 통해서 WinningNumber, LottoNumber로 변환한 후에 다시 꺼내는 것으로 보입니다. 그냥 바로 현재 메소드에서 생성해서 넘겨주면 어떨까요? 그리고 WinningNumber는 결국 6개의 LottoNumber라서 Lotto로 볼 수도 있지 않을까요? :)

2021-01-07 13:37 UTC, dongjoon1251 commented on src/main/java/lotto/domain/LotteryMachine.java
> +        if (num > MAX_VALUE || num < MIN_VALUE) {
LottoNumber에 대한 검증 로직으로 보입니다. LottoNumber of 메소드 내부에서 처리하면 어떨까요?
그러면 MAX_VALUE, MIN_VALUE도 한곳에만 정의할 수 있지 않을까요?

2021-01-07 13:37 UTC, dongjoon1251 commented on src/main/java/lotto/domain/LotteryMachine.java
> +    public static final int MIN_VALUE = 1;
상수이긴 하지만 외부에서 사용되지 않는다면 private으로 사용해주세요 :)

2021-01-07 13:37 UTC, dongjoon1251 commented on src/main/java/lotto/controller/LottoController.java
> +        lottoUI.printStatistics(statistics.toString(), statistics.getProfitRate(money));
toString 메소드를 주로 사용해서 출력 로직을 구현하신 것으로 보입니다. 출력에 관한 코드는 UI 클래스에서 처리하도록 수정해보면 어떨까요?

2021-01-07 13:37 UTC, dongjoon1251 commented on src/main/java/lotto/controller/LottoController.java
> +        Statistics statistics = new Statistics(lottos.raffle(lotteryMachine.getWinningNumber(),lotteryMachine.getBonusNumber()));
raffle 메소드 이름 좋네요 👍 
raffle 메소드의 리턴값이 Statistics가 되면 어떨까요?

2021-01-07 13:37 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Lottos.java
> +    public int getNumOfLotto() {
미션 가이드에 나외있듯이 num이라는 축약형 보다는 count나 number로 표현해주세요 :)

2021-01-07 13:37 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Lottos.java
> +    private Rank getRank(int count, int bonusCount) {
해당 로직은 Rank 내부에 정의하면 어떨까요?

2021-01-07 13:37 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Lottos.java
> +            int bonusCount = lotto.isContain(bonusNumber) ? 1 : 0;
int bonusCount 가 아니라  boolean 타입 변수로 정의해보면 어떨까요?

2021-01-07 13:37 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Money.java
> +            throw new IllegalArgumentException("천원 이상의 금액을 입력해 주세요");
예외 클래스를 직접 만들어서 사용해보면 어떨까요?

2021-01-07 13:37 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Money.java
> +    private static final int LOTTO_PRICE = 1000;
로또의 가격은 Lotto 클래스에 있는게 어떨까요? 다른 도메인들이 추가될때마다 Money 클래스에 비슷한 상수가 추가되면 너무 비대해지지 않을까요?

2021-01-07 13:37 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Rank.java
> +    FIRST(1),
enum 클래스를 잘 정의해주셨네요 💯

2021-01-07 13:37 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Statistics.java
> +    public void addRank(Rank rank) {
이 메소드는 테스트 코드 말고는 사용되는 곳이 없는데 어떤 의도이신가요? 테스트를 위한 생성자를 추가해서 테스트 코드를 작성해보면 어떨까요?

2021-01-07 13:37 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Statistics.java
> +        sb.append(String.format("3개 일치 (5000원)- %d개\n", rankings.getRank(Rank.FIFTH)));
Rank.FIFTH.getRank() 로 표현해보는 건 어떨까요? :)
그리고 해당 메소드는 출력에 관련된 로직으로 보입니다.

2021-01-07 13:37 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Statistics.java
> +        return Rank.stream().mapToLong(this::getProfitPerRank).sum();
stream()을 사용하실 땐 가독성을 위해서 한 라인에 한 포인트만 나오도록 아래와 같이 작성해주세요~
Rank.stream().
    mapToLong(...)

2021-01-07 13:37 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Rankings.java
> +
해당 클래스의 역할이 모호합니다. Statistics 클래스에서 다 처리하도록 수정해보면 어떨까요?

2021-01-07 13:37 UTC, dongjoon1251 commented on src/main/java/lotto/view/LottoUI.java
> +        System.out.println("구입금액을 입력해 주세요.");
문자열도 상수로 분리해보면 어떨까요?

2021-01-07 13:37 UTC, dongjoon1251 commented on src/test/java/lotto/domain/LottosTest.java
> +        WinningNumber w = new WinningNumber(Set.of(LottoNumber.of(1),
하나의 테스트 메소드 안에는 최대한 assert구문을 하나만 넣어야 하는데 이부분을 잘 지켜주셨네요 👍 
추가로, test code는 given/when/then 패턴에 맞춰서 줄바꿈으로 분리해주시면 가독성이 좋아질 수 있습니다.

2021-01-07 13:37 UTC, dongjoon1251 commented on src/test/java/lotto/util/RandomNumberTest.java
> +        randomNumberGenerator.getNumbers().stream().forEach(num -> assertThat(num).isBetween(1,45));
해당 테스트가 꼭 필요한지 한번더 고민해주시기 바랍니다.

2021-01-08 04:38 UTC, kommadot commented on src/main/java/lotto/util/LottoNumberGenerator.java
> +public interface LottoNumberGenerator {
테스트를 용이하게 하기 위해서 인터페이스로 나눴습니다.
랜덤한 결과가 아닌 고정적 결과를 입력하고 싶을때를 위해서요..
혹시 다른 방법이 있을까요?

2021-01-08 05:47 UTC, kommadot commented on src/main/java/lotto/domain/Rankings.java
> +
일급 컬렉션의 용도로서 분리한건데 합치는게 나을까요??

2021-01-08 09:46 UTC, kommadot commented on src/main/java/lotto/controller/LottoController.java
> +        List<Lotto> listLottos = new ArrayList<>();
일급컬렉션이 사용자의 자금에 대해 알필요가 있을까? 해서 따로 넘겨 받진 않았는데
혹시 다른 이유가 있을까요?

2021-01-08 09:48 UTC, kommadot commented on src/main/java/lotto/domain/Statistics.java
> +        sb.append(String.format("3개 일치 (5000원)- %d개\n", rankings.getRank(Rank.FIFTH)));
이 구문은 해당 랭크에 당첨된 복권의 수에 대한 부분입니다.
제가 메소드명을 좀 애매하게 사용해서 메소드명 변경하였습니다!

2021-01-08 09:56 UTC, kommadot commented
## 질문
1. Rank클래스에 else if로 변경을 했는데 오히려 더 보기 좋은 코드일까요? 아니면 오히려 보기 안좋아진 코드일까요?
2. UI클래스를 대부분 static으로 구현했는데 이런식으로 사용하는편이 좋을거라 생각해서.. 괜찮은 방법 인가요?
3. LottoController class의 buyLotto 메소드에서 stream을 배우고 나니 객체생성에 for문을 별로 사용하고 싶지 않아서 Stream으로 억지로 만들긴했는데 오히려 보기 안좋아진게 아닐까 의문이 듭니다.
4. MVC패턴으로 구현하니 View는 출력을 담당하고 Controller는 단순 정보 전달 정도로만 사용되고 핵심적인 로직들은 Domain이라는 패키지에 존재합니다. 저는 Domain == Dto라고 생각해왔어서 Controller에서 핵심로직을 담당해야하지 않나? 라는 의문이 드는데 지금의 구조처럼 Domain이 비즈니스 로직을 담당하는게 원래 맞는 방식인것이죠?

## 감사합니다.

2021-01-11 00:29 UTC, dongjoon1251 commented on src/main/java/lotto/util/LottoNumberGenerator.java
> +public interface LottoNumberGenerator {
말씀해주신 것처럼 향후 확장성 측면에서는 미리 인터페이스를 분리하는 방법도 맞습니다 :)
다만, 실제로 변화가 생기지 않는 부분을 인터페이스로 분리하면 오버엔지니어링이 될수도 있습니다. 
이부분은 정답이 있는 건 아니고 tradeoff가 있으니 그때그때 상황에 맞춰서 적용해주시면 됩니다.

2021-01-11 00:31 UTC, dongjoon1251 commented on src/main/java/lotto/controller/LottoController.java
> +        List<Lotto> listLottos = new ArrayList<>();
사용자의 자금인 것까지는 몰라도 되지만 돈을 주고 Lotto를 사는 관점으로 보면 어색해보이진 않습니다. 
새로 풀리퀘 주신 코드에서 getLottoPrice() getter가 생겼는데 이런 부분들은 Money를 생성자에서 입력받으면 해결될 수 있지 않을까요?

2021-01-11 00:44 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Rankings.java
> +
Statistics 생성자에서 필요한 변수가 rankings 하나라서 Statistics 자체가 일급컬렉션 역할을 할 수 있어보입니다.

2021-01-11 01:17 UTC, dongjoon1251 approved these changes
피드백을 잘 반영해주셨네요 :)
몇가지 코멘트를 드렸으니 다음 단계 pull request에서 적용 부탁드립니다.
질문주신 부분에 대한 답변은 아래와 같습니다.

1. else if에서 사용하는 정보를 해당 클래스 자체에서 가지고 있다면 stream으로 변환해볼 수 있지 않을까요?
2. UI 클래스 자체적으로 내부 필드를 가지는 것이 아니라서 static으로 구현하셔도 무방해보입니다.
3. Money를 생성자 파라미터로 넘겨주면 controller에서이 복잡도가 줄어들 것으로 보입니다. stream이라서 복잡해보인다기보다 로직이 조금씩 중복되어있어서 그런 것 같습니다.
4. Controller에서 핵심 로직을 담당하게 되면 그 로직을 테스트하기가 더 어려워질 수 있습니다. 이부분은 로직 위치를 controller로 바꾸고 테스트 코드를 작성해보려고 시도해보시면 좀더 잘 와닿으실수 있습니다.
5. 그럴 땐 동료들에게 의견을 묻고 방향을 결정해보는 것이 좋습니다. 꼭 정보를 남겨야 한다면 주석보다는 README.md나 관련 위키에 잘 정리된 문서로 남기는 것이 더 좋습니다.

2021-01-11 01:17 UTC, dongjoon1251 commented on src/main/java/lotto/domain/LottoNumber.java
> +            throw new OutOfRangeException("잘못된 숫자를 입력하셨습니다.");
오류에 대한 메시지는 새로 생성한 예외 클래스 내부에서 가지면 어떨까요?

2021-01-11 01:17 UTC, dongjoon1251 commented on src/main/java/lotto/domain/LottoReward.java
> +
LottoReward 정보는 Rank와 연결되는 정보로 보입니다. Rank에서 reward 정보를 함께 가지게 하면 어떨까요?

2021-01-11 01:17 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Rank.java
> +        if (count == 6) {
각 rank 별로 count, bonuxCount에 대한 정보를 미리 가지고 있으면, stream 을 사용해서 리팩토링할 수 있지 않을까요?

2021-01-11 01:17 UTC, dongjoon1251 commented on src/main/java/lotto/controller/LottoController.java
> +                .mapToObj(num -> new Lotto(new LinkedHashSet<>(randomNumberGenerator
Lotto에 lottoNumberGenerator를 받아서 생성하는 부분로 로직이 중복되어 보입니다.

2021-01-11 01:17 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Lotto.java
> +    private static final int LOTTO_PRICE = 1000;
상수는 맨 위에 정의해주세요 :)

2021-01-11 01:17 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Lotto.java
> +    public LottoDto getLottoData() {
Dto와 원래 도메인에 가지는 정보가 같다면 도메인 클래스 자체를 리턴해도 무방해보입니다 :)

2021-01-11 01:17 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Lotto.java
> +    public static int getLottoPrice() {
상수가 외부에서 필요로 한다면 public으로 접근 제어자를 변경하는 것이 어떨까요? 그리고 price에 대한 getter를 사용하지 않을 수 있는 방법은 혹시 없을지 고민해주시기 바랍니다 :)

2021-01-11 01:17 UTC, dongjoon1251 commented on src/main/java/lotto/util/RandomNumberGenerator.java
> +
로또 숫자의 최대 최소값에 대한 LottoNumber에서 가지는 정보와 중복으로 보입니다.

2021-01-11 01:17 UTC, dongjoon1251 commented on src/main/java/lotto/view/LottoUI.java
> +    public static final String RANK_FIFTH_TEXT = "3개 일치 (%d원)- %d개\n";
%d 개 일치로 포맷을 바꾸면 어떨까요?

2021-01-11 01:17 UTC, dongjoon1251 commented on src/main/java/lotto/controller/LottoController.java
> +        lottoController.matchLotto();
해당 클래스 내의 메소드 호출이라서 객체를 만들지 않아도 되지 않을까요?

2021-01-11 01:17 UTC, dongjoon1251 commented on src/main/java/lotto/domain/WinningLotto.java
> +        super(new RandomNumberGenerator());
super() 를 호출하면 어떨까요?

2021-01-11 01:17 UTC, dongjoon1251 commented on src/main/java/lotto/domain/WinningLotto.java
> +    }
해당 클래스와 Lotto의 차이점은 이 메소드인데 이 부분은 Lotto에서 가지고 있어도 되지 않을까요?

2021-01-11 01:17 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Lotto.java
> +    public boolean isContain(LottoNumber lottoNumber) {
lottoNumbers.contains와 맞추어서 contains라고 명명하면 어떨까요?

2021-01-11 01:17 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Rank.java
> +    public static Rank checkRank(int count, boolean bonusCount) {
메소드명으로 find는 어떨까요?

2021-01-11 01:17 UTC, dongjoon1251 commented on src/main/java/lotto/domain/LottosDto.java
> +
DTO를 따로 만들어 주셨네요 👍 
다만, 내부이 필드가 도메인과 거의 동일하다면 도메인을 그대로 리턴해주는건 어떨까요?

2021-01-11 01:17 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Rankings.java
> +            rankings.putIfAbsent(rank, 0);
외부에서 전달받은 rankings의 데이터를 수정하지 않고 적용하는 방법을 고민해보면 어떨까요?

2021-01-11 01:18 UTC, merged