[eli.nabro] 로또 step1 코드리뷰 요청드립니다.
NewKrew2021/java-lotto-kakao pull request #12
Opened 2021-01-08 06:27 UTC by maireneu

로또 자동 step1을 구현하였습니다.

domain
- LottoNo - 로또 번호 객체
- LottoTicket - 로또 티켓 객체
- WinningLottoNos - 당첨 로또 번호 객체
- LottoLogic - 로또 구입,  당첨로또와 매칭
- StatisticsResult - 매칭 결과 객체

view
- LottoInputView - Input UI view
- LottoOutputView - Output UI view

기타
StatisticsType - 로또 당첨 갯수 enum
LottoGameMain - main 함수

리뷰 잘 부탁드립니다!

질문이 한가지 있습니다. 
여러 domain, view 등 여러 곳에서 사용하는 상수값은 어디에 선언하는게 좋을까요?
가령 LottoTicket 가격은 LottoTicket 에 public static 상수로 선언하였는데요,
아예 상수 모음 class를 하나 만들까 고민도 하였습니다. 더 좋은 방법이 있을까요?

감사합니다.

2021-01-08 11:32 UTC, limmmee-bonjour requested changes
안녕하세요 일라이! 로또 미션을 함께하게된 벨입니다 😄 
코드리뷰 주신 부분 잘 보았습니다. 기능 명세와 커밋로그들이 잘 정리되어있어 코드리뷰하는데 수월했어요. 👍 
그런데 코드의 관심사들이 흩어져있고 테스트 케이스 의도가 불분명합니다.
관련해서 리뷰 드렸습니다 :) 이번 리뷰는 Request changes 드릴게요.
[도전!] 이라고 코멘트 단 부분은 고민하셔서 꼭 수정해주시길 바라요!
궁금하신 점이 있으시면 언제든 DM 보내주세요. 그럼 화이팅입니다!

2021-01-08 11:32 UTC, limmmee-bonjour commented on README.md
> +## 기능 명세
기능 명세 잘 정리해주셨습니다 👍

2021-01-08 11:32 UTC, limmmee-bonjour commented on src/main/java/lotto/view/LottoInputView.java
> +        int count = Integer.parseInt(sc.nextLine()) / LottoTicket.LOTTO_PRICE;
1. 중복 되는 코드네요. 하나의 메서드로 중복을 없애주세요! (되도록이면 중복이 없는 코드가 좋습니다:))
```
Integer.parseInt(sc.nextLine()) / LottoTicket.LOTTO_PRICE;
```

2. inputMoney 에서 "빈값, 문자(a)"가 들어온다면 어떻게될까요?
기본적인 예외 사항에 대해서는 validation 체크를 해주는 것이 좋습니다 :) 
테스트케이스에 이와같은 테스트 코드가 추가되면 좋겠죠? 
테스트 케이스는 성공 케이스보다는 항상 실패 케이스에 대해 고민해보아야 해요 :)

2021-01-08 11:32 UTC, limmmee-bonjour commented on src/main/java/lotto/view/LottoInputView.java
> +            LottoTicket lottoTicket = new LottoTicket(nums);
생성자로 레퍼런스 객체를 만들면서 validation 체크를 하네요!
게다가 레퍼런스 객체는 사용되어지지도 않구요. 불필요한 레퍼런스 객체를 만드는 것은 좋지 않습니다.
일반적으로 입력 / 도메인에서 이중으로 validation 체크를 하는 것이 좋습니다 :)
LottoInputView가 너무 커진다면 입력에 대한 validation class를 만드는것도 좋겠죠~?

2021-01-08 11:32 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/WinningLottoNos.java
> +        }
WinningLottoNos를 만들면서 로또번호, 보너스번호에 중복이 없는지를 체킹하고 있네요~
입력시 이미 해당 이슈를 알고 있지 않을까요?
게다가 Exception에는 에러 메세지도 존재하지 않네요~ 보통 Exception을 던질때는 그에 맞는 메세지를 꼭 적어주어야 합니다!

입력시 로또번호, 보너스번호를 한번에 받고, 중복되는지 validation 체크를 한후 DTO로 넘겨주는건 어떨까요?
그러면 입력 / 도메인 관계가 조금 더 느슨해지겠죠?

함께 읽어보면 좋은 글 : [DTO](https://ijbgo.tistory.com/9)

2021-01-08 11:32 UTC, limmmee-bonjour commented on src/main/java/lotto/StatisticsType.java
> +public enum StatisticsType {
로또 당첨과 관련된 Enum을 만들어주셨네요 👍 
그런데 StatisticsType은 조금 애매한 도메인이예요!
로또가 당첨번호와 몇개가 일치하는지 여부를 나타내는 enum으로 사용되어질 것 같은데 현재 도메인은 단지 이름만을 가지고 있고 필요한 기능들이 여기저기 산재해 있는 것 같아요!

만약 StatisticsType의 네이밍이 달라지거나 당첨 기준이 달라지게되면 
StatisticsType Enum 뿐 아니라  
StatisticsResult-priceHash,  WinningLottoNos-MATCH_TABLE 
총 3군데를 바꿔야겠지요? 관련되어있는 기능이 여기저기 뒤죽박죽 섞어있어요 :)

[ 도전! ] 해당 Enum을 로또 랭킹(?)용 enum으로 만들어보는건 어때요
여기서 등수에 따라 당첨금도 가지고 있고 또 등수도 알수 있구요! 도메인 기능을 한 곳으로 모아봅시다 :) :muscle:

2021-01-08 11:32 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/LottoLogic.java
> +    }
로또 번호를 LottoLogic 레이어(Service)에서 만들어주시고 있네요~
이번 과제는 객체지향 설계를 경험하는 것이니 만큼 한번 고민해봅시다 :)

[ 도전! ] 만약 자동로또번호가 아닌 다른방법으로 로또번호가 만들어지면 어떻게될까요?
해당 부분을 다 바꾸어야할거예요! LottoTicket은 그냥 로또만드는방법 인터페이스를 가지고 와서 번호만 생성하면 되니까요!
만드는 과정은 다른 아이로 넘겨 버립니다.
게다가 지금 구조는 유연하지 못하여 변경에 취약해요!
[이 글](https://velog.io/@kyle/%EB%94%94%EC%9E%90%EC%9D%B8-%ED%8C%A8%ED%84%B4-%EC%A0%84%EB%9E%B5%ED%8C%A8%ED%84%B4%EC%9D%B4%EB%9E%80)을 보시면서 어떻게 유연하게 변경할 수 있을지 고민해 보아요 :) 추가로 로또 만드는 방법은 다 새로운 객체로 넘겨버립니다.

2021-01-08 11:32 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/LottoNo.java
> +public class LottoNo implements Comparable<LottoNo>{
LottoNo라는 일급객체를 만들어주셨네요 좋습니다 💯

2021-01-08 11:32 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/LottoNo.java
> +            throw new IllegalArgumentException();
Exception이 발생하면 이유를 알고싶어요! 적절한 메세지를 추가해주세요 :)

2021-01-08 11:32 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/LottoTicket.java
> +    List<LottoNo> numbers = new ArrayList<>();
도메인 멤버변수가 public하게 존재하네요. 이렇게 되면 여기저기서 모두 numbers를 참조할 수 있을거예요!
보통 도메인의 멤버 변수는 private final 하게 만들어줍니다.
기본값이 있더라도 생성자에서 셋팅해주고요 :) 

[ 도전! ] 도메인의 멤버변수를 (큰 이유가 없다면) private final로 만들어주세요

2021-01-08 11:32 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/LottoTicket.java
> +        HashSet<Integer> set = new HashSet<>(numbers);
로또 번호가 중복인지 체크를 하고 있네요 :) 
numbers자체를 Set으로 쓰면 안될까요? List로 쓰신 이유가 있을까요~?

2021-01-08 11:32 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/WinningLottoNos.java
> +    private LottoTicket lottoTicket;
도메인적으로 생각해보면 당첨된 로또 티켓을 가지고있는걸까요?
그냥 단순히 **로또 당첨 번호**일것 같은데요 :)  
LottoTicket은 내가 산 로또 디켓인데 당첨번호와 의미가 섞여져 있네요.
그래서 LottoTicket-matchTickets() 메서드도 내가 산 로또와 비교하는것인가? 라고 착각할 것 같습니다.
네이밍이나 타입을 좀 더 명확하게 하는 것이 좋습니다 :)

만약 확률에 따른 LottoTicket이 만들어지게된다면 (요구사항은 LottoTicket에 가격과 확률을 높이는 멤버변수가 추가됩니다)
이는 WinningLottoNos까지 영향이 있어야할까요~? 고민해 보면 좋을것같아요 :)

2021-01-08 11:32 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/WinningLottoNos.java
> +    }};
이 부분은 위에서도 의견 드렸지만 여기에 있는 것은 이상해보여요~ 옮겨봅시다 :)!

2021-01-08 11:32 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/StatisticsResult.java
> +    }
위에 의견 드린것처럼 이부분도 옮겨 봅시다 :)

2021-01-08 11:32 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/StatisticsResult.java
> +    public double benefit() {
합계, 평균에 대한 동작이 하나의 메소드에 존재하네요 :) 분리해봅시다~!

2021-01-08 11:32 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/WinningLottoNos.java
> +    private StatisticsType checkType(int matchCount, boolean isBonusMatch) {
이 부분도 나중에는 다른 곳에 위치하게 되겠죠 😄

2021-01-08 11:32 UTC, limmmee-bonjour commented on src/test/java/lotto/domain/LottoLogicTest.java
> +public class LottoLogicTest {
보통 테스트는 구현 클래스 패키지를 따릅니다!
추가로 (적절한 곳을 찾지 못해^^) 코드시 mac 버전 cmd+option+L 을 하면 포맷팅이 되어 깔끔한 코드가 됩니다 :)
[ 도전! ] 테스트 클래스도 구현 클래스 패키지와 동일한 위치에 위치시켜주세요 :)

2021-01-08 11:32 UTC, limmmee-bonjour commented on src/test/java/lotto/domain/LottoNoTest.java
> +        LottoNo lottoNo1 = new LottoNo(1);
이렇게 테스트하게되면 불필요한 레퍼런스 객체가 생성되겠죠?
생성자 내에 validation을 메소드 분리해서 validation 을 테스트하는것이 더 좋아보입니다 :)

2021-01-08 11:32 UTC, limmmee-bonjour commented on src/test/java/lotto/domain/LottoNoTest.java
> +    void lottoEqualTest(){
생성자 테스트를 좋은 방법으로 잘 해주셨어요 💯 👍

2021-01-08 11:32 UTC, limmmee-bonjour commented on src/test/java/lotto/domain/LottoTicketTest.java
> +public class LottoTicketTest {
matchTickets 에 대한 테스트케이스가 누락되었네요. 
열려있는 메소드에 대해서는 모두 테스트케이스를 작성해주시는게 좋아요! 😉

2021-01-08 11:32 UTC, limmmee-bonjour commented on src/test/java/lotto/domain/StatisticsResultTest.java
> +    void benefitTest() {
Junit5에는 굉장히 다양한 테스트 어노테이션들이 추가되었습니다!
[해당 글](https://www.baeldung.com/parameterized-tests-junit-5)을 읽어보시면 추후 노가다? 없이 (ㅎㅎ) 간결한 테스트 케이스를 작성하실 수 있으실 거예요!
@CsvSource를 하용해서 테스트케이스를 좀 더 간결하게 만들어볼까요?!

2021-01-08 11:32 UTC, limmmee-bonjour commented on src/test/java/lotto/domain/LottoLogicTest.java
> +    void statisticTest() {
전체적으로 테스트케이스가 어떤 테스트를 목적으로하는지 모호합니다.
보통 테스트케이스에서는 given - when -then이 명확하게 나타나야 합니다. 
해당 케이스에서는 생성자로 LottoTicket를 만들고 어떤것을 테스트하고싶은지 명확하게 나와있지 않아요

[ 도전! ] 아래 글을 참고하셔서 명확한 테스트케이스를 만들어주세요 :) @DisplayName도 붙여주시면 좋을 것 같아요 :) 
참고하면 좋은 글 : [given-when-then 패턴](https://brunch.co.kr/@springboot/292)

2021-01-08 11:32 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/LottoTicket.java
> +    public static final int LOTTO_PRICE = 1000;
Q. 여러 domain, view 등 여러 곳에서 사용하는 상수값은 어디에 선언하는게 좋을까요?
가령 LottoTicket 가격은 LottoTicket 에 public static 상수로 선언하였는데요,
아예 상수 모음 class를 하나 만들까 고민도 하였습니다. 더 좋은 방법이 있을까요?
A. 상수는 웬만하면 도메인 또는 Service로직과 가까이 붙어있는게 좋다고 생각합니다 :)
도메인 내에 상수는 보통 핵심 규칙일 경우가 많은데요 (로또의 금액은 1000원) 이게 상수화 모음 class에 있다면 LottoTicket 도메인의 핵심 규칙이 한눈에 보이지 않을 거예요. 보통 중복이 된다해도 정말 중복이 많지 않은 경우 저는 각 도메인에 셋팅해줍니다.
또는 일라이가 구현해주신대로 public 하게 사용되어도 괜찮을 것 같아요 :)
사실 지금은 입력 부분과 도메인 내의 상수화가 중복이라 이런 경우는 각각 따로 정의해주어도 괜찮을 것 같아요 :)

2021-01-08 11:32 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/LottoNo.java
> +        if( number < 1 || number > 45 ) {
클래스 내에서 상수화 해줄 수 있는 값들은 상수화 해주는게 좋을 것같습니다 :)
물론 중복이나 static 변수로 만들기 위해 상수화를 많이 하지만
1보다는 MIN_SIZE와 같이 네이밍을 주어 그 의도를 나타내는게 코드상에서는 더 가독성 높은 코드를 만들 수 있다고 생각합니다 :)

2021-01-12 04:26 UTC, maireneu commented on README.md
> +## 기능 명세
감사합니다. Readme에 파일목록을 추가하였습니다!

2021-01-12 04:26 UTC, maireneu commented on src/main/java/lotto/view/LottoInputView.java
> +        int count = Integer.parseInt(sc.nextLine()) / LottoTicket.LOTTO_PRICE;
중복되는 코드를 하나로 만들고, 문자열이 입력된  경우에 대한 예외처리를 추가하였습니다!

2021-01-12 04:32 UTC, maireneu commented on src/main/java/lotto/view/LottoInputView.java
> +            LottoTicket lottoTicket = new LottoTicket(nums);
해당 유효성검사 코드를 static 메서드로 변경 후, 호출하도록 하여 객체 생성을 방지하였습니다!

각 유효성 검사 갯수가 무척 많진 않고, 해당 객체 클래스 내부에 있는게 더 직관적이라 생각하여 validation class를 따로 작성하지는 않았습니다. 추후 더 많은 유효성 검사가 존재할경우 해당 class를 작성하여 관리하도록 하겠습니다!

2021-01-12 04:42 UTC, maireneu commented on src/main/java/lotto/domain/WinningLottoNos.java
> +        }
1. 입력시에 유효성 검사를 하도록 변경하였습니다.
2. Exception을 던지는 경우, 에러메시지를 print하도록 수정하였습니다!
3. validation check를 static method로 적용하였으나, validation이 많지 않다고 생각하여 DTO까진 구현하지 않았습니다. 추후 유효성검사가 많아질경우 DTO와 validation class를 작성하여 입력/도메인의 의존관계를 낮추도록 하겠습니다!

2021-01-12 04:43 UTC, maireneu commented on src/main/java/lotto/StatisticsType.java
> +public enum StatisticsType {
StatisticsType에서 당첨금액과 match count를 관리하고, match 여부까지 판별하도록 수정하였습니다!
MATH_TABLE과 PriceHash는 삭제하였습니다.

StatisticsType 클래스에서 해당 작업들을 관리하니 훨씬더 직관적인 코드가 된것 같습니다! 감사합니다.

2021-01-12 04:43 UTC, maireneu commented on src/test/java/lotto/domain/LottoTicketTest.java
> +public class LottoTicketTest {
matchTickets 을 포함한 열린 메서드들에 대해서 모두 테스트케이스를 작성하였습니다. 감사합니다!

2021-01-12 04:45 UTC, maireneu commented on src/test/java/lotto/domain/StatisticsResultTest.java
> +    void benefitTest() {
CSV를 효과적으로 parsing하기위해 CsvParsing 클래스를 만들고, CsvSource를 사용하여서 Test input을 관리하도록 수정하였습니다!

2021-01-12 04:47 UTC, maireneu commented on src/test/java/lotto/domain/LottoLogicTest.java
> +    void statisticTest() {
해당 글과 reference를 정독 후, 테스트코드들을 최대한 given / when / then 이 명확하도록 변경하였습니다. 또한 테스트 코드들을 열린 메서드마다 추가하였으며, 직관적인 메서드 명명법으로 바꾸었습니다!

이전보다 신뢰성 높고, 훨씬 가독성 좋은 테스트코드가 된 것 같습니다. 감사합니다!

2021-01-12 04:49 UTC, maireneu commented on src/main/java/lotto/domain/LottoTicket.java
> +    public static final int LOTTO_PRICE = 1000;
답변 정말 감사합니다! 말씀하신대로 추후에도 domain에 가깝게, 그리고 핵심 규칙이 한눈에 보이는 방향으로 상수를 선언하도록 하겠습니다.

2021-01-12 04:50 UTC, maireneu commented on src/main/java/lotto/domain/LottoNo.java
> +        if( number < 1 || number > 45 ) {
해당 부분을 비롯한 상수값에 대해 상수화를 시켰습니다. 피드백 정말 감사합니다!

2021-01-12 07:18 UTC, maireneu commented on src/main/java/lotto/domain/LottoLogic.java
> +    }
아 이부분이 접혀있어서 코멘트가 존재하는지 몰라서 반영이 늦었습니다ㅠ
말씀하신대로 buyingStrategy를 구현하여 전략패턴으로 티켓구입부분을 수정하였습니다!

2021-01-12 07:19 UTC, maireneu commented on src/main/java/lotto/domain/LottoNo.java
> +public class LottoNo implements Comparable<LottoNo>{
감사합니다! 레이싱카에서 배운걸 사용하였습니다 ㅎㅎㅎ

2021-01-12 07:19 UTC, maireneu commented on src/main/java/lotto/domain/LottoNo.java
> +            throw new IllegalArgumentException();
에러메시지를 전부 출력하도록 변경하였습니다!

2021-01-12 07:25 UTC, maireneu commented on src/main/java/lotto/domain/LottoTicket.java
> +    List<LottoNo> numbers = new ArrayList<>();
실수로 말씀하신부분을 누락한것 같습니다 ㅠ

도메인의 멤버변수를 private으로 고치고, 변하는 특수한 경우를 제외하고 전부 final로 수정하였습니다!

2021-01-12 08:11 UTC, maireneu commented on src/main/java/lotto/domain/LottoTicket.java
> +        HashSet<Integer> set = new HashSet<>(numbers);
말씀하신 부분이 맞습니다. 다시 생각해보니 numbers를 input에서 List로 취급할 이유가 없었어요. set으로 전부 교체하여 좀 더 명료하게 변경하였습니다.

2021-01-12 08:12 UTC, maireneu commented on src/main/java/lotto/domain/WinningLottoNos.java
> +    }};
해당 부분을 StatisticsType 부분으로 이동하였습니다! 감사합니다.

2021-01-12 08:13 UTC, maireneu commented on src/main/java/lotto/domain/StatisticsResult.java
> +    }
해당 부분을 StatisticsType 부분으로 이동하였습니다! 감사합니다.

2021-01-12 08:19 UTC, maireneu commented on src/main/java/lotto/domain/StatisticsResult.java
> +    public double benefit() {
benefit 부분을 수익률 계산 yield 로 바꾸고, 합계와 평균 계산을 분리하였습니다. 메서드가 기능단위로 분화되어서 좀더 명료해졌네요!

2021-01-12 08:19 UTC, maireneu commented on src/main/java/lotto/domain/WinningLottoNos.java
> +    private StatisticsType checkType(int matchCount, boolean isBonusMatch) {
해당 부분도 enum 인 StatisticsType으로 이동하였습니다! 감사합니다.

2021-01-12 08:25 UTC, maireneu commented on src/test/java/lotto/domain/LottoNoTest.java
> +        LottoNo lottoNo1 = new LottoNo(1);
생성자 테스트를 validation test로 변경하여 불필요한 객체 생성을 제거하였습니다!

2021-01-12 08:25 UTC, maireneu commented on src/test/java/lotto/domain/LottoNoTest.java
> +    void lottoEqualTest(){
네 정말 감사합니다!
다만 위에서 말씀하신대로 생성자 테스트 대신 validation test로 모두 변경하였습니다!

2021-01-12 08:27 UTC, maireneu commented on src/test/java/lotto/domain/LottoLogicTest.java
> +public class LottoLogicTest {
구현과 테스트의 패키지의 hierarchy 를 동일하게 수정하였습니다.
다만 이것과 별개로.. LottoLogic을 domain으로 넣지않고 controller로 취급해야할까요?

2021-01-12 08:28 UTC, maireneu commented on src/main/java/lotto/domain/LottoNo.java
> +        if( number < 1 || number > 45 ) {
중간에 코멘트가 접힌부분을 놓쳐서ㅠㅠ.. 확인후 중간에 접힌 코멘트 피드백주신 부분 또한 모두 수정하였습니다!

2021-01-12 08:46 UTC, maireneu commented on src/main/java/lotto/domain/WinningLottoNos.java
> +    private LottoTicket lottoTicket;
말씀하신 부분이 맞는것 같습니다. 당첨 복권은 티켓이 아니라 당첨 로또 번호를 갖는 것이고, LottoTicket의 상태와는 독립적이어야 맞습니다. 편의를 위해 LottoTicket으로 하였는데 실수였네요..

WinningLottoTicket을 WinningLottoNos로 변경하고, LottoTicket이 아닌 LottoNos List를 갖도록 하였습니다. 또한 matchTicket는 당첨 복권과 비교하는 것이므로, WinningLottoNos 클래스로 이동하였습니다.

감사합니다!

2021-01-12 10:52 UTC, limmmee-bonjour approved these changes
안녕하세요 일라이 :) 벨입니다!
코멘트 한 부분 잘 반영해주셔서 코드가 깔끔해졌습니다 :) 👍 👏 
추가적으로 코멘트 드렸으니 step2할 때 고민해주시면 좋을 것 같습니다 :) 
궁금하신 점이 있다면 언제든 DM 주셔요! 그럼 2단계 미션 고고하시죠! 화이팅입니다 !

2021-01-12 10:52 UTC, limmmee-bonjour commented on src/main/java/lotto/StatisticsType.java
> +    NONE( 0, 0 ),
Enum이 아주 풍부해졌고 관심사가 모아졌네요 👏  👏 
참고로 Enum도 도메인의 한 부분이라고 봐주시면 됩니다 :) 패키지를 이동시켜 볼까요?!

2021-01-12 10:52 UTC, limmmee-bonjour commented on src/main/java/lotto/StatisticsType.java
> +    }
이 두 메소드를 하나로 합칠 수 없을까용?
enum 멤버변수에 보너스여부 값을 추가하면 어떨까요? 한번 고민해봅시다! :)

2021-01-12 10:52 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/BuyingStrategy.java
> +public interface BuyingStrategy {
전략패턴을 위해 인터페이스 정의 👍 
그런데, 아래 코드는 인터페이스의 관심사일까요?
만약 수동을 데이터를 받는다면 Set<Interger> 들어올텐데 lottoNumberBasket 과 관계가 있을까요?
인터페이스는 최대한 보수적으로 만들어주는것이 좋습니다 :)
```
static final List<Integer> lottoNumberBasket = makeLottoNumberBasket();

static List<Integer> makeLottoNumberBasket() {
        List<Integer> nums = new ArrayList<>();
        for (int i = LottoNo.MIN_NUMBER; i <= LottoNo.MAX_NUMBER; i++) {
            nums.add(i);
        }
        return nums;
    }
```

2021-01-12 10:52 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/LottoLogic.java
>  public class LottoLogic {
Q. 다만 이것과 별개로.. LottoLogic을 domain으로 넣지않고 controller로 취급해야할까요?
A. LottoLogic은 Service의 역할을 하는 클래스인 것으로 보여지네요 :) 
서비스 패키지를 만들어 이동시키거나, LottoLogic을 각 관심사에 맞게 나눠 객체화 해보는것도 좋을 것 같습니다 !

2021-01-12 10:52 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/LottoNo.java
> +            throw error;
이렇게 정의해줄 수도 있습니다 :)
```
new IllegalArgumentException("로또 번호는 1 이상 45 이하여야 합니다") 
```

2021-01-12 10:52 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/LottoNo.java
> +    public static final int MIN_NUMBER = 1;
상수화 좋습니다 💯

2021-01-12 10:52 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/LottoTicket.java
> +    public static boolean checkValidationLottoTicket(final Set<Integer> numbers) {
checkValidation ~ 보다는 validate 를 자주 사용한답니다 :) (중복된 의미!)

2021-01-12 10:52 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/WinningLottoNos.java
>      public StatisticsType isWinning(LottoTicket lottoTicket) {
is ~ 네이밍을 붙이면 retrun 값은 보통 boolean 입니다! 네이밍 변경이 필요해보여요 :)

2021-01-12 10:52 UTC, limmmee-bonjour commented on src/test/java/lotto/domain/LottoTicketTest.java
> +    )
아래와 같이 delimiter를 변경해서 사용할 수 있습니다 :)
```
 @CsvSource(
            value = "1,2,3,4,5,6 | 5 ", delimiter = '|'
    )
```

2021-01-12 10:54 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/LottoNo.java
> +        if( number < 1 || number > 45 ) {
고생 많이하셨습니다 :) 고민한 흔적이 많이 보여요! step2도 화이팅입니다!! 💯

2021-01-12 10:55 UTC, merged

2021-01-13 05:35 UTC, maireneu commented on src/main/java/lotto/StatisticsType.java
> +    NONE( 0, 0 ),
넵 이해했습니다! enum을 domain 패키지로 이동하였습니다.

2021-01-13 06:28 UTC, maireneu commented on src/main/java/lotto/StatisticsType.java
> +    }
enum에 bonus 값을 넣고, static으로 cache를 제작한다음 stream을 써서 check하도록 변경하였습니다!

2021-01-13 07:03 UTC, maireneu commented on src/main/java/lotto/domain/BuyingStrategy.java
> +public interface BuyingStrategy {
lottoNumberBasket을 LottoNo class로 이동하고, LottoNo에 Cache를 적용하였습니다!

2021-01-13 07:05 UTC, maireneu commented on src/main/java/lotto/domain/LottoNo.java
> +            throw error;
꿀팁 감사합니다! 모두 적용하였습니다.

2021-01-13 07:05 UTC, maireneu commented on src/main/java/lotto/domain/LottoNo.java
> +    public static final int MIN_NUMBER = 1;
감사합니다 ㅎㅎ

2021-01-13 07:26 UTC, maireneu commented on src/main/java/lotto/domain/LottoLogic.java
>  public class LottoLogic {
LottoLogic을 Service 패키지로, LottoGame을 main에서 분리해서 Controller로 이동하였습니다!

2021-01-13 07:47 UTC, maireneu commented on src/main/java/lotto/domain/LottoTicket.java
> +    public static boolean checkValidationLottoTicket(final Set<Integer> numbers) {
감사합니다! 해당부분 수정하였습니다.

2021-01-13 07:49 UTC, maireneu commented on src/main/java/lotto/domain/WinningLottoNos.java
>      public StatisticsType isWinning(LottoTicket lottoTicket) {
해당부분 수정하였습니다. 다음부터도 반드시 return 값이 boolean 일 경우 is를 사용하도록 하겠습니다!

2021-01-13 07:52 UTC, maireneu commented on src/test/java/lotto/domain/LottoTicketTest.java
> +    )
확인하고 해당 문법을 적용하여 테스트 코드를 하나 작성하였습니다! 모든 테스트 코드는 굳이 바꿀필요 없을거 같아서 적용하지 않았지만, 다음부터는 위 문법을 적극적으로 사용하도록 하겠습니다.