[brody.kim_김현우] 로또 1단계 코드리뷰 요청드립니다.
NewKrew2021/java-lotto-kakao pull request #13
Opened 2021-01-08 06:29 UTC by briron

안녕하세요. brody입니다.

로또 1단계 구현이 완료되어 코드리뷰 요청드립니다.

전체적인 구조는 자동차 게임에서 배웠던 MVC 패턴을 적용하였습니다.

LottoMain - 메인 함수로 전체 프로그램의 실행 흐름을 제어합니다.

각 도메인 별로 간략히 설명드리면,
PurchaseMoney - 구입 금액을 저장하고 있는 객체로, 구입금액의 유효성 검사, 구입수량 반환 등을 담당합니다.
Ball - 1부터 45까지 로또의 각 숫자를 저장하고 있는 불변(immutable) 객체입니다.
BallFactory - Ball의 재사용성을 높이기 위해 한번 생성된 Ball을 저장하고, 기존에 생성된 Ball을 반환하는 객체입니다.
Lotto - 6개의 볼 리스트를 저장하고 있는 일급콜렉션으로, 로또 생성 시 필요한유효성 검사 기능을 포함하고 있습니다. 
LottoGroup - 로또 리스트를 저장하고 있는 일급콜렉션으로, 로또 구매를 위해 전략 패턴과 정적 팩토리 메서드를 이용하였습니다.
GenerateStrategy - 로또생성 시 로또 생성방법을 전달하기 위한 함수형 인터페이스입니다.
RandomGenerateStrategy - GenerateStrategy를 상속받아 구현한 클래스로 랜덤으로 중복 없이 숫자를 생성하는 기능을 합니다.
WinningNumberSet - 당첨번호+보너스볼을 저장하고 있는 객체로, 
LottoResult - 당첨 결과를 저장하고 있는 객체로, 당첨순위 별 개수, 상금, 수익률을 구하는 기능을 포함합니다.
Rank - 당첨 순위를 저장하고 있는 Enum 타입으로, 상금과 설명을 포함하고 있고, 일치된 개수와 보너스볼 여부에 따라 객체를 생성하는 정적 팩토리 메서드를 이용하였습니다.

뷰는 아래와 같이 input과 output을 분리하여 작성하였습니다.
LottoInputView - 사용자의 입력을 받기 위한 View 클래스입니다.
LottoOutputView - 사용자에게 결과를 보여주는 View 클래스입니다.

2021-01-08 13:27 UTC, findstar requested changes
안녕하세요 brody. 🙌  로또 미션을 함께할 제임스입니다.
커밋 메세지도 잘 요약되어 있고, 기능요구사항 및 도메인 객체 분리가 잘 되어 있어서
리뷰 잘 할 수 있었습니다. 
구조적으로 크게 변경할 것은 없어보이지만,
더 좋은 코드가 될 것으로 보여 몇가지 코멘트를 남겨드렸습니다. 
확인부탁드립니다. 궁금하신 점은 언제든지 DM 주세요! 그럼 화이팅입니다.

2021-01-08 13:27 UTC, findstar commented on src/main/java/lotto/domain/Ball.java
> +        return BallFactory.getBall(ballString);
Ball 에서 BallFactory 를 의존하고 있네요. Ball 자체의 역할과 BallFactory 의 역할 구분이 흐려지는 것 같습니다.

2021-01-08 13:27 UTC, findstar commented on src/main/java/lotto/domain/Ball.java
> +    public Ball(int ballNumber) {
현재의 코드는 Ball 을 생성할 때 BallFactory 를 통해서만 생성하라고 권장되는 구조 입니다.
Ball 의 숫자 범위를 확인하는 역할은 Ball 이 가지고 있는게 어떨까요?

2021-01-08 13:27 UTC, findstar commented on src/main/java/lotto/domain/PurchaseMoney.java
> +    private void checkMultiple(int money) {
구입금액이 1000의 배수여야한다는 요구사항은 없습니다. 1100원도 입력 가능하게 변경해보세요 😄

2021-01-08 13:27 UTC, findstar commented on src/main/java/lotto/domain/Ball.java
> +public class Ball implements Comparable<Ball> {
Ball 보다는 LottoNumber 와 같은 네이밍은 어떤가요?

2021-01-08 13:27 UTC, findstar commented on src/main/java/lotto/domain/Lotto.java
> +    public Lotto(String lottoText) {
String 으로 부터 바로 Lotto 객체를 생성하려는 경우에는 static 메서드로 만들 수도 있습니다.
여러개의 생성자를 만들어서 활용하는 방법을 알아보세요 😄

2021-01-08 13:27 UTC, findstar commented on src/main/java/lotto/domain/WinningNumberSet.java
> +        if (bonusBall.isDuplicated(winningLotto)) {
보너스 볼에서 로또 번호가 중복되는지 확인하고 있네요. 
반대로 확인해야 하지 않을까요? 
이미 Lotto 에서는 contains 메서드가 준비되어 있네요.

2021-01-08 13:27 UTC, findstar commented on src/main/java/lotto/domain/Rank.java
> +    FIFTH(5000L, "3개 일치"),
Java 7부터 자릿수를 표시하기 위한 underscores(밑줄) 표현이 가능합니다.
숫자를 가독성있게 5000 -> 5_000, 50000 -> 50_000 이렇게 표현할 수 있습니다.

2021-01-08 13:27 UTC, findstar commented on src/main/java/lotto/domain/Rank.java
> +    private final Long prize;
이건 price 의 오타 같군요 😄

2021-01-08 13:27 UTC, findstar commented on src/main/java/lotto/domain/WinningNumberSet.java
> +    public Rank compare(List<Ball> balls) {
WinningNumberSet 에서 Rank 를 구할 때는 List<Ball> 이 아니라 Lotto 를 넘겨 받는게 더 낫지 않을까요?

2021-01-08 13:27 UTC, findstar commented on src/main/java/lotto/domain/Rank.java
> +        if (matchedCount == Lotto.COUNT_OF_NUMBERS) {
굳이 Lotto.COUNT_OF_NUMBER 에서 하나씩 빼가면서 비교하기보다
matchCount 정보는 Rank 가 가지고 있는게 가독성이 더 좋아질 것 같네요.

2021-01-08 13:27 UTC, findstar commented on src/test/java/lotto/domain/RankTest.java
> +public class RankTest {
compare 메서드의 테스트가 빠져있습니다.

2021-01-08 13:27 UTC, findstar commented on src/test/java/lotto/domain/BallFactoryTest.java
> +public class BallFactoryTest {
BallFactory 에서 IllegalArgumentException rk 가 발생하는 경우의 테스트를 추가해주세요.

2021-01-08 13:27 UTC, findstar commented on src/test/java/lotto/domain/LottoResultTest.java
> +public class LottoResultTest {
getRankCount 메서드의 테스트를 추가해주세요.

2021-01-09 12:46 UTC, briron commented on src/main/java/lotto/domain/Ball.java
> +        return BallFactory.getBall(ballString);
LottoNumber과 LottoNumberFactory를 어떻게 기능하도록 할지 매우 많이 고민했습니다.
 사용자는 LottoNumberFactory를 통해서만 LottoNumber을 생성하고, LottoNumberFactory에 이미 생성된 객체를 저장하여 재사용할 수 있도록 구조를 만드려고 했습니다.
 그런데 LottoNumberFactory에서 LottoNumber 객체를 생성하려면 결국 LottoNumber의 생성자나 정적 팩토리 메서드가 public으로 열려있어야 한데, 그러면 사용자나 다른 개발자들이 임의로 LottoNumber을 직접 생성하는 것을 막지 못하는 결과가 발생했습니다.
  그래서 고민 끝에 LottoNumber 안에 private static class로 LottoNumberFactory를 선언하고 LottoNumber의 생성자는 private으로 선언한 이후에 valueOf 라는 정적 팩토리 메서드로 생성하도록 구조를 변경하였습니다.
 혹시 이보다 더 좋은 설계 방법이 있을지 궁금합니다.

2021-01-09 12:46 UTC, briron commented on src/main/java/lotto/domain/Ball.java
> +    public Ball(int ballNumber) {
위와 같은 고민을 했습니다!

2021-01-09 12:46 UTC, briron commented on src/main/java/lotto/domain/PurchaseMoney.java
> +    private void checkMultiple(int money) {
네 변경하였습니다!

2021-01-09 12:47 UTC, briron commented on src/main/java/lotto/domain/Ball.java
> +public class Ball implements Comparable<Ball> {
네 LottoNumber이 더 직관적으로 와닿는것 같아 변경하였습니다.
워낙 ball이라는 이름이 많이 쓰이다보니 메소드명이나 변수명에서도 바꿀게 많았습니다.
이름을 처음부터 잘 정하는게 중요하다는 걸 다시 한번 깨닫게 됐습니다 !

2021-01-09 12:48 UTC, briron commented on src/main/java/lotto/domain/Lotto.java
> +    public Lotto(String lottoText) {
내 정적 팩토리 메서드를 이용해서 생성하는 방법을 추가하였습니다.

2021-01-09 12:48 UTC, briron commented on src/main/java/lotto/domain/WinningNumberSet.java
> +        if (bonusBall.isDuplicated(winningLotto)) {
네 Lotto에서 contains 메서드가 준비되어 있어서 LottoNumber에 isDuplicated 함수가 불필요한 것 같아 변경하였습니다.

2021-01-09 12:49 UTC, briron commented on src/main/java/lotto/domain/Rank.java
> +    FIFTH(5000L, "3개 일치"),
이런게 있는지 처음 알았네요! 훨씬 더 가독성있게 변경된 것 같습니다. 감사합니다.

2021-01-09 12:50 UTC, briron commented on src/main/java/lotto/domain/Rank.java
> +    private final Long prize;
상금을 의미하기 위해 prize라는 단어를 사용했는데 오해의 소지가 있다면 변경하도록 하겠습니다!

2021-01-09 12:51 UTC, briron commented on src/main/java/lotto/domain/WinningNumberSet.java
> +    public Rank compare(List<Ball> balls) {
네 WinningNumberSet 에서 compare 메서드 대신 compareWithLotto 라는 메서드로 변경한 결과, 자료를 구조받는 과정이 더 명확해진 것 같습니다. 감사합니다.

2021-01-09 12:52 UTC, briron commented on src/main/java/lotto/domain/Rank.java
> +        if (matchedCount == Lotto.COUNT_OF_NUMBERS) {
네 Rank에서 matchCount와 hasBouns 정보를 포함토록 변경하였습니다.

2021-01-09 12:52 UTC, briron commented on src/test/java/lotto/domain/BallFactoryTest.java
> +public class BallFactoryTest {
BallFactory 함수를 Ball 내부의 static class로 변경하였습니다.

2021-01-09 12:52 UTC, briron commented on src/test/java/lotto/domain/RankTest.java
> +public class RankTest {
네 추가하였습니다!

2021-01-09 12:52 UTC, briron commented on src/test/java/lotto/domain/LottoResultTest.java
> +public class LottoResultTest {
네 추가하였습니다. 감사합니다.

2021-01-09 12:54 UTC, briron commented
LottoNumber과 LottoNumberFactory를 어떻게 기능하도록 할지 매우 많이 고민했습니다.
 사용자는 LottoNumberFactory를 통해서만 LottoNumber을 생성하고, LottoNumberFactory에 이미 생성된 객체를 저장하여 재사용할 수 있도록 구조를 만드려고 했습니다.
 그런데 LottoNumberFactory에서 LottoNumber 객체를 생성하려면 결국 LottoNumber의 생성자나 정적 팩토리 메서드가 public으로 열려있어야 한데, 그러면 사용자나 다른 개발자들이 임의로 LottoNumber을 직접 생성하는 것을 막지 못하는 결과가 발생했습니다.
  그래서 고민 끝에 LottoNumber 안에 private static class로 LottoNumberFactory를 선언하고 LottoNumber의 생성자는 private으로 선언한 이후에 valueOf 라는 정적 팩토리 메서드로 생성하도록 구조를 변경하였습니다.
 혹시 이보다 더 좋은 설계 방법이 있을지 궁금합니다.

2021-01-09 15:11 UTC, findstar approved these changes
안녕하세요 brody. 🙌  피드백 잘 반영해주셨네요 수고 많으셨습니다. 
코드에서 고민하신 흔적이 보입니다! 👍 
이전의 주요 코멘트는 로또 번호를 생성하기 위해서 필요한 Collections.shuffle() 을 어디서 사용하고
여기에서 사용하는 Number 객체를 캐싱할 수 없는지에 대한 내용이었습니다. 
궁금하신 점은 언제든지 DM 주세요! 
PR 머지 하겠습니다. 다음 단계 진행 해주세요
그럼 화이팅입니다.

2021-01-09 15:11 UTC, findstar commented on src/main/java/lotto/domain/Rank.java
> +        return NOTHING;
다음처럼 개선할 수 있습니다 😄 
```java
        if (matchedCount == SECOND.matchedCount && hasBonus == SECOND.hasBonus) {
            return SECOND;
        }
        
        return Arrays.stream(values())
                .filter(r -> r.matchedCount == matchedCount)
                .findFirst()
                .orElse(Rank.NOTHING);
```

2021-01-09 15:11 UTC, findstar commented on src/main/java/lotto/domain/Rank.java
> +    private final Long prize;
넵 제가 오타로 인식한 것 같네요. 
그냥 두셔도 됩니다 😄

2021-01-09 15:11 UTC, findstar commented on src/main/java/lotto/domain/LottoNumber.java
> +        return 1 > lottoNumber || lottoNumber > 45;
상수는 별도로 정의해서 사용하는 것이 좋습니다 😄

2021-01-09 15:11 UTC, findstar commented on src/test/java/lotto/domain/WinningNumberSetTest.java
> +        assertThat(winningNumberSet).isEqualTo(new WinningNumberSet(winningLotto, bonusLottoNumber));
굳이 equals 를 비교할 필요가 있을까요?
오히려 compareWithLotto 메서드를 테스트 해야할것 같습니다.

2021-01-09 15:11 UTC, merged