[sierra.s] 1단계 코드리뷰 요청드립니다.
NewKrew2021/java-lotto-kakao pull request #14
Opened 2021-01-08 07:46 UTC by 32sylee

안녕하세요, 시에라입니다😃
로또게임 1단계 코드리뷰 요청드립니다.

# 클래스
- LottoNumber: 로또 번호 하나에 해당합니다.
- Lotto: 로또 한 줄(로또 번호 6개)에 해당합니다.
- Lottos: 구입한 모든 로또에 해당합니다.
- Rankings: 각 등수별 당첨개수를 저장하고, 이를 바탕으로 수익률을 계산합니다.
- MatchNumber: 당첨번호와 보너스번호를 저장합니다.
- WinningNumber: 당첨번호에 해당합니다.
- Money: 구매금액을 저장합니다.

# 질문
- DTO에는 게터, 세터를 제외한 다른 로직이 아예 포함될 수 없나요?
  - 질문을 한 이유: RankingsDto는 Rankings에서 사용될 값을 집계하기 위해 만든 클래스입니다(일급컬렉션은 불변 객체로 만들어야 한다고 들어서 이렇게 만들게 되었습니다). 그런데 RankingsDto에서 집계를 편하게 하다 보니 게터, 세터가 아닌 다른 로직까지 약간 포함이 되게 되었습니다. 이런 방식이 괜찮은지 해서 질문드립니다!

2021-01-08 09:45 UTC, parkjoos requested changes
안녕하세요~😊
반갑습니다. 로또 미션을 리뷰하게된 jay 입니다.
테스트 코드 정말 잘 만들어 주셨고,  각 클래스별 역할도 아주 잘 나누어져 있네요
짧은 시간 동안 아주 멋지게 구현해 주신 것 같아요
질문 해주신 내용에 대한 고민과 출력 로직에 대한 분리만 좀 더 되었으면 좋을것 같구요 
세세한 몇가지 코멘트를 추가했습니다.
수정이 가능한 부분이 있는지 확인해 보시고 
질문이나 궁금한 부분은 언제든지 PR 에 댓글을 달아 주시거나 슬랙으로 연락 주세요

2021-01-08 09:45 UTC, parkjoos commented on src/main/java/lotto/domain/Lotto.java
> +        });
```suggestion
        lottoNumbers = new TreeSet<>(Comparator.comparingInt(LottoNumber::getNumber));
```
로 lambda 표현식을 이용하면 좀더 읽기 편한 코드가 될것 같아요

2021-01-08 09:45 UTC, parkjoos commented on src/main/java/lotto/domain/Lottos.java
> +    }
지금은 lottos 를 가지고 Rankings 를 만드는 과정이 
 lottos -> RankingDto -> Rankings 의 과정을 거치는데요
어기서는 Rank 들의 전체 리스트만 결과로 만들고 
이 Rank 리스트를 Rankings 의 생성자로 넘겨서 Rankings의 생성자에서 counting aggregation 을 수행하는것이 어떨까요?

좀더 메소드들의 역할을 간단하게 만든다고 생각해 보면 이 메소드의 역할은 단순히 매칭된 Rank 의 전체 리스트만 준다가 더 좋을 것같아요

2021-01-08 09:45 UTC, parkjoos commented on src/main/java/lotto/controller/LottoController.java
> +        Rankings rankings = new Rankings(rankingsDto.getRankings());
질문에 쓰신것 처럼 RankingsDto 가 aggregation 역할 까지 하고 있는데 Rankings 에서 할 수 있는 방법을 찾아봅시다.
일급 컬렉션이 불변성을 보장하려면 중간에 바뀌지만 않으면 되죠 
생성자에서 counting 을 해버리고 그 이후에 변경되지 않도록 일급 컬렉션 클래스를 구성하면 
그것도 불변성을 보장하는 클래스 라고 볼 수 있을 것 같아요
그러면 lottos.match 의 결과를 좀더 단순하게 하고 
```suggestion
        Rankings rankings = new Rankings(lottos.match(matchNumber)); 
```
형태로 단순화 할 수 있지 않을까요?

2021-01-08 09:45 UTC, parkjoos commented on src/main/java/lotto/domain/Lotto.java
> +                .map(no -> Integer.toString(no))
항상 모든 이름은 명확하게 알 수 있는 용어를 사용하도록 연습해 주시면 좋을것 같아요
언뜻 봤을때 이해하기 어려운 축약어나 이니셜 보다 lottoNumber -> Integer.toString(lottoNumber) 로 명확하게 작성해 주면 좋을 것 같습니다.

2021-01-08 09:45 UTC, parkjoos commented on src/main/java/lotto/domain/Lotto.java
> +    }
이 프로그램의 결과 출력에 사용하기 위해서 도메인에 toString 을 활용하셨는데요. 이 toString 이 로깅등 다른 용도로 필요하다면 좋은 방법은 아닌거 같아요. 차라리 이 역할을 위한 전용 DTO 를 만들거나 view 로직에서 처리하는건 어떨까요?

2021-01-08 09:45 UTC, parkjoos commented on src/main/java/lotto/domain/LottoNumber.java
> +        return lottoNumberCache.get(number);
바로 LottoNumber 를 만들어서 리턴하지 않고 cache 를 이용한 이유가 뭘까요? 이부분은 궁금해서 제가 질문 드립니다.

2021-01-08 09:45 UTC, parkjoos commented on src/main/java/lotto/domain/Lotto.java
> +    }
이 함수는 이 도메인이 없어도 되는 함수로 보이네요
어느 도메인에서 다루면 좋은 로직일지 한번 고민해 주세요

2021-01-08 09:45 UTC, parkjoos commented on src/main/java/lotto/domain/Rankings.java
> +    }
이부분도 출력 로직을 분리 하는 것 한번 생각해 주세요

2021-01-08 17:31 UTC, parkjoos commented on src/main/java/lotto/util/RandomNumberGenerator.java
> +        }
제가 놓친 부분이 있어서 추가 코멘트 드립니다.
이 로직은 이론상 최악의 상황에서 무한 루프에 빠질 수도 있는 로직이네요 
요구사항에 보시면 Collections.shuffle() 을 사용할 수 있다고 되어 있는데요 이걸 사용해서 안전한 로직으로 변경해 보세요

2021-01-10 13:56 UTC, 32sylee commented on src/main/java/lotto/domain/Lotto.java
> +        });
앗 이런 방법이 있었네요!! 감사합니다 😊

2021-01-10 13:58 UTC, 32sylee commented on src/main/java/lotto/domain/Lottos.java
> +    }
리스트로 반환하면 RankingDto가 굳이 없어도 되겠네요!! 말씀주신 방법으로 수정해보겠습니다:)

2021-01-10 14:01 UTC, 32sylee commented on src/main/java/lotto/controller/LottoController.java
> +        Rankings rankings = new Rankings(rankingsDto.getRankings());
넵 말씀주신 방법이 더 단순하고 좋은 것 같아요! 생성자에서 카운팅까지 하도록 수정해보겠습니다

2021-01-10 14:02 UTC, 32sylee commented on src/main/java/lotto/domain/Lotto.java
> +                .map(no -> Integer.toString(no))
네! 축약어 사용하지 않도록 수정하겠습니다.

2021-01-10 14:04 UTC, 32sylee commented on src/main/java/lotto/domain/Lotto.java
> +    }
네 다시 보니 좋은 방법이 아닌 것 같습니다 ㅠㅠ 출력부분 개선시켜보겠습니다!

2021-01-10 14:07 UTC, 32sylee commented on src/main/java/lotto/domain/LottoNumber.java
> +        return lottoNumberCache.get(number);
로또 번호는 어차피 1~45번으로 정해져있으니 매번 객체를 여러개 만드는 것보다는 미리 1~45까지 객체를 만들어놓고 필요할 때 가져다 쓰면 되지 않을까 생각했어요!

2021-01-10 14:09 UTC, 32sylee commented on src/main/java/lotto/domain/Lotto.java
> +    }
Rank를 구하기 위한 로직이니 Rank로 가는 것이 적절할까요?? 요부분 고민해서 이동시켜보겠습니다!!

2021-01-10 14:10 UTC, 32sylee commented on src/main/java/lotto/domain/Rankings.java
> +    }
네:)

2021-01-10 14:14 UTC, 32sylee commented on src/main/java/lotto/util/RandomNumberGenerator.java
> +        }
앗 제가 요구사항을 놓쳤었네요ㅠㅠ
무한루프에 빠질 수도 있다는 생각은 못했었는데 안일(?)하게 생각했던 것 같습니다.
Collections.shuffle 사용하도록 수정하겠습니다:)

2021-01-11 09:43 UTC, 32sylee commented
@parkjoos 
코멘트주셨던 수정사항들 반영하였습니다! :)

2021-01-11 10:15 UTC, parkjoos approved these changes
안녕하세요 
리뷰로 남겼던 내용을 아주 잘 반영되었네요! 👍
수고 많으셨고 바로 다음 스텝으로 진행해도 좋을 것 같습니다.
제가 추가로 남긴 코멘트들은 다음 스텝 진행 하면서 개선 하시면 좋을것 같네요 
그럼 다음 스텝도 화이팅 입니다. 👏

2021-01-11 10:15 UTC, parkjoos commented on README.md
> +총 수익률은 30%입니다.
기능 명세와 함께 요구 사항 전체를 써 주셔서 너무 좋습니다. 제가 리뷰 할때에도 도움이 많이 되었어요 👍

2021-01-11 10:15 UTC, parkjoos commented on src/main/java/lotto/domain/LottoNumber.java
> +        return lottoNumberCache.get(number);
여러건의 로또를 구매할때 인스턴스가 여러개 생성되는것보단 한정적인 인스턴스를 사용하게 되어서 좋은 방법 인것 같습니다.
그리고 로또가 매칭되었는지 체크 할때에도 번호숫자를 직접 비교 할 필요 없이 그냥 인스턴스를 비교할 수도 있고요 👍

2021-01-11 10:15 UTC, parkjoos commented on src/main/java/lotto/domain/Lottos.java
> +    }
이부분은 stream().map 으로 좀더 간결하고 읽기 쉽게 변경이 가능 할 것 같네요
다음 스텝에서 한번 수정해 보세요

2021-01-11 10:15 UTC, parkjoos commented on src/main/java/lotto/domain/Rankings.java
> +        }
이런 부분은 초기화 하는 부분 같은데요. 
이 기능에서 주 관심사는 아닌것 같네요
private 메소드 분리가 가능 할 것 같습니다.

2021-01-11 10:15 UTC, merged