[echo.ohce 김환석] 로또 미션 step1 코드리뷰 요청 드립니다.
NewKrew2021/java-lotto-kakao pull request #15
Opened 2021-01-08 09:07 UTC by 10000sukk

피드백 많이 주시면 정말 감사하겠습니다!

2021-01-11 01:18 UTC, sehan requested changes
안녕하세요. 로또 미션을 함께 하게된 니오입니다 😊

원시값 포장, 객체별 역할 할당, 코딩 컨벤션까지 전체적을 아주 좋습니다. 💯 💯 💯 
여기에 추가로 객체간 협업을 통해 문제를 해결해나가는 방식으로 코드를 개선하면 더 좋을거 같아서 Request Changes 드립니다. 

화이팅입니다. 👍 👍 👍

2021-01-11 01:18 UTC, sehan commented on README.md
> +## 로또 기능 요구 사항
👍

2021-01-11 01:18 UTC, sehan commented on src/main/java/LottoMission/controller/LottoController.java
> +    public LottoController(int userMoney){
LottoController 는 로또를 구입하고 생성하는 역할을 하고 있습니다. 그와 동시에 main() 의 처리흐름이 method() 로 하나하나 구현되어 있습니다.  LottoController 는 Main.main() 과 함께 controller layer 를 구성하고 있는 동시에 로또의 구입과 생성 역할을 가지고 있습니다.

로또의 구입과 생성 담당하는 도메인객체를 생성하여 역할을 넘겨주는 것이 어떨까요?

controller 에서 역할을 담당할 수도 있지만 model 로 내릴 수 있다면 역할을 이동해주는 것을 제안드려요~ 
역할이 많다보니 멤버변수의 수도 많습니다. 객체가 꼭 상태로 가져야 하는  멤버인가 고민해 주세요 😊

2021-01-11 01:18 UTC, sehan commented on src/main/java/LottoMission/domain/UserMoney.java
> +public class UserMoney {
원시값 포장 아주 좋습니다. 👍

2021-01-11 01:18 UTC, sehan commented on src/main/java/LottoMission/domain/LotteryWinnings.java
> +public enum LotteryWinnings {
enum 활용 아주 좋습니다. 👍

2021-01-11 01:18 UTC, sehan commented on src/main/java/LottoMission/domain/Lotto.java
> +    public void winningPrize(LottoAnswer answer) {
로또의 당첨결과를 객체가 멤버로 유지해야 하는가? 하는 질문을 던져 봅니다.

winningPrize(answer) 실행 후 getWinngingStat() 으로 조회를 해야 한다면
winningPrize(answer) 호출시 바로 LotteryWinnings 를 return 해서 처리하고 객체의 멤버에서는 제거 해도될 거 같습니다.

2021-01-11 01:18 UTC, sehan commented on src/main/java/LottoMission/domain/Lotto.java
> +        boolean hasBonusNo = numbers.isContainLottoNumber(bonus);
answer 에서 bonusNumber 를 꺼내서 numbers 에 포함되는지 여부를 확인 할 수 도 있지만 answer 에게 도움을 요청하게 되면 answer.getBonusNumber 로 꺼내지 않고 hasBonusNo 를 얻어낼 수 있습니다.
객체의 상태를 꺼내기 보다는 객체에게 도움을 요청하는 방향으로 개선해 보세요 😊

2021-01-11 01:18 UTC, sehan commented on src/main/java/LottoMission/domain/Lotto.java
> +        combine.addAll(this.numbers.getNumbers());
아래 hasBonusNo 처럼 상태를 꺼내오기 보다는 answer 에게 도움을 요청하는 방식으로 좀 더 고민해주세요 😊

2021-01-11 01:19 UTC, sehan commented
패키지명은 소문자로 작성해주세요. ex) LottoMission

2021-01-11 07:12 UTC, 10000sukk commented on src/main/java/LottoMission/controller/LottoController.java
> +    public LottoController(int userMoney){
우선 이렇게 자세히 피드백 주셔서 정말 감사드립니다! ㅎㅎ 
이 부분을 리펙토링 하는 것이 굉장히 어렵게 느껴졌습니다. 기존의 인스턴스 필드 들이 필수라고 생각했던 편견이 쉽게 깨지지 않더라고요.. ㅎㅎ;;
그래서 LottoGame class 를 추가해서 이부분 으로 Lotto 자동생성을 기능을 옮겼습니다.
맞는건지 잘 모르겠습니다.. 혹시 잘못되었다면 힌트나 피드백 조금만 더 주신다면 감사하겠습니다.ㅎㅎ

2021-01-11 07:17 UTC, 10000sukk commented on src/main/java/LottoMission/domain/Lotto.java
> +    public void winningPrize(LottoAnswer answer) {
피드백 감사드립니다 ㅠㅠ 정말로 ㅜㅜ
이부분에서 바로 enum 객체를 return 하니 필드도 필요 없고 더 테스트도 깔끔해 진듯 합니다.
하지만 멤버를 없애다 보니 outputView 에서 마지막에 수익률을 출력하는 부분에서 한번더 winningPrize 를 호출하는 있어서는 안될(?)..불상사가 생긴듯 합니다 ㅎㅎ
이 부분에 대한 생각을 해봣는데 출력하는 부분에서 resultView의 메서드와 totalEarningsView 를 합치면 굳이 두번 호출하지 않아도 되는거 같아서 합치는 것을 고려해 보았지만 의미상으론 분리 가능해서 일단은 그냥 두었습니다.
혹시 어떻게 생각하시는지 의견을 조금만 공유 가능 할까요??

2021-01-11 07:37 UTC, 10000sukk commented on src/main/java/LottoMission/domain/Lotto.java
> +        combine.addAll(this.numbers.getNumbers());
감사합니다!! ㅎㅎ LottoAnswer 에 메세지를 보내는 방향으로 수정 해 보았습니다!

2021-01-11 08:13 UTC, sehan commented on src/main/java/LottoMission/domain/Lotto.java
> +    public void winningPrize(LottoAnswer answer) {
Lotto 의 당첨순위는 당첨결과를 구하는 부분에서 한번만 생성되면 됩니다. 
Lottos.getAllLottoRankCount 와 getSumAllWinningMoneny 모두 구입한 로또의 순위를 시작으로 값을 구합니다.
그렇다면 AllLottoRankCount 와 SumAllWinningMoney 를 멤버로 가지는 객체를 만들어서 두 상태에 대한 책임을 가지게 만들면 됩니다. 

구입한로또의 순위집계(AllLottoRankCount) 와 구입한로또의 당첨금액(SumAllWinningMoney) 을 책임지는 객체를 LottosResult 라고 한다면

controller 에서는 Lottos 에서 LottosResult 를 가져오와서 View 로직을 수행하면 됩니다. 

OutputView.totalEarningsView() 에 LottosResult 를 넘겨주거나 LottosResults.getTotalEarnings() 값을 직접넘겨주면 됩니다.
OutputView.resultView() 에도 LottosResult 를 넘겨주면 됩니다.

2021-01-11 08:39 UTC, sehan requested changes
피드백 잘 반영해 주셨습니다. 👍 

LottoGame 에 대한 생각을 좀 더 해봤으면 하는 바램에서 한번더 Request changes 드립니다.
그리고 추가로 몇가지 수정사항들을 남겨놨습니다.

조금 더 힘내주세요 👍

2021-01-11 08:39 UTC, sehan commented on src/main/java/lottoMission/domain/Lotto.java
> +    public LotteryWinnings winningPrize(LottoAnswer answer) {
아주 읽기 좋아졌습니다 👍

2021-01-11 08:39 UTC, sehan commented on src/main/java/lottoMission/domain/LottoAnswer.java
> +        combine.addAll(this.answerNumbers.getNumbers());
여기서 다시도 LottoNumbers.getNumbers() 로 숫자들을 꺼내고 있습니다. 
LottoNumbers 에게 도움을 요청해보세요 😄 
도움의 연속이군요... 객체간의협업의 끝은 어디일까요? : (

2021-01-11 08:39 UTC, sehan commented on src/main/java/lottoMission/domain/LottoGame.java
> +public class LottoGame {
LottoGame 의 역할은 무엇일까요? 

지금은 돈을 넣어주면 로또를 자동으로 생성해주고 있습니다.
LottoGame 이 크고작은 도메인들을 아울러 controller 와 메세지를 주고받는 창고 역할을 해보는건 어떨까요? 

controller 는 view 에게 돈을 입력받아 lottoGame 에게 자동으로 로또를 구입해달라고 부탁합니다.
lottoGame 은 lotto 를 생성해서 controller 에게 제공합니다. buyLottoAuto 는 Lottos 를 제공하고 있지만 controller 와 메세지를 주고 받는 창구를 lottoGame 이 전담한다고 한다면 Lottos 대신 List<Lotto> 를 제공해주면 controller 는 구입한 로또 번호를 출력하기에 충분한 정보를 얻었습니다.  Lottos 는 당첨결과도 제공해주는 역할을 가지고 있기 때문에 로또만 구입했는데 좀 과한 역할을 가진 객체를 돌려준다는 기분이 드네요.. 아마도 기분탓이겠죠? ㅎㅎ
controller 는 이제 당첨결과를 알고 싶어서 당첨번호를 가지고 결과를 알고 싶습니다.  물어볼 곳은 lottoGame 뿐이기 때문에 lottoGame 에게 도움을 요청합니다. 구입한  List<Lotto> 와 당첨번호를 전달하면서 당첨결과를 알려달라고 합니다. lottoGame.getLottosResult() 매소드에게 물어봅니다. 당첨결과는 Lottos 가 역할을 담당하고 있기 때문에 lottoGame 은 다시 Lottos 에게 도움을 요청해서 LottosResult 를 얻어옵니다. 이로써 controller <-> lottoGame <-> Lottos 가 협업하여 로또 구입에서 부터 로또결과 확인까지 목적을 달성하게 됩니다. 

어떤가요? controller 와 객체간 협업의 모습이 그려지나요? 도움이 되었기를 바랍니다. 👍

2021-01-11 08:39 UTC, sehan commented on src/main/java/lottoMission/domain/Lottos.java
> +        result.remove(LotteryWinnings.UNRANKED);
위에 있는 2번의 for 구문을 stream 을 사용해서 처리해보세요!
map, collect(Collector.toMap()) 을 활용해 보세요. 다른 더 좋은 방법이 있으면 언제나 환영입니다.

2021-01-11 08:39 UTC, sehan commented
패키지명에 아직도 대문자가 있습니다. ㅎㅎ.  lottoMission

2021-01-11 20:52 UTC, 10000sukk commented on src/main/java/lottoMission/domain/LottoGame.java
> +public class LottoGame {
정말 생각을 많이 해볼 수 있게 해주셔서 감사합니다. 솔직히 많이 어렵더라고요 ㅎㅎ 그래도 많이 미흡하지만 최대한 lottoGame 의 의미를 생각하면서 리펙토링 해보았습니다. Lottos 클래스 인스턴스와 LottoAnswer 클래스 인스턴스를 LottoGame 이 가지게 해주었습니다. 그러다 보니 자연스럽게 Lottos에 있던 순위 통계 구하는 기능도 LottoGame으로 옮기게 되었던거 같습니다.
많은 도움주셔서 감사합니다.
미흡한점 더 말씀해 주신다면 감사하겠습니다!!

2021-01-11 21:02 UTC, 10000sukk commented on src/main/java/lottoMission/domain/LottoGame.java
> +public class LottoGame {
제가 느끼기에는 
LottoGame -> 로또들과 답을 가지고 그에 맞는 기능들을 제공
LottoResult -> 랭크 통계 값을 저장
LottoController -> 위의 객체들의 협업을 도울수 있도록 기능 제공

이렇게 생각 하는데 혹시 맞을까요?? 솔직히 이부분은 자신이 없습니다....ㅎㅎ....😭

2021-01-12 02:26 UTC, sehan requested changes
피드백 반영해주시느라 고생하셨습니다.  👍 

LottoGame, LottoController 를 중점적으로 리팩토링 해야할 필요성이 보여서 다시한번 Request Changes 드립니다.

코멘트 확인 부탁드립니다. 
힘든 과정이지만 더 힘내주세요 👍 👍 👍

2021-01-12 02:26 UTC, sehan commented on src/main/java/lottoMission/controller/LottoController.java
> +    private UserMoney userMoney;
LottoController 가 오히려 로직을 방해하고 있는거 같습니다. 실제로 Controller 가 없어져도 Main.main() 에 코드는 현재와 크게 달라지지 않음을 알 수 있을 겁니다. 특단의 조치로 LottoController 를 삭제하는것이 좋겠습니다.

Controller 가 자동으로 Lotto 를 생성하는 역할을 가지고 있는데 이 역할을 맡아줄 domain 객체는 새로 생성하고 Controller 를 삭제해주세요. 그런 후 Main.main() 에 domain 객체들 ( LottoGame, LottoResult, UserMoney , 새로만들 Lotto 생성역할을 맡아줄 객체 ) 을 직접 사용하는것이 더 좋겠습니다.

2021-01-12 02:26 UTC, sehan commented on src/main/java/lottoMission/domain/LottoGame.java
LottoGame 의 역할은 getAllLottoRankCount() 가 해주는게 전부입니다. Lottos 와 LottoAnswer 를 사용해서 로또순위별 당첨수를 집계하는 일입니다.  getAllLottoRankCount() 에 Lottos, LottoAnswer 인자를 받아서 처리하는것이 더 좋습니다. Lotts 와 LottoAnswer 의상태를 유지할 필요가 없기 때문입니다. 
결국, LottoGame 이름과는 다르게 구입한로또와 당첨번호를 입력하면 순위별 로또당첨수를 집계해주는 역할을 하고 있습니다.

역할에 맞게 이름을 지어주시고 객체가 상태를 유지해야할 멤버인지를 다시 고민해주세요

2021-01-12 02:26 UTC, sehan commented on src/main/java/lottoMission/domain/LottoGame.java
> +public class LottoGame {
네, 현재 LottoController 는 객체간 협업을 돕지는 않고 있습니다. 

* LottoController 는 로또 구입금액을 주면 생성이 됩니다.  
* controller 에게 로또를 구입하라고 메세지를 주면(buyLottos())  얼마를 살지를 모르겠지만 알아서 구입해 줍니다. ( 호출자는 controller 내부의 userMoney 상태를 모르기 때문입니다 ) 구입은 했지만 Lotto 를 return 해주지는 않습니다.  
* 당첨번호를 입력받아서 당첨결과를 확인해보려고 하는데  일단 여기서 구입한 로또를 가지고 있지 않기 때문에 어찌할바를 모르게 됩니다.  
* 당첨번호만 우선 입력해(setLastWeekWinningNumber()) 봅니다.
* 그리고 결과를 계산합니다(calLottoResult()). 하지만 결과는 알려주지 않습니다.

LottoController 를 보면서 해석한 내용입니다. main() 절차적으로 작성될 코드들을 조각조각 매소드로 분리해 놓았을뿐 객체의 역할을 하고 있지 않습니다.

2021-01-12 02:26 UTC, sehan commented on src/main/java/lottoMission/controller/LottoController.java
> +    private List<Lotto> createRandomLottoList(){
객체를 새로 생성해서 로또생성책임을 넘겨주는건 어떨가요?

2021-01-12 02:26 UTC, sehan commented on src/main/java/lottoMission/domain/LottoGame.java
> +        for (Lotto lotto : lottos.getLottos()) {
getAllLottoRankCount 가 Lottos 내에 있을때는 Lottos.getLottos() 해서 값을 꺼내오지 않아도 되었지만 여기서는 Lottos 내부 상태를 꺼내오고 있습니다. Lottos 에게 메세지를 보내서 도움을 요청하는 방식으로 변경해주세요.

2021-01-12 02:26 UTC, sehan commented on src/main/java/lottoMission/domain/LottoGame.java
> +    public List<List<Integer>> getLottosList() {
구입한 로또를 화면에 출력하기 위해서 LottoGame 에서 로또를 꺼내고 있습니다. 
로또를 구입할때 로또정보를 제공해 주었으면 LottoGame 에 로또 상태를 유지하지 않아도 되고 getter 를 통해 다시 꺼내오지 않아도 됩니다.

2021-01-12 02:26 UTC, sehan commented on src/main/java/lottoMission/domain/LottoNumbers.java
> +        combineSet.addAll(lottoNumbers.getNumbers());
LottoNumbers.getNumbers() 로 LottoNumbers 내부 Set<LottoNumber> 를 꺼내오고 있습니다. 
LottoNumbers 에게 호출자의 Set<LottoNumber> 를 보내 객체에게 도움을 요청하는 방식으로 변경해주세요

2021-01-12 02:26 UTC, sehan commented on src/main/java/lottoMission/domain/LottoGame.java
> +public class LottoGame {
LottoGame 을 controller 와 메세지를 주고받는 창구로 본다면 이란 말의 의도가 잘못전달 된걸로 보입니다.
LottoGame 의 역할을 먼저 명확히 해주셔야 합니다. LottoGame 은 로또를 발급하고 발급된 로또와 당첨번호를 입력하면 당첨결과를 알려주는 기능을 가진다고 하면  일단 2개의 매소드를 가져야 합니다.
* 구입금액에 따라 로또를 발급하는 매소드 ( input 구입금액, output 로또 )
* 구입한 로또와 당첨번호를 입력하면 당첨결과를 알려주는 매소드 ( input 구입한로또, 당첨번호, output 당첨결과 )
LottoGame 내부적으로 해당 로직을 직접구현할지 다른 도메인객체에게 도움을 요청하는지는 LottoGame 내부구현에. 따릅니다

로또를 발급하기위해 필요한 기능(책임)들을 나열하고 역할별로 분리할 수 있다면 다른객체를 생성하거나 이미 존재하는 다른객체에게 기능(책임)을 위임해서 문제를 해결해 나갑니다.

위와 같은 관점에서 리팩토링을 진행해주시면 좋겠습니다. 😄

2021-01-12 02:33 UTC, sehan commented
생각해 보니 로또미션이 내일 까지인걸로 알고 있습니다.
마지막 피드백 내용은 step2 를 진행하면서 함께 고민해 주시는게 좋을거 같습니다. 

화이팅입니다

궁금하신 내용은 slack DM 으로 문의주시면 언제든 환영입니다.

2021-01-12 02:34 UTC, merged

2021-01-12 09:08 UTC, 10000sukk commented on src/main/java/lottoMission/controller/LottoController.java
> +    private UserMoney userMoney;
감사합니다! 삭제 했습니다!

2021-01-12 09:12 UTC, 10000sukk commented on src/main/java/lottoMission/domain/LottoGame.java
LottoGame 클래스의 메서드들이 인자값을 받는 것으로 고쳤습니다! 여기서 의문점이 하나 드는데 그러면 필드에 상태를 저장을 안해도 되기에 필드를 다 없앴습니다. 그러면 LottoGame 의 메서드 기능들을 사용하기 위해서 굳이 객체를 생성할 필요를 느끼지 못해서 혹시나 이 메서드들을 static으로 하면 더 괜찮을 것 같은데 혹시 어떻게 생각하시는지 니오의 생각이 궁금합니다!