[ky.kiske] 로또 미션 코드 리뷰 요청합니다.
NewKrew2021/java-lotto-kakao pull request #16
Opened 2021-01-08 09:50 UTC by SimJung

로또 미션 코드 리뷰 요청드리며 질문이 있습니다만,
LottoManager 클래스에서 한 메소드의 덩치가 좀 커진 것 같아 이를 해결하기 위해 어떤식으로 처리해야할지 궁금합니다.
각 단계별로 메소드를 분리하여 메소드의 수와 깊이를 늘려야 하는 것인지 궁금합니다!
그리고 테스트 코드를 작성할 때, private한 메소드나 반환형이 void인 메소드같이 테스트하기 어려운 메소드는 어떤 식으로 다뤄야할지도 궁금합니다! 감사합니다!!!

2021-01-09 16:45 UTC, kriery requested changes
안녕하세요 카이, 리뷰를 맡게된 크리스입니다.
점점 미션이 커지고, TDD를 꾸미자니 코드가 서로 엉켜서 복잡해지죠?
1. 로또 번호 생성과
2. 결과 처리에서 코드 플로우가 매끄럽지 않은 내용
3. 원시값 포장

관련해서 **수정 요청** 드렸어요.
- 리뷰가 난해하거나 이해가 어려운점, 설계랑 리뷰가 안맞은점.. 
- 아니면 그냥 질문

이 있으면 언제든 DM 은 환영합니다

2021-01-09 16:45 UTC, kriery commented on src/main/java/lotto/domain/LottoGenerator.java
> +        }
hint에서
```
로또 자동 생성은 Collections.shuffle() 메소드 활용한다.
```

라고 되어있는데 굳이 Random을 이용하신 이유가 있을까요?
예를 들어 처음부터 1, 2 라는 번호를 차례대로 뽑을 확률을 고려해보면,
shuffle일땐

```
(45개 중에 1을 뽑을 확률) x (1을 제외한 44개중에 2를 뽑을 확률)
= 1/45 x 1/44
```

이지만,
중복을 제거하는 random 일때는

```
(45개중에 1을 뽑을 확률) x { (45개중에 2를 뽑을 확률) + (45개중에 1을 뽑고 45개중에 2를 뽑을 확률) + (45개중에 1를 뽑고 45개중에 1을 뽑고 45개중에 2를 뽑을 확률) ... }
= 1/45 x (1/45 + 1/45x1/45 + 1/45x1/45x1/45 + 1/45x1/45x1/45x1/45...)
```

이렇게 되서 의미상으로 좀 달라져요

2021-01-09 16:45 UTC, kriery commented on src/main/java/lotto/service/LottoManager.java
> +        lottoOutputView.printProfitRatio(new LottoReview().getProfitRatio(lottos.lottosResult(wonLotto)));
`lottos.lottosResult`는 당첨 결과를 받아온 내용일텐데요,
당첨 결과에 대한 처리를 한번은 `Lottos`에서 하고,
한번은 `LottoReview`에서 하는 것은 다소 어색해 보입니다. 
결과 처리를 일원화 하는 것은 어떨까요?

2021-01-09 16:45 UTC, kriery commented on src/main/java/lotto/service/LottoManager.java
> +        lottoOutputView.printInputWonlottoPhrase();
`지난 주 당첨 번호를 입력해주세요.` 가 두번 출력되고 있어요
<img width="286" alt="image" src="https://user-images.githubusercontent.com/47452850/104100541-8015db00-52e0-11eb-9c8a-3b5bf408ac25.png">

2021-01-09 16:45 UTC, kriery commented on src/main/java/lotto/service/LottoManager.java
> +        int bonusBall=lottoInputView.getBonusBall();
`LottoInputView` 말 그대로 "입력/**보기**" 인데,
입력을 위한 화면 메시지 출력정도는 `InputView`에서 해도 괜찮지 않을까요?

2021-01-09 16:45 UTC, kriery commented on src/main/java/lotto/domain/LottoGenerator.java
> +        return new Lotto(parsedLotto);
전반적으로 빈 Collection을 만들어놓고 loop에서 add 하는 코드 진행이 자주 보이는데요.
이 방법이 틀린것은 아니지만, 앞으로 stream을 활용할 일이 자주 있을거예요.
이 기회에 stream을 활용해 보면 어떨까요?

2021-01-09 16:45 UTC, kriery commented on src/main/java/lotto/domain/WonLotto.java
> +        return LottoRank.FIRST;
`LottoRank` 생성에 대한 책임을 `WonLotto`에서 해주고 있는 것으로 보여요.
결과적으로 `WonLotto`에서 `LottoRank`의 각 단계별 매칭 조건을 다 알고 있어야 할것 같습니다.
매칭에 필요한 정보를 `LottoRank`에게 줘서 적절한  `LottoRank`를 받아오는 방법도 있을것 같아요
예를 들면,
```suggestion
        int matchNo=wonLotto.checkSameCount(lotto);
        boolean isBonusMatched=lotto.getLotto().contains(bonusNo);
        
        return LottoRank.rankForMatched(matchNo, isBonusMatched);
```

2021-01-09 16:45 UTC, kriery commented on src/main/java/lotto/domain/Lotto.java
> +    }
일급 컬랙션을 이용하는 이유중에는, 불필요한 컬랙션의 변경을 차단하는 기능도 포함됩니다.
예를 들어 이미 만들어진 로또(`Lotto`)를 가져와서(`getLotto`), 변경하는 내용도 포함해서 말이죠.
```
getLotto().set(3, 35); 
```
이런 불상사를 막기 위해,
1. 불필요한 getter를 없애거나 
2. 부득이하게 제공을 해야 한다면 불변 객체를 이용하는 방법이 권장됩니다.

2021-01-09 16:45 UTC, kriery commented on src/main/java/lotto/domain/LottoRank.java
> +    FIFTH(5000, 4, "3개 일치 "), NONE(0, 5, "");
`2000000000` 과 같이 반복된 숫자가 너무 길어서 보기가 어려울땐,
`2_000_000_000` 처럼 끊어서 보면 눈이 편해져요.
참고: [Underscores in Numeric Literals](https://docs.oracle.com/javase/7/docs/technotes/guides/language/underscores-literals.html)

2021-01-09 16:45 UTC, kriery commented on src/main/java/lotto/Lotto.java
>      private List<Integer> lotto;
로또를 구성하는 6개의 **숫자**(;`Integer`)가 원시값 포장이 되지 않았어요.
원시값 포장이 귀찮고 _왜 해야하나_ 라는 생각이 들 수도 있는데요.
일급 컬랙션과 마찬가지로, 
1. 불필요한 노출로 인한 정합성 불일치를 피하기 위해
2. 객체에 메서드를 추가해주기 위해(=기능을 더 제공하기 위해)(=역할을 부여하기 위해)(=책임을 넘기기 위해)

인데요.
`List<Integer>`는 [-1,-2,-3,-4,-5,-6] 으로도 이루어질 수 있지만,
`List<로또번호>`는 저렇게 되어서는 안되게 만들 수 있겠죠.

2021-01-11 17:07 UTC, SimJung commented
리뷰 감사합니다!! 언급해주신 부분들 위주로 리팩토링을 진행했습니다.
아낌없는 회초리 부탁드리겠습니다...!!!! 감사합니다!!

2021-01-12 00:42 UTC, kriery approved these changes
안녕하세요 카이, 새벽까지(?) 고민을 많이 하셨군요.
리펙토링은 해도해도 끝이 없겠지만, 객체들간의 분리가 충분하고 책임 이행이 잘 되고 있는것 같습니다.
이번 단계는 여기서 마무리 해도 될것 같아요. 머지 합니다.
아래 남긴 피드백은 다음 단계해서 정리해 주시면 좋겠어요.
그럼 다음 단계에서 뵙죠!

2021-01-12 00:42 UTC, kriery commented on src/main/java/lotto/domain/LottoNumber.java
> +        return new LottoNumber(Integer.parseInt(text));
String으로 넘어온 숫자의 범위에 대한 검사는 이 경우 무시되겠네요
```suggestion
        return makeNumber(Integer.parseInt(text));
```

2021-01-12 00:42 UTC, kriery commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
static factory method :+1:

2021-01-12 00:42 UTC, kriery commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
`isBlank`와 `isNumber`를 이 클래스 안에서만 이용하고 있는데, 이 메서드들은 `LottoNumber`와는 직접적인 관계가 없다 보니까, 별도로 기능을 제공해주는 class가 있으면 좋겠지만 (타 라이브러리에서는 `StringUtils.isBlank` 같은 녀석이 있죠)
validation check를 위해 만들어 쓰는 경우라면 `private`으로 제한하는게 좋을 것 같아요.

2021-01-12 00:42 UTC, kriery commented on src/main/java/lotto/domain/Lotto.java
>          this.lotto = lotto;
(생각해볼 문제) Lotto의 성격상,
- 중복 숫자가 존재하지 않고 (set의 특성)
- sort된 채로 데이터를 관리

해야 한다면, 내부 데이터 구조는 List보다 SortedSet이 더 적합해 보여요.

더 보기: 
- [SortedSet](https://docs.oracle.com/javase/7/docs/api/java/util/SortedSet.html)
- [TreeSet](https://docs.oracle.com/javase/7/docs/api/java/util/TreeSet.html)

2021-01-12 00:42 UTC, kriery commented on src/main/java/lotto/domain/Lotto.java
>          }
이 부분도 stream을 이용하여 간단히 처리할 수도 있습니다
```suggestion
        count = (int)userLotto.lotto.stream()
                .filter(lotto::contains)
                .count();
```

2021-01-12 00:42 UTC, kriery commented on src/main/java/lotto/domain/LottoGenerator.java
> +                .collect(Collectors.toList()));
`List.stream.limit.collect`도 좋지만 보다 간편한 `List.subList`를 이용해 보는건 어떨까요?

2021-01-12 00:42 UTC, kriery commented on src/main/java/lotto/domain/LottoGenerator.java
>          int bonusNo = RandomUtil.getRandomValue();
`generrateLotto`는 `shuffle`로 하셨는데, `generateBonus`는 여전히 `Random`이네요 :sob:
아마 "이미 6개의 번호를 뽑은 상태"에서 다시 `shuffle`을 할 수는 없고,
그렇다고 이미 `shuffle` 해놓은 `List`에서 7번째 element를 뽑자니 정합성이 어긋날까봐 찜찜한 상태일것 같은데요,
두 가지 옵션이 있어요
1. `WonLotto`를 만들어 주는 `LottoGenerator` 메서드를 추가하거나,
2. `Lotto`또는 `WonLotto`를 만들기 위한 중간 모델 (6개 또는 7개의 임의의 숫자)을 반환하는 메서드를 추가

2021-01-12 00:42 UTC, kriery commented on src/test/java/lotto/domain/LottoNumberTest.java
> +        }).isInstanceOf(RuntimeException.class);
`RuntimeException`을 직접 이용하기 보단, 좀 더 세분화 해서 이용하는 것이 좋아요
1. 특정 상황에 대한 Exception(RuntimeException을 상속받는)을 직접 만들어 이용해도 좋고
2. 미리 만들어져 있는 `IllegalArgumentException`과 같은 Exception을 이용하는 것도 좋을것 같습니다

2021-01-12 00:42 UTC, kriery commented on src/test/java/lotto/domain/LottoNumberTest.java
> +        }).isInstanceOf(RuntimeException.class);
`isBlank`의 조건인, `null`값에 대한 테스트도 같이 했으면 좋았을것 같아요!
이 경우 통과는 하는데요, NullPointerException이 발생하고 이 역시 RuntimeException이라서 통과를 하고 있어요.
위에 RuntimeExecption을 세분화 하는 것이 좋다는 내용은 이 얘기였습니다 (_ _)

2021-01-12 00:42 UTC, kriery commented on src/main/java/lotto/domain/LottoNumber.java
> +        return text.isEmpty() || text == null;
```suggestion
        return text == null || text.isEmpty();
```
이 두 가지는 (논리적으로는) 같아 보이지만, 사실 서로 달라요
더 보기: [Short-circuit evaluation](https://en.wikipedia.org/wiki/Short-circuit_evaluation)

2021-01-12 00:42 UTC, merged

2021-01-12 00:47 UTC, kriery reviewed
빠뜨린 리뷰가 있어서 추가했어요 😄

2021-01-12 00:47 UTC, kriery commented on src/main/java/lotto/domain/LottoGenerator.java
> +    }
`LottoGenerator`는 생성자에서 처리해 주는 로직이 없고, static field로만 이루어져 있는데요.
이 경우 굳이 singleton으로 처리할 필요 없이, 각 method들을 static으로 관리하는 helpter class로 전환이 가능할것 같아요.

2021-01-12 00:55 UTC, kriery commented
PR 본문에 있는 질문에 대해서.. 
private / void 메소드에 대한 테스트는 이렇다할 왕도는 없습니다.
그래도 몇가지 추천을 드릴 수 있을것 같아요.

### void method
ex: `void Lottos.add`
`void` method 는 수행 전/후로 클래스 내부 데이터가 변경이 됨을 추측해볼 수 있어요
(만약 그렇지 않다면 static method로 빠져나왔어야 했구요)
그렇다면 그 전/후 데이터로 테스트가 가능하겠죠?

### private method
ex: `LottoReview.calculateRatio`
`private` method는 테스트 객체에서 직접 접근이 곤란해서 테스트 하기가 까다로운데요,
1. method 단위의 직접적인 테스트를 하지 않고, 해당 method를 invoke 하는 다른 method를 테스트 함으로 써 간접적인 테스트를 합니다.
2. `private` method의 로직을 꼭 테스트 해야 하는 경우라면, 한정적으로 제한자를 느슨하게 만들어 줄 수도 있지요
   - ex: `LottoReview.calculateRatio`에 default 제한자를 이용하고, `LottoReviewTest`를 `LottoReview`와 같은 패키지에 넣는다
3. 하지만, method를 간결하게 만들고 method 내부에서 이용하는 타 로직들에 대한 단위 테스트를 충분하게 하여 (1)과 같은 상황으로 만들어 주는 것이 바람직 합니다.

2021-01-12 01:05 UTC, kriery commented
메서드가 길어져서 단계별 메서드를 재생산 하는 부분은,
예를 들면 복잡한 로직을 가진 logic1, logic2, logic3이 있을 때,
```
methodA:
  logic1
  logic2
  logic3
```
처럼 되면 methodA가 너무 길어지는 부분.
또는, logic이 서로 종속적이여야 하는 부분
```
methodA:
   logic1: 이 안에서 if(...) 참이면,
      logic2: 이 안에서 for...
         logic3:
```
처럼 되는 경우일텐데요.
말씀하신것 처럼 각 logic만을 다루는 method를 재생산 하는 것은 가장 최후의 수단으로 남겨두고,
가급적이면 각 logic이 왜 길어지는지를 파악 해서, 해당 처리를 적합한 클래스(또는 새로운 클래스)로 위임하는 것이 좋습니다.