[mark.lim 임상진] 로또 step1 코드리뷰 요청드립니다.
NewKrew2021/java-lotto-kakao pull request #17
Opened 2021-01-08 09:50 UTC by limdef

안녕하세요 마크입니다.

아직 도메인 설계가 쉽지는 않은 것 같습니다. 
피드백 잘 부탁드리겠습니다. 감사합니다.

질문.
도메인내에서 구현을 할 때 getter를 지양하며 원하는 값을 얻어내려다 보니, 
값들을 이리저리 보내면서 복잡해지는 것 같은데 좋은 방법이 있는지 궁금합니다.
(LottoTickets에서 로또 티켓과 당첨 티켓의 일치 개수를 얻기 위해서
LottoTickets ->  LottoWinningNumber -> LottoTicket 의 과정을 거쳤습니다)

## 구현 클래스 요약
### domain
- Amount - 로또 구입 금액을 포장한 클래스
- LottoNumber - 로또 티켓에 사용하는 번호를 포장한 클래스
- LottoTicket - 로또 번호 6개를 가진 클래스
- LottoTickets - 로또 티켓 여러장을 가지는 클래스
- LottoService - 랜덤 로또 티켓을 발급해주는 클래스
- LottoWinningNumber - 당첨 로또 티켓과 보너스 번호를 가지는 클래스
- WinningInfo - 당첨 결과 통계 정보를 가지는 클래스 
### view
- LottoInputView - 입력과 입력 메시지 출력
- LottoOutputView - 결과 출력
### controller
- LottoController - 로또 시뮬레이션에 대한 로직 담당

2021-01-08 12:48 UTC, limmmee-bonjour requested changes
안녕하세요 마크! 로또 미션을 함께하게된 벨입니다 😄 
코드가 전반적으로 깔끔하고 구조가 잘 정리되어 있어서 코드리뷰를 잘 할 수 있었습니다! 👏 
잘해주셨지만 말씀해주신 것처럼 결과값을 얻기위해 너무 복잡도 높은 코드가 만들어졌어요.
이 부분을 해결하기 위해 코멘트 드렸으니 고민해주시고 [ 도전! ]이라고 코멘트 단 부분은 꼭 수정해주세요.
궁금하신 점이 있으시면 언제든 DM 보내주세요. 그럼 화이팅입니다!

2021-01-08 12:48 UTC, limmmee-bonjour commented on src/main/java/controller/LottoController.java
> +        LottoOutputView.printTicketsCount(ticketsCount);
입력 - 서비스(도메인)레이어를 연결시켜주는 DTO를 만들어주셨네요 :) 💯 
DTO 자체를 파라메터로 넘기는게 좋습니다 :)

2021-01-08 12:48 UTC, limmmee-bonjour commented on src/main/java/controller/LottoController.java
> +        LottoNumber bonusNumber = new LottoNumber(LottoInputView.inputBonusNumber());
요 부분은 LottoWinningNumber에서 관심사가 아닐까요~?
단 입력부분은 LottoWinningNumber과 느슨한 상태여야겠죠? LottoWinningNumber는 당첨로또번호와 보너스번호만 알면 되니까요 😉

2021-01-08 12:48 UTC, limmmee-bonjour commented on src/main/java/domain/Amount.java
> +public class Amount {
입력 - 서비스(도메인)레이어를 연결시켜주는 [DTO](https://velog.io/@gillog/Entity-DTO-VO-%EB%B0%94%EB%A1%9C-%EC%95%8C%EA%B8%B0)를 의도하신거라 이해해도 될까요? 👏 
DTO를 만들어주신부분 굿입니다! DTO는 보통 패키지를 따로 만들어주는게 좋아요 :) (domain - dto)

다만 "빈값, 문자(a)"가 들어온다면 어떻게될까요?
기본적인 예외 사항에 대해서는 validation 체크를 해주는 것이 좋습니다 :)
테스트케이스에 이와같은 테스트 코드가 추가되면 좋겠죠?
테스트 케이스는 성공 케이스보다는 항상 실패 케이스에 대해 고민해보아야 해요 :)

2021-01-08 12:48 UTC, limmmee-bonjour commented on src/main/java/domain/Amount.java
> +            throw new InvalidAmountException();
익셉션을 정의해주셨네요 👍  
그러나 메세지가 없어요.
사용자는 익셉션만 보고는 읭? 할수 있겠죠? 메세지를 꼭 넣어주세요 :)

2021-01-08 12:48 UTC, limmmee-bonjour commented on src/main/java/domain/LottoNumber.java
> +    private void validate(int number) {
validation도 나누어서 잘 구현해주셨네요 :) 👍

2021-01-08 12:48 UTC, limmmee-bonjour commented on src/main/java/domain/LottoService.java
> +    }
로또 번호를 LottoService에서 만들어주시고 있네요~
이번 과제는 객체지향 설계 및 도메인을 경험하는 것이니 만큼 한번 고민해봅시다 :)

[ 도전! ] 만약 자동로또번호가 아닌 다른방법으로 로또번호가 만들어지면 어떻게될까요?
해당 부분을 다 바꾸어야할거예요! LottoTicket은 그냥 로또만드는방법 인터페이스를 가지고 와서 번호만 생성하면 되니까요!
만드는 과정은 다른 아이로 넘겨 버립니다.
게다가 지금 구조는 유연하지 못하여 변경에 취약해요! 다른방법로 번호를 받게되면 서비스 레어가 너무너무 뚱뚱해지고 복잡해질거예요!
[이 글](https://velog.io/@kyle/%EB%94%94%EC%9E%90%EC%9D%B8-%ED%8C%A8%ED%84%B4-%EC%A0%84%EB%9E%B5%ED%8C%A8%ED%84%B4%EC%9D%B4%EB%9E%80)을 보시면서 어떻게 유연하게 변경할 수 있을지 고민해 보아요 :) 추가로 로또 만드는 방법은 다 새로운 객체로 넘겨버립니다.

2021-01-08 12:48 UTC, limmmee-bonjour commented on src/main/java/domain/LottoTicket.java
> +    private LottoTicket(List<LottoNumber> numbers) {
생성자는 정적 팩토리 메서드보다 위에 위치하는게 좋습니다 :)

2021-01-08 12:48 UTC, limmmee-bonjour commented on src/main/java/domain/LottoTicket.java
> +    public static LottoTicket ofLottoNumber(List<LottoNumber> numbers) {
정적 팩토리 메서드를 만들어주셨네요 💯 👏

2021-01-08 12:48 UTC, limmmee-bonjour commented on src/main/java/domain/LottoTicket.java
> +    public static LottoTicket ofIntegerNumber(List<Integer> integerNumbers) {
해당 정적메소드 팩토리는 테스트를 위해 존재하네요. 이 메서드 없이 테스트 케이스를 작성할 수 있을까요?
위에서 얘기한대로 전략 패턴을 써서 전략패턴으로 번호를 생성하고,
테스트 케이스에서는 "로또 만드는 방법"인터페이스를 구현한 테스트구현클래스를 만들면? 테스트가 좀 더 쉬워질거예요 :)

[ 도전! ] 해당 메서드 없이 테스트 케이스를 작성해보아요 :)

2021-01-08 12:48 UTC, limmmee-bonjour commented on src/main/java/domain/LottoTicket.java
> +    private final List<LottoNumber> numbers;
중복된 수를 피하려면 List 컬렉션이 적합할까요? :monocle_face:
아래서 validation 체크하는것보다 타입을 바꾸는건 어때요?

2021-01-08 12:48 UTC, limmmee-bonjour commented on src/main/java/domain/LottoTickets.java
> +    private List<LottoTicket> lottoTickets;
요 부분도 final로 정의하면 좋을것같습니다 :)

2021-01-08 12:48 UTC, limmmee-bonjour commented on src/main/java/domain/LottoTickets.java
> +    }
Q. 도메인내에서 구현을 할 때 getter를 지양하며 원하는 값을 얻어내려다 보니,
값들을 이리저리 보내면서 복잡해지는 것 같습니다.
만약 더 큰 프로젝트를 한다면 더 복잡해질 것 같은데, 좋은 방법이 있는지 궁금합니다.
(LottoTickets에서 로또 티켓과 당첨 티켓의 일치 개수를 얻기 위해서
LottoTickets -> LottoWinningNumber -> LottoTicket 의 과정을 거쳤습니다)

A. 이 부분에 대한 답을 여기서 하면 될것같아요! (혹시 제가 잘못 질문을 이해했다면 알려주세요 :))
해당 코드는 너무 어려워요@.@ 숫자가 뭘 의미하는지도 모르겠고 메소드를 이리저리 왔다갔다 해야 이해할 수 있겠어요~

우리는 로또 랭킹과 관련된것만 원하고 있어요! 
내가 산 로또가 1등부터 7등까지 어디에 속하는지, 등수에 따른 당첨금이 얼마인지만 알면 됩니다.
LottoTickets, LottoWinningNumber 계산하고있는 랭킹 클래스를 하나 만들어볼까요?
게다가 이 랭킹은 특정 상태들이있죠! 이럴때 Enum을 사용해보는거 어때요?

Enum에 멤버변수로 당첨금과 일치카운트도 지정할수 있겠죠?
내가가진 로또번호의 당첨 번호일치 개수에 따라 등수가 어떤지, 나중에는 그 등수에 따라 당첨금까지 계산한다면!
좀 더 깔끔한 코드가 될거예요 :)

자 그럼! [ 도전! ] 로또 랭킹에 관련된 Enum 클래스를 만들어 관심사를 모두 여기에 모아주세요 :)
[이 글](https://woowabros.github.io/tools/2017/07/10/java-enum-uses.html)이 도움이 될거예요 화이팅!


+) 추가로 getter를 지양하니 어려운 점이 많을거예요!
(이 부분은 저도 어려운것 같아요.) 최대한 의미있는 메서드를 만들고, 데이터 리스트를 출력할때는 [iterator 패턴](https://jusungpark.tistory.com/25)을 만들고, 주도 도메인을 숨기기위해 DTO를 만들고 하는 방법이 답이 될 수 있을거예요!
프로젝트를 진행하면서 좀 더 고민해보아요 :)!

2021-01-08 12:48 UTC, limmmee-bonjour commented on src/main/java/domain/LottoWinningNumber.java
> +    public List<Integer> getLottoWinningTicket() {
사용되지 않는 메소드는 삭제해주세요 :)

2021-01-08 12:48 UTC, limmmee-bonjour commented on src/main/java/domain/LottoWinningNumber.java
> +    private final LottoTicket lottoWinningTicket;
도메인적으로 생각해보면 당첨된 로또 티켓을 가지고있는걸까요?
그냥 단순히 로또 당첨 번호일것 같은데요 :)
LottoTicket은 내가 산 로또 디켓인데 당첨번호와 의미가 섞여져 있네요.
그래서 LottoTicket-matchTickets() 메서드도 내가 산 로또와 비교하는것인가? 라고 착각할 것 같습니다.
네이밍이나 타입을 좀 더 명확하게 하는 것이 좋습니다 :)

만약 확률에 따른 LottoTicket이 만들어지게된다면 (요구사항은 LottoTicket에 가격과 확률을 높이는 멤버변수가 추가됩니다)
이는 WinningLottoNos까지 영향이 있어야할까요~? 고민해 보면 좋을것같아요 :)

2021-01-08 12:48 UTC, limmmee-bonjour commented on src/main/java/domain/WinningInfo.java
> +    private final List<Long> PRIZE = Arrays.asList(5000l, 50000l, 1500000l, 30000000l, 2000000000l);
이부분도 Enum이 만들어지면 그곳으로 이동시키는게 좋을것같아요 😉 
그리고 상수화 할땐 static을 꼭 잊지 말아요!

2021-01-08 12:48 UTC, limmmee-bonjour commented on src/main/java/domain/exceptions/InvalidAmountException.java
> +public class InvalidAmountException extends RuntimeException{
익셉션 정의 좋습니다 👏

2021-01-08 12:48 UTC, limmmee-bonjour commented on src/test/java/domain/AmountTest.java
> +        Amount amount = new Amount(1000);
생성자 테스트를 좋은 방법으로 잘 해주셨어요 💯 👍
모든 테스트케이스에 @DispayName도 꼼꼼히 달아주셔서 보기 좋습니다 👍

2021-01-08 12:48 UTC, limmmee-bonjour commented on src/test/java/domain/AmountTest.java
> +public class AmountTest {
getCount()에 관련된 테스트케이스도 작성해주세요!

Junit5에는 굉장히 다양한 테스트 어노테이션들이 추가되었습니다!
[해당 글](https://www.baeldung.com/parameterized-tests-junit-5)을 읽어보시면 추후 노가다? 없이 (ㅎㅎ) 간결한 테스트 케이스를 작성하실 수 있으실 거예요!
예를 들어 CsvSource 라던가... ValueSource 라던가...ㅎㅎㅎ

2021-01-08 12:48 UTC, limmmee-bonjour commented on src/test/java/domain/LottoNumberTest.java
> +    @ValueSource(ints = {1, 45})
오오 위에 설명드렸는데 이미 써주시고 계셨군요 👍  좋습니다~~ 👏

2021-01-08 12:48 UTC, limmmee-bonjour commented on src/test/java/domain/LottoTicketsTest.java
> +    @DisplayName("구입 티켓과 당첨 티켓의 번호가 3개가 일치하면 WinningInfo가 1,0,0,0,0 이여야 한다.")
DisplayName 보고 어떻게 동작하는지 알았어요 ㅎㅎㅎ 
자 이제 위에 도전으로 드린대로 다른 방식으로 우리 테스트 케이스를 만들어보아요! 화이팅 !

2021-01-08 13:25 UTC, limdef commented on src/main/java/domain/Amount.java
> +            throw new InvalidAmountException();
메시지 꼭 넣겠습니다 :)

2021-01-08 13:26 UTC, limdef commented on src/main/java/domain/Amount.java
> +public class Amount {
예외 사항을 더 신경쓰도록 해볼게요

2021-01-08 13:36 UTC, limdef commented on src/main/java/domain/LottoTickets.java
> +    }
Enum을 공부해서 사용해보도록 하겠습니다 :)

2021-01-08 13:43 UTC, limdef commented on src/main/java/domain/LottoService.java
> +    }
고민해보겠습니다 :)

2021-01-08 13:43 UTC, limdef commented on src/main/java/domain/LottoWinningNumber.java
> +    private final LottoTicket lottoWinningTicket;
고민해보겠습니다 :)

2021-01-11 04:28 UTC, limdef commented on src/main/java/domain/LottoTicket.java
> +    public static LottoTicket ofIntegerNumber(List<Integer> integerNumbers) {
이 부분을 말씀해주신대로 잘 적용했는지 모르겠습니다.

2021-01-11 04:36 UTC, limdef commented
안녕하세요 벨! 피드백 감사드립니다.

피드백 주신 부분을 최대한 반영해봤습니다.
enum을 사용해보았고, 전략패턴도 적용해보았습니다.
아직 익숙하지 않아서 제대로 적용한 것인지 확신은 없지만..

특히 피드백 주신 부분 중 "로또 만드는 방법"인터페이스를 구현한 테스트구현클래스를 만들어 보면 어떨까 에 대해서도
고민해보고 반영해봤는데 잘 적용했는지.. 궁금합니다.

그리고 WinningInfoTest에서도 뭔가 노가다로 테스트한 것 같아서.. ㅎㅎ 의견이 궁금합니다

2021-01-11 04:38 UTC, limdef commented
안녕하세요 벨! 피드백 감사드립니다.

피드백 주신 부분을 최대한 반영해봤습니다.
enum을 사용해보았고, 전략패턴도 적용해보았습니다.
아직 익숙하지 않아서 제대로 적용한 것인지 확신은 없지만..

특히 피드백 주신 부분 중 "로또 만드는 방법"인터페이스를 구현한 테스트구현클래스를 만들어 보면 어떨까 에 대해서도
고민해보고 반영해봤는데 잘 적용했는지.. 궁금합니다.

그리고 WinningInfoTest에서도 뭔가 노가다로 테스트한 것 같아서.. ㅎㅎ 의견이 궁금합니다

2021-01-11 09:55 UTC, limmmee-bonjour approved these changes
안녕하세요 마크! 😄 
피드백 드린 내용을 모두 잘 적용해주셨어요 💯 💯 
고민하신 흔적이 많이 보입니다! 몇가지 더 고민하면 좋을 내용에 대해 코멘트 남겼습니다 :)
답은 없으니 한번 고민해보아요! 그럼 다음 스텝을 진행해보시죠 화이팅입니다!

2021-01-11 09:55 UTC, limmmee-bonjour commented on src/main/java/controller/LottoController.java
> +        LottoOutputView.printTicketsCount(amount);
관심사를 옮겨 Controller가 깔끔해졌네요 👍 
추가로, inputAmount에서 Amount 객체를 바로 리턴해도 좋을 것 같아요 :)

2021-01-11 09:55 UTC, limmmee-bonjour commented on src/main/java/domain/Lotto.java
> +    private final TreeSet<LottoNumber> numbers;
명시적으로 TreeSet를 적어주는 것도 좋지만
Java Collections API의 목적 중 하나는 구현 세부 정보를 숨기기 위해 인터페이스를 제공하는 다형성이라고 생각합니다.
TreeSet을 써주신 이유가 있을까요~?

2021-01-11 09:55 UTC, limmmee-bonjour commented on src/main/java/domain/Lotto.java
> +    }
정적 팩토리 메서드에서 of와 from의 차이가 있을까요~?
네이밍을 조금 더 고민해보아요 :)!

2021-01-11 09:55 UTC, limmmee-bonjour commented on src/main/java/domain/LottoManualGenerator.java
> +public class LottoManualGenerator implements NumberGenerateStrategy {
전략 패턴을 잘 적용해주셨습니다! 좋습니다 💯

2021-01-11 09:55 UTC, limmmee-bonjour commented on src/main/java/domain/Rank.java
> +public enum Rank {
Rank Enum을 잘 만들어주셨어요! 👍 
로또 랭킹에 관련된 부분이 여기로 다 모여져 있어 보기 편하네요!! 💯

2021-01-11 09:55 UTC, limmmee-bonjour commented on src/main/java/dto/Amount.java
> +            throw new InvalidAmountException("로또 구입 금액은 "+LOTTO_PRICE+"이상이어야 합니다.");
Message 도 추가로 잘 적어주셨네요 👍

2021-01-11 09:55 UTC, limmmee-bonjour commented on src/main/java/controller/LottoController.java
> +        LottoOutputView.printYield(amount, winningInfo.getTotalPrize());
output에서 계산하는 것 보다 수익율도 winningInfo의 관심사 아닐까요?

2021-01-11 09:55 UTC, limmmee-bonjour commented on src/test/java/domain/WinningInfoTest.java
> +public class WinningInfoTest {
Q. 그리고 WinningInfoTest에서도 뭔가 노가다로 테스트한 것 같아서.. ㅎㅎ 의견이 궁금합니다
A. 전반적으로 테스트케이스를 잘 작성해주셨습니다!
노가다라고 생각하시는건 아래 테스트가 테스트값만 변경되고 나머지는 모두 같기 때문에 겠죠?

변경되는 값은 lotto번호, 보너스 번호, 랭킹 이겠죠?
이 값을 사용해주신 @CsvSource 를 사용해서 하나의 테스트케이스로 만들수 있지 않을까요?
@ParameterizedTest의 name 을 사용하면 테스트별 description도 동적으로 만들수 있어요!

2021-01-11 09:55 UTC, limmmee-bonjour commented on src/test/java/domain/LottoTest.java
> +        LottoManualGenerator generator = new LottoManualGenerator(Arrays.asList(1, 2, 3, 4, 5, 45));
Q. 특히 피드백 주신 부분 중 "로또 만드는 방법"인터페이스를 구현한 테스트구현클래스를 만들어 보면 어떨까 에 대해서도
고민해보고 반영해봤는데 잘 적용했는지.. 궁금합니다.
A. 네 잘 적용해주셨습니다 👏 
제가 의도했던 바는 아래와 같습니다! 중복되니 일반적으로 사용하는 테스트 generator를 만드는 것이었어요 :) 
```
public class LottoGeneratorTest implements NumberGenerateStrategy {

        @Override
        public Lotto generate() {
            // 1,2,3,4,5,6
            Set<Integer> lottoNumber = IntStream.range(1, 7)
                    .boxed()
                    .collect(Collectors.toSet());

            return Lotto.of(lottoNumber);
        }
    }
```

2021-01-11 09:55 UTC, merged

2021-01-11 10:49 UTC, limdef commented on src/main/java/domain/Lotto.java
> +    private final TreeSet<LottoNumber> numbers;
구현 세부 정보를 숨기는 것 까지는 미처 생각 못했네요!
또 하나 배워갑니다 :)

2021-01-11 10:50 UTC, limdef commented on src/main/java/domain/Lotto.java
> +    private final TreeSet<LottoNumber> numbers;
구현 세부 정보를 감추는 것 까지는 미처 생각 못했네요!
또 하나 배워갑니다 :)