[bmo.adventure] 로또 미션 코드리뷰 요청합니다.
NewKrew2021/java-lotto-kakao pull request #18
Opened 2021-01-08 10:17 UTC by dddfff22

안녕하세요!
로또 미션 코드리뷰 요청드립니다.

궁금한 점이 있습니다. 
1. mvc 패턴으로 패키지를 분리할때, 입력부분은 controller, 출력부분은 view, 도메인은 domain으로 하고, 그외 로직을 담당하는 부분은 service로 현하였는데요 이렇게 하는게 맞을까요?
2. 여러 클래스에서 중복되서 사용하는 변수를 static으로 만들어 LottoFixedValue 클래스에 넣었는데요. 이 방식 말고 enum을 만들고 get으로 값을 가져오는게 더 좋은 방법일까요?

2021-01-09 11:42 UTC, findstar requested changes
안녕하세요 로또 미션 리뷰를 하게된 제임스입니다.
주말이라 조금 늦게 리뷰를 진행했네요. 수고 많으셨습니다. 👏
다음은 리뷰에 남겨주신 질문에 대한 답변입니다.
Controller는 말 그대로 컨트롤, 즉 제어하는 역할을 수행합니다. 
이 과제에서는 간단하게 InputView, OutputView 클래스 인스턴스를 넘겨받아서 처리할 수 있습니다. 

여러 클래스에서 중복되어 사용된다면 각각의 역할 분리가 잘되지 않았다고도 볼 수 있습니다.
과제에서 사용되는 전체 상수를 위한 static 클래스를 만드셨는데 각각의 클래스에서 책임을 가질 수 있도록 개선해보는게 어떨까요?

코멘트와 함께 추가로 다음 사항을 고민해봐주세요.
1. 코드 스타일을 맞추기 위해서 reformat 을 활용해보세요. 
2. 테스트 코드를 작성할 때는 커버리지를 확인해봐주세요. 현재는 각각의 메서드에 대한 테스트가 충분하지 않아 보입니다.
그럼 화이팅입니다.

2021-01-09 11:42 UTC, findstar commented on src/main/java/lotto/domain/LottoFixedValue.java
> +public class LottoFixedValue {
LottoFixedValue 라는 클래스로 Lotto 어플리케이션의 모든 상수값을 모아두기 보다는
각각의 역할을 담당하는 클래스가 가지고 있는 것이 더 낫습니다. 

특히 당첨금액은 enum 클래스에 있는 것이 맞습니다. 😄

2021-01-09 11:42 UTC, findstar commented on src/main/java/lotto/domain/Lottos.java
> +
공백도 의미있게 사용합니다. 코드 스타일이 정돈되어 있으면 다른 사람이 짠 코드라도 내가 짠 것 처럼 읽힙니다.
코드 스타일이 다르면 내용보다도 형식에 눈이 밟히는 경우가 많거든요 😄

2021-01-09 11:42 UTC, findstar commented on src/main/java/lotto/service/LottoGeneratorService.java
> +        if (number > LottoFixedValue.LOTTO_MAX_INT || number <= 0) {
LottoNumber 를 별도의 클래스로 분리해보면 어떨까요?
숫자 범위에 대한 책임이 분리될 수 있습니다.

2021-01-09 11:42 UTC, findstar commented on src/main/java/lotto/domain/Lottos.java
> +    public Lottos(List<Lotto> lottos) {
이 메서드는 현재 사용하는 곳이 없습니다.

2021-01-09 11:42 UTC, findstar commented on src/main/java/lotto/controller/LottoController.java
> +    private final LottoView lottoView = new LottoView();
컨트롤러에 생성자가 없네요. 
InputView / OutputView 를 구분하고 이를 생성자에서 주입받아서 사용해보세요.

2021-01-09 11:42 UTC, findstar commented on src/main/java/lotto/view/LottoView.java
> +public class LottoView {
LottoView 를 통째로 사용하기 보다는
InputView 와 OutputView 를 구분해보는건 어떨까요?

2021-01-09 11:42 UTC, findstar commented on src/main/java/lotto/controller/LottoController.java
> +        lottoView.printSameCountPhrase(lottos.lottosRankingResult(lottos.lottosResult(wonLotto)));
메서드 호출의 깊이가 너무 깊지는 않나요?

2021-01-09 11:42 UTC, findstar commented on src/main/java/lotto/controller/LottoController.java
> +    public int validateLottoBuyAmount(int amount) {
1. 로또 구입 금액이 음수가 들어오면 어떻게 되나요?
2. 로또 구입 금액은 1000 단위로 떨어지지 않더라도 구매 가능해야 합니다. 로직을 개선해보세요 😄

2021-01-09 11:42 UTC, findstar commented on src/main/java/lotto/controller/LottoController.java
> +        while ((amount = getLottoBuyAmount()) == -1) ;
이런 코드는 눈에 잘 읽히지 않고 의미를 파악하기 어렵습니다.
입력받은 값을 별도의 클래스로 분리해보면 어떨까요?

2021-01-09 11:42 UTC, findstar commented on src/main/java/lotto/domain/Lotto.java
> +    private List<Integer> lotto;
Lotto 안에 Lotto 가 있네요. 의미가 있는 네이밍을 짓도록 고민해봐주세요 😄

2021-01-09 11:42 UTC, findstar commented on src/main/java/lotto/domain/Lotto.java
> +            count += lotto.contains(number) ? 1 : 0;
Lotto 객체에 contain 메서드를 만들어보세요. 구조가 더 단순해 질 수 있습니다.

2021-01-12 14:03 UTC, findstar requested changes
안녕하세요. 제임스 입니다. 
기능을 잘 구현해주셨는데요, 개선할 부분이 있어서 코멘트 남겼습니다. 
확인부탁드립니다. 

궁금하신 점 있으면 언제든 문의주세요!

덧) 단계별로 진행되는 과제를 위해서
PR 은 기존 appoved 된 PR을 다시 오픈하지 마시고, 새로운 브랜치에서 작성하여 요청하시는 것이 좋습니다
다음번에는 참고해주세요 😄

2021-01-12 14:03 UTC, findstar commented on src/main/java/lotto/view/LottoInputView.java
> +            int money = Integer.parseInt(scanner.nextLine());
scanner.nextInt() 를 사용하면 integer 값을 획득할 수 있습니다.

2021-01-12 14:03 UTC, findstar commented on src/main/java/lotto/controller/LottoController.java
> +        while (amount == null);
null 을 사용한 무한 루프를 사용하셨는데 이런 코드는 오류가 나기 쉽습니다.
올바른 입력을 받을 때까지 계속 입력값을 받는 의도인것으로 보입니다.
여기에서는 단순히 잘못된 입력에 대한 IllegalArgumentException 을 throw 하고 종료하도록 변경해보세요 :)

2021-01-12 14:03 UTC, findstar commented on src/main/java/lotto/view/LottoOutputView.java
> +
입력화면에서 보여줄 메세지는 InputView 클래스로 옮겨보는건 어떨까요?
출력화면에서 보여줄 메세지만 남겨놓는게 좋을것 같습니다.

2021-01-12 14:03 UTC, findstar commented on src/main/java/lotto/view/LottoOutputView.java
> +    public void printInputDuplicatePhrase() {
이 메서드는 호출되는 곳이 없습니다.

2021-01-12 14:03 UTC, findstar commented on src/main/java/lotto/service/LottoGeneratorService.java
> +    private static final ArrayList<LottoNumber> lottoSelectors;
ArrayList 를 사용하기 보다 List 를 사용하는 것을 권장합니다. 
구체적인 타입을 명시하기 보다 List 컬렉션을 사용하여 조금  더 유연하게 작성해보세요. 
참고 링크 : https://stackoverflow.com/questions/2279030/type-list-vs-type-arraylist-in-java

2021-01-12 14:03 UTC, findstar commented on src/main/java/lotto/service/LottoGeneratorService.java
> +
공백도 컨벤션입니다. 
java 코드 컨벤션을 찾아보세요:)

2021-01-12 14:03 UTC, findstar commented on src/main/java/lotto/view/LottoInputView.java
> +        String wonLotto = scanner.nextLine();
이경우는 바로 return 하는게 더 나아보입니다.

2021-01-12 14:03 UTC, findstar commented on src/main/java/lotto/view/LottoInputView.java
> +        int bonusBall = Integer.parseInt(scanner.nextLine());
scanner.nextInt() 를 사용하면 integer 값을 획득할 수 있습니다.

2021-01-12 14:03 UTC, findstar commented on src/main/java/lotto/domain/LottoNumber.java
> +    private static final int LOTTO_SMALL_INT = 1;
LOTTO_MAX_INT 와 맥락을 맞추려면 LOTTO_MIN_INT 가 더 나아보입니다.

2021-01-12 14:03 UTC, findstar commented on src/main/java/lotto/service/LottoGeneratorService.java
> +    public Lotto generateLotto() {
generateAutoLotto 가 더 어울릴것 같습니다.

2021-01-12 14:03 UTC, findstar commented on src/main/java/lotto/service/LottoGeneratorService.java
> +    static {
다음과 같이 캐싱해놓고 사용할 수 있습니다. 그런데 이 로직이 Generator 에 있어야 할까요?
아니면 LottoNumber 에 있어야 할까요? 고민해보면 좋겠습니다. 

```java
private static final List<LottoNumber> lottoSelectors = IntStream.rangeClosed(LOTTO_SMALL_INT, LOTTO_MAX_INT)
            .mapToObj(LottoNumber::new)
            .collect(Collectors.toList());
```

2021-01-12 14:03 UTC, findstar commented on src/main/java/lotto/domain/LottoRank.java
> +    FIRST(2_000_000_000, 0, "6개 일치 "), SECOND(30_000_000, 1, "5개 일치, 보너스 볼 일치"),
요런 경우에는 한줄씩 내려서 작성하는게 가독성이 더 좋습니다.

2021-01-12 14:03 UTC, findstar commented on src/main/java/lotto/domain/LottoRank.java
> +    LottoRank(int money, int index, String matchedPhrase) {
index 를 지정하지 말고 matchedCount 를 정의해서 사용해보세요. 

매칭 카운트와 보너스 번호 유무를 인자로 받는 스태틱 메서드를 추가해보세요.

2021-01-12 14:03 UTC, findstar commented on src/main/java/lotto/domain/LottoRanks.java
> +        double ratio = (double) totalPrize() / (double) (lottoRanks.size() * LOTTO_PRICE);
이런 경우에는 BigDecimal 을 사용하면 좀 더 간결해집니다.

2021-01-12 14:03 UTC, findstar commented on src/main/java/lotto/domain/LottoRanks.java
> +    private List<Integer> rankStatistics() {
LottoResult 를 위한 별도의 클래스를 정의해보는건 어떨까요?

2021-01-12 14:03 UTC, findstar commented on src/main/java/lotto/domain/WonLotto.java
> +    }
이 코드의 역할을 LottoRank 로 옮겨보세요 😄

2021-01-12 14:03 UTC, findstar commented on src/main/java/lotto/domain/Lottos.java
> +public class Lottos {
일급객체 사용 좋습니다. 💯

2021-01-12 14:03 UTC, findstar commented on src/main/java/lotto/domain/WonLotto.java
> +    public WonLotto(Lotto lotto, LottoNumber bonusNo) {
WonLotto 를 로또와 당첨번호를 인자로 받는 생성자로 구성하셨네요 💯

2021-01-12 14:03 UTC, findstar commented on src/test/java/lotto/domain/LottosTest.java
> +        wonLotto = new WonLotto(new Lotto(Arrays.asList(new LottoNumber(1), new LottoNumber(2), new LottoNumber(3), new LottoNumber(4), new LottoNumber(5), new LottoNumber(6))), new LottoNumber(7));
Lotto 클래스에 문자열을 입력받아 Lotto 인스턴스를 생성하는 스태틱 메서드를 추가해보세요. 
테스트 코드가 한결 간결해질 수 있습니다.

2021-01-13 12:32 UTC, dddfff22 commented
초기 설계의 중요성을 느꼈습니다. 
클래스 역할이 명확하지 않으니 리펙토링 할때 권한을 어디로 위임해야할지 정하기가 어렵네요 ㅠㅠ

2021-01-13 14:43 UTC, findstar requested changes
안녕하세요. 피드백 진행하는 제임스 입니다.
지난번 코멘트드린 내용을 수정해주셨는데
아직 몇가지 추가로 개선하면 좋을 부분이 있습니다.
확인부탁드립니다. 계속 화이팅해주세요 😄 
궁금한점은 언제든지 질문 부탁드립니다.

2021-01-13 14:43 UTC, findstar commented on src/main/java/lotto/domain/LottoNumber.java
> +
참고로 스트림을 사용하면 다음과 같이 선언할 수도 있습니다. 
```java
private static final Map<Integer,LottoNumber> lottoNumbers = IntStream.rangeClosed(LOTTO_MIN_INT, LOTTO_MAX_INT)
            .boxed()
            .collect(toMap(Function.identity(),LottoNumber::new));
```

2021-01-13 14:43 UTC, findstar commented on src/main/java/lotto/service/LottoGeneratorService.java
> +    private static final int LOTTO_SMALL_INT = 1;
LottoNumber 에 이미 이러한 정보가 있으니 LottoNumber 에 역할을 위임하는게 어떨까요?

2021-01-13 14:43 UTC, findstar commented on src/main/java/lotto/service/LottoGeneratorService.java
> +    }
LottoNumber 로 위임할 수 도 있을것 같습니다.

2021-01-13 14:43 UTC, findstar commented on src/main/java/lotto/view/LottoInputView.java
> +    private final String INPUT_MONEY_PHRASE = "구입금액을 입력해주세요.";
입력화면을 담당하는 InputView 에서 메세지도 같이 확인할 수 있으니 좀 더 역할이 잘 구분된것 같습니다. 💯

2021-01-13 14:43 UTC, findstar commented on src/main/java/lotto/domain/Lottos.java
> +            int matchNo = wonLotto.getWonLotto().checkSameCount(lotto);
가급적 축약해서 사용하지 않는 것이 좋습니다. 
checkSameCount 의 결과니까 matchCount 정도가 더 적당하지 않을까요?

2021-01-13 14:43 UTC, findstar commented on src/main/java/lotto/domain/WonLotto.java
> +    public LottoNumber getBonusNo() {
이것도 축약을 제거해주세요. getBonumNumber 라고 변경하는게 어떨까요?

2021-01-13 14:43 UTC, findstar commented on src/main/java/lotto/domain/Lotto.java
> +    public int contain(LottoNumber number) {
여기서는 boolean 값을 반환하는게 더 나아보입니다.

2021-01-13 14:43 UTC, findstar commented on src/main/java/lotto/domain/LottoRank.java
> +    }
다음과 같이 작성할 수도 있습니다. 그런데 isBonus 가 int 형식이네요 . 수정이 필요해보입니다. 
```java
        if(matchNo == SECOND.matchedCount && isBonus == 1) {
            return SECOND;
        }

        return Arrays.stream(values())
                .filter(r -> r.matchedCount == matchNo)
                .findFirst()
                .orElse(LottoRank.NONE);
```

2021-01-13 14:43 UTC, findstar commented on src/main/java/lotto/domain/LottoResult.java
> +
수익률은 구입금액의 정보를 가지고 있는 Amount 에서 값을 받아서 처리하는게 어떨까요? 
금액에 대한 역할이 LottosResult 에도 있고, Amount 에도 있습니다.

2021-01-14 01:13 UTC, dddfff22 commented on src/main/java/lotto/domain/LottoResult.java
> +
역할을 위임하는 어떤 기준이 있을까요? 역할을 나누는부분이 너무 어렵네요 ㅠㅠ

2021-01-14 12:31 UTC, findstar approved these changes
안녕하세요 제임스 입니다. 
설계에 대한 고민을 토로해주셨는데요
DM 과 코멘트로 가이드 해드린대로 수정해주시면 좋겠습니다.
일단 이 PR 은 머지하고 수동 입력과 관련된 사항을 추가해주세요.

2021-01-14 12:31 UTC, findstar commented on src/main/java/lotto/domain/LottoNumber.java
> +        numbers = numbers.subList(0, Lotto.LOTTO_NUMBER_COUNT);
Lotto 클래스에 의존하지 않도록 개선해주세요.

2021-01-14 12:31 UTC, findstar commented on src/main/java/lotto/domain/Amount.java
> +    public int BuyCount() {
Amount 에 로또 구입 금액, 거스름돈 정보등을 담을 수 있습니다.

2021-01-14 12:31 UTC, findstar commented on src/main/java/lotto/domain/LottoRank.java
> +    public static LottoRank checkRanking(int matchCount, boolean isBonus) {
isBonus 가 boolean 으로 수정되었네요 💯

2021-01-14 12:31 UTC, findstar commented on src/main/java/lotto/view/LottoOutputView.java
> +    private final String INPUT_QUANTITY_PHRASE = "개를 구매했습니다.";
이것도 InputView 로 이동해도 좋습니다.

2021-01-14 12:31 UTC, merged