[kuri.copper 송동욱] 로또 step1 리뷰 요청드립니다.
NewKrew2021/java-lotto-kakao pull request #19
Opened 2021-01-08 10:19 UTC by D-kuri

안녕하세요 kuri입니다 :) 
아직까지 TDD나 자바 문법에 익숙하지 않아 단계를 진행해가며 많은 것을 배우고 있습니다.
몇가지 질문드리고 싶습니다 !

1. controller에서 결과를 출력하기 위해 view에 string을 인자로 전달함으로써 거의 대부분을 처리하고 있는데 view에서 논리를 처리하여 출력을 해도 되는지 궁금합니다.
2. 1번과 비슷한 질문인데 출력을 위해 도메인 내부에 결과를 만들어내어 get과 같은 방법으로 String을 전달해주는 방법을 사용하고 있습니다. 어떻게 보면 getter와 비슷하게 사용중인것 같은데 이렇게 사용해도 되는지 궁금합니다.

**클래스 설명**
---------------------------------------------------
- controller
LottoGame : 뷰와 연동하여 입출력을 관리하고 도메인과 연동된 부분
- domain
Number : 숫자 유효성 검사와 숫자 정보 저장
LottoNumber : 1-45까지의 숫자 생성, 45개의 숫자를 섞고 6개를 전달
LottoTicket : 로또 티켓에 대한 정보, 숫자 1개의 일치여부, 다른 티켓과의 같은 숫자 포함 여부, 당첨번호를 이용해 당첨 정보 확인
LottoTickets : 로또 티켓들에 대한 정보, 당첨정보를 이용해 자신이 가지고 있는 전체 티켓의 당첨 정보 확인
WinningNumber : 6개의 로또 숫자 정보와 보너스 정보를 저장
LottoRank : enum으로 로또 순위 정보 저장
RankTable : (맞은숫자, 보너스 일치여부)를 통한 당첨 정보 저장
LottoResults : 생성자를 통해 초기 모든 당첨 정보는 0으로 초기화, 당첨될 경우 당첨 정보 증가, 전체 결과 반환
- view
InputView : 입력과 관련된 기능
ResultView : 로또 결과 출력, 입력된 금액에 따른 로또 티켓 정보 출력

2021-01-10 11:39 UTC, sehan commented
> 1. controller에서 결과를 출력하기 위해 view에 string을 인자로 전달함으로써 거의 대부분을 처리하고 있는데 view에서 논리를 처리하여 출력을 해도 되는지 궁금합니다.

알고 계시듯이 MVC 에서 View 의 역할은 보여지는 영역에 대한 처리입니다. view 에서 논리를 처리한다는게 도메인이 처리해야할 논리(책임)을 말하는 것이라면 view 영역에 구현하면 안됩니다. model 에서 view 에 필요한 data 를 전달해주면 그 data 를 기반해서 view 를 구성하는 것이라면 괜찮습니다.  

> 2. 1번과 비슷한 질문인데 출력을 위해 도메인 내부에 결과를 만들어내어 get과 같은 방법으로 String을 전달해주는 방법을 사용하고 있습니다. 어떻게 보면 getter와 비슷하게 사용중인것 같은데 이렇게 사용해도 되는지 궁금합니다.

중요한것은 get 으로 가져오는 String 이 View 에 의존적인지가 중요합니다. Domain model 변경없이 View 의 구성을 변경할 수 있는가? 하는 부분을 고민해 보시면 좋겠습니다.

2021-01-10 14:27 UTC, sehan requested changes
안녕하세요. 로또미션을 함께 하게된 니오입니다. 
금요일 저녁 리뷰주셨는데 주말이라 리뷰가 많이 늦었습니다. 😓

MVC 구조로 패키지 구분은 잘 되어 있지만 View 의 역할이 Model 쪽에 섞여 있는 부분들이 보입니다.
또한 Model 에 있어야할 역할을 Controller 가 담당하고 있는 부분도 눈에 띄입니다. 
레이어간 역할 분담이 더 필요해 보이고 객체의 역할과 책임들이 명확하지 않은 곳들이 좀 있습니다.
관련 내용을 코멘트로 남겨 놓았습니다. 내용 확인해 보시고 개선 요청드립니다. 

Request Changes 하겠습니다. 화이팅 👍👍👍

2021-01-10 14:27 UTC, sehan commented on src/main/java/lotto/controller/LottoGame.java
> +public class LottoGame {
Controller 역할을 하는 main() 에서 LottoTickets 을 생성하는 책임을 가지고 있습니다.
로또를 생성(발급) 하는 책임을 새로운 도메인 객체에게 넘겨주면 controller 에 구현된 로직을 model 로 옮길 수 있습니다.



도메인 객체에게 로또생성의

2021-01-10 14:27 UTC, sehan commented on src/main/java/lotto/controller/LottoGame.java
> +    private static WinningNumber setWinningNumber() {
WinngingNumber 를 생성하는 static factory method 입니다. WinningNumber 로 로직을 이동시킬 수 있습니다. 
그렇게 하면 WinningNumber 를 생성하기 위해 포장된 Number 를 사용는 것이 아니라 primitive type 을 그대로 사용할 수 있어서 WinngingNumber 를 사용할때 Number 를 알 필요가 없어집니다. 그만큼 WinngingNumber 를 생성하기 편리해지고 쉬워 집니다.

2021-01-10 14:27 UTC, sehan commented on src/main/java/lotto/domain/LottoTickets.java
> +        LottoResults lottoResults = new LottoResults();
LottoResults 를 생성하는 method 입니다. 
LottoResults 를 생성하기 위해 LottoResults 에 upsert() 매소드가 추가되어 있습니다.
upsert 는 객체 생성을 위해서만 사용됩니다. 생성 이후 에는 필요가 없는 매소드 입니다. 또한 LottoResults 는 한번 생성된 이후에는 그 결과가 변경되어서는 안됩니다. 
 LottoResults 객체가 생성되면 immutable ( 변경불가 ) 하도록 해주세요.

2021-01-10 14:27 UTC, sehan commented on src/main/java/lotto/domain/LottoResults.java
> +    public LottoResults() {
LottoResults 는 DTO 입니다.  생성자에서 로또결과와 구입가격을 입력받아 총수익율을 계산해 두고 getter 만 제공하는것이 LottoResults 이 역할에 적합해 보입니다. 
지금은 Map<LottoRank, Integer> results 을 final 로 선언 후 upsert() 매소드로 내부값을 변경하고 있습니다. java 에서 final 은 초기 할당시에만 제약을 가지기 때문에 Map 같은 경우 생성 이후 내부값을 변경할 수 있게 되어 주의가 필요합니다.

2021-01-10 14:27 UTC, sehan commented on src/main/java/lotto/domain/LottoResults.java
> +    public String result(int price) {
1. 컨벤션에 따라 get 을 붙여 주세요 😊
2. 수익율을 가져오는 매소드인데 result 는 매소드의 기능에 부적합한 이름입니다. 적합한 이름으로 변경 해주세요
3. 수익율을 계산시 구입가격은 변경되면 안되는 값입니다. 로또구입시 5000원을 지불하고 로또결과 수익율을 구할때 다른값을 입력하여 잘못된 수익율을 구할 위험이 있습니다. 
 즉, LottoGame 에서 로또생성시 구입금액을 입력하고 결과를 볼때 구입금액을 입력하고 있습니다. controller 구현시 실수를 한다면 잘못된 수익율을 제공합니다.
4. 수익율을 구하는데 view 로직이 섞여 있습니다. 분리해주세요

2021-01-10 14:27 UTC, sehan commented on src/main/java/lotto/domain/LottoResults.java
> +    public String toString() {
view 구현을 의식해 result() 는 수익율에 대한 view format 문자열을 toString() 은 로또결과에 대한 view format 을 구현한것으로 보입니다.  view 관련 로직은 view 로 옮겨주세요

2021-01-10 14:27 UTC, sehan commented on src/main/java/lotto/domain/LottoTicket.java
> +    public int matchCount(LottoTicket compareTicket) {
내부에서만 사용됩니다.  private 으로 변경해주세요

2021-01-10 14:27 UTC, sehan commented on src/main/java/lotto/domain/WinningNumber.java
> +    public boolean contains(Set<Number> numbers) {
contains 라는 매소드명이 기능을 잘 표현하지 못하고 있습니다.
보너스번호가 로또번호에 포함되어 있는지 확인해주는 기능을 하지만 매소드명은 번호들이 당첨번호에 포함되어 있는지 여부를 묻고 있는거 같습니다.

2021-01-10 14:27 UTC, sehan commented on src/main/java/lotto/domain/LottoTicket.java
> +        return RankTable.get(count * 10 + (bonus && count == 5 ? 1 : 0));
현재 순위를 구하기 위한 로직이 LottoTicket , RankTable 에 분산되어 있습니다. 
랭킹을 구하기 위해 필요한 입력은 matchCount, bonus 입니다.  분산되어 있는 순위로직을 LottoRank 에게 넘겨주면 LottoTicket , RankTable 에서 순위로직을 제거 할 수 있고 LottoRank 에서 조건에 따른 순위를 단위테스트로 작성하기 용이해집니다.

2021-01-10 14:27 UTC, sehan commented on src/main/java/lotto/exception/InvalidNumberException.java
> +package lotto.exception;
해당 exception 은 domain 에서만 사용되기 때문에 domain 패키지로 이동하는 것이 좋습니다.

2021-01-10 14:27 UTC, sehan commented on src/main/java/lotto/exception/InvalidNumberException.java
> +        System.out.println(INVALID_NUMBER);
상위클래스인 RuntimeException 에 message 를 인자로 받는 생성자가 있기 때문에 보통 아래와 같이 사용합니다. 
```suggestion
      super(INVALID_NUMBER);
```

메세지를 console 에 출력하기 위함 이라면 try/catch 후 exception.getMessage() 로 가져온 후 출력할 수 있습니다.

2021-01-10 14:27 UTC, sehan commented on src/main/java/lotto/domain/Number.java
> +    public Number(int number) {
원시값 포장 잘 하셨네요 👍

2021-01-10 14:27 UTC, sehan commented on src/test/java/lotto/NumberTest.java
> +    void exceptionTest() {
최대값을 넘어서는 경계값 테스트는 없네요. 추가해주세요 😊

2021-01-10 16:17 UTC, D-kuri commented on src/main/java/lotto/controller/LottoGame.java
> +    private static WinningNumber setWinningNumber() {
말씀해주신대로 놀라울만큼 생성하는데 있어 편리해지고 코드의 길이가 짧아졌습니다 !!

2021-01-10 17:07 UTC, D-kuri commented on src/main/java/lotto/domain/LottoTicket.java
> +    public int matchCount(LottoTicket compareTicket) {
외부에서도 사용하는 기능이되어 public 그대로 유지했습니다 !!

2021-01-11 07:55 UTC, sehan requested changes
안녕하세요. kuri~
피드백 반영해 주셔서 감사합니다. 👍

추가로 몇가지 수정사항을 좀 더 드렸습니다. 
* 객체의 상태를 꺼내지 않고 객체에 메세지를 보내는 방식으로 개선해야 할 부분들이 좀 보입니다.
* static 이 잘못사용되고 있는 부분들도 코멘트 드렸습니다. 
* RankTable 을 제거하고 LottoRank 로 순위판단로직을 이동시킬 것을 제안드렸습니다
* LottoResults 에 대한 단위테스트 보강이 필요합니다. 

코멘트 확인 부탁드려요 : )

2021-01-11 07:55 UTC, sehan commented on src/main/java/lotto/domain/WinningNumber.java
> +    public WinningNumber(String winningNumber, int bonusNumber){
👍 👍 👍

2021-01-11 07:55 UTC, sehan commented on src/main/java/lotto/domain/LottoTickets.java
> +                            lottoTicket.contains(winningNumber.getBonusNumber())));
winningNumber 에서 bonusNumber 를 꺼내오지 않고 winningNumber 에게 메세지를 보내 보너스번호가 lottoTicket 에 포함되었는지 여부를 요청하면 어떨까요? 그렇게 되면 bonusNumber 를 꺼내지 않고도 포함여부를 확인할 수 있습니다.

2021-01-11 07:55 UTC, sehan commented on src/main/java/lotto/domain/LottoTickets.java
> +    public Map<LottoRank, Integer> getResults(WinningNumber winningNumber) {
Map 을 return 하는것도 좋지만 그보다 좋은 LottoResults 를 그대로 return 하는것이 더 좋겠네요 😊

2021-01-11 07:55 UTC, sehan commented on src/main/java/lotto/domain/LottoResults.java
> +        lottoResults = new LottoResults(lottoTickets, winningNumber);
static factory method 로 생성한 객체를 static member 로 할당해서 사용하고 있는데 필요없는 부분입니다.
아래와 같이 그대로 return 해서 사용하면 됩니다.
```
return new LottoResults(lottoTickets, winningNumber);
```

2021-01-11 07:55 UTC, sehan commented on src/main/java/lotto/domain/LottoResults.java
> +        }};
생성자에서 results.get(rank) 가 존재하지 않을 경우를 대비한 초기화 코드라면 
results 에 Map.putIfAbsent() , Map.computeIfPresent 같은 매소드를 활용해 보세요.
또다른 팁으로는 map() 으로 List<LottoTicket> 을 List<LottoRank> 로 변환한 후 Collectors.toMap() 을 사용하면 간결하게 results 를 만들 수 있습니다
```
Collector<T, ?, Map<K,U>> toMap(Function<? super T, ? extends K> keyMapper,
                                    Function<? super T, ? extends U> valueMapper,
                                    BinaryOperator<U> mergeFunction)
```

2021-01-11 07:55 UTC, sehan commented on src/main/java/lotto/domain/LottoResults.java
> +    private Map<LottoRank, Integer> getResults(){
Map 을 return 해서 view 가 모든것을 알아서 하게 할수도 있지만 LottoResults 의 역할을 매소드를 통해 더 잘 드러내고자 한다면 LottoResults 에게 "로또 1등에 당첨된 로또수를 알려줄래?" 하는 메세지를 보내서 도움을 요청 할 수 있도록 getCountOfRankedLotto(LottoRank) 같은 매소드를 제공해주면 LottoResults 가 제공하려는 것에 대해 그 의미가 더 명확해 집니다.

2021-01-11 07:55 UTC, sehan commented on src/main/java/lotto/domain/RankTable.java
> +        return RANK_TABLE.get(matchCount * 10 + (bonusNumber && matchCount == 5 ? 1 : 0));
LottoTicket 에서 순위로직 제거까지 성공했습니다. 👍 
여기서 한번더 고민해 볼 필요가 있습니다. RankTable 이정말 필요할까? 에 대해서 입니다. 
enum 인 LottoRank 에 순위결정에 필요한 속성을 추가해주면  RankTable 에서 사용하고 있는 matchCount * 10 + bonusNumber 같은 수식 계산없이 matchCount, matchBonus 2개 값을 가지고 순위를 판단할 수 있습니다.

복잡한 수식없이 처리가능하다면 수식은 제거하는것이 좋습니다.
RankTable 을 제거에 도전해보세요 😊

2021-01-11 07:55 UTC, sehan commented on src/main/java/lotto/domain/WinningNumber.java
> +    public Number getBonusNumber() {
LottoResults 에서 코멘드 드렸듯이 getBonusNumber() 를 제거 해보세요 😊

2021-01-11 07:55 UTC, sehan commented on src/main/java/lotto/view/ResultView.java
> +        for (LottoRank rank : LottoRank.values()) {
LottoResults 으로 당첨금액합산 로직을 이동시키면 view 에서 로직을 제거 할 수 있습니다.

2021-01-11 07:55 UTC, sehan commented on src/main/java/lotto/controller/LottoGame.java
> +        CreateTicket makeTicket = new CreateTicket(price);
LottoTickets 와 협업하는 객체를 만들기를 기대했는데 의도와는 다르게 LottoTickets 와는 협업하지 않는 구조로 티켓생성 로직을  분리 하셨네요.  

CreateTicket 이 LottoMachine 이라고 한다면 사용자에게 로또를 발급해주고 발급된 로또의 당첨결과를 확인해 주는 책임을 가지도록 할 수 있을것입니다. LottoGame 은 LottoMachine 와 협업하고 LottoMachine 은 Lottos 와 협업하는 모습을 기대했었습니다 🥰

2021-01-11 07:55 UTC, sehan commented on src/test/java/lotto/LottoResultsTest.java
> +public class LottoResultsTest {
view 로직이 제거 되어 단위테스트가 한결 좋아 졌습니다 👍

2021-01-11 07:55 UTC, sehan commented on src/test/java/lotto/LottoResultsTest.java
> +    void getLottoResultsTest(){
당첨순위집계에 대한 단위테스트가 보강되어야 합니다.

주어진 로또티켓들과 당첨번호가 입력되었을때 기대되는 당첨순위별 로또수를 테스트 하는 코드가 필요해 보입니다.

2021-01-12 01:08 UTC, sehan approved these changes
피드백 잘 반영해 주셨습니다. 고생하셨습니다. 👍 👍 👍 

이번 step 은 여기서 merge 하도록 하겠습니다.
그래도 리팩토링은 계속되어야 하기에 몇가지 고민해 볼 것들을 코멘트에 남겨두었습니다.
다음 step 을 진행하면서 함께 고민해 주세요. 

고생하셨습니다.

2021-01-12 01:08 UTC, sehan commented on src/main/java/lotto/domain/WinningNumber.java
> +    public boolean bonusNumberContain(LottoTicket lottoTicket){
👍

2021-01-12 01:08 UTC, sehan commented on src/main/java/lotto/controller/LottoGame.java
> +    private static WinningNumber winningNumber;
LottoTickets 와 WinngingNumber 를 static member 로 가질 필요는 없습니다.
LottoGame 은 main() 매소드를 실행하는것이 전부이기 때문에 member 가질 필요가 없습니다. 
main() 내부에 로컬변수로 처리하면 됩니다. 즉, setLottoTickets() 매소드도 제거 하고 main() 매소드 내에 풀어써 주세요.
main() 코드가 길어진다고 생각되면 static 으로 풀어내는것 보다는 로직을 domain 으로 이동시킬 것은 없는지 고민해주세요

2021-01-12 01:08 UTC, sehan commented on src/main/java/lotto/domain/CreateTicket.java
> +    public static LottoTickets createAutoTicket(int price){
CreateTicket 이 멤버로 lottoTickets 의 상태를 관리해야할 필요가 있는가? 에 대한 생각을 해볼 필요가 있습니다.
CreateTicket 이 발급한 모든 lottoTicket 을 관리하는 책임을 가지고 있다면 의미가 있지만 현재는 그런 책임을 가지고 있지 않습니다. CreateTicket 은 구입금액을 입력받으면 그에 맞는 티켓을 생성해주고 역할이 끝이 납니다.  발급된 티켓의 상태를 내부에 유지해 둘 필요가 없습니다. CreateTicket 의 객체를 생성할때는 관리할 상태가 있을 경우 입니다. 그렇지 않다면 static 매소드만 제공하면 됩니다.
 현재 설계상으로는 lottoTickets 멤버와 getTickets() 메소드 모두 필요가 없습니다.  createAutoTicket() 메소드는 내부에서 CreateTicket 객체를 생성할 필요없이 ticket 을 생성하면 됩니다.

2021-01-12 01:08 UTC, sehan commented on src/main/java/lotto/domain/LottoRank.java
> +
LottoRank 에 순위확인 역할을 잘 구현해 주셨네요 👍

2021-01-12 01:08 UTC, sehan commented on src/main/java/lotto/domain/LottoResults.java
> +        results = new HashMap<LottoRank, Integer>();
LottoResults 생성로직을 잘 분리해 주셨습니다. 👍 
LottoTickets 에서 LottoResults 생성부분을 잘 분리해 보니 LottoResults 생성자 부분이 좀 뚱둥해 보이죠? 
로또순위집계 데이터인 results 생성하는 역할도 분리해 볼 수 도 있겠죠? ^^

2021-01-12 01:08 UTC, sehan commented on src/test/java/lotto/LottoResultsTest.java
> +        LottoTickets lottoTickets = new LottoTickets(Arrays.asList(lottoTicket));
LottoResults 단위테스트 잘 작성해 주셨어요 👍 👍 👍 

작성해보고 나니 LottoResults 를 생성하기 위해 ticket , winningNumber 생성하는 비용이 상당히 많이 드는것을 확인할 수 있습니다. 단위테스트에서 테스트 하려고 하는것(lottoResults.getCountLottoRank(rank) )은 순위를 넘겨주면 Count 를 가져오는 간단한 기능인데 말이죠.

이렇게 테스트코드를 작성하다보면 리팩토링이 필요한 부분들이 드러나게 됩니다.
테스트코드 작성하기 왜 이렇게 힘들까? 라는 생각이 들면 리팩토링이 필요하다는 신호 입니다.
즉, LottoTickets 에서 LottoResults 생성부분을 분리하는데 성공 했지만 더 분리할게 남아 있다는 것이죠 ^^
이제 LottoResults 에서 Map<LottoRank, Integer> results 를 만들어내는 로직을 분리해내면 LottoResults 에 
LottoResults( Map<LottoRank, Integer> results ) 생성자를 추가 할 수 있게 되고 LottoResults 를 생성하기 위해 ticket, winningNumber 를 생생해야 하는 코드를 제거 할 수 있게 됩니다. 

리팩토링은 계속됩니다. 😄

2021-01-12 01:08 UTC, merged