[huey.j 전준호] 로또 시뮬레이션 step1 코드 리뷰 요청드립니다.
NewKrew2021/java-lotto-kakao pull request #2
Opened 2021-01-07 09:55 UTC by jh280722

안녕하세요 huey 입니다. 
이번에 로또 시뮬레이션 1단계를 완료해서
코드 리뷰 요청드립니다.

2021-01-07 12:39 UTC, ljh131 requested changes
전체적으로 클래스들이 서로 너무 엮여있습니다.
mvc라는 구조를 생각하면서, 뷰에서 데이터를 입력받고 컨트롤러가 데이터를 처리한 후 다시 뷰에 데이터를 출력하도록 간단하게 만들어보세요. 그 후 요구사항에 나온 `원시값과 문자열 포장` 이런거 리팩토링 해보세요.

2021-01-07 12:39 UTC, friediceday commented on src/main/java/lotto/domain/Price.java
> +    @Override
혹시 이건 왜 오버라이드 한건가요?

2021-01-07 12:39 UTC, friediceday commented on src/main/java/lotto/domain/WinningLotto.java
> +        this(winningLotto, new Digit(37));
37은 어떤 숫자인가요?

2021-01-07 12:39 UTC, friediceday commented on src/main/java/lotto/domain/LottoSimulation.java
> +    public LottoSimulation(Price price, String text, String bonusBall) {
인자 이름은 의미있게 쓰는게 좋겠습니다.

2021-01-07 12:39 UTC, friediceday commented on src/main/java/lotto/domain/Lottos.java
> +    public static Lottos getInstance(int number) {
좀 더 의미있는 이름이 좋을 것 같아요.

2021-01-07 12:39 UTC, friediceday commented on src/main/java/lotto/view/InputView.java
> +    public static String getText() {
겟 텍스트라는 일반적인 이름보다는 당첨번호라는 의미를 나타내면 더 좋겠습니다.

2021-01-07 12:39 UTC, friediceday commented on src/main/java/lotto/view/OutputView.java
> +public class OutputView {
여기 메서드들이 너무 많은 클래스들을 참조하고 있는데요... 특히 LottoSimulation를 가져와서 게터를 꺼내는 방식은 좋아보이지 않습니다. LottoSimulation라는 큰 객체이기 때문이죠. 게다가 인풋과 달리 로직적인 부분들과 엮여졌습니다.
메서드는 꼭 필요한 최소 규모의 인자만 받아서 일을 수행하면 좋겠습니다.

2021-01-07 12:39 UTC, friediceday commented on src/main/java/lotto/domain/Digit.java
> +        return digit < 1 || digit > 45;
이런 로직이 들어간 이상 클래스 이름에 로또 번호라는 의미를 나타내면 어떨까요? 그리고 상수도 필요할 것 같습니다.

2021-01-07 12:39 UTC, friediceday commented on src/main/java/lotto/domain/WinningLotto.java
> +        return LottoResults.mapResult(winningLotto.matchCount(lotto), lotto.contains(bonusBall));
LottoResults가 WinningLotto와 lotto 두개를 받아 비교하는건 어떤가요

2021-01-07 12:39 UTC, ljh131 commented on src/main/java/lotto/domain/LottoResults.java
> +        reward += getResultCount(Result.THREE) * THREE_PRICE;
매치된 개수+상금을 조합해 정의해놓으면 더 편할텐데요. 반복문으로 돌릴수도 있고요.

2021-01-07 12:39 UTC, ljh131 commented on src/main/java/lotto/domain/LottoResults.java
> +    public String toString() {
뷰 클래스가 별도로 있으니 거기서 출력 내용을 만들어주는건 어떤가요? 그런데 단순히 뷰가 여기에 필요한 메서드들을 전부 호출하는 방식이 아니라, 모델을 넘겨주는 방식으로요.

2021-01-08 08:40 UTC, jh280722 commented
앗 리뷰를 보다가 이것저것 누르면서 리뷰요청을 보내버렸네요 아직 수정중인데 요청보내서 죄송합니다...
빨리 피드백 적용해볼게요

2021-01-08 09:06 UTC, jh280722 commented on src/main/java/lotto/domain/Price.java
> +    @Override
테스트에서 create를 만들다가 equals를 만들어놓고 쓸일이 없을것같아 지우다가 미쳐 못 지운것 같습니다.

2021-01-08 09:07 UTC, jh280722 commented on src/main/java/lotto/domain/LottoSimulation.java
> +    public LottoSimulation(Price price, String text, String bonusBall) {
네 최대한 의미있게 바꾸겠습니다.

2021-01-08 09:07 UTC, jh280722 commented on src/main/java/lotto/domain/Lottos.java
> +    public static Lottos getInstance(int number) {
넵

2021-01-08 09:08 UTC, jh280722 commented on src/main/java/lotto/view/OutputView.java
> +public class OutputView {
한번 DTO를 만들어서 해보겠습니다.

2021-01-08 09:08 UTC, jh280722 commented on src/main/java/lotto/domain/Digit.java
> +        return digit < 1 || digit > 45;
네 상수처리화하겠습니다.

2021-01-08 09:15 UTC, jh280722 commented on src/main/java/lotto/domain/LottoResults.java
> +    public String toString() {
네 저희도 그에 대해 많이 고민했는데요 toString으로 String을 넘겨주는건 지양하는 것이 좋나요?

2021-01-08 09:16 UTC, jh280722 commented on src/main/java/lotto/domain/WinningLotto.java
> +        return LottoResults.mapResult(winningLotto.matchCount(lotto), lotto.contains(bonusBall));
일급 컬렉션으로 포장하다보니 접근에 대해 어려워서 이렇게 했던 것 같습니다.
다시 한 번 고민해보고 클래스 역할에 맡도록 바꿔보겠습니다.

2021-01-08 09:16 UTC, jh280722 commented on src/main/java/lotto/domain/LottoResults.java
> +        reward += getResultCount(Result.THREE) * THREE_PRICE;
음 어떻게 조합한다는 건지 잘 이해가 안갑니다.

2021-01-08 09:18 UTC, jh280722 commented on src/main/java/lotto/domain/WinningLotto.java
> +        this(winningLotto, new Digit(37));
처음 테스트를 할때 만든 생성자로 남아있는 거였는데요
이렇게 테스트를 위해서만 만든 코드를 다시 사용하지않으면 완성된 후 리펙토링해야 하는지가 궁금합니다.

2021-01-08 13:12 UTC, jh280722 commented
Digit을 LottoNumber로 바꾸고 Lotto 자체에 넘겨줄때 List<Interger> 를 넘겨주던 방법을 List<LottoNumber> 로 바꿨습니다. 그런데 그렇게 바꾸면서 테스트를 할 때 
new Lotto(Arrays.asList(1,2,3,4,5,6)
                        new LottoNumber(1),
                        new LottoNumber(2),
                        new LottoNumber(3),
                        new LottoNumber(4),
                        new LottoNumber(5),
                        new LottoNumber(6)
                ) 와 같이 만들어야합니다. 이럴때 테스트를 위해 생성자를 만들어도 되는지가 궁금합니다. 그리고 만들게 되면 추가적으로 포장을 하는 메소드를 만들어야되는데 생성자를 만들어도 된다해도 그런 작업도 해도 되는지가 궁금합니다.

2021-01-08 14:21 UTC, jh280722 commented on src/main/java/lotto/domain/LottoResults.java
> +        reward += getResultCount(Result.THREE) * THREE_PRICE;
public long getReward() {
        long reward = 0;
        for (LottoResult lottoResult : lottoResults) {
            reward += lottoResult.getReward();
        }
        return reward;
    }
제가 이렇게 접근한게 맞을까요? LottoResult에 해당되는 상금을 getReward로 받아오게 했습니다.

2021-01-08 14:45 UTC, jh280722 commented on src/main/java/lotto/domain/LottoResults.java
> +    public String toString() {
Lottos에 List<Lotto>  -> Lotto -> LottoNumber순으로 다 포장이 되어있는데요
Lottos를 view에서 넘겨주게된다면 OutputView에서 계속해서 get으로 빼내면서 출력을 해줘야하는건가요?

2021-01-10 12:22 UTC, jh280722 commented
toString을 OutputView로 변경하고 LottoResults를 아예 LottoSimulation에서 빼서 DTO로서 역할로 바꾸었습니다.
그리고 리터널의 상수화와 이름에 대해 많이 바꾸었습니다. 
LottoResult의 enum에서 enum 값에 따른 상금에 대한 리턴을 하도록 담당하였고 그를 통해 상금을 구할때 반복문을 통해 구하도록 구현하였습니다. 의문이 가는 점들은 따로 댓글로 달아봤습니다. 리뷰해주셔서 감사합니다.

2021-01-11 07:21 UTC, ljh131 requested changes
안녕하세요. 커멘트 드렸으니 확인해보시고 수정해주시면 좋겠습니다. 그리고 커멘트에 대해 궁금한 점이 있으시면 질문주세요.

2021-01-11 07:21 UTC, friediceday commented on src/main/java/lotto/domain/LottoNumber.java
> +    private static final Map<Integer, LottoNumber> lottoNumbers = new HashMap<>();
static final이면 upper case로 하는게 어떨까요

2021-01-11 07:21 UTC, friediceday commented on src/main/java/lotto/domain/LottoNumber.java
> +            throw new IllegalArgumentException("로또 숫자는 1~45 사이로만 입력해주세요.");
상수를 사용하면 어떨까요

2021-01-11 07:21 UTC, friediceday commented on src/main/java/lotto/domain/LottoSimulation.java
> +    public LottoSimulation(Price price, String text, String bonusBall) {
이 부분 확인해주시면 좋겠습니다.

2021-01-11 07:21 UTC, friediceday commented on src/main/java/lotto/domain/Price.java
> +    private static final int ZERO = 0;
이름이 zero인건 상수의 의미가 없는 것 같은데요, 어떻게 생각하세요?

2021-01-11 07:21 UTC, friediceday commented on src/main/java/lotto/domain/RandomNo.java
> +    public static final int ZERO = 0;
여기도 zero가 있네요

2021-01-11 07:21 UTC, friediceday commented on src/main/java/lotto/utils/LottoResult.java
> +        if (count == 6) return FIRST;
여기 상수도 많이 들어가야 하고, if도 너무 많은데요. 개선이 있었으면 좋겠는데 어떠신가요?
간단한 방법으로는 enum을 class처럼 사용하는 방법이 있습니다.

2021-01-11 07:21 UTC, friediceday commented on src/main/java/lotto/view/OutputView.java
> +        lottoResultsString.append("3개 일치 (" + LottoResult.FIFTH.getReward() + "원)- " + lottoResults.getResultCount(LottoResult.FIFTH) + "개\n");
이 부분도 코드가 많고 중복도 있는데 간단하게 할 수 있는 방법이 없을까요?

2021-01-11 07:21 UTC, friediceday commented on src/main/java/lotto/domain/LottoSimulation.java
> +                .forEach(lotto::add);
functional인데 side effect가 있으면 좋지 않을 것 같습니다. 게다가 사이드 이펙트가 없는 다른 방법으로 충분히 가능할 것 같아요.

2021-01-11 07:21 UTC, friediceday commented on src/main/java/lotto/domain/Lottos.java
> +    public List<LottoResult> allConfirm(WinningLotto winningLotto) {
confirm이라는 메서드가 많이 등장하는데 의미 전달이 모호해보여요. 메서드의 역할이 분명하게 나타날 수 있도록 이름을 바꾸는건 어떨까요?

2021-01-11 07:21 UTC, friediceday commented on src/main/java/lotto/domain/Lottos.java
> +                .forEach(lottoResults::add);
여기도 마찬가지로 사이드이팩트가 없도록 하는게 좋겠습니다.

2021-01-11 07:21 UTC, friediceday commented on src/main/java/lotto/domain/Lottos.java
> +    public static Lottos getLottosInstance(int limitNumber) {
get이라면 원래 있는걸 갖고오는 느낌이라서 새로 만드는거면 다른 이름이면 어떨까요? 그리고 랜덤 생성한다는 것의 의미도 표현되었으면 좋겠습니다.

2021-01-11 07:21 UTC, friediceday commented on src/test/java/lotto/domain/LottoNumberTest.java
> +    void StringEqual() {
메서드명 컨벤션이 일관되었으면 좋겠습니다. 아래 메서드도요.

2021-01-11 07:21 UTC, ljh131 commented on src/main/java/lotto/DTO/LottoResults.java
> +        return (int) lottoResults.stream()
매번 이렇게 돌면서 검사하는건 효율적이지 않을 것 같아요.

2021-01-11 07:21 UTC, ljh131 commented on src/main/java/lotto/DTO/LottoResults.java
> +    public long getReward() {
여기도 매번 호출시 계산하는데, 굳이 그럴 필요가 있을까요?

2021-01-11 07:21 UTC, ljh131 commented on src/main/java/lotto/DTO/LottoResults.java
> +package lotto.DTO;
dto라는 이름은 왜 사용하신건지 궁금해요.

2021-01-11 07:21 UTC, ljh131 commented on src/main/java/lotto/domain/Lotto.java
> +    public boolean equals(Object o) {
equals와 hashCode를 여기뿐만 아니라 여러 클래스에서 오버라이드 하셨는데 각각 어디서 사용하는지 궁금합니다.

2021-01-11 07:27 UTC, jh280722 commented on src/main/java/lotto/domain/Lotto.java
> +    public boolean equals(Object o) {
각각 테스트를 할 때 포비께서 처음 테스트를 만들때 잘 모르겠으면 create부터 만들면서 진행하라고 하셔서
강의에서 배운대로 잘 만들어졌는지 확인할때 사용했습니다. 실사용이 되지않는다면 지우는 것이 좋을까요?

2021-01-11 07:29 UTC, jh280722 commented on src/main/java/lotto/DTO/LottoResults.java
> +package lotto.DTO;
도메인에서 만들어진 결과를 DTO를 통해 전달하고 View에서 모델을 가지고 출력하기위해 DTO라고 생각했는데요 도메인이 맞을까요?

2021-01-11 07:30 UTC, jh280722 commented on src/main/java/lotto/DTO/LottoResults.java
> +    public long getReward() {
인스턴스 변수로 바꿨다가 오늘 포비의 강의에 인스턴스 변수를 최소화하고 이미 메소드가 있는 것이면 그걸 호출하면 된다하셔서
다시 바꿔봤습니다. 다시 생각해보니 연산이 많이 되는데 자꾸 불러올 필요는 없는 것 같네요.

2021-01-11 07:32 UTC, jh280722 commented on src/main/java/lotto/domain/Lottos.java
> +    public List<LottoResult> allConfirm(WinningLotto winningLotto) {
네 알겠습니다

2021-01-11 07:34 UTC, jh280722 commented on src/main/java/lotto/domain/LottoNumber.java
> +    private static final Map<Integer, LottoNumber> lottoNumbers = new HashMap<>();
네 알겠습니다

2021-01-11 07:35 UTC, jh280722 commented on src/main/java/lotto/domain/LottoNumber.java
> +            throw new IllegalArgumentException("로또 숫자는 1~45 사이로만 입력해주세요.");
좋은 생각인 것 같아요 제가 스트링 처리를 빼먹었네요

2021-01-11 07:37 UTC, jh280722 commented on src/main/java/lotto/domain/Price.java
> +    private static final int ZERO = 0;
그럼 상수를 안 써도 되는 수는 뭐가 더 있을까요?

2021-01-11 07:37 UTC, jh280722 commented on src/main/java/lotto/domain/Lottos.java
> +    public static Lottos getLottosInstance(int limitNumber) {
네 알겠습니다.

2021-01-11 07:47 UTC, ljh131 commented on src/main/java/lotto/domain/Price.java
> +    private static final int ZERO = 0;
좋은 질문입니다. 0이라서 그런게 아니라 이름을 얘기한건데요, 예를 들어 지금은 최저 금액이 0원인데, 1000원으로 바뀌었다고 생각해보면, 
```
    private static final int ZERO = 1000;
```
이렇게 되겠죠.

2021-01-11 07:49 UTC, ljh131 commented on src/main/java/lotto/DTO/LottoResults.java
> +package lotto.DTO;
그런데 전달만 하는 transparent한 객체라고 하기 어렵지 않을까요? 나름의 로직이 있어서요.

2021-01-11 07:52 UTC, jh280722 commented on src/test/java/lotto/domain/LottoNumberTest.java
> +    void StringEqual() {
네 좀더 신경쓰겠습니다.

2021-01-11 07:54 UTC, jh280722 commented on src/main/java/lotto/DTO/LottoResults.java
> +        return (int) lottoResults.stream()
더 생각해보겠습니다

2021-01-11 08:06 UTC, ljh131 commented on src/main/java/lotto/domain/Lotto.java
> +    public boolean equals(Object o) {
사용한다는 테스트가 LottoTest.sort, create 인가요? 굳이 불필요해보입니다.
이 클래스를 보면 제일 중요한 것은 생성했을때 예외가 안나는지(자연스럽게 위에 있는 프라이빗도 같이 테스트 되겠죠), 그리고 나머지 퍼블릭 메서드들 입니다.
그러고 보니 나머지 퍼블릭 메서드들에 대한 테스트가 없네요. 이 부분 테스트도 추가해주시면 좋겠습니다.

2021-01-11 08:09 UTC, jh280722 commented on src/main/java/lotto/utils/LottoResult.java
> +        if (count == 6) return FIRST;
네 공부해서 개선해보겠습니다.

2021-01-11 08:10 UTC, ljh131 commented on src/main/java/lotto/domain/WinningLotto.java
> +        this(winningLotto, new Digit(37));
테스트를 위해서만 만든 코드는 별로 좋지 않은 생각같습니다. 테스트용 코드 따로, 실행용 코드 따로면 테스트가 별로 의미 없을 것 같네요.

2021-01-11 08:11 UTC, ljh131 commented on src/main/java/lotto/domain/LottoResults.java
> +        reward += getResultCount(Result.THREE) * THREE_PRICE;
오늘 리뷰에서 약간의 힌트를 드렸습니다.(enum)

2021-01-11 08:18 UTC, jh280722 commented on src/main/java/lotto/DTO/LottoResults.java
> +package lotto.DTO;
로직이 없이 데이터 전달만 하는 객체를 DTO라고 생각하면 될까요?

2021-01-11 08:19 UTC, ljh131 commented on src/main/java/lotto/domain/LottoResults.java
> +    public String toString() {
오늘 수정하신 버전은 이때 LottoResults와 다르게 별도 결과를 만들어서 넘겨주는 방식으로 하셨으니 훨씬 좋아진 것 같습니다.

2021-01-11 08:21 UTC, jh280722 commented on src/main/java/lotto/domain/Lotto.java
> +    public boolean equals(Object o) {
네 알겠습니다

2021-01-11 08:36 UTC, jh280722 commented on src/main/java/lotto/domain/LottoSimulation.java
> +                .forEach(lotto::add);
side effect가 형변환이 이루어지는 map을 말씀하시는 것 맞나요? side effect가 무엇인지 궁금합니다.
`    public static Lotto of(List<Integer> lotto) {
        return new Lotto(lotto.stream()
                .map(LottoNumber::of)
                .collect(Collectors.toList()));
    }` 
위와 같은 방식의 정적 팩토리 메소드 구현도 잘못된 방식인가요?

2021-01-11 08:37 UTC, jh280722 commented on src/main/java/lotto/view/OutputView.java
> +        lottoResultsString.append("3개 일치 (" + LottoResult.FIFTH.getReward() + "원)- " + lottoResults.getResultCount(LottoResult.FIFTH) + "개\n");
enum을 사용해 문자열을 모아서 하는 방식으로 해보려고 합니다.

2021-01-11 09:28 UTC, jh280722 commented on src/main/java/lotto/DTO/LottoResults.java
> +        return (int) lottoResults.stream()
Map을 사용해서 LottoResult에 대한 count를 모아서 만들었습니다.

2021-01-11 09:30 UTC, ljh131 commented on src/main/java/lotto/domain/LottoSimulation.java
> +                .forEach(lotto::add);
이 책을 읽어보진 않았는데, 잘 설명되어있네요.
https://livebook.manning.com/book/functional-programming-in-scala/chapter-1
물어보신 코드는 괜찮아보입니다.

2021-01-12 02:38 UTC, ljh131 reviewed
전체적으로 개선된 것 같습니다. 이번 단계는 머지하겠습니다. 
커멘트 드린 내용들은 참고하시고 다음에 반영해주시면 좋겠습니다. 특히 네이밍 컨벤션은 지켜주세요.

2021-01-12 02:38 UTC, friediceday commented on src/main/java/lotto/domain/Money.java
> +            throw new IllegalArgumentException("가격은 음수가 될 수 없습니다.");
사소한건데 MINIMUM_MONEY가 현재 0이라 그렇지만 바뀐다면 에러메시지가 유효하지 않겠네요. 
그리고 유효성을 체크하는 책임은 isInvalid메서드에게 있는거라서 여기선 유효한지 안유효한지만 알 수 있고 정확한 내용은 모르는게 좋을 것 같아요.

2021-01-12 02:38 UTC, friediceday commented on src/test/java/lotto/domain/LottoNumberTest.java
> +    void StringEqual() {
이 부분 camelCase를 얘기한거였습니다. 확인해주세요.

2021-01-12 02:38 UTC, friediceday commented on src/main/java/lotto/domain/LottoNumber.java
> +            throw new IllegalArgumentException(
이 메서드도 엄밀히 말하면 범위가 얼만지 모릅니다. 있는지 없는지만 알 뿐이죠. 만약 저렇게 에러를 상세히 내줄거면 범위를 체크하는 별도 메서드를 분리해서 거기서 처리하면 더 좋을 것 같아요.

2021-01-12 02:38 UTC, friediceday commented on src/main/java/lotto/domain/result/LottoResults.java
> +    private final Map<LottoResult, Long> LOTTO_RESULTS;
static final이 아닌 이상 camelCase로 하는게 좋겠습니다.

2021-01-12 02:38 UTC, friediceday commented on src/main/java/lotto/dto/LottoResultsDto.java
> +    private final Map<LottoResult, Long> LOTTO_RESULTS;
여기도요

2021-01-12 02:38 UTC, friediceday commented on src/main/java/lotto/dto/LottoResultsDto.java
> +    public Map<LottoResult, Long> getLOTTO_RESULTS() {
여기도 케멜케이스가 좋겠습니다

2021-01-12 02:38 UTC, friediceday commented on src/main/java/lotto/dto/LottoResultsDto.java
> +    private LottoResultsDto(Map<LottoResult, Long> lotto_results, double yield) {
여기도요

2021-01-12 02:38 UTC, friediceday commented on src/main/java/lotto/dto/LottoResultsDto.java
> +public class LottoResultsDto {
그냥 LottoResults를 써도 될 것 같은데 이런 중복 객체를 따로 만든 이유가 궁금해요

2021-01-12 02:38 UTC, ljh131 commented on src/main/java/lotto/domain/result/LottoResults.java
> +    private static void fillDefaultCount(Map<LottoResult, Long> lotto_Results) {
아웃풋에서 맵가지고만 출력을 해서 이렇게 넣어주는 것 같네요. 아웃풋에서 LottoResult에 정의된 값들을 이용해서 보여주면 이렇게 안넣어줘도 될 것 같은데 어떤가요?

2021-01-12 02:38 UTC, ljh131 commented on src/main/java/lotto/dto/LottoResultsDto.java
> +        Map<LottoResult, Long> sortedLottoResults = new TreeMap<>(lottoResults.getLOTTO_RESULTS())
출력 순서를 위해서 트리맵을 쓰신것 같은데요, 그냥 맵으로 전달하면 받은 쪽에서 이게 무슨맵인지 알 수 없으니 혼란스러울 것 같아요. 
가장 좋은 방법은 아웃풋에서 트리맵이 아니더래도 순서를 보장할 수 있는 방법이 가장 좋겠고요, 그렇게 하지 않겠다면 구체적인 타입을 넘겨주는것도 좋을 것 같아요.

2021-01-12 02:38 UTC, merged

2021-01-12 03:26 UTC, jh280722 commented on src/main/java/lotto/dto/LottoResultsDto.java
> +public class LottoResultsDto {
포비 강의를 들으면서 도메인에서 모델을 넘겨줄때 사용을 한다고 들었는데요.
이미 LottoResults가 final로 되어있으니까 안 만들어도 되는건가요?