[tars.case 장석현] 로또 미션 1단계 리뷰 요청 드립니다.
NewKrew2021/java-lotto-kakao pull request #22
Opened 2021-01-08 12:17 UTC by tjrgus1213

안녕하세요! 타스입니다.
이번 로또 미션 진행하면서 몇가지 궁금한 점이 있어서 여쭤보고 싶습니다.
1. MVC패턴으로 작성할 때 main 함수의 위치를 컨트롤러에 포함시키는 것이 좋을지 아니면 따로 분리하여 클래스를 작성해야 할지 궁금합니다.
2. LottoResultTest에서 테스트 코드를 작성할 때 인덴트 2 이하 규칙때문에 메소드를 분리하여 작성했는데 이와 같이 작성했을 때 오히려 가독성이 떨어지는 문제가 발생하지 않는지 궁금합니다.

2021-01-09 14:45 UTC, findstar requested changes
안녕하세요 로또 미션 리뷰를 하게된 제임스입니다.
주말이라 조금 늦게 리뷰를 진행했네요. 수고 많으셨습니다. 👏
다음은 리뷰에 남겨주신 질문에 대한 답변입니다.
main 함수는 말 그대로 애플리케이션을 실행시키는 함수이기 때문에 MVC 와는 구분됩니다.
컨트롤러는 제어의 역할을 수행하는 객체로 이해하시면 됩니다. 
그리고 테스트 코드는 좀 더 유연하게 작성할 수 있습니다. 다만 개별 클래스의 테스트가 일부 빠진 경우가 있으니 보완 부탁드립니다.

몇가지 추가 코멘트를 남겼습니다. 
그리고 코드 커버리지를 확인해보세요. 다음과 같이 인텔리J 에서 커버리지를 확인할 수 있습니다. 

![image](https://user-images.githubusercontent.com/1266944/104094527-bcdbd500-52d4-11eb-948a-1542f828fb6e.png)

그럼 화이팅입니다.

2021-01-09 14:45 UTC, findstar commented on src/main/java/lotto/domain/LottoRank.java
> +    FIFTH(5000, "3개 일치"),
Java 7부터 자릿수를 표시하기 위한 underscores(밑줄) 표현이 가능합니다.
숫자를 가독성있게 5000 -> 5_000, 50000 -> 50_000 이렇게 표현할 수 있습니다.

2021-01-09 14:45 UTC, findstar commented on src/main/java/lotto/domain/NumberPool.java
> +    public static NumberPool getInstance() {
굳이 getInstance 가 필요할까요? static 메서드에 미리 Numbers 를 캐싱해놓을 수 있도록 개선을 고려해주세요

2021-01-09 14:45 UTC, findstar commented on src/main/java/lotto/domain/NumberPool.java
> +        numbers = IntStream.range(Number.MIN_LOTTO_NUMBER, Number.MAX_LOTTO_NUMBER + 1)
Intstream을 사용하셨네요 💯 
rangeClosed 를 사용하시면 +1 을 하지 않아도 됩니다.

2021-01-09 14:45 UTC, findstar commented on src/main/java/lotto/view/LottoGameView.java
> +public class LottoGameView {
사용자 입력을 위한 InputView 와 출력을 위한 OutputView 로 분리하면 좀 더 작은 단위로 클래스를 설계할 수 있습니다.

2021-01-09 14:45 UTC, findstar commented on src/main/java/lotto/domain/LottoTicket.java
> +    public LottoRank getRank(WinnerNumber winnerNumber) {
LottoTicket 에서 Rank 를 구하는것과 WinnerNumber 에서 Rank 를 구하는 것 어느것이 더 
역할 분리가 잘 된것일까요?

2021-01-09 14:45 UTC, findstar commented on src/main/java/lotto/domain/RankTable.java
> +    private static final MatchResult FIRST = new MatchResult(6, false);
RankTable 을 별도로 분리하기 보다 LottoRank 에서 static method 를 추가하는 것이 어떨까요?

2021-01-09 14:45 UTC, findstar commented on src/main/java/lotto/domain/WinnerNumber.java
> +public class WinnerNumber extends LottoTicket {
WinnerNumber 와 LottoTicket 상속구조로 연결되면서
WinnerNumber 에는 contains와 같은 메서드 호출이 가능해집니다.
이는 의도한게 아니기 때문에 이 경우에는 상속보다는 분리된 구조의 클래스로 유지하는게 나아보입니다.

2021-01-09 14:45 UTC, findstar commented on src/main/java/lotto/domain/Price.java
> +public class Price {
아주 간단한 클래스라도 테스트 해주세요 😄

2021-01-09 14:45 UTC, findstar commented on src/main/java/lotto/util/StringUtility.java
> +public class StringUtility {
유틸리티 클래스를 만들 때는 범용성을 생각하면서 만들어야 합니다. 

다음의 메서드는 모두 도메인 객체 생성을 위한 요구사항의 일부로 볼 수 있네요.

2021-01-09 14:45 UTC, findstar commented on src/main/java/lotto/domain/LottoResults.java
> +    public double calculateRate(int price) {
이런 경우에는 BigDecimal 를 사용하면 수식이 좀 더 간결해집니다.

2021-01-09 14:45 UTC, findstar commented on src/main/java/lotto/view/LottoGameView.java
> +        System.out.println("총 수익률은 " + lottoResults.calculateRate(price) + " 입니다.");
System.out.printf 를 활용해보세요.

2021-01-09 14:45 UTC, findstar commented on README.md
> +## 구현 클래스
클래스 별 역할을 아주 잘 정리 해주셨네요 👍
1단계 요구사항도 추가 부탁드립니다~!

2021-01-09 14:45 UTC, findstar commented on src/main/java/lotto/domain/LottoResults.java
> +        if(isNothing(rank))
Rank 가 null 인경우가 있을까요? Rank.NOTHING (꽝) 을 추가해보세요.

2021-01-10 15:25 UTC, tjrgus1213 commented on src/main/java/lotto/domain/RankTable.java
> +    private static final MatchResult FIRST = new MatchResult(6, false);
LottoRank는 enum인데 static method나 변수를 가져도 상관없을까요?

2021-01-10 15:58 UTC, tjrgus1213 commented on src/main/java/lotto/domain/WinnerNumber.java
> +public class WinnerNumber extends LottoTicket {
LottoTicket과 WinnerNumber 클래스가 공통되는 부분이 많다고 생각하는데 그러면 WinnerNumber가 LottoTicket을 상속받는 것이 아닌 LottoTicket과 WinnerNumber가 같은 클래스를 상속받도록 수정하는건 어떨까요??

2021-01-11 02:14 UTC, findstar commented on src/main/java/lotto/domain/RankTable.java
> +    private static final MatchResult FIRST = new MatchResult(6, false);
enum 도 static method 를 가질 수 있습니다. 
제가 말씀드린건 static method 를 사용하여 
매칭 카운트와 보너스 정보를 전달하여 
Rank 인스턴스을 생성할 수 있도록 개선해보는 방법이 있다는 것을 알려드린겁니다.

2021-01-11 02:18 UTC, findstar commented on src/main/java/lotto/domain/WinnerNumber.java
> +public class WinnerNumber extends LottoTicket {
상속은 아주 강한 결합입니다. 
따라서 상위 클래스의 위치에 하위 클래스가 전달되어도 문제없이 사용될 수 있어야 합니다. 
대신 조합(Composition)을 사용해보는건 어떨까요?

2021-01-11 05:23 UTC, tjrgus1213 commented
테스트 코드를 좀 더 유연하게 작성해보려고 노력했는데 쉽지 않은 것 같습니다..
어떻게 하면 조금 더 테스트 코드를 유연하게 작성 할 수 있을까요??

2021-01-11 11:57 UTC, findstar approved these changes
안녕하세요 타스. 제임스입니다.
지난번 코멘트 드린 피드백 반영 잘 해주셨네요. 
궁금한 사항은 언제든 편하게 질문주세요.
수고하셨습니다. 다음 단계 진행해주세요 😄

2021-01-11 11:57 UTC, findstar commented on src/main/java/lotto/domain/Number.java
> +        IntStream.rangeClosed(MIN_LOTTO_NUMBER, MAX_LOTTO_NUMBER).forEach(number -> numberPool.add(new Number(number)));
IntStream 을 활용해서 캐싱 하는군요 좋습니다 💯

2021-01-11 11:57 UTC, findstar commented on src/main/java/lotto/domain/WinnerNumber.java
> +    public WinnerNumber(LottoTicket winnerNumbers, Number bonusNumber) {
WinnerNumber 가 상속 구조를 벗어나 조합하는 구조로 변경되었네요 💯

2021-01-11 11:57 UTC, findstar commented on src/main/java/lotto/domain/LottoTicket.java
> +    public static LottoTicket from(String rawNumbers) {
정적 메서드를 활용한 생성하고 있군요 💯

2021-01-11 11:57 UTC, findstar commented on src/main/java/lotto/domain/LottoRank.java
> +    public static LottoRank get(int matchCount, boolean isBonus) {
LottoRank 에서 랭크를 구하고 있네요. 좋습니다 💯

2021-01-11 11:57 UTC, merged