[corby.kim] 로또 미션 1단계 리뷰 요청 드립니다.
NewKrew2021/java-lotto-kakao pull request #23
Opened 2021-01-08 14:28 UTC by ddaaac

안녕하세요 😃

이번 미션에서 제가 고민을 가장 많이 한 부분은 `LottoTicket`이란 클래스를 만들고 컴포지션을 활용해서 `LottoNumbers`를 인스턴스 필드로 둘지 여부 였던 것 같습니다. 그런데 `LottoTicket`이 갖는 책임이 `LottoNumbers`와 차이가 없어보여서 만들지 않고, 변수명들만 `LottoNumbers lottoTicket = LottoNumbers.from()`와 같이 `lottoTicket`으로 두었습니다. 혹시 리뷰어님은 `LottoTicket`이란 클래스를 만들었을지 궁금합니다!!

가감없는 피드백 부탁드립니다 :)

2021-01-09 05:35 UTC, parkjoos requested changes
안녕하세요 로또 미션 리뷰를 하게된 jay 라고 합니다. 
주말이라 조금 늦게 리뷰를 해드려서 죄송해요 
테스트 케이스가 아주 잘 만들어져 있고 도메인의 역할 분리도 아주 잘 되어 있는것 같습니다. 👍
로또당첨을 확인하는 결과에서 수익률 계산 로직에 오류가 있는것 같아서 수정 요청을 드립니다. 
추가로 코멘트들을 보시고 개선이 가능한 부분이 있을지 확인 부탁드립니다.

리뷰 본문에 남겨주신 고민중에 LottoTicket 은 저는 비슷하게 LottoRound 라는 이름으로 만들어보긴 했었네요
로또를 보면 이번주 몇회, 또 다음주가 되면 몇회 이렇게 되잖아요 그런걸 생각하고 엄청 큰 단위로 LottoRound 를 만들었는데요
사실 너무 오버 스펙이었습니다. 
지금 단계에서 그정도까지 생각할 필요는 없는게 맞는것 같구요 
이 다음 스텝에서 수동이 들어 가게 될때 지금 구조에서 어떻게 적용 되면 좋을지만 고민 해봐도 좋을것 같습니다. 
LottoBonusApplicable 에 대해서는 코멘트를 통해서 의견 전달 드렸어요 한번 확인 부탁드립니다. 

수고 많으셨습니다. 👏

2021-01-09 05:35 UTC, parkjoos commented on src/main/java/lotto/LottoMain.java
> +    }
LottoMain 에 main 함수와 함께 비즈니스 로직이 다 들어 있는데요
LottoService 나 LottoController 같은 Controller 레이어 를 하나 만들어서 그쪽에서 수행하도록 옮겨 보면 어떨까요?
LottoMain 클래스는 프로그램의 entry 역할만 하도록요
나중에 로또 프로젝트에 기능이 늘어난다고 하면 main 클래스에 비즈니스 로직들이 모여 있는것은 좋지 않을것 같아요

2021-01-09 05:35 UTC, parkjoos commented on src/main/java/lotto/LottoMain.java
> +    }
이로직도 위처럼 별도의 LottoController 같은 Controller 레이어 클래스나 
아니면 특별한 역할을 하니 LottoStatisticsController 클래스로 분리해 보는것도 좋을것 같네요

2021-01-09 05:35 UTC, parkjoos commented on src/main/java/lotto/domain/number/LottoNumbers.java
> +    }
이렇게 중복 인스턴스 개수를 찾을 수 있군요. 한 수 배우고 갑니다 👍

2021-01-09 05:35 UTC, parkjoos commented on src/main/java/lotto/domain/number/RandomLottoNumberGenerator.java
> +        }
randomNumbers 는 RandomLottoNumberGenerator 클래스의 생명 주기동안 유일할 필요가 있어 보여요
지금은 generate() 가 호출될 때마다 매번 생성이 될 것 같네요
생성자에서 static 한 데이터로 만들어 버리면 어떨까요?

2021-01-09 05:35 UTC, parkjoos commented on src/main/java/lotto/domain/number/LottoNumbers.java
> +    private final List<LottoNumber> lottoNumbers;
로또 번호를 구매할때의 특성을 생각해보면 List 보다는 Set 가 더 적합한 자료 구조 일것 같네요 
아래 distinct 체크 하는 부분에서 set 에 별도로 넣고 있는데 처음부터 자료구조가 set 이면 불필요한 로직을 좀 줄일수 있을것 같아요
그리고 요구사항을 자세히 보시면 로또를 출력할때 전부 정렬이 되어 있는걸 볼 수 있습니다.
출력할때 정렬을 할수도 있고 lottoNumbers 를 생성할때 정렬을 할 수 가 있겠죠
어떤게 더 효율적일까요?
Set 중에  자동으로 정렬을 해주는 자료구조가 뭔지 아신다면 그걸 이용해 보는 방법도 좋을 것 같네요

2021-01-09 05:35 UTC, parkjoos commented on src/main/java/lotto/domain/ranking/LottoRanking.java
> +    RANK_1(6, DONT_CARE, 2_000_000_000L, "6개 일치 (2000000000원)-"),
큰 long 형 숫자를 _ 로 읽기 쉽게 표현 하는 부분 아주 좋습니다. 👍

2021-01-09 05:35 UTC, parkjoos commented on src/main/java/lotto/domain/ranking/LottoBonusApplicable.java
> +}
설명해 주신 부분이네요 
어떤 부분 때문에 고민이 되는지 완전히 이해가 됩니다. 
읽기쉽고 직관적인 코드를 포기하고 람다 표현식과 함수형 프로그래밍을 이용할때는 그럴만한 이유가 있어야 할것 같은데요
제생각에는 지금의 경우 원래 코드의 로직이 엄청 복잡하지고 않고 성능상의 문제도 없을 것으로 보여요
이 방식을 유지 하려고 한다면 Function 의 이름을 좀더 직관적으로 지어 보는것도 좋을것 같습니다. 
apply 도 좀더 사용하는 쪽에서 이해하기 쉬운 이름이면 좋을것 같네요 한번 고민해 보세요

2021-01-09 05:35 UTC, parkjoos commented on src/main/java/lotto/view/OutputView.java
> +        System.out.printf("총 수익률은 %.2f입니다.", revenueRate.getRate());
요구사항에 보시면 수익률은 % 로 표현됩니다. 확인 후 수정 부탁드려요

2021-01-09 05:35 UTC, parkjoos commented on src/main/java/lotto/domain/ranking/LottoStatistics.java
> +        return LottoRevenueRate.of(calculateTotalPrice(), countTicket());
LottoRevenueRate.of 의 signature 를 보니 
`public static LottoRevenueRate of(long revenue, long totalTicketMoney)`
네요 실제로 로직을 보니 두번째 파라메터에 전체 구매 금액이 들어 가야 할 것 같은데 
지금은 countTicket 만 들어 가는것 같아요 실제 결과가 정상으로 나오지 않고 있을 것 같습니다. 
확인 부탁드립니다.

2021-01-09 05:35 UTC, parkjoos commented on src/test/java/lotto/domain/ranking/LottoStatisticsTest.java
> +        assertThat(result.getRate()).isEqualTo(6301000.0);
이 테스트 케이스가 실제 원하는 결과와 다른것 같아요
지금은 당첨 갯수가 많아서 TDD 에 맞게 테스트 케이스를 만들때 암산 해보기 좀 어려울 수 있을것 같은데요 
간단하게 한개 정도의 로또만 사서 당첨이 안되는경우 당첨이 되는 경우를 테스트 케이스로 만들어서 rate 가 의도에 맞게 나오는지 확인해 보면 좀더 쉬운 테스트 케이스가 될것 같아요

2021-01-09 17:22 UTC, ddaaac commented on src/main/java/lotto/domain/number/RandomLottoNumberGenerator.java
> +        }
`Collections.shuffle()`이 리스트를 직접 조작하는 것 같아서 thread-safe하게 randomNumbers를 공유하기 위해서 Collections.synchronizeList()로 감쌌습니다. 그런데 이걸로 리스트 전체의 조작에 대한 thread-safe가 보장되는지는 모르겠네요😓

2021-01-09 17:22 UTC, ddaaac commented on src/main/java/lotto/LottoMain.java
> +    }
LottoStatisticsController까지 분리는 생각도 못했네요 👍 
감사합니다!

2021-01-09 17:22 UTC, ddaaac commented on src/main/java/lotto/view/OutputView.java
> +        System.out.printf("총 수익률은 %.2f입니다.", revenueRate.getRate());
중간에 강의교안이 바뀌어서 맞춰서 표현했습니다...!

2021-01-09 17:22 UTC, ddaaac commented on src/test/java/lotto/domain/ranking/LottoStatisticsTest.java
> +        assertThat(result.getRate()).isEqualTo(6301000.0);
마지막에 귀찮았던 제 자신이 반성되는 코드네요... 감사합니다!

2021-01-09 17:22 UTC, ddaaac commented on src/main/java/lotto/domain/ranking/LottoStatistics.java
> +        return LottoRevenueRate.of(calculateTotalPrice(), countTicket());
테스트를 제대로 짜지 않아서 문제가 생겼네요 😅
감사합니다~

2021-01-09 17:22 UTC, ddaaac commented on src/main/java/lotto/domain/ranking/LottoBonusApplicable.java
> +}
나름 고민도 많이 해본 결과 BonusCondition으로 이름을 바꾸고 각 필드와 enum 형의 이름도 분명히 했습니다.
이전보다는 나아진 것 같네요 :)

감사합니다!!

2021-01-10 11:23 UTC, parkjoos approved these changes
리뷰 내용 반영 아주 잘 해주셨습니다. 👍
RandomLottoNumberGenerator 는 corby 이야기를 보고 나니 기존 로직이 더 좋았다는 생각이드네요
synchroziedList 의 경우 read 에도 lock 이 걸려서 multi thread 환경을 고려한다면 오히려 좋지 않을것 같아요
다음 단계에서 이부분은 다시 원래 로직으로 돌리는것도 좋을것 같아요
이번 미션은 이대로 머지 해도 좋을 것 같습니다.   
1단계 너무 고생 많으셨습니다. 다음 단계도 화이팅 입니다.!👏

2021-01-10 11:24 UTC, merged