[ian.lock 양정일] 로또 미션 1단계 PR
NewKrew2021/java-lotto-kakao pull request #24
Opened 2021-01-08 17:25 UTC by Jjungs7

안녕하세요 이안입니다. 잘 부탁드립니다!

미션을 진행하면서 제가 구현하는게 DTO가 맞는지 의문이 들었어요. 정확히는 어디까지가 DTO인지 잘 구분이 안 갔습니다. 미션에서는 getter를 통해 저장된 데이터를 단순히 반환하는 클래스들만 DTO로 분류하였는데, 데이터를 가지고 가공하여서 새로운 정보(이번 미션에서 StatisticsResult 클래스)를 반환하는 클래스도 DTO인가요?
---
주요 구현사항은 다음과 같습니다:

- LottoNumbers: 유저의 로또 한 장을 표현합니다
- LottoTickets: 유저가 가진 로또 묶음을 표현합니다
- WinningNumbers: 지난 주 당첨 번호를 나타냅니다
- LottoMatcher: 유저가 가진 로또 묶음과 지난 주 당첨 번호를 비교하여 등수별로 몇 개가 당첨되었는지 판별해주는 기능입니다
- LottoStatistics: 통계를 내주는 클래스입니다. 여러 결과(수익률, 당첨 개수)를 반환해야하기 때문에 StatisticsResult를 이용하여 반환합니다

도메인에서 랜덤 로직을 분리하기 위해 로또 발급기(LottoTicketIssuer)에서 숫자를 주입하는 방식으로 구현하였습니다
Consumer를 이용하여 최대한 getter 사용을 자제하였습니다.

2021-01-08 17:31 UTC, Jjungs7 commented on src/test/java/lotto/domain/LottoMatcherTest.java
> +class lottoNumberArgumentsProvider implements ArgumentsProvider {
모든 MatchResult Enum에 대해 테스트하기 위해 custom provider를 만들었습니다. 모든 Enum에 하지 않고 몇 개의 Enum만 테스트해도 됐을까요? 랜덤 숫자는 경계값이 확실해서 그 주변을 테스트하면 될 것 같은데 Enum의 경우에는 모든 값이 다 중요해보여서 모두 테스트하게 되었어요

2021-01-08 17:33 UTC, Jjungs7 commented on src/test/java/lotto/domain/LottoMatcherTest.java
> +    private List<LottoNumber> lottoNumberArgument(int... parameters) {
이 메소드는 여러 Test파일에서 사용하고 있어서 분리하고싶은데 test 패키지에 utils패키지를 만들어서 분리해도 될까요?

2021-01-08 17:38 UTC, Jjungs7 commented on src/test/java/lotto/domain/LottoMatcherTest.java
> +    private List<LottoNumber> customLottoNumbers(int... parameters) {
이 메소드는 여러 Test파일에서 사용하고 있어서 분리하고싶은데 test 패키지에 utils패키지를 만들어서 분리해도 될까요?

2021-01-09 20:05 UTC, Hue9010 requested changes
안녕하세요. 이번 리뷰를 맡은 휴입니다!
주말이라 리뷰가 조금 늦었네요. 🙏 
질문에 대한 답변은 피드백에 같이 드렸어요. 
피드백과 함께 확인하시고 궁금하신 사항은 언제든 문의주세요.

2021-01-09 20:05 UTC, Hue9010 commented on src/main/java/lotto/LottoMain.java
> +    private static InsertPrice insertPrice;
실행 시작점인 main에서 사용하다보니 별수 없이 모두 static 변수로 선언을 할 수 밖에 없는데 Model과 View를 연결하는 컨트롤러를 만들어보세요. 그리고 커밋 히스토리를 보니 일정 시점에 지역변수에서 필드로 변경하셨던데 컨트롤러를 만들면서 컨트롤러가 상태를 가져야 할지 한번 고민해보세요.

2021-01-09 20:05 UTC, Hue9010 commented on src/main/java/lotto/domain/dto/InsertPrice.java
> +            throw new IllegalArgumentException(message);
```java
throw new IllegalArgumentException("price cannot be negative.");
```
다른 곳도 마찬가지지만 바로 메시지를 넘겨줘도 충분합니다.

2021-01-09 20:05 UTC, Hue9010 commented on src/main/java/lotto/view/InputView.java
> +    }
-1을 반환해줄 필요가 있을까요? 🤔

2021-01-09 20:05 UTC, Hue9010 commented on src/main/java/lotto/domain/LottoMatcher.java
> +    }
`int count`는 람다 내에서 사용 못하지만 `int[] count`는 가능합니다. 왜 그럴까요? 

[What are the rules for a local variable in lambda expression in Java?](https://www.tutorialspoint.com/what-are-the-rules-for-a-local-variable-in-lambda-expression-in-java)

참고로 int[]도 한번 더 할당하면 안됩니다. ㅎㅎ
```java
        int[] count = new int[1];
        count = new int[1];
        LottoNumbers luckyNumbers = winningNumbers.getLuckyNumbers();

        luckyNumbers.delegate(lottoNumbers ->
                count[0] = (int) lottoNumbers.stream()
                .filter(lottoTicket::contains)
                .count());
```

2021-01-09 20:05 UTC, Hue9010 commented on src/main/java/lotto/domain/LottoMatcher.java
> +    }
> Consumer를 이용하여 최대한 getter 사용을 자제하였습니다.

getter를 사용하지 않았을 뿐 getter를 사용하지 않는 이유 중 하나인 캡슐화를 위반하고 있습니다. 그리고 `List<LottoNumber> lottoNumbers`의 존재도 외부에 드러내고 있으며 실제 로직도 모두 외부에서 이뤄지고 있습니다. 일급 컬렉션을 만들어 두고 일급 컬렉션이 가지고 있는 컬렉션을 마음대로 사용가능한 방법을 제공해 주고 있네요. unmodifiableList로 불변 컬렉션을 제공한다는 것 빼고는 일급 컬렉션의 역할이 부족해 보입니다.

getter를 사용하지 않는것에만 집중하다가 위 사항들을 놓친 것 같아요. 그리고 컨슈머는 하나의 인수를 받고 반환은 하지 않는 단순 소비 함수입니다. 하지만 반환값을 만들기 위해 약간의 편법을 사용했네요.(위 람다 질문)

아래와 같은 시그니처를 가진 메서드를 만들 수 있었을 것 같은데(어떤걸 기준으로 번호를 맞춰 볼지에 따라 택1) getter를 사용하지 않는 방법으로 컨슈머를 적극 사용한 이유를 알고 싶습니다. 🤔
```java
public class LottoNumbers {
    public int matchWinning(WinningNumbers winningNumbers);
}

public class WinningNumbers {
    public int matchLotto(LottoNumbers lottoNumbers);
}
```

2021-01-09 20:05 UTC, Hue9010 commented on src/main/java/lotto/domain/dto/LottoNumber.java
> +    private final int number;
매번 LottoNumber를 만들지 말고 캐싱을 적용해 인스턴스 생성을 최소화 할 수 있을 것 같네요. 😉 

한가지 질문 
```java
Integer a = 127; 
Integer b = 127;
```

> a == b (true? false?)

a == b의 답은 뭘까요?

답은 요기에! [[Java] Integer.valueOf(127) == Integer.valueOf(127) 는 참일까요?](https://meetup.toast.com/posts/185)

2021-01-09 20:05 UTC, Hue9010 commented on src/main/java/lotto/domain/StatisticsResult.java
> +public class StatisticsResult {
> 미션을 진행하면서 제가 구현하는게 DTO가 맞는지 의문이 들었어요. 정확히는 어디까지가 DTO인지 잘 구분이 안 갔습니다. 미션에서는 getter를 통해 저장된 데이터를 단순히 반환하는 클래스들만 DTO로 분류하였는데, 데이터를 가지고 가공하여서 새로운 정보(이번 미션에서 StatisticsResult 클래스)를 반환하는 클래스도 DTO인가요?

DTO는 Data Transfer Object로 데이터 전송을 위한 객체입니다. getter 위주의 단순한 Object인지가 아니라 (주로 계층간)데이터 전달 위한 Object인지 여부가 중요합니다. 대표적으로 Request/Response에 사용되는 값을 생각하시면 됩니다.

Spring을 아신다는 전제하에 간단히 보면
```java
   @GetMapping("/example")
   public ResponseEntity<MemberResponse> save(@RequestBody MemberRequest memberRequest) {
       ...
   }
```
서로 다른 계층인 Controller <-> View로 데이터를 주고 받을 때 사용하는 Request/Response가 대표적인 DTO입니다. 그렇기 때문에 getter 외 다른 기능이 필요하지 않는 겁니다. 즉, 단순한 구조로 getter만 존재하는지가 아닌 계층간 데이터를 주고 받기 위한 객체인지가 DTO인지를 구분 짓는 요소입니다.

그런면에서 결과 MatchResults를 통해 결과 값을 찾는 행위까지 하는 StatisticsResult는 DTO가 아닙니다.

2021-01-09 20:05 UTC, Hue9010 commented on src/main/java/lotto/domain/dto/TotalPrice.java
> +public class TotalPrice {
TotalPrice와 InsertPrice를 따로 두는 이유가 있을까요?

그리고 price는 DTO보다는 VO의  성격이 강할 것 같네요. VO에 대한 설명은 오래된 글이지만 추천 도서에 있는 객체지향의 사실과 오해의 저자 조영호님 블로그의 포스팅 추천드립니다.
[Domain-Driven Design의 적용-1.VALUE OBJECT와 REFERENCE OBJECT 1부 ](http://aeternum.egloos.com/1105776)
[위 연재글 목록(총 4부)](http://aeternum.egloos.com/category/Domain-Driven%20Design/page/3)

2021-01-09 20:05 UTC, Hue9010 commented on src/main/java/lotto/domain/LottoTicketIssuer.java
> +                .map(ignore -> new LottoNumbers(strategy.generateLottoNumbers()))
[Java8 Stream은 loop가 아니다.](https://www.popit.kr/java8-stream%EC%9D%80-loop%EA%B0%80-%EC%95%84%EB%8B%88%EB%8B%A4/)
스트림을 단순 반복문으로 사용한 케이스 같습니다. ignore가 그 흔적으로 보이네요.

2021-01-09 20:05 UTC, Hue9010 commented on src/main/java/lotto/utils/RandomPickStrategy.java
> +public class RandomPickStrategy implements NumberPickStrategy {
👍
이후 수동까지 고려한 스펙으로 보이는군요. 😏
인터페이스를 잘 쓰기 쉽지 않은데 제대로 사용해 주셨네요.👍

한기지 개선을 해 보자면 RandomPickStrategy가 1~45 범위의 리스트를 generateLottoNumbers를 수행할 때 마다 매번 만들 필요가 있을까요?

2021-01-09 20:05 UTC, Hue9010 commented on src/main/java/lotto/domain/MatchResults.java
> +                .orElse(0);
Map의 getOrDefault를 한번 찾아보세요. 컬렉션에는 알아두면 편한 기능이 많답니다.😉

2021-01-09 20:05 UTC, Hue9010 commented on src/main/java/lotto/domain/LottoMatcher.java
> +    }
getter 사용 자제를 위해 Consumer를 사용하는 방법을 채택한 이유가 궁금해요. 의견을 주고받고서 개선 방향을 얘기하고 싶지만 과제별로 짧은 호흡으로 진행되는 점을 고려해서 가능하다면 Consumer를 제거하고 Consumer로 만들었던 로직을 각 객체가 가지게 바꾸는 걸 추천드릴게요. (혹여 다른 방향을 생각하신다면 의견주셔도 됩니다.)

2021-01-09 20:05 UTC, Hue9010 commented on src/test/java/lotto/domain/dto/InsertPriceTest.java
> +    }
정상적인 값에 대한 테스트만하기 쉬운데 음수에 대한 처리 확인까지 잘해주셨네요. 👍

2021-01-09 20:05 UTC, Hue9010 commented on src/test/java/lotto/domain/LottoNumbersTest.java
> +    @CsvSource({"1,true", "7,false"})
junit5를 잘 활용하셨군요. 👍

2021-01-09 20:05 UTC, Hue9010 commented on src/main/java/lotto/domain/MatchResults.java
> +        resultCounter = new EnumMap<>(MatchResult.class);
EnumMap 😮 👍

2021-01-09 20:05 UTC, Hue9010 commented on src/main/java/lotto/domain/MatchResult.java
> +        if (MatchResult.FIRST.matchCount == matchCount) {
각 enum이 count와 bonus번호를 가지고 일치하는지 확인하는 기능을 제공한다면 if문이 아니라 다형성을 통해 해결할 수 있지 않을까요? 😉

2021-01-09 20:05 UTC, Hue9010 commented on src/main/java/lotto/domain/MatchResult.java
> +    NULL(0, 0, "꽝!"),
NULL이 꽝을 의미하진 않는것 같아요. 좀더 좋은 이름은 없을까요? 🤔

2021-01-09 20:05 UTC, Hue9010 commented on src/main/java/lotto/domain/StatisticsResult.java
> +public class StatisticsResult {
한가지 궁금한 사항은 지금 단계에서 DTO를 만들어 보는 목적이 무엇인지 궁금해요. 개인적으로 DTO는 Request/Response 외에는 필요성을 느끼지 않으면 만들지 않는 편입니다.
DTO에 관해서는 익숙한 분이 보이는 아래 글에서 많이 얘기를 하고 있네요.  😏 
[혹시 DTO(VO) 작성하시나요?](https://www.slipp.net/questions/22)

2021-01-09 20:05 UTC, Hue9010 commented on src/main/java/lotto/view/InputView.java
> +        }
아무 처리를 안하는걸 명시적을 표현하기 위한 `NumberFormatException ignore` 💯

2021-01-09 20:05 UTC, Hue9010 commented on src/test/java/lotto/domain/LottoTicketIssuerTest.java
> +        LottoTickets tickets = LottoTicketIssuer.issue(() -> Stream.of(1, 2, 3, 4, 5, 6)
💯  👍

2021-01-09 20:05 UTC, Hue9010 commented on src/test/java/lotto/domain/LottoMatcherTest.java
> +class lottoNumberArgumentsProvider implements ArgumentsProvider {
[테스트 커버리지에 현혹되지 말자 ](http://aeternum.egloos.com/1209470)
테스트 커버리지에 대한 얘기지만 실제로는 무엇을 테스트할지에 대한 얘기라 어떤걸 테스트할지 고민될 때 보면 좋을 것 같아요.

질문에 대한 답변을 예/아니요로 드리자면 예 하는게 좋다고 생각됩니다. 😉

2021-01-09 20:05 UTC, Hue9010 commented on src/test/java/lotto/domain/LottoMatcherTest.java
> +    private List<LottoNumber> customLottoNumbers(int... parameters) {
좋은 부분을 문의하셨네요. 👍 
넵, 테스트를 위해 private 메서드를 만들었던 것 처럼 공통적으로 사용한다면 별도의 클래스를 만들어 사용할 수 있습니다.
TestUtil로 만들지는 말고요! 이름을 TestUtil 이런식으로 지으면 무엇이나 해주는(무엇을 하는지 모르는) 클래스가 만들어집니다. test 패키지 내 코드도 프로그래머가 관리할 코드라는걸 상기하는게 좋습니다. 😉

2021-01-10 14:03 UTC, Jjungs7 commented on src/main/java/lotto/domain/LottoMatcher.java
> +    }
consumer가 아무 값도 리턴하지 않는다는 점과 lambda에서 primitive 사용하는데 제한이 있다는 점에서 눈치챘어야했는데 끝까지 꼼수를 쓰게 되었네요. 보내주신 글을 읽으면서 lambda의 scope에 관하여 더 이해할 수 있었고 자바는 변수를 초기화할 때 effectively final로 초기화 한다는 것을 배웠습니다 😆

consumer을 사용한 부분은 궁금한 점을 해소한 다음 수정하고싶어서 질문 드리고자 합니다! 먼저, Consumer를 적극 사용한 이유는 작업을 상위 클래스에서 정하고 이것을 위임한다는 것이 consumer가 작동하는 방식과 일치한다고 생각해서 활용하게 되었어요. 제가 아직 작업을 위임한다는 것을 제대로 이해하지 못해서 그런 것 같습니다 😢  아래 헷갈리는 상황을 적어볼게요!

- 첫 번째 상황: [LottoMatcher.match(LottoTickets lottoTickets)](https://github.com/next-step/java-lotto-kakao/pull/24/files/86b0b9f97f3d528b768c4960518b18db117c7259#diff-68b1175df01ea775d0999fa9ac83597a80d12bce619aab476b6efe69858423c4R17) 에서 `LottoTickets`가 *tickets*을 저장하고 있고 당첨번호와 비교하기 위해서는 *tickets*에 대한 정보가 필요한 상황입니다. 만약 `LottoTickets`에다가 작업을 위임한다고 하면 `LottoTickets.getMatched(WinningNumbers numbers)` 와 같은 메소드를 만들어서 `LottoTickets`가 정보를 반환하게 하는 것이 맞을까요? 그렇게 된다면 아래와 같은 코드가 나올 것으로 예상이 되는데 match() 함수가 하는 일이 너무 없어지는 것이 아닌가 의문이 들어요 ㅠㅠ
```java
// LottoMatcher.java
...
public MatchResults match(LottoTickets lottoTickets) {
    return lottoTickets.getMatched(winningNumbers);
}

// LottoTickets.java
...
public MatchResults getMatched(WinningNumbers numbers) {
    // 당첨 번호와 로또 티켓 뭉치들을 비교하여 몇 개가 당첨됐는지 반환
}
```

- 두 번째 상황: [OutputView.printStatistics(LottoStatistics statistics)](https://github.com/next-step/java-lotto-kakao/pull/24/files/86b0b9f97f3d528b768c4960518b18db117c7259#diff-940d1c44120ea83f932b0ee11c19b877bf63456804f1092acf8a622ed268e26cR29)에서 당첨된 개수를 출력하려면 `MatchResults`에 대한 정보가 모두 필요한 상태입니다. 여기서 `MatchResults`에 작업을 위임하려고 하는데, `MatchResults.constructOutput()` 같은 메소드를 만들어서 필요한 출력 메시지를 구성하려니 view에 관한 로직이 MatchResults에 들어가는 것 같고(또 OutputView는 너무 하는 일이 없어지는 것 같고) `MatchResults.getResults()` getter를 통해서 `EnumMap` 를 전부 가져오자니 내부 데이터를 숨기자는 OOP원칙에 위배되는 것 같아요. 이런 상황에서는 어떻게 하는게 맞을까요??

2021-01-10 14:26 UTC, Jjungs7 commented on src/main/java/lotto/domain/StatisticsResult.java
> +public class StatisticsResult {
DTO, VO 에 관한 개념이 모호했는데 답변해주신 것과 아래 블로그 글까지 모두 보니까 더 명확해진 것 같아요!! 한 가지 더 궁금한 점은 인터넷에서 본 블로그 글 중에 DTO와 VO의 차이는 VO가 read-only라는 점이다라고 언급되어 있는데 제가 생각하기엔 아닌 것 같아요. DTO, VO는 객체 간에 데이터를 주고 받기 위한 구조체이고(즉, get/set 외에는 다른 행위를 하여서는 안됨) DTO는 VO를 포함하는 개념, 하지만 VO는 원시값 하나만을 갖고 있는 가장 기본이 되는 단위로 이해했습니다. 따라서 이번 미션의 [WinningNumbers](https://github.com/next-step/java-lotto-kakao/pull/24/files/86b0b9f97f3d528b768c4960518b18db117c7259#diff-5aae81d8456b88144a182eebb98366de17f0a0557420512b5aee488971c67aa5R5)의 경우 로또 티켓과 보너스볼을 갖고 있으니 DTO이고 나머지 `InsertPrice, LottoNumber, Rate, TotalPrice`는 VO이다가 맞을까요??

---
이번 미션 요구사항 중 **규칙 3: 모든 원시값과 문자열을 포장한다**가 포함되어 있어서 보이는 원시값을 모두 포장하려 했습니다!!

2021-01-10 14:32 UTC, Jjungs7 commented on src/main/java/lotto/domain/dto/TotalPrice.java
> +public class TotalPrice {
규칙 3에 의거해서 유저가 투자한 금액, 유저의 총 당첨 금액이 서로 다른 개념이라 생각돼서 다른 VO로 작성하였지만, 다시 읽어보니 Price라는 큰 틀 안에서 해도 됐을 것 같아요

DTO/VO 에 관하여 자세히 모르는데 다른 분들이 쓰셔서 DTO가 맞나보다 하고 썼던 것 같아요😫 . 제대로 알고 사용하지 않으니까 오히려 혼란을 일으키게 된 것 같네요. 용어를 쓸 땐 확실히 알고 사용 해야겠다는 생각이 들었습니다!!

2021-01-10 14:40 UTC, Jjungs7 commented on src/main/java/lotto/domain/LottoTicketIssuer.java
> +                .map(ignore -> new LottoNumbers(strategy.generateLottoNumbers()))
단순 반복문의 경우에는 for, while문으로 하고 list로 어떤 작업을 하고 싶은 경우에는 stream을 사용하는 것이 더 나을까요?
아니면 단순 반복적인 일을 하는 stream의 경우 성능 하락만 잘 유의해서 쓴다면 stream을 사용해도 괜찮을까요?

일반적으로 stream을 사용하는 것이 for, while문보다 깔끔한 코드가 나오는 것 같은데 성능 하락을 방지하기 위해 의식적으로 for, while문을 쓰는 것이 나을 수도 있겠다는 생각이 들어서요!

2021-01-10 23:07 UTC, Hue9010 commented on src/main/java/lotto/domain/LottoTicketIssuer.java
> +    }
> 단순 반복문의 경우에는 for, while문으로 하고 list로 어떤 작업을 하고 싶은 경우에는 stream을 사용하는 것이 더 나을까요?
아니면 단순 반복적인 일을 하는 stream의 경우 성능 하락만 잘 유의해서 쓴다면 stream을 사용해도 괜찮을까요?
>
> 일반적으로 stream을 사용하는 것이 for, while문보다 깔끔한 코드가 나오는 것 같은데 성능 하락을 방지하기 위해 의식적으로 for, while문을 쓰는 것이 나을 수도 있겠다는 생각이 들어서요!

반복문도 List 선언, 일반 for문을 사용하는 점에서 생각보다 깔끔하진 못하군요. 😭 이번 사례는 약간의 취향 문제가 될 수 있을 것 같네요.

결론부터 말씀드리자면 최적화를 너무 고려하실 필요는 없습니다. 그래서 스트림의 사용 유무는 가독성을 우선시하면 된다고 생각합니다. 
저는 주로 변환(map)이나 수집(collect) 연산이 필요할 때 사용합니다. for문을 사용해도 생각보다 가독성에 큰 차이가 없거나 거꾸로 로직을 파악하기 더 쉬운 경우도 있어 스트림 사용에 대한 피드백을 드렸었습니다. 이번경우는 팀내 컨벤션이 있다면 따르거나 각 작업자의 취향정도로 정리하면 될 것 같습니다.

성능에 관련해서는 `과도한 최적화는 필요 없다.`, `정말로 필요하기 전까지는 성능 최적화를 할 필요 없다.`라는 조언이 유명하죠. 마찬가지로 생각됩니다. 임베디드 등 지나치게 한정된 하드웨어의 자원에서 돌아가는 프로그래밍을 하는게 아닌 이상 성능을 우선적으로 고려할 필요는 없다고 생각합니다. 세세하게 고려하려면 지금의 for문도 조건절에 있는 getTicketCount가 조건 확인 때마다 이뤄지는지 컴파일러단에서 최적화를 통해 for문 밖으로 종료 값을 계산해두는지 확인이 필요할 겁니다.

게다가  웹 백엔드에서는 특정 API의 응답 지연이 발생하면 보통은 (정말로 말도안되게 반복하는게 아닌 이상)자바 코드 내의 문제보다는 DB나 외부 API와의 통신 구간에서의 지연이 문제인 경우가 많습니다. 이런 문제는 캐싱, 쿼리 개선, 스펙 업 등등 문제의 원인을 파악하고 그에 따른 조치를 하면 됩니다.

추가로 map은 변환 연산으로 스트림에 있는 요소를 변환할 때 사용합니다. 그런 면을 엄격하게 적용하면 이전 스트림은 map보다는 foreach에서 add하는게 좋지 않을까 생각됩니다. numbers를 스트림 외에서 선언해야 하는 단점도 있고해서 이건 저도 좀 고민되는 작은? 의견입니다.

2021-01-10 23:07 UTC, Hue9010 commented on src/main/java/lotto/domain/RandomPickStrategy.java
> +            .collect(Collectors.toList());
단순한 할당이 아니면 `LottoNumber`처럼 `static {}`을 사용하는게 좋아보여요.

2021-01-10 23:07 UTC, Hue9010 commented on src/main/java/lotto/domain/LottoMatcher.java
> +    }
### 첫번 째 :
[역할, 책임, 협력](https://velog.io/@ljinsk3/%EC%97%AD%ED%95%A0-%EC%B1%85%EC%9E%84-%ED%98%91%EB%A0%A5), 
[생각하라, 객체지향처럼](https://woowabros.github.io/study/2016/07/07/think_object_oriented.html)를 참고하면 좋을 것 같아요. 구현할 코드가 별로 없는 것(하는 일이 적은 것)은 고려하실 필요가 없습니다. 둘 다 조영호님의 책(객체지향의 사실과 오해, 오브젝트)이 기반인데 가볍게(?) 볼 수 있는 `객체지향의 사실과 오해`를 추천드립니다.

> LottoMatcher: 유저가 가진 로또 묶음과 지난 주 당첨 번호를 비교하여 등수별로 몇 개가 당첨되었는지 판별
 
유저가 가진 로또 묶음을 받아 당첨 번호와 비교하여 결과를 내는 역할을 충분히 담당한다고 볼 수 있습니다. 현실에서는 관리자의 여러 일 중 작업자한테 업무를 배정해주는 일만 대입해서 생각해보면 관리자는 업무만 주고 결과만 받으니 아무 일을 안하는 걸까요? 🤔 협력이라는게 생각보다 별거 없답니다. 😉

### 두번 째 :
넵, 출력메시지를 어떻게 다룰지는 View의 영역입니다. 이 부분에서 DTO로 제공하여 사용하면 View에서 그런 고민을 할 필요가 없습니다. StatisticsResult를 DTO로 만든다면 StatisticsResult의 필드도 모두 DTO로 만들어야 합니다. 그러면 MatchResults의 Map<MatchResult, Integer>를 사용하는 것도 문제가 없죠. 사실 지금은 View가 자바환경이지만 웹 페이지라면 statisticsResult.getResultCountOfSomeMatch같이 객체의 메서드를 사용할 수도 없습니다. View에서는 객체를 다룬다기보다는 데이터를 다룬다고 생각하고 접근하는게 좋습니다. 다만 DTO는 그 변환 과정의 피로도와 코드가 복잡해지는 면이 있고 득보다는 실이 커보이고 과정이 빠른 속도로 진행됨에 따라 지금 단계보다는 Spring을 사용하는 과제때 집중해보는걸 추천드립니다.

2021-01-10 23:29 UTC, Hue9010 commented on src/main/java/lotto/domain/StatisticsResult.java
> +public class StatisticsResult {
DTO와 VO가 구성에 있어서는 비슷한 점이 많지만 서로 연관지어 생각하지말고 이름 그대로 Data Transfer Object, Value Object로만 구분하는걸 추천드려요. 계층간 데이터를 전송할 때 사용하기 위한 객체인지, 값으로서 사용 되는 객체인지 말이죠. 단순 getter/setter만 존재해도 데이터 전송을 위해 만든 객체가 아니라면 DTO가 아닙니다. 객체의 형태가 DTO, VO로의 구분을 결정 짓는게 아닙니다.

VO가 read-only인 점은 DTO와 별개로 VO만 고려해서 생각해도 간단합니다. 정확히는 read only라기보다는 불변 객체라는게 맞을 것 같네요. VO가 왜 불변해야하는지는 만원 지폐의 값이 바뀌는 상황을 생각하면 될 것 같네요.(애초에 제대로 된 VO라면 값이 바꼈는데 동일 객체로 본다는게 말이 안되네요.)

참고로 원시값을 포장한다고해서 꼭 VO로 만들 필요는 없습니다. 대표적으로 Integer가 그러한데 원시값을 포장하고 그 외의 기능도 제공을 해주죠. 이번 미션에서 원시값을 포장한 객체를 VO로 만들지 아닐지는 선택사항입니다. 

말씀처럼 xxPrice, Rate, LottoNumber는 VO이고 WinningNumbers는 일반 Object로 보입니다.

2021-01-10 23:32 UTC, Hue9010 approved these changes
주말에 빠르게 반영해주셨네요. 👍 
큰 줄기에 변경이 필요한 부분은 아직 반영이 안됐지만 다음 단계의 요구사항을 봤을 때 같이 진행해도 좋을 것 같네요. 이번 단계는 머지할게요. 
질문에 대한 답변 남겼는데 확인하고 다음 단계 진행하면 됩니다! (혹시 제가 놓친 질문이 있다면 말씀 주세요. 😉)
참고로 궁금한 사항은 언제든 질문해주세요.

2021-01-10 23:32 UTC, merged