[dy.namic] 로또 미션 1단계 리뷰 요청 드립니다.
NewKrew2021/java-lotto-kakao pull request #26
Opened 2021-01-08 23:55 UTC by kdy2000

안녕하세요 :)

계속해서 과제를 진행하다보니 이런 프로젝트가 조금씩 익숙해지고 있는 것 같습니다. 과제수행 초반에는 빨리 풀리퀘하고 피드백 받아서 수정하자는 마음이 컸었는데, 과제를 진행하면서 부족한 부분들이 자꾸 신경쓰여 리팩토링을 계속 했던것 같습니다. 그래서 간단한 과제임에도 시간을 많이 사용했습니다. ㅜㅠ

과제를 진행하다보니, 테스트 클래스들이 여러 패키지에 산재하게 되었습니다. 현재는 유닛테스트 한번 돌릴때마다, 테스트 클래스에서 run버튼을 일일이 클릭하고 있습니다. 리뷰어께서는 어떻게 테스트 하시는지 궁금합니다!

사용된 클래스에 대한 설명은 README.md 에 간략히 적어두었습니다.
가감없는 피드백 부탁드립니다 ㅎㅎ

2021-01-09 16:41 UTC, limmmee-bonjour requested changes
안녕하세요 :)! dy 이번 로또 미션을 함께하게 될 벨입니다 😄 
기능구현도 꼼꼼히 남겨주시고 코드상에 주석도 적절히 적어주셔서 코드리뷰를 잘 할수 있었습니다 👍 
그런데 코드상에 에러 코드로 인해 정상적으로 프로그램이 동작하지 않아요!
사용되지 않는 클래스도 여러군데 존재하고요. 
해당 부분과 [ 도전! ]이라고 코멘트 드린 부분은 고민하셔서 꼭 수정 부탁드립니다. 
이번 리뷰는 Request changes 드릴게요!  관련해서 궁금하신 점이 있으시면 언제든 DM 주세요! 
그럼 화이팅 입니다!

2021-01-09 16:41 UTC, limmmee-bonjour commented on README.md
> +## 기능구현 목록
기능 정리를 아주 꼼꼼히 잘 해주셨네요 👍

2021-01-09 16:41 UTC, limmmee-bonjour commented on src/main/java/lotto/controller/LottoMachine.java
> +public class LottoMachine {
해당 클래스는 Controller 용도로 만들어주신걸로 보여지네요!
그런데 꼭 객체로 만들어져야 할까요? 레퍼런스 객체를 한 번만 만들것 같은데, 경계가 모호해보입니다. 어떻게 생각하시나요?

2021-01-09 16:41 UTC, limmmee-bonjour commented on src/main/java/lotto/controller/LottoMachine.java
> +        userMoney = Input.getPriceFromUser();
"빈값, 문자(a)"가 들어온다면 어떻게될까요?
기본적인 예외 사항에 대해서는 validation 체크를 해주는 것이 좋습니다 :)
테스트케이스에 이와같은 테스트 코드가 추가되면 좋겠죠?
테스트 케이스는 성공 케이스보다는 항상 실패 케이스에 대해 고민해보아야 해요 :)

2021-01-09 16:41 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/LottoGame.java
> +public class LottoGame {
해당 클래스때문에 application이 정상적으로 동작하지 않네요!
확인해보시고 사용되지 않는 클래스라면 삭제해주세요 :)

2021-01-09 16:41 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/LottoPaperGenerator.java
> +public class LottoPaperGenerator {
해당 클래스는 두 가지가 관심사(LottoPaper를 생성하는것, 로또를 만드는 방법)를 가지고 있는것 같습니다.
게다가 해당 클래스를 객체보다는 [팩토리](https://jusungpark.tistory.com/14)로써의 의미가 강해보이네요. (레퍼런스 객체를 만들 필요가 없어보여요!)
두가지 관심사를 분리해볼까요?

[ 도전! ] 만약 자동로또번호가 아닌 다른방법으로 로또번호가 만들어지면 어떻게될까요?
LottoPaperGenerator에 코드가 추가되어 엄청 뚱뚱해질거예요!
Generator가 로또만드는 방법을 가지고 있기보다는 로또만드는방법 자체를 Ticket에게 넘겨주어 ticker은 생성만 하게만 하면 되지 않을까요? 그러면 티켓은 만드는방법에 따라 유연하게 로또 번호를 가지고 있을거예요!
[이 글](https://velog.io/@kyle/%EB%94%94%EC%9E%90%EC%9D%B8-%ED%8C%A8%ED%84%B4-%EC%A0%84%EB%9E%B5%ED%8C%A8%ED%84%B4%EC%9D%B4%EB%9E%80)을 보시면서 어떻게 유연하게 변경할 수 있을지 고민해 보아요 :) 
이렇게 로또 만드는방법을 전략패턴으로 만들면 지금보다 조금 더 쉬운 테스트케이스를 작성할 수 있을거예요 :) 

+) generateManually 메서드도 로또 만드는 방법 중 하나겠지요? 
+) 코드상에 LottoNumberGenerator 만들어주신 코드가 남아있는데 롤백(?)한 이유가 있을까요?

2021-01-09 16:41 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/LottoPaperGenerator.java
> +        } while (genNumbers.size() < 6);
6에게 이름을 붙여주세요! 
중복이나 static 변수로 만들기 위해 상수화를 많이 하지만 네이밍을 주어 그 의도를 나타내는게 코드상에서는 더 가독성 높은 코드를 만들 수 있다고 생각합니다 :)

2021-01-09 16:41 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/NonRandomNumberGenerator.java
> +import java.util.HashSet;
사용되지 않는 클래스라면 삭제해주세요 😉

2021-01-09 16:41 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/Ticket.java
> +
당첨 로또 번호와 내가 가진 로또를 비교하여 랭킹을 가져오는것은 해당 도메인에 있는게 맞을까요?
Ticket은 레퍼런스 객체인데 모든 레퍼런스가 랭킹을 메기는법에 대하여 다 가지고 있어야하는 걸까요?
게다가 ticket의 관심사도 아닌것처럼 보여요 :)
만약 Rank의 값이 추가되면 ticket도 수정해줘야겠죠? 

[ 도전! ] Rank Enum도 잘 만들어주셨는데, 내가 일치하는 번호만 알려주면, Rank에서 등수를 알려주면 되지 않을까요?
등수 메기는법은 랭킹의 관심사로 보여집니다 :)
이 부분을 관심사가 맞는 곳으로 옮겨줍시다!

2021-01-09 16:41 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/WinnerBalls.java
> +    private final Ticket ticket;
도메인적으로 생각해보면 WinnetBalls는 로또 티켓을 가지고있는걸까요?
그냥 단순히 로또 당첨 번호일것 같은데요 :)
Ticket은 내가 산 로또 티켓인데 당첨번호와 의미가 섞여져 있네요.
네이밍이나 타입을 좀 더 명확하게 하는 것이 좋습니다 :)

만약 확률에 따른 Ticket이 만들어지게된다면 (요구사항은 Ticket에 가격과 확률을 높이는 멤버변수가 추가됩니다)
이는 WinningBalls까지 영향이 있어야할까요~? 고민해 보면 좋을것같아요 :)

2021-01-09 16:41 UTC, limmmee-bonjour commented on src/main/java/lotto/dto/LottoNumberData.java
> +public class LottoNumberData {
DTO 잘 만들어주셨습니다 👍

2021-01-09 16:41 UTC, limmmee-bonjour commented on src/main/java/lotto/dto/LottoResult.java
> +    final int[] orderCount = new int[10];
orderCount를 배열로 만들어주신 이유가 있나요? 
size인 10은 어떤 의미일까요~?

2021-01-09 16:41 UTC, limmmee-bonjour commented on src/main/java/lotto/setting/Format.java
> +public class Format {
validation 클래스를 잘 만들어주셨습니다 :) 
다만 모든 메서드가 정적메서드인 유틸리티 클래스로 보여지네요!
유틸리티 클래스를 만들때는 레퍼런스 변수를 만들지 못하도록 기본생성자에 Exception을 추가해주는게 좋습니다 :) 
그리고 Format보다는 의미가 더 드러나도록 네이밍을 변경해주시는게 좋을 것 같아요 :) 
```
private Format() {      throw new IllegalStateException("Utility class");    }
```

2021-01-09 16:41 UTC, limmmee-bonjour commented on src/main/java/lotto/setting/Format.java
> +            throw new RuntimeException("invalid Ticket size!!");
RuntimeException 보다는 의미가 더 드러나는 Exeption을 사용해주세요.
(보통 RuntimeException은 지양하고 있습니다 :))

2021-01-09 16:41 UTC, limmmee-bonjour commented on src/main/java/lotto/setting/Prize.java
> +    public static final long MONEY_FOR_FIRST = 2000000000;
보통 숫자는 가독성을 위해 천단위로 _ 를 붙여줍니다 :) 5_000 !

2021-01-09 16:41 UTC, limmmee-bonjour commented on src/main/java/lotto/setting/Rank.java
> +public enum Rank {
Enum 클래스를 잘 만들어주셨어요 👍

2021-01-09 16:41 UTC, limmmee-bonjour commented on src/main/java/lotto/utils/Utils.java
> +    public static List<Integer> extractIntFrom(String userInput, String delimiter) {
예외사항에 대해서도 꼼꼼하게 잘 처리해주셨네요 💯

2021-01-09 16:41 UTC, limmmee-bonjour commented on src/main/java/lotto/view/Input.java
> +    private static WinnerBalls validationCheckAndWrap(List<Integer> userInputNumbers, int bonusBall){
validation은 항상 고민이 되는 주제입니다 :)
저 같은 경우에는 입력 / 도메인에서 각각 validation을 처리합니다.
입력레이어와 도메인레이어는 완벽하게 분리되어야하는 레이어이기 때문에 입력 / 도메인에 따라 각각 validation 처리합니다.
그리고 보통 도메인의 경우에는 validation도 하나의 정책이 될 수 있기 때문에 가까이 있는게 좋다고 생각합니다. 그래서 도메인 내부에 validation을 위치시키고 있습니다. (만약 빈값 확인같이 기본적인 validation은 유틸을 사용하고요!)
입력의 경우는 다양한 입력방식이 있기때문에 입력 validation 유틸 클래스로 따로 만드는 편입니다.
정답은 없다고 생각합니다. dy가 고민하셔서 원칙에 맞는(이유가 있는) 개발을 하시면 될 것 같아요 :)

2021-01-09 16:41 UTC, limmmee-bonjour commented on src/main/java/lotto/view/InputView.java
> +public class InputView {
사용되지 않는 클래스같은데 지워주세요 ~!

2021-01-09 16:41 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/LottoPaper.java
> +        return money;
네이밍은 getScore~인데 return 변수는 money네요! 맞춰주는게 가독성을 높일 수 있습니다 :)
그리고 금액을 return하는데 score라는 네이밍은 조금 어색한 것 같아요!

2021-01-09 16:41 UTC, limmmee-bonjour commented on src/main/java/lotto/dto/LottoResult.java
> +    public double getRate(int inputMoney){
비즈니스 로직은 DTO보다는 도메인에 있는게 좋을 것 같아요 :)!

2021-01-09 16:41 UTC, limmmee-bonjour commented on src/test/java/lotto/domain/LottoPaperGeneratorTest.java
> +public class LottoPaperGeneratorTest {
1. 보통 @DisplayNames을 써서 의도를 드러내주시는게 좋습니다:) 
2. public으로 만들어주신 메서드는 (생성자를 포함해) 모두 테스트케이스를 만들어주시는게 좋습니다 :)!
3. Q. 현재는 유닛테스트 한번 돌릴때마다, 테스트 클래스에서 run버튼을 일일이 클릭하고 있습니다. 리뷰어께서는 어떻게 테스트 하시는지 궁금합니다!
 A. gradle - tasks - verification 을 통해 모든 테스트를 실행시킬 수 있습니다 :) 
![스크린샷 2021-01-10 오전 1 37 30](https://user-images.githubusercontent.com/73266174/104103251-72faeb00-52e4-11eb-9406-de2cb0b7f5f7.png)

2021-01-09 16:41 UTC, limmmee-bonjour commented on src/test/java/lotto/domain/LottoPaperGeneratorTest.java
> +        );
14000원어치를 샀는데 LottoNumberData는 3개밖에 없는것은 테스트케이스가 어떻게 되는걸까요?
그럼 테스트케이스는 유효한 테스트 케이스일까요~? 
위에 드린 의견과 함께 수정 부탁드려요 :)

2021-01-09 16:41 UTC, limmmee-bonjour commented on src/test/java/lotto/domain/LottoPaperTest.java
> +    public void getScoreCompareWith_test_1() {
Junit5에는 굉장히 다양한 테스트 어노테이션들이 추가되었습니다!
[해당 글](https://www.baeldung.com/parameterized-tests-junit-5)을 읽어보시면 추후 노가다? 없이 (ㅎㅎ) 간결한 테스트 케이스를 작성하실 수 있으실 거예요!

2021-01-09 17:44 UTC, kdy2000 commented on src/main/java/lotto/controller/LottoMachine.java
> +public class LottoMachine {
그렇군요.. 일단, 객체로 만든이유 다음과 같아요. 사용자에게 도메인, 뷰 등의 역할을 하는 다른 클래스들을 노출시키지 않으려고 했습니다. 사용자는 LottoMachine만 알면 되고, 이 머신을 적절히 조작만 하면 된다... 하는 생각으로 설계했습니다. 로또머신이 제공하는 메소드들을 static으로 만들면, 이 메소드를 호출한 사용자는 WinnerBalls, LottoPaper등의 객체를 리턴받아서 다시 넘겨주어야 할텐데, 이게 좀 마음에 걸리더군요. 굳이 이렇게까지 생각할 필요는 없을까요?

2021-01-12 03:08 UTC, kdy2000 commented on src/main/java/lotto/controller/LottoMachine.java
> +public class LottoMachine {
아니면, LottoMachine이라는 클래스 자체를 허물고, Main을 담고 있는 클래스와 합치라는 의도 였을까요?

2021-01-12 03:11 UTC, kdy2000 commented on src/main/java/lotto/domain/LottoPaperGenerator.java
> +public class LottoPaperGenerator {
말씀 듣고보니 이 클래스를 삭제해야 겠다는 생각이 듭니다. strategy 인터페이스를 하나 만든 후, 랜덤 strategy, 수동 strategy로 구현하여 이것을 LottoPaper의 생성자로 전달해서, 생성하도록 해보겠습니다.

2021-01-12 03:12 UTC, kdy2000 commented on src/main/java/lotto/domain/NonRandomNumberGenerator.java
> +import java.util.HashSet;
사용되지 않은 클래스를 삭제했다고 생각했는데, git에 미숙하여 잘못 컨트롤이 된것 같습니다.😂 다음 pr때는 재점검후 pr드리도록 하겠습니다.

2021-01-12 03:14 UTC, kdy2000 commented on src/main/java/lotto/setting/Format.java
> +            throw new RuntimeException("invalid Ticket size!!");
IllegalArgumentException 이 대안이 될 수 있을까요?

2021-01-12 04:31 UTC, kdy2000 commented on src/main/java/lotto/controller/LottoMachine.java
> +public class LottoMachine {
아니면..... Main 클래스를 삭제하고, main메서드만 LottoMachine으로 가져오는게 나을까요?

2021-01-12 04:32 UTC, limmmee-bonjour commented on src/main/java/lotto/controller/LottoMachine.java
> +public class LottoMachine {
의견 주신 부분을 제가 못봤네요^^
LottoMachine은 제가 이해했을때 굳이 객체화가 필요한가였어요!
Controller에서 LottoMachine의 메소드를 호출하는 것 뿐이라면 Controller에 로직이 있는게 더 낫지 않을까하는 의견이긴했습니다!
하지만 여기에 대한 답은 없는 것 같아요! 제가 [ 도전! ]이라고 적어주신것 외에는 dy가 생각했을 때 올바른 방식이면 될 것 같습니다.

dy가 생각했을 때 아래 의견과 같다면 (개발시 이유가 있는 개발이라면) 이렇게 정의되어도 크게 문제는 없어보입니다^^
> 로또머신이 제공하는 메소드들을 static으로 만들면, 이 메소드를 호출한 사용자는 WinnerBalls, LottoPaper등의 객체를 리턴받아서 다시 넘겨주어야 할텐데, 이게 좀 마음에 걸리더군요.

2021-01-12 04:35 UTC, kdy2000 commented on src/main/java/lotto/controller/LottoMachine.java
> +public class LottoMachine {
아하 그렇군요! 알겠습니다

2021-01-12 04:38 UTC, kdy2000 commented on src/main/java/lotto/domain/LottoPaperGenerator.java
> +public class LottoPaperGenerator {
+) 롤백이유: strategy pattern을 사용해볼까 했는데, 학습이 부족해서 일단 편한 방식으로 구현했었습니다. 리뷰어님께서 주신 링크 보면서 다시 학습했습니다. 이제 strategy pattern으로 구현해볼까 합니다.

2021-01-12 07:22 UTC, kdy2000 commented on src/main/java/lotto/domain/WinnerBalls.java
> +    private final Ticket ticket;
BuyingTicket, WinnerTicket 이렇게 두개의 클래스를 만든 후, abstract Ticket 클래스를 상속하게 하는 것은 어떤가요? Ticket 클래스에서 티켓에 관한 여러가지 규격들을 담게 하면, 두 티켓이 동일한 성격을 유지하면서도, 서로 다른 의미를 가지게 할 수 있을것 같습니다.

2021-01-12 20:17 UTC, kdy2000 commented
리팩토링을 하면서 TDD를 자꾸 벗어나는 듯한 기분이 들었습니다. 너무 많은 곳을 뜯어고치다 보면 어느새, TDD는 저만치 떨어져 있더라구요.

고쳐야 할게 여러가지인데, 하나만 수정하고, 컴파일 가능하게 만들려면, 어차피 다시 지워져야할 코드를 너무 많이 생산하게 됩니다. 그래서 한번에 여러 기능들을 수정하게 되었습니다.

view와 연관되어 있어 test하지 않았던 메서드인데, 새롭게 분리하고, 테스트코드를 작성해주었습니다. 이렇게 하고보니, 이것도 어쩌다보니 코드를 먼저 구현하고 test를 작성해준 셈이 되었습니다.

이외에도, 클래스간의 의존도가 너무 강한경우, 리팩토링시에 싹 갈아엎어야 해서 Test하기가 힘들었습니다.

앞으로는 TDD를 하기전에, 기능분리가 잘 되도록 '아주 잘' 설계를 한 다음에 TDD로 구현을 시작해야 할 것 같습니다.....

2021-01-13 09:24 UTC, limmmee-bonjour approved these changes
안녕하세요 dy! 벨입니다. 
제가 다른 업무로 코드 리뷰가 좀 늦었어요! 죄송합니다 😢 
제가 요청드린 부분에 대해 많은 고민 하신게 느껴져요! 잘 반영해주셨습니다.
추가로 좀 더 고민해볼 부분이나 어렵게 느끼셨을 부분에 대해 코멘트 드렸습니다 :) 
이번 미션은 여기서 approve 할게요! 다음 미션 진행해주세요!
궁금하신 점 있으시면 언제든 DM 주세요!

2021-01-13 09:24 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/GeneratingStrategy.java
> +public interface GeneratingStrategy {
전략 패턴을 잘 적용해주셨네요 :) 👍 
그런데 getLimit는 전략패턴에서 알고 있어야할 메서드일까요?
generator 에서 사용할 때 해당 메서드를 필요로 하고 있지 않은 것 같고, 몇개 생성할지의 카운트로 보여지는데..
로또 만드는 방법이 알고 있어야할 관심사일까요?

2021-01-13 09:24 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/LottoResult.java
> +        Arrays.stream(Rank.values()).forEach(rank -> ranks.put(rank, 0));
Rank.values()를 사용하여 ranks를 셋팅해주셨네요 👍

2021-01-13 09:24 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/ManuallyGeneratingStrategy.java
> +    public ManuallyGeneratingStrategy(List<Set<Integer>> inputNumberSets) {
List<Set<Integer>>를 파람으로 받는 생성자를 만드는 이유가 있나요?
해당 전략은 테스트에서만 사용되어지고 있는 것 같네요 
어떻게 사용하시려고 해당 전략을 만들었는지 모르겠어요! 설명해주시면 좋을것같아요 :)

2021-01-13 09:24 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/Rank.java
> +   public static Rank getRankAccordingTo(int matchCount, boolean matchBonusBall) {
Enum으로 기능을 모아주셔서 훨씬 깔끔해졌네요 💯  👍

2021-01-13 09:24 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/WinnerBalls.java
> +    }
한 메서드에서 너무 많은 내용을 담고 있어요! validation을 하는것 같은데 validation을 나눠주셔도 좋을 것 같습니다 :)

2021-01-13 09:24 UTC, limmmee-bonjour commented on src/main/java/lotto/setting/Prize.java
> +    public static final long MONEY_FOR_FIRST = 2_000_000_000;
가독성이 좋아졌어요 👍

2021-01-13 09:24 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/LottoPaper.java
> +            lottoResult.putRank(Rank.getRankAccordingTo(matchCount, matchBonusBall));
이 로직은 로또 페이퍼에 있어야할까요? matchCount와 matchBonusBall을 각각 계산해서 넘겨줘야할까요?
이렇게 되니 테스트케이스가 더 복잡해지는것 같아요~
WinningBall에서 몇개 맞았는지 확인해보고 Rank를 리턴해 줄 수 없을까요?

2021-01-13 09:24 UTC, limmmee-bonjour commented on src/test/java/lotto/domain/LottoPaperTest.java
> +    private static Stream<Arguments> providePaperAndResult() {
해당 테스트 케이스는 가독성이 너무 떨어지네요!
테스트 케이스를 좀 더 잘게 나누거나, 동일한 기능이라도 이런경우에는 테스트 케이스를 여러개 나누는게 맞을 것 같은데요
좀 더 가독성 높은 테스트 케이스를 만들 수 없을까요~?

Q. 리팩토링을 하면서 TDD를 자꾸 벗어나는 듯한 기분이 들었습니다. 너무 많은 곳을 뜯어고치다 보면 어느새, TDD는 저만치 떨어져 있더라구요.
고쳐야 할게 여러가지인데, 하나만 수정하고, 컴파일 가능하게 만들려면, 어차피 다시 지워져야할 코드를 너무 많이 생산하게 됩니다. 그래서 한번에 여러 기능들을 수정하게 되었습니다.
view와 연관되어 있어 test하지 않았던 메서드인데, 새롭게 분리하고, 테스트코드를 작성해주었습니다. 이렇게 하고보니, 이것도 어쩌다보니 코드를 먼저 구현하고 test를 작성해준 셈이 되었습니다.
이외에도, 클래스간의 의존도가 너무 강한경우, 리팩토링시에 싹 갈아엎어야 해서 Test하기가 힘들었습니다.

A. 맞아요~ 리팩토링하면서 테스트케이스를 작성하는 것은 꽤나 어려운 일입니다!
게다가 이번에는 수정범위가 커서 더 그러셨을 텐데요!
TDD 시에는 도메인 단위부터 큰단위로 짜시면 좀 더 좋습니다.
예를 들어 기본이 되는 Ticket 부터 테스트 하고 그 다음 LottoPaper 를 테스트하여 관심사를 모으고 해당 도메인에서 어떤 작업을 하면좋을지 고민해보면서 테스트 케이스를 짜는게 좋습니다.
또는 전략패턴을 적용한 RandomlyGeneratingStrategy, ManuallyGeneratingStrategy 먼저 테스트하고, 여기서 통과된 테스트 케이스는 다른 비즈니스에서 또 테스트 할 필요는 없습니다.
비즈니스 로직이나 input, output 에 관련된 테스트 케이스는 그 후에 작성하는 것이 좋습니다.

처음엔 리팩토링 하시면서 TDD 하시는게 어려울 것 같아요 :) 그래도 작은 도메인부터 차근차근 하시면 점차 익숙해지실 겁니다! 설계는 아무래도 한계가 있는 것 같아요... 최대한 테스트 케이스가 복잡하지 않도록 그 기능을 객체화 하고 테스트 하는게 좋을 것 같습니다 :)

2021-01-13 09:24 UTC, limmmee-bonjour commented on src/test/java/lotto/domain/RankTest.java
> +    @MethodSource("provideMatchCountAndMatchBonusBallAndRank")
이런 경우는 @MethodSource 보다는 @CsvSource가 가독성이 더 좋답니다 :) (delimiter를 추가해서 사용해보셔요~)

2021-01-13 09:24 UTC, merged

2021-01-13 12:36 UTC, kdy2000 commented on src/main/java/lotto/domain/ManuallyGeneratingStrategy.java
> +    public ManuallyGeneratingStrategy(List<Set<Integer>> inputNumberSets) {
실제코드를 테스트하기 위해, 그리고 2단계에 있을 수동입력에도 대비하여, 수동으로 로또정보를 제공하는 strategy를 만들었었습니다.

2021-01-14 23:05 UTC, kdy2000 commented on src/test/java/lotto/domain/RankTest.java
> +    @MethodSource("provideMatchCountAndMatchBonusBallAndRank")
Rank 객체도 같이 전달해주어야해서, csvSource가 적용이 안되는 것 같아요. 
`
    @DisplayName("matchCount와 보너스볼 일치여부를 받아 랭크를 반환하는 기능 테스트")
    @ParameterizedTest
    @CsvSource(delimiter = ':',
            value = {
                    "6:false:Rank.FIRST",
                    "5:true:Rank.SECOND",
                    "5:false:Rank.THIRD",
                    "4:false:Rank.FOURTH",
                    "3:false:Rank.FIFTH",
                    "2:false:Rank.OUT",
                    "1:false:Rank.OUT"
            }
    )
    public void getRankArccordingToTest(int matchCount, boolean matchBonusBall, Rank rank) {
        assertThat(
                Rank.getRankAccordingTo(
                        matchCount, matchBonusBall
                )
        ).isEqualTo(rank);
    }
`

이렇게 사용하는것이 맞을까요?