[Danial 유기백] 제출합니다.
NewKrew2021/java-lotto-kakao pull request #27
Opened 2021-01-09 07:45 UTC by Yookibaek

이번과제는 정말 어려웠던 것 같습니다... 이따금 TDD를 하기 위해서 객체에서 값을 꺼내와야만 하는 상황이 있었습니다. 그때마다 getter를 만들었는데 이렇게해도 괜찮을까라는 생각이 들었습니다..

2021-01-11 01:50 UTC, humbledude requested changes
안녕하세요~

구현해 주신 코드 잘 봤습니다.
개선해봤으면 하는 포인트를 코멘트로 드렸는데요, 한번씩 살펴보시고 괜찮다 싶으면 수정해서 다시 리뷰 요청 주세요~
크게 잘못된 부분은 없는거 같아서 간단하게 수정이 되지 않을까... 예상해봅니다만 ㅎㅎㅎ

그리고 질문 주신만큼 getter 가 많이 쓰인거 같지는 않네요~
강의에서 들으셨겠지만, getter 는 최소한으로 필요한 부분에만 사용하는 것으로 생각하고 개발을 하다보면 연습이 될꺼 같아요~
나중에 점점 복잡한 도메인을 다루게 되다보면 피할수는 없겠지만,
작게 쪼개다 보면 지금이랑 비슷한 수준을 유지할수는 있을꺼 같네요~!

2021-01-11 01:50 UTC, humbledude commented on src/main/java/lotto/Constant.java
> +    public static final int LOTTO_PRICE = 1000;
개발하다보면 각종 상수를 모아놓는 Constant 클래스를 만들기도 하는데요 ㅎㅎ
이번 미션에서는 가능하면 가장 연관있는 클래스로 보내는게 어떨까요?

2021-01-11 01:50 UTC, humbledude commented on src/main/java/lotto/domain/LottoNo.java
> +public class LottoNo implements Comparable<LottoNo> {
개발 규칙에 축약 금지 항목이 있는데요,
No 라는게 물론 Number 를 많이들 No 로 줄이기는 하지만,
이번 미션에서는 줄여쓰는 부분을 최소한으로 하면 어떨까 생각이 들었어요~

2021-01-11 01:50 UTC, humbledude commented on src/main/java/lotto/domain/LottoNo.java
> +    int number;
접근 제한자를 default 로 하신 이유가 있을까요?

2021-01-11 01:50 UTC, humbledude commented on src/main/java/lotto/domain/WinningLottoNos.java
> +    public StatisticsType isWinning(LottoNos lottoNos) {
is 로 시작하는 method 이름은 관례상 boolean 을 리턴할 것이다 라는 기대가 있어요 ㅎㅎ
다른 이름으로 정해보는게 어떨까요?

2021-01-11 01:50 UTC, humbledude commented on src/main/java/lotto/domain/WinningLottoNos.java
> +    private StatisticsType checkEnum( int matchCount, boolean isBonusMatch) {
이부분은 StatisticsType 에 구현할 수 있을거 같습니다.

2021-01-11 01:50 UTC, humbledude commented on src/main/java/lotto/input/ValidInputGuaranteer.java
> +    protected String getComment(){
이거를 꼭 구현해야 하기 때문에 abstract 로 선언해도 될꺼 같아요

2021-01-11 01:50 UTC, humbledude commented on src/main/java/lotto/input/WinningLottoNumsValidInputGuaranteer.java
> +    protected void checkValid(String input){
ValidInputGuaranteer 를 상속한 클래스들이 checkValid 에 생성자를 쓰게 되는 경향이 있네요.
생성자를 validator 로 사용하고,
외부에서 input 을 다시 또 생성자에 보내기 위해 같은 코드를 중복으로 쓰게 되네요
이부분을 개선해 볼수 있지않을까요?

2021-01-11 01:50 UTC, humbledude commented on src/main/java/lotto/view/LottoOutputView.java
> +    public static void printWinningStatistics(List<LottoNos> lottos) {
요거는 안쓰는 건가요?

2021-01-11 01:50 UTC, humbledude commented on src/test/java/lotto/domain/LottoLogicTest.java
> +    void statisticTest() {
테스트가 어떤걸 테스트 하려고 하는지 알수 없네요

2021-01-11 01:50 UTC, humbledude commented on src/main/java/lotto/domain/StatisticsResult.java
> +    static {
이부분도 StatisticsType 안으로 포함시킬 수 있지 않을까요?

2021-01-11 01:50 UTC, humbledude commented on src/main/java/lotto/domain/StatisticsResult.java
> +        return "3개 일치 (5,000원)-" + hashMap.get(StatisticsType.THREE) + "\n" +
(일치하는 숫자수, 상금, 해당 로또 갯수) 의 패턴이 반복되고 있습니다.
이 부분의 공통 코드를 줄일 수 있을까요?

2021-01-11 01:50 UTC, humbledude commented on src/main/java/lotto/domain/LottoLogic.java
> +            lottoTickets.add(new LottoNos(nums.subList(0, 6)));
여기 6 이라는 숫자는 어디 정의되어있는거 가져다 쓸수 있겠어요~

2021-01-11 01:50 UTC, humbledude commented on src/main/java/lotto/domain/LottoLogic.java
> +        for (int i = 1; i <= 45; i++) {
여기 1, 45 도 이미 정의되어있는 숫자네요 가져다가 쓰면 좋지 않을까요?

2021-01-11 14:20 UTC, Yookibaek commented on src/main/java/lotto/Constant.java
> +    public static final int LOTTO_PRICE = 1000;
"로또 가격" 클래스를 만들어 위임 하였습니다!

2021-01-11 14:27 UTC, Yookibaek commented on src/main/java/lotto/domain/LottoNo.java
> +public class LottoNo implements Comparable<LottoNo> {
풀 네임으로 변경 했습니다!

2021-01-11 14:31 UTC, Yookibaek commented on src/main/java/lotto/domain/LottoNo.java
> +    int number;
미처 인지하지 못 하고 있었습니다. 지적 감사합니다. 변경 완료 하였습니다.

2021-01-11 14:50 UTC, Yookibaek commented on src/main/java/lotto/domain/WinningLottoNos.java
> +    public StatisticsType isWinning(LottoNos lottoNos) {
로또 결과를 가져온다는 의미에서, getMatchCount로 변경 완료 하였습니다.

2021-01-11 14:52 UTC, Yookibaek commented on src/main/java/lotto/input/ValidInputGuaranteer.java
> +    protected String getComment(){
abstract 클래스 공부하여 적용 하였습니다. 집어주셔서 감사합니다!

2021-01-11 14:53 UTC, Yookibaek commented on src/main/java/lotto/view/LottoOutputView.java
> +    public static void printWinningStatistics(List<LottoNos> lottos) {
사용하지 않는 메소드 삭제 하였습니다.

2021-01-11 14:55 UTC, Yookibaek commented on src/main/java/lotto/domain/LottoLogic.java
> +        for (int i = 1; i <= 45; i++) {
수정 완료 하였습니다!

2021-01-11 14:57 UTC, Yookibaek commented on src/main/java/lotto/domain/LottoLogic.java
> +            lottoTickets.add(new LottoNos(nums.subList(0, 6)));
매직넘버 제거 하였습니다!

2021-01-11 15:23 UTC, Yookibaek commented on src/main/java/lotto/domain/WinningLottoNos.java
> +    private StatisticsType checkEnum( int matchCount, boolean isBonusMatch) {
완료 하였습니다!

2021-01-12 08:54 UTC, humbledude approved these changes
고생많으셨습니다~!

피드백 드린게 도움이 되었으면 좋겠네요~
추가로 드린 코멘트는 특별한 내용이 없습니다 ㅎㅎㅎ
다음 미션에서도 많이 성장하시길 바래요~

2021-01-12 08:54 UTC, humbledude commented on src/main/java/lotto/domain/LottoNumbers.java
> +        if (numbers.size() != 6) {
ㅎㅎㅎ 상수 선언했으니까 써주세요 ㅎㅎ

2021-01-12 08:54 UTC, humbledude commented on src/main/java/lotto/domain/LottoNumbers.java
> +            set.add(numbers.get(i));
addAll 메소드를 쓰면 한번에 다 들어갑니다.
또는 HashSet 생성자 중에서 List 를 받는 방법도 체크해보세요~

2021-01-12 08:54 UTC, humbledude commented on src/main/java/lotto/input/ValidInputGuaranteer.java
> +public abstract class ValidInputGuaranteer <T>{
제네릭 쓰셨군요 👍

2021-01-12 08:54 UTC, merged