[jon.snow] 로또 미션 1단계 리뷰 요청 드립니다.
NewKrew2021/java-lotto-kakao pull request #28
Opened 2021-01-10 07:23 UTC by PFCJeong

2021-01-11 04:51 UTC, ljh131 requested changes
안녕하세요. 몇 가지 커멘트 드렸습니다. 확인해보시고 수정해주시면 좋겠습니다. 그리고 커멘트에 대해 궁금한 점이 있으시면 질문주세요.

2021-01-11 04:51 UTC, ljh131 commented on src/main/java/lotto/LottoResult.java
> +        if (matchCount == FIRST_WINNER_MATCH_CONT) return FIRST;
이렇게 많은 if 없이 간단히 할 수 있는 방법은 없을까요?

2021-01-11 04:51 UTC, ljh131 commented on src/main/java/lotto/Lotto.java
> +        for (int i = 0; i < 6; i++) {
상수를 쓰는게 좋을 것 같아요. 아래도요

2021-01-11 04:51 UTC, ljh131 commented on src/main/java/lotto/LottoNumber.java
> +    private static final LottoNumber[] list = new LottoNumber[46];
final static 멤버명은 upper case가 좋을 것 같아요. 상수도 사용하면 좋겠습니다.

2021-01-11 04:51 UTC, ljh131 commented on src/main/java/lotto/LottoNumber.java
> +    public static LottoNumber getInstance(int number) {
thread safe한가요?

2021-01-11 04:51 UTC, ljh131 commented on src/main/java/utils/NumberUtil.java
> +    private static final int MAX_LOTTO_NUMBER = 45;
유틸이면 general 해야 될 것 같은데, 비지니스 요구사항이 들어가있네요.

2021-01-11 04:51 UTC, ljh131 commented on src/main/java/utils/NumberUtil.java
> +        List<Integer> lottoNumbers = new LinkedList<>();
링크드리스트를 사용하는 이유가 궁금해요

2021-01-11 04:51 UTC, ljh131 commented on src/main/java/lotto/Lotto.java
> +    public Lotto() {
이 생성자는 자동인데, 아래 생성자는 수동이군요. 제 생각엔 모든 생성자가 되도록 동일한 역할을 하는게 좋을 것 같습니다.

2021-01-11 04:51 UTC, ljh131 commented on src/main/java/lotto/Lottos.java
> +    public void addLotto(int n){
여기도 위 오버로드된 메서드들과 역할이 달라요. 하는 일이 다른데 이름이 동일하면 혼란스럽지 않을까요. 자동이라는 이름을 메서드명에서 유추할 수가 없네요.

2021-01-11 04:51 UTC, ljh131 commented on src/main/java/lotto/LottoResult.java
> +    public static LottoResult init(int matchCount, boolean bonusMatch) {
이름도 초기화라기보다는 다른 이름이 좋을 것 같아요.

2021-01-11 04:51 UTC, ljh131 commented on src/main/java/lotto/LottoManager.java
> +    public int[] countRanks() {
배열을 그냥 넘기는 것은 안좋지 않을까요? 콜러가 배열의 어떤 인덱스와 값이 어떤 의미이고 어떻게 매핑되어 있다는걸 알아야 하는데, 
차라리 그런 정보가 담겨있는 클래스를 넘기면 더 좋을 것 같아요.

2021-01-11 04:51 UTC, ljh131 commented on src/main/java/view/InputView.java
> +            throw new IllegalArgumentException();
약간이라도 정보를 내주면 좋을 것 같습니다.

2021-01-11 05:38 UTC, PFCJeong commented on src/main/java/lotto/Lotto.java
> +    public Lotto() {
아래와 같이 수정하면 괜찮을까요?

아니라면 생성자가 동일한 역할을 하는 것이 무슨 의미인지를 제가 제대로 이해하지 못하고 있는 것 같습니다. 설명 부탁드립니다!

```
    private Lotto(List<Integer> numbers) {
        validate(numbers);
        numbers.forEach(num ->
                lottoNumbers.add(LottoNumber.getInstance(num))
        );
    }

    public static Lotto generateRandomLotto(){
        return new Lotto(generateLottoNumbers());
    }

    public static Lotto generateLotto(List<Integer> numbers){
        return new Lotto(numbers);
    }
```

2021-01-11 07:32 UTC, ljh131 commented on src/main/java/lotto/Lotto.java
> +    public Lotto() {
네 수정하신 코드가 기존 코드보다 의미상 더 적절하지 않나요?

2021-01-12 06:33 UTC, ljh131 requested changes
리뷰 중에 계속 커밋을 하셔서 리뷰 하기가 어렵네요. 수정이 완료되면 다시 리뷰 요청해주세요.
일단 삭제 안된 커멘트는 남겨놓겠습니다.

2021-01-12 06:33 UTC, friediceday commented on src/main/java/lotto/LottoNumber.java
> +    private static final LottoNumber[] LIST = new LottoNumber[46];
상수를 쓰는게 어떨까요

2021-01-12 06:33 UTC, friediceday commented on src/main/java/lotto/LottoResult.java
> +    public static final int FIRST_WINNER_MATCH_CONT = 6;
여기 상수들은 꼭 필요한가요?

2021-01-12 06:33 UTC, friediceday commented on src/main/java/lotto/LottoResult.java
> +        boolean finalBonusMatch = matchCount == 5 ? bonusMatch : false;
상수를 쓰는건 어떤가요?
그리고 애초에 이넘값에 설정할 수 있으면 더 좋을 것 같아요.

2021-01-12 06:33 UTC, ljh131 commented on src/main/java/lotto/LottoManager.java
> +            throw new IllegalArgumentException();
에러 메시지가 있으면 좋겠습니다

2021-01-12 06:33 UTC, ljh131 commented on src/main/java/lotto/LottoManager.java
> +        for(LottoResult lottoResult : LottoResult.values()){
0으로 모두 초기화하지 않는 방법으로 하는건 어떤가요?

2021-01-12 06:33 UTC, ljh131 commented on src/main/java/lotto/Lottos.java
> +    public void addLotto(Lotto lotto){
공백+중괄호 컨벤션을 지키면 좋겠습니다

2021-01-12 06:33 UTC, ljh131 commented on src/main/java/lotto/LottoResult.java
> +        boolean finalBonusMatch = matchCount == SECOND.matchCount ? bonusMatch : false;
SECOND이라는걸 몰라도 되지 않을까요? 어차피 bonusMatch가 있는데요

2021-01-12 06:35 UTC, PFCJeong commented
페어와 2단계를 같이 하고 있었는데 그 과정에서 실수로 2단계 관련 푸시를 해버렸네요. 죄송합니다 ㅠㅠ
커밋은 끝났습니다!

2021-01-12 09:38 UTC, ljh131 reviewed
수고하셨습니다. 이번 단계는 머지하겠습니다. 커멘트들은 참고해보시고 다음 단계에 반영해주세요.

2021-01-12 09:38 UTC, ljh131 commented on src/main/java/lotto/LottoResult.java
> +        boolean finalBonusMatch = matchCount == SECOND.matchCount ? bonusMatch : false;
이 부분 확인해주세요.

2021-01-12 09:38 UTC, ljh131 commented on src/main/java/lotto/LottoNumber.java
> +    private static final LottoNumber[] LIST = new LottoNumber[46];
이 부분 확인해주세요.

2021-01-12 09:38 UTC, ljh131 commented on src/main/java/LottoApplication.java
> +        if (money % LOTTO_PRICE != 0 || money == 0) {
혹시 음수면 어떻게 되나요

2021-01-12 09:38 UTC, ljh131 commented on src/main/java/lotto/LottoResult.java
> +        if (matchCount == SECOND.matchCount && bonusMatch)
SECOND라는걸 알 필요없이 bonus만 가지고도 알 수 있지 않을까요? 일반적인 경우는 `ㅁ개 일치 ㅁ원`, 보너스가 있으면 중간에 문자열을 끼워넣는 식은 어떤가요

2021-01-12 09:39 UTC, merged