coeat.k 로또자동 step1 PR입니다.
NewKrew2021/java-lotto-kakao pull request #3
Opened 2021-01-07 10:15 UTC by kukaro

안녕하십니까 신입 4기 공채 coeat입니다.
로또 로직을 작성하여 리뷰를 요청드립니다.

질문 점은 아래와같습니다.
- 로또의 한장을 의미하는 LottoTicket과 로또 번호6개와 bonus번호를 가지는 WinnerNumber가 있는데 이렇게 작성해도 상관없는것인지를 알고 싶습니다.
- controller내부에 private함수중에서 View에 통신하는 로직과 리턴하는 로직이 섞여있는데 이런 함수를 만들어도 되는지 궁금합니다.
- RankTable같은 매핑 테이블을 만드는것에 대한 의견을 들을수 있다면 좋을것 같습니다.
- NumberPool을 일반 인스턴스 클래스로 만들었는데 싱글턴이나 static으로 만들면 좋을지 궁금합니다.

항상 감사합니다.

2021-01-08 06:52 UTC, htrucci requested changes
안녕하세요, 로또 미션 리뷰를 하게 된 데빈입니다.
빠르게 잘 구현해주셨네요! 클래스별 역할을 README에 잘 정리해주셔서 이해가 편했습니다.
랩핑 클래스 및 당첨 구분 알고리즘을 인상적으로 봤고 몇가지 리뷰를 남겨드렸으니 확인 부탁드리고 
리뷰 반영 및 수익률 버그를 잡아 다시 요청 부탁드립니다~!

2021-01-08 06:52 UTC, htrucci commented on README.md
> +
클래스 별 역할을 아주 잘 정리 해주셨네요 👍 
1단계 요구사항도 추가 부탁드립니다~!

2021-01-08 06:52 UTC, htrucci commented on src/main/java/controller/LottoGame.java
> +    }
구입금액 입력값에 대한 검증도 추가해볼까요?
제안 : TDD사이클에 맞추어 필요한 테스트 코드들을 먼저 작성 후 로직을 추가해보세요~!

2021-01-08 06:52 UTC, htrucci commented on src/main/java/domain/LottoTickets.java
> +    }
lottoTickets는 생성 이후 변경되지 않으므로 final로 선언해도 되지 않을까요?

불변 객체 만들기 (immutable object)
* 객체의 상태를 변경하는 메소드를 제공하지 않는다.
* 클래스를 확장할 수 없도록 한다.(public final class)
* 모든 필드를 final로 선언한다.
* 모든 필드를 private으로 선언한다.

2021-01-08 06:52 UTC, htrucci commented on src/main/java/domain/LottoTickets.java
> +    }
중복을 고려하여 Set을 이용하신 점이 인상적입니다 💯

2021-01-08 06:52 UTC, htrucci commented on src/main/java/controller/LottoGame.java
> +    }
Stream 사용해서 아주 깔끔하게 해주셨네요 👍 
다만 Scanner가 LottoGame과 LottoView 두군데서 사용하고 있는데 
getPrice()와 묶어 입력을 담당하는 객체로 분리해도 좋을 것 같아요.

2021-01-08 06:52 UTC, htrucci commented on src/main/java/domain/LottoTicket.java
> +    }
이번 요구사항 중 축약 금지가 있어 축약된 변수명을 변경해볼까요?
규칙 5: 줄여쓰지 않는다(축약 금지).

2021-01-08 06:52 UTC, htrucci commented on src/main/java/domain/LottoResults.java
> +    }
upsert란 단어를 처음봤는데요. 찾아보니 예상한대로 update+insert이네요 😄 
저는 ORACLE, MYSQL밖에 경험이 없어, merge into 혹은 insert update 정도로 얘기를 하곤 하는데
이게 편하게 얘기하려고 만든 단어가 아니라 다른 DB군에서는 실제 SQL문법으로 있는 단어인지? 궁금하네요 ㅎ

다만,, 이번 요구사항 중 축약 금지가 있어 축약된 변수명을 변경해볼까요?
규칙 5: 줄여쓰지 않는다(축약 금지).

이번에 축약금지 규칙이 있는건 과도한 축약으로 인해 클래스나 메서드의 의미가 
한번에 잘 보이지 않아 가독성을 저해하는 부분을 막고자 연습하는 의미인 것 같아요.

2021-01-08 06:52 UTC, htrucci commented on src/main/java/domain/LottoTickets.java
> +    }
아래와 같이 쓴다면 논리 로직이 좀 더 명확히 보이고 getRank를 한번만 해도 될 것 같아요! 👀 

lottoTickets.stream()
        .map(ticket -> ticket.getRank(winnerNumber))
        .filter(Objects::nonNull)
        .forEach(lottoRank->lottoResults.upsert(lottoRank));

2021-01-08 06:52 UTC, htrucci commented on src/main/java/domain/NumberPool.java
> +                .collect(Collectors.toList());
해당 함수를 모르는 사람이 봤을때는 1부터 46까지 생성하는건가? 생각하고 가독성을 떨어뜨릴 수 있으니 😭 
상수로 분리하고 의미를 명확히 하거나 주석을 달거나 하면 좋을 것 같아요.

아래와 같이 사용하면 마지막 range를 포함합니다 😄 

IntStream.rangeClosed(1, 45)

2021-01-08 06:52 UTC, htrucci commented on src/main/java/domain/NumberPool.java
> +}
💯

2021-01-08 06:52 UTC, htrucci commented on src/main/java/domain/LottoTicket.java
> +    }
처음에 이해를 못했다가 자릿수를 이용한 부분인걸 보면서 알고 천재시구나 생각했습니다. 👀 
고민을 좀 되기는한데 알고리즘을 잘 만드신 것 같아, 매직넘버 상수화 정도로 코멘트를 드릴게요!

2021-01-08 06:52 UTC, htrucci commented on src/main/java/domain/Number.java
> +    }
매직넘버 상수화 해주세요~!
그리고 취향차이인지 컨벤션과 관계있는지 잘 모르겠는데,, 보통 비교대상을 왼쪽에 놓지 않나요?
 if (number < 1 || number > 45) {

2021-01-08 06:52 UTC, htrucci commented on src/main/java/domain/Number.java
> +    }
정적 팩토리 메소드 패턴을 적용해보면 어떨까요? 아래 도움이 될만한 글 남겨놓을께요 😃

 https://johngrib.github.io/wiki/static-factory-method-pattern/

2021-01-08 06:52 UTC, htrucci commented on src/main/java/view/LottoGameView.java
> +    }
출력 메시지도 상수화 해놓으면 관리하기 좋을 것 같아요 👀

2021-01-08 06:52 UTC, htrucci commented on src/test/java/domain/LottoResultsTest.java
> +    }
헛 toString까지 검증을 해주시는 👍 
텍스트가 많아 어떤 테스트인지 정확히 보기가 어려우니 아래처럼 일부분만 검증해도 될 것 같기두 하구요?

assertTrue(lottoResults.toString().contains("6개 일치 (2000000000원) - 1개"));

2021-01-08 06:52 UTC, htrucci commented on src/test/java/domain/NumberTest.java
> +    }
numberPoolTest로 이름을 바꿔도 될 것 같네요 😄

2021-01-08 06:52 UTC, htrucci commented on src/main/java/domain/LottoResults.java
> +    }
수익률 계산이 잘못된 것 같아요~
1000원써서 5000원 당첨되면 수익률이 400% 겠죠?  🙄

2021-01-08 07:51 UTC, kukaro commented on src/main/java/controller/LottoGame.java
> +    }
안녕하십니까 coeat입니다. 메소드가 프라이빗인데 어떻게 테스트를 할 수 있을까요?

2021-01-08 08:18 UTC, kukaro commented on src/main/java/domain/LottoResults.java
> +    }
이게 라이브러리에서 자주 저렇게 쓰길래 축약어라고 생각을 못했습니다. 고치도록할께요!

2021-01-08 17:01 UTC, kukaro commented on src/main/java/domain/Number.java
> +    }
그 부분은 포함 범위를 손보다가 이상하게 짜진거 같습니다. 수정하겠습니다.

2021-01-08 17:19 UTC, kukaro commented on src/test/java/domain/NumberTest.java
> +    }
실제로는 테스트 해보는 내용이 없어서 삭제했습니다.

2021-01-08 17:47 UTC, kukaro commented
안녕하십니까 신입 공채 4기 Coeat입니다.
상세한 피드백 감사합니다!
피드백 사항들을 적용하여 코드를 대거 수정하였습니다.
private 메소드를 테스트를 어떻게 할지에 대한 의문점을 제외하곤 다 적용하였습니다.
감사합니다.

2021-01-10 09:07 UTC, htrucci commented on src/main/java/controller/LottoGame.java
> +    }
default 접근제어자를 가진다면 private상태에서 테스트코드 작성이 가능할 것 같습니다.
도메인 패키지와 동일한 패키지 경로를 갖게 되면 동일 패키지의 default 접근제어자인 멤버에 접근이 가능합니다!
아래 참고하실만한 링크 첨부해드릴게요! 

https://wikidocs.net/232

2021-01-10 10:14 UTC, htrucci commented
Q. 로또의 한장을 의미하는 LottoTicket과 로또 번호6개와 bonus번호를 가지는 WinnerNumber가 있는데 이렇게 작성해도 상관없는것인지를 알고 싶습니다.
A. LottoTicket에서 추가적인 보너스번호만 필요한 상태이므로 상속 관계로 분리하여 잘 표현하셨다고 생각됩니다!

Q. controller내부에 private함수중에서 View에 통신하는 로직과 리턴하는 로직이 섞여있는데 이런 함수를 만들어도 되는지 궁금합니다.
A. 음,, 어떤부분인지 정확히 모르겠는데,, 제가 봤을때 문제가 되는 부분이 크게 안보이긴 하네요..;; 😌 

Q. RankTable같은 매핑 테이블을 만드는것에 대한 의견을 들을수 있다면 좋을것 같습니다.
A. 알고리즘을 사용하여 창의적으로 문제를 푸셔서 잘하셨다고 생각됩니다 👍  
     다만, LottoRank와 동일하게 Enum으로 관리되도 되지않을까 하는 생각은 듭니다.
 
Q. NumberPool을 일반 인스턴스 클래스로 만들었는데 싱글턴이나 static으로 만들면 좋을지 궁금합니다.
A. 맞아요, 질문해주신대로 LottoTickets을 생성할때마다 NumberPool을 재생성하고 있으므로 필드에 numberPool이 있을 필요가 없어보이네요! static하게 바꿔주면 매번 Pool을 재생성하지 않고 shuffle만 해주면 되겠어요. 생각 못하고 넘어갔었는데 잘 말씀해주셨습니다 🥇  👍

2021-01-10 10:17 UTC, htrucci approved these changes
안녕하세요, 데빈입니다.
리뷰 피드백을 잘 반영해주셨네요! 👍  
첫 PR에서 주신 질문을 놓친 것 같아 코멘트로 답변을 함께 드렸습니다.
주신 PR은 머지 하도록하고 다음 단계도 화이팅 해주세요~!

2021-01-10 10:17 UTC, htrucci commented on src/main/java/domain/Number.java
> +            .collect(Collectors.toList());
👍

2021-01-10 10:17 UTC, htrucci commented on src/main/java/domain/Number.java
> +    }
정적 팩토리 메서드 사용시 네이밍 컨벤션을 지켜주면 좋을 것 같아요!

[정적팩토리메서드](https://velog.io/@ljinsk3/%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C%EB%8A%94-%EC%99%9C-%EC%82%AC%EC%9A%A9%ED%95%A0%EA%B9%8C)

2021-01-10 10:17 UTC, htrucci commented on src/test/java/domain/LottoResultsTest.java
> +                .contains("6개 일치 (2000000000원) - 1개");
리뷰반영 💯

2021-01-10 10:17 UTC, merged

2021-01-10 10:45 UTC, kukaro commented on src/main/java/controller/LottoGame.java
> +    }
감사합니다! 근데 패키지 접근제어자를 사용해도 될까요? 자주 사용되나요? 궁금합니다!

2021-01-10 12:30 UTC, htrucci commented on src/main/java/domain/LottoRank.java
> +    FIRST(2000000000, "6개 일치");
자바에서는 큰 숫자를 다루기 위해
[Java] 큰 숫자(실수) 다루기 BigDecimal 사용법 & 예제 총정리 을 제공하고 있습니다.
FIRST(2_000_000_000, "6개 일치");