[ocean.world 김중선] lotto PR 요청드립니다
NewKrew2021/java-lotto-kakao pull request #32
Opened 2021-01-11 05:06 UTC by wndtjs101

안녕하세요, ocean 입니다! lotto 1차미션 pr 드립니다

이번미션에서 고민이 많았습니다. 

특히 클래스분리를 계속하려다보니 어떤 클래스에서 계산을 로또 매칭을 계산해야 할 지 고민이 많았고,
내부 로직을 노출 시키지 않으면서 결과를 출력시킬 수 있도록 DTO를 사용해보았는데, 이것이 맞게 사용된지 모르겠습니다.

인스턴스 캐싱 등 사실 더 고쳐야 할 점 이 많은 것 같지만.. 일단 리뷰어님의 피드백을 빠르게 받는 것이 우선인것 같아서 이렇게 pr 보냅니다!!

2021-01-11 12:18 UTC, adeldel requested changes
안녕하세요 오션! 로또 미션 리뷰를 하게 된 아델입니다. 반가워요 😸 
기능 요구사항을 상세히 기록하고 잘 구현해주셨습니다.
도메인객체도 잘 나누고 전체적인 구조는 잘 잡아주셨어요.
다만, 일부 로직을 좀 더 리팩토링하면 좀더 좋을 것 같아 코멘트 남겨드렸습니다.
확인 후 재요청 부탁드립니다. 🙏

2021-01-11 12:18 UTC, adeldel commented on README.md
> +    4) 쉼표로 구분
👍 기능 상세 정리

2021-01-11 12:18 UTC, adeldel commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
여기시 이미 로또번 1~45호를 미리 생성해서 지난주 당첨번호만 쓰고 있네요.
 자동으로 구매하는 로또도 이 로또번호 객체를 재사용 할 수 있도록 수정하면 좋을것 같습니다.

2021-01-11 12:18 UTC, adeldel commented on src/main/java/lotto/domain/Money.java
> +    private static final int SINGLE_PRICE = 1000;
가독성있게 숫자표현을 해보는건 어떨까요? 1000 -> 1_000
Java 7 이상에서 자릿수를 표시하기 위한 underscores(밑줄)이 포함되었습니다.

2021-01-11 12:18 UTC, adeldel commented on src/main/java/lotto/domain/RankState.java
> +    FAIL(0, 0,2);
가독성있게 숫자표현을 해보는건 어떨까요? 2000000000 -> 2_000_000_000
Java 7 이상에서 자릿수를 표시하기 위한 underscores(밑줄)이 포함되었습니다.

2021-01-11 12:18 UTC, adeldel commented on src/main/java/lotto/domain/GenerateStrategy.java
> +    LottoNumbers generate();
개인적인 의견입니다만, 현재로서는 불필요한 인터페이스가 아닐런지 생각됩니다. 
(추후 해당 인터페이스를 사용하는 다른 구현체가 생길거라면 확장성을 위해서 남겨주셔도 됩니다.)

2021-01-11 12:18 UTC, adeldel commented on src/main/java/lotto/domain/RandomGenerateStrategy.java
> +        IntStream.rangeClosed(1, 45).forEach(numbers::add);
로또번호는 1~45 한정되어 있습니다. 미리 한번만 생성하여 재사용하는게 어떨까요?
그리고 로또번호도 한장의 로또객체가 될수 있을것 같아요.

2021-01-11 12:18 UTC, adeldel commented on src/main/java/lotto/domain/RankState.java
> +                .orElseThrow(IllegalRankStateException::new);
rank 값을 구할때 디폴트 `FAIL`을 돌려주는건 어떨까요? 그럼 0,1개일때도 자연스럽게 `FAIL`로 처리될것 같아요.
```suggestion
                return Arrays.stream(values())
                .filter(rank -> rank.isMatchCount(matchCount))
                .findFirst()
                .orElse(FAIL);

2021-01-11 12:18 UTC, adeldel commented on src/main/java/lotto/view/InputView.java
> +        return scanner.nextInt();
구입금액에 문자열이 들어오면 의도치 않은 에러가 발생하지 않을까요? 
의도치 않는 에러가 발생하지 않도록 에러처리를 해준다면 프로그램이 좀더 견고해 집니다

2021-01-11 12:18 UTC, adeldel commented on src/main/java/lotto/view/InputView.java
> +        return scanner.nextInt();
보너스볼에 문자열이 들어오면 의도치 않은 에러가 발생하지 않을까요?

2021-01-11 12:18 UTC, adeldel commented on src/main/java/lotto/utils/Splitter.java
> +        return Arrays.stream(numbers).boxed().collect(Collectors.toList());
가독성을 위해 줄바꿈을 하고 아래처럼 합칠수 있을것 같아요.
```suggestion
        return Stream.of(string.split(delimiter))
                .mapToInt(Integer::parseInt)
                .boxed()
                .collect(Collectors.toList());

2021-01-11 12:18 UTC, adeldel commented on src/main/java/lotto/view/OutputView.java
> +        printProfitRate(lottoStatisticDTO.getProfitRate());
LottoStatisticDTO 를 이용하여 결과출력 👍

2021-01-11 12:18 UTC, adeldel commented on src/test/java/lotto/domain/LottoGameTest.java
> +    public void create() {
보통 유닛테스트 이름은 앞에 test를 붙입니다. (유닛테스트 명명규칙이 관례적이진 않으나, 인기있는 패턴은 존재합니다.)
참고 : https://it-is-mine.tistory.com/3

2021-01-11 12:18 UTC, adeldel commented on src/main/java/lotto/exception/BonusDuplicateException.java
> +    public BonusDuplicateException() {
사용안하는 생성자는 제거해주세요.

2021-01-11 12:18 UTC, adeldel commented on src/main/java/lotto/domain/LottoNumbers.java
> +            throw new NumberDuplicateException(DUPLICATE_EXCEPTION_MESSAGE);
상세한 에러처리 👍

2021-01-11 14:56 UTC, wndtjs101 commented on src/main/java/lotto/domain/GenerateStrategy.java
> +    LottoNumbers generate();
랜덤 로직을 분리해서 테스트가능 하게 만들고,
추후에 수동으로 입력을 받아 숫자를 생성해내도록 하려고 인터페이스를 사용해보았습니다!

2021-01-11 15:40 UTC, wndtjs101 commented on src/main/java/lotto/domain/RankState.java
> +                .orElseThrow(IllegalRankStateException::new);
이부분은 사실 matchCount 가 7 이상의 비정상적인 인풋을 처리하기 위함이었는데, 
말씀주신대로 변경하여 그냥 이 경우 FAIL을 반환하도록 수정하였습니다

2021-01-11 16:58 UTC, wndtjs101 commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
자동으로 구매하는 로또도 new LottoNumbers() 형태로 리턴되고, 
LottoNumbers 생성자 안에서 List<Integer>형태의 파라미터를 받으면, 미리 만들어 놓은 LottoNumber 들을 사용하도록 하여서 
재사용 된다고 생각하는데 혹시 제 생각이 틀렸을까요..?!

2021-01-12 00:39 UTC, adeldel commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
음, 로또 번호를 가지고 있는 `LottoNumber` 라는 공이 이미 45개가 생성되어 있는데 이 45개의 공을 랜덤하게 섞어서 거기서 6개만 뽑으면 `LottoNumbers` 객체를 만들수 있지 않을까요? 
현재 로직에서는 1~45개의 숫자를 섞어서 6개의 셋을 만들었지만, 이 값들은 로또번호가 아닌 Map 키값으로 쓰고 있어요.
이미 만들어져 있는 로또번호들에서  숫자를 키값으로 이용하여  LottoNumber를 얻어서 사용하죠.
더 나아가 로또번호를 굳이 Map형태로 관리하지 않아도 충분히 6개셋을 얻을 수 있을 것 같습니다.

2021-01-12 03:06 UTC, wndtjs101 commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
Map 으로 관리 한 이유는, 
일단 이미 만들어놓은 45개의 숫자 인스턴스를 재활용 하기 위해서 이미 해당 key값의 인스턴스가 만들어져 있는지 판단하기 위해 Map을 사용하였고,
HashMap 형태이기 때문에 get/put 의 시간복잡도가 O(1) 일 것이라 판단하여 사용하였는데 혹시 Map형태로 관리하지 않는다는 말씀은 어떤 식으로 관리를 한다는 것인가요?

2021-01-12 03:17 UTC, wndtjs101 reviewed
랜덤으로 숫자를 생성하는 부분에서 문제를 겪었던 점입니다.
LottoNumbers를 만들 때 미리 만들어진 45개의 LottoNumber들을 섞어 6개를 뽑지 않고, List<Integer> 형태로 숫자를 생성한 후 LottoNumbers를 만든 이유는,   
LottoNumbers 클래스 생성자의 parameter가 List<LottoNumber> 형태로 외부에 노출시키게 되면, 테스트 코드 작성 시나 LottoNumbers 를생성하는 모든 부분에서 new LottoNumbers(Arrays.asList(new LottoNumber(1),new LottoNumber(2).......))  형태로 굉장히 단점이 많다고 생각되어 생성자 parameter를 List<Integer>로 정하였고, 이 form에 맞추기 위함이었습니다.

List<LottoNumber> 형태의 생성자를 추가하려고 했지만, Java에서는 List<T> 형태의 오버로딩을 동일한 시그니쳐로 판단을 하였습니다. (https://stackoverflow.com/questions/1998544/method-has-the-same-erasure-as-another-method-in-type)
고민 끝에 LottoNumbers의 두 생성자는 List<Integer> 형태와 set<LottoNumber> 형태로 받게하였고, 특히 TreeSet 을 활용해 따로 정렬을 하지 않아도 로또번호가 정렬이 된 상태를 유지하게 하여 이 문제를 해결하였습니다

2021-01-12 10:51 UTC, adeldel commented on src/main/java/lotto/domain/LottoNumbers.java
> +        Set<LottoNumber> lottoNumbers = new TreeSet<>();
treeSet을 이용하였네요. Set 인터페이스를 구현한 다양한 자료구조를 잘 활용하시면 정렬,중복문제 등을 자연스럽게 해결할 수 있죠. 👍 👍

2021-01-12 10:51 UTC, adeldel commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
제가 추천했던 구현방식은 LottoNumber 객체를 45개 만들어둔 로또객체를 섞고(shuffle), 거기서 6개의 LottoNumber를 list형태로 돌려줘도 되지 않나 싶었어요.  그렇다면 shuffleNumbers 메소드에서 45개의 숫자를 매번 섞지 않아도 되고, Map이 아닌 리스트형태로 사용해도 괜찮지 않나 라는 생각으로 의견드렸었어요. 
개선된 소스를 보니 TreeSet 으로 최종 구매로또를 관리하여 중복비허용으로 하신 부분은 칭찬드립니다. 👍 
현재 리팩토링 하신 로직도 크게 성능차이는 없어보여서 이대로 두어도 괜찮습니다.

2021-01-12 11:02 UTC, adeldel commented on src/test/java/lotto/domain/LottoGameTest.java
> +    public void create() {
이 부분은 한번 훓어봐주세요. 꼭 테스트명을 변경하실 필요는 없으나, 일반적인 패턴으로 작성하면 더 좋겠죠.

2021-01-12 11:03 UTC, adeldel approved these changes
안녕하세요. 리뷰가 좀 늦어져서 죄송합니다. 🙏 
이전 리뷰에서 코멘트 드린 부분 대다수 잘 반영해주셨습니다.
코멘트 주신 내용을 보니 많이 고민하신 흔적이 보이고, 저도 오션의 의견을 존중합니다.
이번 스탭은 머지해둘께요. 다음 step도 화이팅! 💪

2021-01-12 11:03 UTC, merged

2021-01-12 11:13 UTC, wndtjs101 commented on src/test/java/lotto/domain/LottoGameTest.java
> +    public void create() {
네 step2 에서는 이 부분 참고해보겠습니다!