[yell.ow] 로또 미션 2단계 수동 PR입니다.
NewKrew2021/java-lotto-kakao pull request #33
Opened 2021-01-11 05:50 UTC by idealgu

로또 미션 2단계 리뷰를 요청드린 옐입니다!
리뷰주셨던 코멘트를 참고하여 리팩토링을 진행했습니다.
구조 자체에 큰 변화는 없이 2단계 기능을 추가했습니다.
많은 피드백 부탁드립니다! 😅

## 수정/추가부분
- Domain
  - LottoNumber : **1~45까지의 LottoNumber객체 풀을 가지도록 수정**
  - Lottos : **List<Lotto>와 PurchaseInfo를 저장**
  - Lotto : **생성 시 전략 패턴을 결정하도록 수정**
  - Status : **LottoStatus.values()를 활용하도록 수정**
  - **SelfLottoStrategy : 문자열 입력으로 로또를 생성할 때 사용하도록 추가**
  - PurchaseInfo : **입력금액 및 수동 로또 구입 개수, 현 시점에서 구매한 로또의 개수 저장**
  - Simulator : **Lottos, Answer를 통해 결과 출력**

## 질문사항
  - 로또를 생성할 때 마다 strategy를 새로 생성하는 부분의 개선이 어떻게 가능할까요? 좋은 방법이 떠오르지 않습니다.. Lottos의 인스턴스 변수로 strategy를 가지고 있게끔 수정하는 방식과 같이 개선하는게 더 나은 방식일까요?

2021-01-11 09:11 UTC, humbledude requested changes
안녕하세요~

코드 잘 봤습니다.
제가 이해하기 어려웠던 부분은 아래에 코멘트 남겨 두었는데요,
PurchaseInfo 와 Lottos 의 역할 분리에 대해서 한번 더 생각해 보시고 개선 해보시면 좋을꺼 같습니다~!
여기가 로또 구매의 핵심 부분인데, 수동 로또의 생성이 새로 요구사항으로 들어오면서 좀 난해해진 감이 있습니다.

질문으로 주신 로또 생성할때마다 strategy 를 새로 생성하는 부분에 있어서 제 아이디어는요~
(자동에서) strategy 는 새로 생성 되더라도, 내부 로직중에 전체 로또 번호를 항상 새로 생성하지는 않아도 될꺼 같은데요.
요런식으로 개선하면 어떨까 의견 드려보구요~

커밋을 하실때, 여러 수정사항 항목을 뭉쳐서 하지 마시고, 단위별로 나누어 커밋하시는걸 추천 드립니다.
커밋로그는 refactor 로 시작하는데, 리팩토링과 기능구현이 합쳐져 있어서 신규 기능의 구현이 어디에 되어있는지 알아보기가 힘들었어요
참고하셔서 수정 진행 해보시길 바랍니다~

2021-01-11 09:11 UTC, humbledude commented on src/main/java/domain/Lotto.java
> +        List<Integer> numbers = lottoStrategy.numberChooseStrategy();
전략 객체를 받아서 로또 번호 생성 👍

2021-01-11 09:11 UTC, humbledude commented on src/main/java/domain/LottoNumber.java
> +            lottoNumbers.put(i, new LottoNumber(i));
로또 번호를 미리 생성해두고 pool 에서 꺼내는 군요 👍

2021-01-11 09:11 UTC, humbledude commented on src/main/java/domain/PurchaseInfo.java
> +    public boolean buyAllSelfLottos() {
네이밍이 수동 로또를 돈 되는 만큼 사는 거 같아요~

2021-01-11 09:11 UTC, humbledude commented on src/main/java/domain/Lottos.java
> +    public void buyLotto(LottoStrategy lottoStrategy) {
PurchaseInfo 에서 수동 / 자동 로또 구매 갯수 데이터를 갖고
실제 로또는 Lottos 에 들어가는 구조가 좀 이해하기 어려운거 같습니다.

buyLotto 에서 전략 객체를 받아서 로또를 생성하고, 
purchaseInfo.buyLotto() 를 호출할때는 어떤 전략 (수동 / 자동?) 인지 알려주지 않았는데도 카운트가 잘 될까 싶네요~

구매 이력관리와 실제 로또 번호 관리라는 두가지 기능을 나누는 시도는 좋았던거 같은데요,
수동이 들어오면서 구매 이력관리의 복잡도가 올라가면서 이해하기 어려워 진거 같아요

이부분 다시 아이디어 잡고 구현해보면 어떨까요?

2021-01-11 09:11 UTC, humbledude commented on src/main/java/controller/LottoController.java
> +        lottoSimulatorView.printBuyLottoCount(purchaseInfo.getSelfLottoPurchaseCount(),
프린트 기능은 프린트 쪽으로 모으는게 좋겠어요~

2021-01-11 11:43 UTC, idealgu commented
피드백 주신 부분 수정해보았습니다!
기능 구현을 하는데 집중해 커밋하는 것을 잊고 진행하여 큰 단위로 커밋하다 보니 제가 봐도 커밋로그를 이해하기 어렵네요ㅠㅠ
다음부터는 더욱 신경써서 커밋 로그를 남기도록 하겠습니다. 😥

1. 우선 RandomLottoStrategy의 lottoNumbers를 static으로 변경하였습니다.
2. Lottos에서 purchaseInfo를 가지고 상태를 확인하는 것이 아닌 자동/수동 구매 정보를 포함하는 purchaseInfos를 생성하여 purchaseInfos의 상태를 확인하며 lottos에 로또를 저장하게끔 수정했습니다.

2021-01-12 01:56 UTC, humbledude approved these changes
수고 많으셨습니다~
피드백이 도움이 되셨으면 좋겠네요
잘 구현하셔서 merge 합니다
다음 미션도 즐겁게 진행하시길 바랄꼐요~ 👍

2021-01-12 01:56 UTC, humbledude commented on src/main/java/domain/PurchaseInfos.java
> +    private PurchaseInfo autoLottoPurchaseInfo;
자동 수동을 따로 카운트 하기로 하셨군요~ 👍

2021-01-12 01:56 UTC, humbledude commented on src/main/java/domain/Lottos.java
> -    private final PurchaseInfo purchaseInfo;
구매 관련된 내용은 따로 정리하시는군요 👍

2021-01-12 01:56 UTC, humbledude commented on src/main/java/domain/Lotto.java
> +            throw new IllegalArgumentException(LOTTO_CONTAINS_DUPLICATE_NUMBER_ERROR_MESSAGE);
매번 번호를 추가할때마다 중복을 체크하는 방법도 있지만,
자료구조 중에 Set 은 애초에 중복된 번호는 중복제거를 하는 특성이 있어요
Set 을 사용하면 중복제거를 더 쉽게 할수있습니다

2021-01-12 01:56 UTC, humbledude commented on src/main/java/controller/LottoController.java
> +        if (purchaseInfos.canBuySelfLotto()) {
buyLotto 흐름이 더 쉽게 읽히네요~ 👍 
추가적으로는, lottos.buyLotto 와 purshaceInfos.buyLotto 가 엮이면 더 좋을꺼 같아요
둘중 하나만 변경을 하게 되면 데이터 정합성이 깨지기 때문에요~

2021-01-12 01:56 UTC, merged