[yuni.code] 로또 자동 step1 PR입니다.
NewKrew2021/java-lotto-kakao pull request #4
Opened 2021-01-07 12:23 UTC by dsyun96

안녕하세요, yuni입니다.
페어 프로그래밍 및 혼자서 리팩토링하는 과정에서 생긴 궁금한 점을 정리해 보았습니다.

## 궁금한 점
- 출력할 때 도메인 객체에서 toString을 오버라이딩하지 않고 View에서 따로 처리하는 방법이 있을까요?
- 원활한 테스트를 위해 추가한 생성자(혹은 메서드)는 그대로 두는 게 일반적인가요?
- 3개 일치, 4개 일치 등의 상태를 enum 클래스로 관리하였는데 이 경우 하드코딩이 불가피합니다. 더 좋은 방법이 있을까요?
- RandomNo 클래스에서 static 블록 (초기화 블록)은 처음 사용해봤는데, 저런 식으로 하는 게 적절할까요?

2021-01-08 01:51 UTC, adeldel requested changes
안녕하세요. 로또 미션을 함께할 아델입니다. 😄 
전체적으로 커밋을 잘 나눠주셔서 따라가 보기 편했고, 도메인객체도 잘 나눠서 책임분리를 잘 해주셨습니다.
기능 요구사항에 대해서는 잘 구현해주셨습니다. 👍 👍 
다만, 질문주신 사항들 포함해서 리팩토링하면 더 좋을 포인트들을 코멘트로 남겨드렸습니다.
확인해보시고 궁금하신 사항은 다시 코멘트 주시거나 편하게 DM 주세요!

2021-01-08 01:51 UTC, adeldel commented on README.md
> +- 구입금액에 따른 로또 개수 파악하는 기능
기능 요구사항 정리 👍

2021-01-08 01:51 UTC, adeldel commented on src/main/java/lotto/domain/Digit.java
> +public class Digit {
`Digit` 라는 제너럴한 이름보다 여기서는 `로또번호`이므로 좀더 의미있는  객체이름을 쓰는건 어떨까요?

2021-01-08 01:51 UTC, adeldel commented on src/main/java/lotto/utils/Result.java
> +    THREE, FOUR, SIX, FIVE, BONUSFIVE, UNDERTHREE
enum을 사용해주셨네요. 👍  여기서 enum을 사용한 김에 인스턴스 변수를 추가하여 로또 일치 개수와 그에 따른 리워드값(당첨금액)을 관리해주면 어떨까요?  그러면 LottoResults 와 Result 도메인을 합치면서 좀더 로직도 간결해지는 효과가 있을 것 같습니다.
 
질문 주신  `3개 일치, 4개 일치 등의 상태를 enum 클래스로 관리하였는데 이 경우 하드코딩이 불가피합니다. 더 좋은 방법이 있을까요?` 내용에 대한 답변이 되었을까요.

2021-01-08 01:51 UTC, adeldel commented on src/test/java/lotto/domain/LottoResultsTest.java
> +        assertThat(LottoResults.mapResult(6, true)).isEqualTo(Result.SIX);
junit5 의 `@ParameterizedTest` 를 활용해 반복되는 검증문을 개선해보면 어떨까요?
힌트를 드리자면 `@MethodSource` 를 같이 활용하면 좋을 것 같습니다. 
- https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-sources-null-and-empty

2021-01-08 01:51 UTC, adeldel commented on src/main/java/lotto/view/InputView.java
> +        return Integer.parseInt(input.nextLine());
숫자형의 값이 들어오지 않으면 어떤 에러가 발생할까요? 의도치 않는 에러가 발생하지 않도록 에러처리를 해준다면 프로그램이 좀더 견고해 집니다. 마찬가지로 당첨번호나 보너스볼 정보 입력시에도 체크해주면 좋겠죠.

2021-01-08 01:51 UTC, adeldel commented on src/main/java/lotto/domain/RandomNo.java
> +            numbers.add(i);
미리 로또번호 1~45번을 생성해주셨군요 👍  
여기서 조금 더 개선한다면 이 숫자들도 결국 로또번호이므로 만들어주신 `Digit` 객체로 만들어줘도 되지 않을까 싶습니다.  

그리고 질문주신 내용 중에 `RandomNo 클래스에서 static 블록 (초기화 블록)은 처음 사용해봤는데, 저런 식으로 하는 게 적절할까요?` 라고 하셨는데 제 생각은 문제될 건 없을 것 같아요.  만드는 김에 값이 변할 일이 없으므로 `불변객체`로  변경해주시면 더 좋을 것 같습니다.

2021-01-08 01:51 UTC, adeldel commented on src/main/java/lotto/domain/Lotto.java
> +    private List<Digit> mapDigit(List<Integer> digits) {
1~45의 로또번호를  생성할때 `로또번호객체`로 생성해두고  재사용한다면 여기서 다시 생성할 필요는 없어지겠죠?

2021-01-08 01:51 UTC, adeldel commented on src/main/java/lotto/domain/Lottos.java
> +    public String toString() {
`출력할 때 도메인 객체에서 toString을 오버라이딩하지 않고 View에서 따로 처리하는 방법이 있을까요?`
여기서 toString을 override하지 않고 이 로직을 뷰객체로 분리해서 lottos를 넘겨주고 출력을 담당하는게 더 깔끔할 것 같긴 합니다. 
일반적으로 mvc패턴에서 응답(출력)을 담당하는 view 를 만들어서 사용하니깐요. 
대체로 객체에 대한 모든 멤버변수를 출력하는 경우도 있지만, 도메인 객체의 일부만 응답데이터에 필요한 경우도 있기 때문에 output 뷰를 관리해주는게 좋다고 생각합니다.  
다른 결과들은 OutputView로 넘겨주어 출력했듯이 이 부분도 lottos를 넘겨주고 outputview에서 출력을 담당해주어도 될것 같습니다.

2021-01-08 01:51 UTC, adeldel commented on src/main/java/lotto/view/OutputView.java
> +public class OutputView {
👍 👍

2021-01-08 01:51 UTC, adeldel commented on src/test/java/lotto/domain/WinningLottoTest.java
> +    }
질문사항 : 원활한 테스트를 위해 추가한 생성자(혹은 메서드)는 그대로 두는 게 일반적인가요?
답변 : 그렇지 않습니다. 보통 테스트를 위한 생성자를 추가히지 않고, 로직에서 사용하는 생성자를 이용하여 테스트하는게 좋아요.
이 테스트는 아래와 같이 기존 생성자를 쓰도록 바꿔주면  충분히 테스트가 가능해요. 
테스트에서만 사용하는 생성자가 존재하면 다른 사람들이 오해할 소지가 있고 잘못 생성자를 택해서 사용할 경우 사이드이펙트가 발생할 수 있으니 지양해주세요. 
```suggestion
WinningLotto winningLotto = new WinningLotto(new Lotto(Arrays.asList(1, 2, 3, 4, 5, 6)), new Digit(37));
        assertThat(winningLotto)
                .isEqualTo(new WinningLotto(new Lotto(Arrays.asList(1, 2, 3, 4, 5, 6)), new Digit(37)));

2021-01-08 01:51 UTC, adeldel commented on src/test/java/lotto/domain/DigitTest.java
> +    void StringEqual() {
보통 유닛테스트 이름은 앞에 test를 붙입니다. (유닛테스트 명명규칙이 관례적이진 않으나, 인기있는 패턴은 존재합니다.)
참고 : https://it-is-mine.tistory.com/3

2021-01-08 01:51 UTC, adeldel commented on src/main/java/lotto/domain/LottoResults.java
> +        return resultString.toString();
여기도 도메인객체에서 출력을 담당할게 아니라, 리워드 결과를 출력뷰로 넘겨주어 출력하도록 하면 더 좋을것 같습니다.

2021-01-08 01:55 UTC, adeldel commented on src/main/java/lotto/domain/LottoResults.java
> +    private static final long SIX_PRICE = 2000000000;
가독성있게 숫자표현을 해보는건 어떨까요? `2000000000 -> 2_000_000_000`
Java 7 이상에서 자릿수를 표시하기 위한 underscores(밑줄)이 포함되었습니다.

2021-01-08 04:57 UTC, dsyun96 commented on src/main/java/lotto/domain/Digit.java
> +public class Digit {
LottoNumber로 변경하면 적절하겠네요!

2021-01-11 06:21 UTC, dsyun96 commented
## 궁금한 점
- 입력을 받는 getPrice 메서드에서 정수로 파싱하는 부분을 try-catch로 감싸주었고 에러가 발생할 경우 문구를 출력하고 System.exit(-1)으로 처리해 주었습니다. 이래도 괜찮을까요?
- 당첨번호나 보너스 볼은 한 줄을 입력받고 컨트롤러 부분에서 적절한 객체 형태로 바꿔줍니다. 이 경우 올바르지 않은 입력에 대한 처리는 컨트롤러 내부에서 처리하는게 맞나요?

2021-01-11 10:46 UTC, adeldel commented
안녕하세요 유니!
리팩토링해주신 내용 잘 보았습니다. 궁금한 점에 대한 답변 남깁니다.
> Q. 입력을 받는 getPrice 메서드에서 정수로 파싱하는 부분을 try-catch로 감싸주었고 에러가 발생할 경우 문구를 출력하고 System.exit(-1)으로 처리해 주었습니다. 이래도 괜찮을까요?
> A. 에러상황에 대해서는 Exception을 Throw 해주면서 에러메시지를 넘겨주면 중단되는 효과가 있습니다. System.exit 보다 에러를 throw 하는게 더 자연스러울 것 같아요.


> Q. 당첨번호나 보너스 볼은 한 줄을 입력받고 컨트롤러 부분에서 적절한 객체 형태로 바꿔줍니다. 이 경우 올바르지 않은 입력에 대한 처리는 컨트롤러 내부에서 처리하는게 맞나요?
A. 어떤 validate 체크냐에 따라 다를것 같습니다. 예를 들어 price는 숫자형만 허용되니 InputView 에서 숫자형을 체크하고, 로또 번호는 1~45 라는 고유한 값만 허용하므로, 이런 경우는 Lotto 도메인 객체에서  체크해주는게 맞겠죠. 각각의 도메인 객첵가 책임져야 할 로직은 이런 validation도 포함이라고 생각합니다.

2021-01-11 10:52 UTC, adeldel approved these changes
안녕하세요 유니! 리뷰요청 사항을 잘 반영해주셨어요 👍 
추가로 질문 주신 내용을 댓글로 남겨두었습니다.
첫번째 스탭은 여기서 마무리하고,  다음 스탭을 진행해주세요.
수고 많으셨습니다.

2021-01-11 10:52 UTC, merged