[dino.bin lotto게임 Step2 Pr입니다.]
NewKrew2021/java-lotto-kakao pull request #41
Opened 2021-01-11 10:29 UTC by kommadot

## 요약 
lottokind란 클래스가 수동과 자동의 갯수를 갖고 있습니다. 

### 감사합니다

2021-01-11 11:13 UTC, dongjoon1251 requested changes
1단계 머지하는 시점에 드렸던 코멘트 중에 일부 적용이 안된 부분들이 보여서 다시 코멘트 남겼습니다. 확인 부탁드립니다 :)

2021-01-11 11:13 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Lotto.java
>      private static final int LOTTO_PRICE = 1000;
해당 상수도 public으로 선언해서 사용하는게 어떨까요?

2021-01-11 11:13 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Lotto.java
> +        lottoNumbers = new LinkedHashSet<>();
lottoNumbers를 numbers의 stream을 통해서 만들어보면 어떨까요?
힌트) 순서가 중요하다면 Set대신에 List 형으로 받아서 sort하고, 중복제거는 stream()의 distinct 메소드를 사용

2021-01-11 11:13 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Lotto.java
> +        return lottoNumbers.size() < LOTTO_NUMBER_LENGTH;
생성자를 통해 중복되지 않은 숫자가 6개 초과해서 들어올 경우도 생길 수 있을 것 같습니다.

2021-01-11 11:13 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Lotto.java
>      public Lotto(LottoNumberGenerator lottoNumberGenerator) {
수동과 자동입력 분리를 위해서 interface를 만들었지만 의도했던 역할대로 수행되지 않는 것으로 보입니다. 랜덤 생성은 Util 클래스하나로 만드는게 어떨까요?

2021-01-11 11:13 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Lottos.java
>          Map<Rank, Integer> rankingsMap = new TreeMap<>();
Statistics 클래스로 WinningLotto, List<Lotto> 를 넘겨서 통계를 생성하게 하면 어떨까요?

2021-01-11 11:13 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Lotto.java
Collections.unmodifiableSet()으로 외부에서 클래스 내부의 컬렉션을 수정하지 못하게 막았으니 DTO로 새로 반환하지 않아도 되지 않을까요?

2021-01-11 11:13 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Lottos.java
>          return new Statistics(rankingsMap);
lottos는 생성될떄부터 Collections.unmodifiableList()라서 dto로 따로 변환하지 않아도 되지 않을까요?

2021-01-11 11:13 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Rank.java
>          if (count == 6) {
values(), stream(), filter() 등을 이용해서 if 문을 사용하지 않도록 리팩토링해보면 어떨까요?

2021-01-11 11:13 UTC, dongjoon1251 commented on src/main/java/lotto/domain/WinningLotto.java
> +    public WinningLotto(LottoNumberGenerator lottoNumberGenerator, int bonusNumber) {
이부분은 테스트 말고는 실제로 사용되는 곳은 없는 것으로 파악됩니다.

2021-01-11 11:13 UTC, dongjoon1251 commented on src/main/java/lotto/exception/BonusNumberException.java
> +    public BonusNumberException() {
IllegalArgumentException 을 상속해서 사용해주셨네요 👍 
RuntimeException을 상속해주셔도 무방합니다

2021-01-11 11:13 UTC, dongjoon1251 commented on src/main/java/lotto/view/InputView.java
> +    private static final Scanner scanner = new Scanner(System.in);
사용자로부터 입력을 받기위해 질의하는 부분도 이 클래스에서 처리하게 하면 어떨까요? :)

2021-01-11 11:13 UTC, dongjoon1251 commented on src/main/java/lotto/view/OutputView.java
> +    public static final String RANK_FIFTH_TEXT = "%d개 일치 (%d원)- %d개\n";
%d로 바꾼후에 중복된 상수들이 보이네요. 하나로 합쳐주는게 어떨까요? 
보너스볼이 일치한 경우만 다른 포맷이 나오게 하면 될 것 같은데 어떻게 리팩토링해볼 수 있을까요?

2021-01-11 11:13 UTC, dongjoon1251 commented on src/main/java/lotto/view/OutputView.java
> +        StringBuilder sb = new StringBuilder();
Rank.values(), stream()을 통해서 리팩토링해볼 수 있지 않을까요?

2021-01-11 11:13 UTC, dongjoon1251 commented on src/main/java/lotto/controller/LottoController.java
> +        OutputView.printStatistics(statistics, statistics.getProfitRate(money));
printStatistics 메소드 내부에서 get을 통해 데이터를 가져오고 있습니다. statistics만 넘겨주고 getProfitRate도 printStatistics 메소드 안에서 호출하면 어떨까요? 아니면 statistics에서 필요한 데이터를 먼저 다 받아서 파라미터로 넘겨주는게 어떨까요?

2021-01-11 11:13 UTC, dongjoon1251 commented on src/main/java/lotto/controller/LottoController.java
> +        lottos = new Lottos(Stream.concat(buySelfLottos(lottoKind.getSelfLottoCount()).stream(), buyRandomLottos(lottoKind.getRandomLottoCount()).stream())
Lottos에서 random으로 생성하는 로또와 입력받는 로또 두가지가 있다는 사실을 인지해도 된다고 가정하고 리팩토링해보면 어떨까요?
Lottos를 생성하기 위해서 필요한 로직들이 Controller 내부에 많아서 복잡도를 높이는 것 같습니다.

2021-01-11 11:13 UTC, dongjoon1251 commented on src/main/java/lotto/controller/LottoController.java
>          lottoController.matchLotto();
이부분은 객체 생성 없이 해당 클래스 내의 메소드를 static으로 선언해서 호출하셔도 무방합니다 :)

2021-01-11 12:44 UTC, kommadot commented on src/main/java/lotto/domain/Lottos.java
>          return new Statistics(rankingsMap);
List에 대한 수정은 막지만, Lotto라는 객체 내부의 값 수정은 제한할 수 없다고 알고 있습니다. 그래서 DTO로 한번더 분리를 시켰습니다.

2021-01-11 12:45 UTC, kommadot commented on src/main/java/lotto/domain/Rank.java
>          if (count == 6) {
한번 변환을 해보려했는데 bonusCount와 꽝일때의 경우를 상정하기가 쉽지 않아서.. 일단 내려놨습니다...

2021-01-11 13:31 UTC, kommadot commented on src/main/java/lotto/controller/LottoController.java
> +        lottos = new Lottos(Stream.concat(buySelfLottos(lottoKind.getSelfLottoCount()).stream(), buyRandomLottos(lottoKind.getRandomLottoCount()).stream())
만약 그렇게 되면 lottos를 두개 관리하지 않는한 다루기 힘들지 않을까요?
lottos가 각각(수동, 자동)의 로또를 받아 합치게 된다면 불변성이 깨진다 생각이 되어서 밖에서 합친 리스트를 lottos로 생성해주었습니다. 방법이 있을까요?

2021-01-11 13:33 UTC, kommadot commented on src/main/java/lotto/controller/LottoController.java
>          lottoController.matchLotto();
만약 생성을 안하면 모든 필드와 모든 메소드를 static으로 선언해야 하는데 괜찮나요?

2021-01-11 14:12 UTC, kommadot commented on src/main/java/lotto/domain/Lotto.java
그렇게 되면 반환형이 일급컬렉션이 아닌 Set<LottoNumber>가 될텐데 괜찮은가요?

2021-01-11 14:35 UTC, kommadot commented
말씀하신것들 중 최대한 리팩토링을 진행했지만 제가 의도를 이해 못한 부분에 대해선 코멘트를 남겼습니다.

소중한 리뷰 감사합니다!

2021-01-12 00:15 UTC, dongjoon1251 commented on src/main/java/lotto/controller/LottoController.java
>          lottoController.matchLotto();
메소드가 분리되면서 lottos, money, lottoKind와 같은 변수들이 생겼네요. 메소드로 분리하지 않고 inline 시키면 로컬 변수로만 사용해도 될 것 같습니다.

2021-01-12 00:23 UTC, dongjoon1251 commented on src/main/java/lotto/controller/LottoController.java
> +        lottos = new Lottos(Stream.concat(buySelfLottos(lottoKind.getSelfLottoCount()).stream(), buyRandomLottos(lottoKind.getRandomLottoCount()).stream())
수동과 자동으로 생성한 로또를 분리해서 다루어야 할 부분은 없어서, 두개를 관리해야하는지에 대해서는 의문이 있습니다.
또한 생성자 로직에서 리스트를 합친다고 해서 불변성이 깨질 것 같지 않습니다.
자동 로또 개수와 수동 로또 생성을 위한 String List를 생성자로 넘겨주는 방식으로 리팩토링해보시면 어떨까요?

2021-01-12 00:25 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Lotto.java
꼭 일급 컬렉션으로 반환해야 한다는 규칙은 없습니다 :)

2021-01-12 00:26 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Lottos.java
>          return new Statistics(rankingsMap);
Lotto라는 객체를 그대로 넘겨줘도 Lotto를 새로 생성하지 않는 한 내부 필드인 lottoNumbers를 수정할 수 있는 방법이 없어보입니다.

2021-01-12 00:26 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Rank.java
>          if (count == 6) {
bonusCount도 enum의 필드로 추가하면 어떨까요?

2021-01-12 00:37 UTC, dongjoon1251 requested changes
문의주신 부분에 대해서 답변 및 추가 코멘트 남겼습니다.
확인 부탁드려요 :)

2021-01-12 00:37 UTC, dongjoon1251 commented on src/main/java/lotto/controller/LottoController.java
> +        inputMoney();
메소드로 분리하면서 불필요한 클래스 필드가 생긴것으로 파악됩니다. 모두 inline시키고 로컬 변수로 사용하게 리팩토링해보면 어떨까요?

2021-01-12 00:37 UTC, dongjoon1251 commented on src/test/java/lotto/domain/LottoTest.java
> +    void matchTest1() {
어떤 테스트인지 메소드 이름이나 @DisplayName으로 구분할 수 있으면 좋을 것 같습니다.
그리고 같은 로직을 다른 파라미터로 테스트하고자 할때는 @ParameterizedTest를 사용해보면 어떨까요?

2021-01-12 00:37 UTC, dongjoon1251 commented on src/main/java/lotto/domain/LottoKind.java
> +
해당 클래스의 역할이 모호합니다. controller내에서 해당 하는 필드들을 로컬 변수로 사용하고 domain, view로 모두 따로 전달해서 사용하는게 어떨까요? randomLottoCount 검증 로직은 Lottos에 생성자로 넘겨주면 이동이 가능해보입니다.

2021-01-12 00:37 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Statistics.java
> +        return (long) getCountOfRank(rank) * prize.get(rank.getRank());
prize.get(rank.getRank()) 이부분은 rank.getReward()와 같이 수정할 수 있지 않을까요? 그러면 prize 필드는 없어도 될 것 같습니다.

2021-01-12 00:37 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Lottos.java
>          Map<Rank, Integer> rankingsMap = new TreeMap<>();
Rankings로 리턴타입은 변했는데 생성로직은 그대로 Lottos내부에 있네요. 이부분을 Rankings 생성자 내부로 옮기면 어떨까요?

2021-01-12 01:12 UTC, kommadot commented on src/main/java/lotto/controller/LottoController.java
> +        inputMoney();
오히려 메소드 분리로 인해 불필요한 클래스필드가 생성돼서 분리한 메소드를 합치라는 말씀 이신가요?

2021-01-12 03:05 UTC, kommadot commented on src/main/java/lotto/domain/Rank.java
>          if (count == 6) {
적용하긴 했는데...이런 방식의 적용이 맞는지 모르겠습니다.

2021-01-12 03:19 UTC, kommadot commented
### 항상 리뷰 감사합니다
더 노력하겠습니다..

2021-01-12 04:39 UTC, dongjoon1251 commented on src/main/java/lotto/controller/LottoController.java
> +        inputMoney();
넵 맞습니다.

2021-01-12 04:50 UTC, dongjoon1251 approved these changes
피드백을 잘 반영해주셨네요 :)
이번 미션은 여기서 마무리하도록 하겠습니다.
향후 다른 미션에서 도움이 될 만한 부분들을 추가로 코멘트 남겼습니다. 
고생하셨습니다!

2021-01-12 04:50 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Lotto.java
> +        return lottoNumbers.size() > LOTTO_NUMBER_LENGTH;
LOTTO_NUMBER_LENGTH 와 같지 않을 때만 확인해주면 조건문을 하나만 만들어도 되지 않을까요?

2021-01-12 04:50 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Lottos.java
> +        this.lottos = lottos.stream().map(Lotto::new).collect(Collectors.toList());
stream() 은 항상 한 라인에 한 포인트만 나오게 줄바꿈해주세요 :)

2021-01-12 04:50 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Rank.java
> +                .filter(rank -> {
filter하는 부분을 메소드로 빼보면 어떨까요?

2021-01-12 04:50 UTC, dongjoon1251 commented on src/main/java/lotto/domain/Rank.java
> +                .get();
파라미터로 matchCount가 6보다 큰 엉뚱한 값이 들어왔을 경우에 대비패서 orElse나 orElseThrow로 Exception이 발생하게 해보면 어떨까요?

2021-01-12 06:46 UTC, merged