[ian.lock 양정일] 로또 미션 2차 PR
NewKrew2021/java-lotto-kakao pull request #43
Opened 2021-01-11 12:17 UTC by Jjungs7

[matchWinning, matchLotto](https://github.com/next-step/java-lotto-kakao/pull/24#discussion_r554453852) 이전 PR에서 피드백 해주셨던 것들 수정하다가 궁금한 점 몇가지 생겨서 코드 사이에 질문 남겨드리겠습니다!

---

### 추가 기능 요약
- Buyer는 구매자를 나타내고, 수동 구매하는 로또티켓 개수가 자신의 예산을 초과하지 않음을 보장함
- ManualPickStrategy가 수동 입력을 처리

### 수정 사항
- InsertPrice와 TotalPrice를 하나의 Price VO로 통합
- delegate 메소드 전부 삭제 후 작업을 위임하는 방식으로 변경
- dto 패키지명을 vo 로 수정
- StatisticsResult 클래스 삭제, 해당 기능을 LottoStatistics가 대신함
- Buyer가 기존 Issuer의 책임 일부(사용자 잔돈 반환, 티켓 개수 세어주기, 사용자의 원금 저장)를 넘겨받음

2021-01-11 12:21 UTC, Jjungs7 commented on src/main/java/lotto/view/OutputView.java
> +        Map<MatchResult, Integer> matchResults = statistics.getResults();
결과값을 저장하던 StatisticsResult 는 삭제하고 LottoStatistics 에 있는 데이터를 getter로 Map 상태를 그대로 받아서 출력 문자열을 구성하였습니다. 이렇게 하는 것이 맞을까요?

2021-01-11 12:38 UTC, Jjungs7 commented on src/main/java/lotto/domain/WinningNumbers.java
> +    public MatchResults matchLotto(LottoTickets lottoTickets) {
[알려주셨던](https://github.com/next-step/java-lotto-kakao/pull/24#discussion_r554453852) 메소드 중에 `matchLotto`로 구현했어요. 근데 하다가 깔끔하지 않게 나온거같아서 이후에 수정했는데, 각각의 구현에 관해서 궁금했던 점을 여쭤보고 싶어서 커밋을 남기게 되었습니다!

신경쓰였던 부분은 `matchLotto(LottoTicket lottoTicket)`을 만들었는데, `matchLotto(LottoTickets lottoTickets)`에서 이것을 활용하지 못하고 비슷한 로직으로 새로운 메소드를 만들어야했던 것이에요. 같은 시그너처를 갖는데도 불구하고 각자 독립적으로 구현되는건 일관성이 깨진다고 생각했어요. `matchLotto(LottoTicket lottoTicket`을 활용하려면 LottoTickets 에서 getter를 제공해야 하는데, 이런 경우에는 다른 방법을 찾는게 더 맞을까요?

두 번째 질문은 matchLotto 로 하니까 두 개의 리스트를 받아서 따로 처리하는 방식이 깔끔하지 못한데 더 좋은 방법이 있을지 여쭤보려했어요. 근데 다시 보니까 LottoTickets쪽에 luckyNumbers, bonusNumber 두 개 모두 넘겨서 LottoTickets 쪽에서 MatchResult를 반환하게 할 수도 있었네요

2021-01-11 12:49 UTC, Jjungs7 commented on src/main/java/lotto/domain/LottoTickets.java
> +    public MatchResults matchWinning(WinningNumbers winningNumbers) {
여기서 궁금했던 점은 실행 흐름이 *LottoMatcher.match* -> *LottoTickets.matchWinning* -> *WinningNumbers.getMatchResult* -> *LottoNumbers.matchWinning* 이렇게 네 단계로 들어가는데 흔한 패턴인가요? 깊게 내려가면 내려갈수록 코드를 이해하는데 방해가 될 것 같아서요!

2021-01-11 12:50 UTC, Jjungs7 commented on src/main/java/lotto/domain/LottoTickets.java
> +    public List<List<Integer>> getAllTicketNumbers() {
`OutputView.PrintStatistics`에 최대한 데이터만 넘기겠다는 의미로 이중리스트를 반환하였는데 이렇게 하는 것이 맞을까요?

2021-01-11 12:53 UTC, Jjungs7 commented on src/main/java/lotto/controller/Lotto.java
> +        LottoTickets manualTickets = inputView.scanManualChooseTickets(buyer.getManualChooseTicketAmount());
우려되는 부분이 수동입력을 처리하는 과정에서 `LottoTicketIssuer.issue`를 현재 파일과 `InputView.scanManualChooseTickets`에 나눠서 실행하고 있습니다. 일관성이 깨진다는 생각이 드는데 더 나은 방법이 안 떠올라서요 ㅠㅠ 이런 구조 괜찮을까요? 아님 더 나은 방법이 있나요?

2021-01-11 12:56 UTC, Jjungs7 commented on src/main/java/lotto/domain/Buyer.java
> +    public void setLottoTickets(LottoTickets tickets) {
티켓이 구매자의 것이다를 표현하고싶어서 setter를 만들었어요. `Lotto.java`에서 new Buyer를 통해서 이미 생성된 구매자를 또 생성하는 것은 맞지 않을 것 같고 "구매금액, 수동입력개수, 티켓목록"을 모두 갖고 생성하기에는 구매금액과 수동입력개수와 관련된 context가 필요합니다. 그렇다고 해서 controller에 tickets 이라는 변수를 두고 사용하는 것은 꼼수(?)같은 느낌이 드는데 이 setter는 적절하게 사용한건가요?

2021-01-12 02:59 UTC, Jjungs7 commented on src/main/java/lotto/domain/LottoNumbers.java
> +        }
여기서 제가 2단 indent를 빼보려고 했는데 아래 방법밖에 안 떠오르더라구요...
LottoNumber에 이 메소드 하나만을 위해서 private field를 만드는 것은 LottoNumbers 전체에게 봤을 때 득보다 실이 더 커보였어요 (다른 메소드는 count라는 변수를 쓰지 않을텐데 LottoNumbers에게 중요한 변수인것처럼 field로 들어가있어서요)
이럴때 새로운 클래스로 분리해야되는 것인가요?
```java
public class LottoNumbers {
    private int count = 0;
...
    public int getMatchCount(LottoNumbers luckyNumbers) {
        for(...) {
            addCountIfLottoNumberExistsInLuckyNumbers(luckyNumbers);
        }
        ...
    }

    private void addCountIfLottoNumberExistsInLuckyNumbers(LottoNumbers luckyNumbers) {
        if (luckyNumbers.contains(lottoNumbers) {
            count++;
        }
    }
```

2021-01-12 12:27 UTC, Hue9010 requested changes
리뷰가 약간 늦었네요. 🙏 
주신 질문 답변 드렸습니다. 혹시 부족한 부분이나 궁금하신 사항 질문 남겨주세요!
피드백 확인 부탁드려요!

2021-01-12 12:27 UTC, Hue9010 commented on src/main/java/lotto/domain/LottoNumbers.java
> +        }
보통 인덴트가 2단 이상이 될 때는 for, if 안에 있는 로직을 이해하기 어렵기 때문에 메서드 추출의 효과를 크게 봅니다. 그리고 조건문과 반복문에 많은 로직을 넣어 작성하는 경향이 있어 학습 차원에서 1단을 강제하여 의식적인 학습하게 하기 위함이라고 생각 됩니다.
그런면에서 지금 수준에서는 무리해서 변경하실 필요는 없다고 생각됩니다. 별도 메서드를 안 빼도 스트림의 filter와 count를 이용하면 될 것 같네요.

count를 다른 메서드에서는 사용하지 않는다는 점 보다는 count가 LottoNumbers의 상태가 맞는지 고민하는게 더 좋을 것 같아요. 아무리 다른 곳에서 사용하지 않는다 해도 LottoNumbers의 한 요소라고 판단되면 한 메서드에서만 사용하는건 문제가 안됩니다.

2021-01-12 12:27 UTC, Hue9010 commented on src/main/java/lotto/domain/LottoTickets.java
> +    public MatchResults matchWinning(WinningNumbers winningNumbers) {
다시한번 객체지향의 사실과 오해 추천드립니다. 👍  
주변 시니어 분은 2~3년에 한번씩 다시보는데 볼때마다 얻는게 다르다고 하네요. 😮

2021-01-12 12:27 UTC, Hue9010 commented on src/main/java/lotto/domain/LottoTickets.java
> +    public List<List<Integer>> getAllTicketNumbers() {
LottoTicketsDto가 있다면 해결될 문제라 지금은 너무 심려치 마세요. 😢 

```java
public class LottoTicketsDto {
    private final List<LottoNumbersDto> tickets;
```

LottoTicketsDto를 만들면 LottoNumbers도 Dto로 만든다는걸 유의해주세요.

2021-01-12 12:27 UTC, Hue9010 commented on src/main/java/lotto/domain/Buyer.java
> +    public void setLottoTickets(LottoTickets tickets) {
setter와 동일한 동작을 한다고 setXX라는 이름을 사용할 필요는 없습니다. 로또를 지급 받는다는 표현을 사용하면 어떨까요? (영어가 어려워서 좋은 이름이 안 떠오르네요. 😭)

이름에 대해서 몇가지 더 말씀드리면 
```java
private final Price insertPrice;
private LottoTickets allTickets;
```
Buyer 입장에서는 insertPrice라고 표현할 필요가 없을 것 같네요. 지극히 데이터 관점에서의 표현 같아요. 단순 price나 구매금액으로 표현할 수 있을 것 같아요.
allTickets는 all이 필요 없어보여요. 이름, 특히 필드, 메서드를 만들때는 작업자나 데이터가 아닌 객체 입장에서 생각해보는게 좋답니다. 😉

2021-01-12 12:27 UTC, Hue9010 commented on src/main/java/lotto/controller/Lotto.java
> +        LottoTickets manualTickets = inputView.scanManualChooseTickets(buyer.getManualChooseTicketAmount());
로또를 지급해주는 팩토리를 만들면 어떨까요? 현실 세계를 생각해도 사람이 로또를 살 때는 수동 번호와, 자동 번호 로또 모두를 포함해서 금액을 지불합니다. 그런 측면에서 사람한테 요청 받아 구매한 로또를 지급해주는 객체를 만드는건 어떨까요? 🤔

2021-01-12 12:27 UTC, Hue9010 commented on src/main/java/lotto/domain/MatchResults.java
> +        }
```java
        for (MatchResult result : MatchResult.values()) {
            total += result.calculateTotalReward(resultCounter.get(result));
        }
or
        for (MatchResult result : resultCounter.keySet()) {
            total += result.calculateTotalReward(resultCounter.get(result));
        }
```
위처럼 result에서 계산해줄 수 있을 것 같네요. map은 자료구조상 조회는 (일반적으로)1인데 entrySet을 사용한 이유가 있을까요? 🤔

2021-01-12 12:27 UTC, Hue9010 commented on src/main/java/lotto/view/OutputView.java
> +        Map<MatchResult, Integer> matchResults = statistics.getResults();
사실상 DTO라고 볼 수 있을 것 같네요. 변경하신 김에 MatchResults Dto도 만들어 보는건 어떨까요?

2021-01-12 12:27 UTC, Hue9010 commented on src/main/java/lotto/domain/Buyer.java
> +    private final int manualChoose;
manualChoose보다는 manualCount가 낫지 않을까요?
로또 도메인 특성상 수동이라는 것 자체가 번호를 선택한거라는 의미를 포함하고 있어 choose의 의미가 꼭 필요한 상황이 아니라면 사용하지 않아도 될 것 같아요.
ex ) getManualChooseTicketAmount -> getManualTicketAmount or getManualAmount

2021-01-12 12:27 UTC, Hue9010 commented on src/main/java/lotto/domain/ManualPickStrategy.java
> +        return new InputView().scanTicket();
사실상 InputView에 로직이 존재하네요. 기존에 만들어둔 인터페이스와 달리 입력 값이 필요해서로 보이는데 ManualPickStrategy 생성 시점에 주입해줄 수 있지 않을까요? 😉

2021-01-13 13:16 UTC, Jjungs7 commented
컨트롤러에서 유저 수동입력 티켓 값을 입력 받은 후에 ManualPickStrategy에 전달하고 하나씩 소모하는 방식으로 변경했어요! 추가로 dto를 생성해보았는데 이렇게 하는 것이 맞을까요? 🧐

2021-01-13 15:40 UTC, Hue9010 approved these changes
피드백 반영 잘해 주셨어요. 👍👍

이번 단계는 여기서 머지하도록 할게요. 로또 진행하시느라 고생 많으셨습니다! 👏 
질문에 대한 답변과 몇가지 피드백 드렸는데 반영하기 보다는 한번쯤 생각해보는 정도로 충분해 보여요.😉
추가로 궁금한 사항 있으면 언제든 문의주세요! 또한 답변드리지 않은 질문이 있다면 말씀주세요! 😸 

남은 과정도 화이팅 입니다!

2021-01-13 15:40 UTC, Hue9010 commented on src/main/java/lotto/domain/MatchResults.java
> +                .reduce(0L, Long::sum);
map, reduce 👍

2021-01-13 15:40 UTC, Hue9010 commented on src/main/java/lotto/domain/MatchResults.java
> +    }
보통 Model -> Dto로 변환하는 메서드는 toDto로 짓는 편입니다. 마찬가지로 Dto에선 from을 사용하기도 합니다.

```java
public static MatchResultsDto from(MatchResults matchResults)
```

지금처럼 엄격히 getter를 통제 할 때는 Dto에서 Model의 필드를 가져올 방법이 없기 때문에 Model에도 Dto로 변환하는 메서드가 필요하지만 getter에 한해서는 허용하는 경우 Model <-> Dto의 변환은 모두 Dto에만 두기도 합니다. Model은 Dto와의 의존성을 가지지 않게하기도 합니다. (Model에서 Dto를 참조하게되면 Dto의 생성과정이 변할 때 Dto만 수정하면 되는게 아니라 Model의 코드까지 수정이 필요해지죠)

참고로 DTO나 getter에 관해서는 팀마다 조금씩 정책이 다를 수 있을 것 같네요.

2021-01-13 15:40 UTC, Hue9010 commented on src/main/java/lotto/view/OutputView.java
> +        message.append(String.format("총 수익률은 %d%%입니다.", statistics.getEarningRate().getRate()));
LottoStatistics에서 MatchResultsDto, EarningRate의 rate를 받아 오는데 LottoStatisticsDto로 View에서 사용할 데이터를 한번에 제공해 줄 수 있을것 같아요.

Dto라고 Model의 필드와 일대일 대응 할 필요는 없습니다. Dto를 사용하는 이유 중 하나가 필요한 데이터만 제공하기 위함임을 생각해보면 Model에서 View에 제공할 필요 없는 데이터는 제외하고 Dto로 전달해 주면 됩니다.
```java
public class LottoStatisticsDto {
    private Map<MatchResult, Integer> resultCounter;
    private Integer rate;
}
```
즉, 위처럼 LottoStatisticsDto를 통해 View에는 Model을 전달하지 말고 View에서 사용할 데이터만 전달 해 줄 수 있습니다.

개인적으로 Dto에 Vo가 포함된 경우는 다루지 않아 고려치 않던 부분인데 Vo를 Dto에 포함 시킬 것인가 고민해본 결과 Vo는 Data가 아니기 때문에 엄격히 따져서는 포함시키지 않는게 맞을 것 같아요.

핵심적인 사항만 알면 되니 굳이 반영할 필요는 없을 것 같습니다. 😉

2021-01-13 15:40 UTC, Hue9010 commented on src/main/java/lotto/domain/ManualPickStrategy.java
> +    }
idx가 List 사이즈를 넘어갔을 때에 대한 처리가 추가되면 좋을 것 같아요.
혹은 LinkedList등 pop을 제공하는 특정 자료구조를 활용하여 idx 없이 구현 가능 할 것 같네요. List, Map, Set 인터페이스로 선언한다는데 집중하다 보면 거꾸로 특정 자료구조를 활용한다는 생각이 막히는 경향도 있어요. 그래서 기본 인터페이스로는 뭔가 깔끔한 처리가 불가능 하다고 느낄 때는 다른 자료구조를 고려하는 것도 좋아요. 😉

2021-01-13 15:40 UTC, Hue9010 commented on src/main/java/lotto/controller/Lotto.java
>          OutputView outputView = new OutputView();
클린 코드(인사이트) 5장 형식 맞추기 : 수직 거리 (p.101)
> 서로 밀접한 개념은 세로로 가까이 둬야 한다.
> ...
> **변수 선언.** 변수는 사용하는 위치에 최대한 가까이 선언한다. 우리가 만든 함수는 매우 짧으므로 지역 변수는 각 함수 맨 처음에 선언한다.

함수가 매우 짧다는 기준이 애매하기도 하고 사실 클린 코드가 가이드 중 하나이지 규칙은 아니기 때문에 사람(팀)에 따라 컨벤션은 조금씩 다를 수 있다는 점 참고 해두면 좋아요. 😉

2021-01-13 15:40 UTC, Hue9010 commented on src/main/java/lotto/domain/MatchResults.java
> +    }
> dto를 생성해보았는데 이렇게 하는 것이 맞을까요?

몇가지 코멘트를 남겼는데 충분히 잘 해 주셨다고 생각돼요. 👍 
지금은 View가 자바 환경 내에서 Console 출력이기 때문에 그 경계가 명확하지 않아 생기는 혼동도 있는데 이 후 웹으로 넘어 가면 View는 웹페이지로 변경되어 그 경계가 명확해지고, Controller에서 Response라는 Dto를 View에 제공하는 구조 덕분에 Dto에 대해서 생각해보기 더욱 수월 해 질 겁니다.

2021-01-13 15:41 UTC, merged