[pavlo.v 최환] 로또 2차 코드리뷰 부탁드립니다.
NewKrew2021/java-lotto-kakao pull request #45
Opened 2021-01-11 15:25 UTC by choihwan2

전에 했던 피드백들을 반영하여 최대한 리팩토링 한 후 2단계 까지 진행해 보았습니다. 
처음에 고생을 좀 했던 기억이 있는데 그런것들 덕분인지 2단계는 조금 수월하게 진행했네요! LotteryUtil 클래스도 없애버렸습니다!

질문이 하나 있는데 지금 여기 있는 코드들에서 InputView에서 `readManualLotteries(int count)` 라는 메소드가 수동으로 번호를 입력받은후에 그걸 Lotteries로 반환하는 메소드가 있습니다. 무언가 만들면서 InputView에서 번호들을 입력받고 생성한다음 반환하는 로직을 사용해도 되는가..? 라는 생각이 자꾸만 들었습니다. 

Lotteries 라는 클래스에 메시지를 보내거나 입력받은 String들을 전부다 보내서 생성하더라도 결국 반환하고 생성하는 작업들이 필요할 것 같은데, InputView에서 String들을 입력만 받고 후에 Main에서 그 입력 받은 String들을 Lotteies에 새로운 메소드를 만들어서 보내준다음 반환받는게 좋은 것인지, 지금처럼 InputView에서 직접 반환하는 메소드가 좋은 것인지 조언을 좀 해주실 수 있으실까요??

2021-01-12 13:16 UTC, Hue9010 requested changes
리뷰가 늦었네요. 🙏 
잘 구현해주셨어요.👍  Util이 사라지니까 객체간 관계가 더 명확해진 것 같네요. 특히나 수동 로또 생성을 만들때 Util이 있었다면 Util에 로직을 넣을까 고민하지 않았을까 싶군요. 😏 
질문 주신 사항과 몇가지 피드백 남겼는데 확인하고 궁금하신 점 있으면 언제든 문의주세요!

2021-01-12 13:16 UTC, Hue9010 commented on src/main/java/lotto/ui/Main.java
> +        lotteries.addRandomLotteries(autoLotteriesCount);
> 질문이 하나 있는데 지금 여기 있는 코드들에서 InputView에서 readManualLotteries(int count) 라는 메소드가 수동으로 번호를 입력받은후에 그걸 Lotteries로 반환하는 메소드가 있습니다. 무언가 만들면서 InputView에서 번호들을 입력받고 생성한다음 반환하는 로직을 사용해도 되는가..? 라는 생각이 자꾸만 들었습니다.
>
> Lotteries 라는 클래스에 메시지를 보내거나 입력받은 String들을 전부다 보내서 생성하더라도 결국 반환하고 생성하는 작업들이 필요할 것 같은데, InputView에서 String들을 입력만 받고 후에 Main에서 그 입력 받은 String들을 Lotteies에 새로운 메소드를 만들어서 보내준다음 반환받는게 좋은 것인지, 지금처럼 InputView에서 직접 반환하는 메소드가 좋은 것인지 조언을 좀 해주실 수 있으실까요??

👍👍  좋은 고민이네요. 
생성 로직이 View에 존재하기 때문에 가능하다면 제거해주시는게 좋습니다. 이럴때는 객체지향이 현실 세계를 모방한다는 점을 고려해보면 어떨까요?

현실에서 로또를 살 때 `구매할 수동 번호 꾸러미?`와 `자동 로또 갯수`, `구매 금액`을 판매점에 지불하고 로또를 받게 되죠? 이처럼 로또를 지급해주는 역할을 담당할 팩토리를 만드는건 어떨까요? 🤔

2021-01-12 13:16 UTC, Hue9010 commented on src/main/java/lotto/domain/LotteryRank.java
> +    private final HashMap<LotteryPrize, Integer> lotteryRank;
HashMap -> Map 😉

2021-01-12 13:16 UTC, Hue9010 commented on src/test/java/lotto/domain/LotteryUtilTest.java
>      @CsvSource({"0, 0", "999, 0", "1000, 1", "1001,1", "1999, 1", "2000 , 2"})
"0, 0", "999, 0"는 실패합니다. 확인 부탁드려요. 😉 
테스트는 가능하면 commit or push 전에는 전체 테스트 돌려보는걸 추천드립니다. 가능하다면 일부분이 바꼈다고 바뀐 곳에 대한 테스트만 하기보다는 매번 전체 테스트를 하는 게 좋습니다.

2021-01-12 13:16 UTC, Hue9010 commented on src/main/java/lotto/domain/Lotteries.java
> +
사용되지 않고 있네요. 😉

2021-01-12 13:16 UTC, Hue9010 commented on src/main/java/lotto/domain/Lottery.java
> +        this(Arrays.stream(strings)
`public Lottery(List<LotteryNumber> numbers);`를 호출해서 동일한 validation을 가지게 했네요. 👍

2021-01-12 13:16 UTC, Hue9010 commented on src/main/java/lotto/domain/LotteryAnswer.java
>          if (Lottery.isDuplicatedLotteryNumbers(answerLottery, bonusNumber)) {
이제보니 isDuplicatedLotteryNumbers를 static이 아니라 answerLottery.isDuplicatedLotteryNumbers(bonusNumber)로 바꿀 수 있을 것 같아요.

is보다는 has가 더 좋을 것 같아요. 시간 되실 때 [A Useful Framework for Naming Your Classes, Functions, and Variables](https://medium.com/better-programming/a-useful-framework-for-naming-your-classes-functions-and-variables-e7d186e3189f) 읽어보면 좋습니다. 😉

2021-01-12 13:16 UTC, Hue9010 commented on src/main/java/lotto/domain/Money.java
> +        return money.value < LOTTERY_PRICE;
전 로또 가격보다 적을 수 있다는 걸 고려 못했는데 😮 💯

2021-01-12 13:16 UTC, Hue9010 commented on src/test/java/lotto/domain/LotteryUtilTest.java
>      @CsvSource({"0, 0", "999, 0", "1000, 1", "1001,1", "1999, 1", "2000 , 2"})
LotteryUtil이 사라진 만큼 LotteryUtilTest도 제거해주세요!

2021-01-12 13:16 UTC, Hue9010 commented on src/main/java/lotto/domain/Lottery.java
> +        this(Arrays.stream(strings)
문자열로 생성하는 것도 테스트 할 수 있겠네요.

2021-01-12 13:16 UTC, Hue9010 commented on src/main/java/lotto/exception/InvalidMoneyException.java
> +    private static final String MSG_WRONG_MONEY_VALUE = "돈은 로또 가격보다 낮을 수 없습니다.";
지금보니 메시지를 받는 생성자는 불필요해 보이네요. 필요할 때 만들어도 충분합니다!(InvalidLotteryNumberException 포함)
```java
public InvalidMoneyException(String message)
```
대신 기본 생성자를 this가 아닌 super로

2021-01-13 16:13 UTC, choihwan2 commented on src/test/java/lotto/domain/LotteryUtilTest.java
>      @CsvSource({"0, 0", "999, 0", "1000, 1", "1001,1", "1999, 1", "2000 , 2"})
급하게 리팩토링하면서 놓친 부분들이 많이 있었네요.. 잘잡아주셔서 감사합니다.

2021-01-13 16:16 UTC, choihwan2 commented on src/main/java/lotto/domain/Lottery.java
> +        this(Arrays.stream(strings)
추가해보았습니다!

2021-01-13 16:19 UTC, choihwan2 commented on src/main/java/lotto/exception/InvalidMoneyException.java
> +    private static final String MSG_WRONG_MONEY_VALUE = "돈은 로또 가격보다 낮을 수 없습니다.";
꼼꼼한 리뷰 감사합니다.

2021-01-13 16:19 UTC, choihwan2 commented on src/main/java/lotto/domain/Money.java
> +        return money.value < LOTTERY_PRICE;
피드백 영상을 보다보니 그렇게 적혀있더라구요 ㅎㅎ

2021-01-13 17:22 UTC, choihwan2 commented on src/main/java/lotto/ui/Main.java
> +        lotteries.addRandomLotteries(autoLotteriesCount);
조금 많은 고민을 해보았는데, 여기서 뭔가 팩토리 디자인 패턴 처럼 찾다보니 인터페이스를 활용하는 경우에는 팩토리 패턴이 좋을 것 같지만 지금같이 그냥 로또들을 생성하는 것은 Lotteries의 생성자를 추가해서 해결하는것이 더 효율적이지 않을까?? 라는 생각을 하게 되었습니다.(팩토리를 만든다고 하더라도 결국 팩토리 내부에서 입력값을 받으면 Lottery 나 Lotteries의 생성자를 호출한후 반환하는 형식일 것 같았습니다.) 그래서 InputView 부분을 조금 다르게 수정해보았는데,`readManualLotteries()` 메소드 내부에서 객체를 생성하는 것이 아닌, 먼저 입력을 받고 그 입력값을 반환해준 후 Main 에서 추가한 생성자를 호출해서 만드는 것이 어떨까 였습니다.

이렇게 하다보니 InputView 에 있는 다른 객체를 반환하는 메소드들도 다 수정을 하는게 맞지 않을까라는 생각이 드는데 혹시 어떨까요?? 그리고 InputView 에 있는 출력 부분들도 OutputView 의 메소드들로 모두 빼는게 확실할까요?? 리팩토링을 하다보니 많은 고민이 들었습니다..🤔

2021-01-13 20:03 UTC, Hue9010 commented on src/main/java/lotto/domain/Money.java
> +        return money.value < LOTTERY_PRICE;
그걸 캐치해서 적용 해 주셨네요 👍 😏

2021-01-13 20:03 UTC, Hue9010 commented on src/main/java/lotto/ui/Main.java
> +        lotteries.addRandomLotteries(autoLotteriesCount);
로또를 지급해주는 객체라고 꼭 팩토리일 필요는 없습니다. 현실 세계에 비추어 판매점이 필요하다 생각되면 만들어 주시면 됩니다. 지금은 꼭 필요한 상황까지는 아니라 선택사항이라고 생각되네요. 생성과 관련된 추가 요구사항이 들어오면 만들 법 한데 알 수 없는 미래의 요구사항을 지나치게 고려할 필요는 없습니다. 게다가 이번 미션은 여기서 끝이란걸 확실히 알고 있는 상황이죠. 😉 

만드는 것도 중요하지만 지금처럼 고민하고 결정하는 과정 자체가 성장의 밑거름이 된답니다. 😄 

--------

> InputView 에 있는 다른 객체를 반환하는 메소드들도 다 수정을 하는게 맞지 않을까

[2단계 - 자동차 경주 리펙토링](https://edu.nextstep.camp/s/bb4PXLji/ls/W1LFM86E)의 MVC 그림 위 이런 문구가 있습니다.

> MVC 패턴 기반으로 리팩토링해 view 패키지의 객체가 domain 패키지 객체에 의존할 수 있지만, domain 패키지의 객체는 view 패키지 객체에 의존하지 않도록 구현한다.
![mvc](https://firebasestorage.googleapis.com/v0/b/nextstep-real.appspot.com/o/lesson-attachments%2F-L9D5L4Xj_6xjTfOTRks%2Fdomain.PNG?alt=media&token=5083069f-e922-4f0e-95a4-d3fb9fb95224)

view에서 domain 패키지에 의존하는 상황은 출력을 할 때도 있지만 입력 부에서도 허용을 한다고 생각합니다. 엄격히 따져서는 DTO를 활용하는게 맞다고 생각하지만 자바 콘솔 환경의  Input/output을 사용하고 있는 지금의 과정에서 view에 대한 경계를 정확히 구분짓기 어려운 감이 있어 이 부분은 view가 웹 페이지가 되는 웹 미션 때 좀더 신경 써주시는게 좋다고 생각돼요. 그런 면에서 지금도 충분히 InputView, OutputView를 잘 구분해 주셨다고 생각됩니다. 👍 

-----

> InputView 에 있는 출력 부분들도 OutputView 의 메소드들로 모두 빼는게 확실할까요?

View를 웹 페이지로 생각해보면 회원 가입 페이지에 순수하게 입력만 존재하지 않고 여러 출력이 같이 존재하죠? 그런 면에서 출력이 같이 존재해도 문제 없어 보입니다. 입력을 받기 위한 View라고 생각 해주세요. 😉

2021-01-13 20:09 UTC, Hue9010 approved these changes
피드백 반영 잘 해주셨네요! 👍👍
이번 단계는 여기서 머지하도록 할게요. 고생 하셨습니다! 
질문 주신 내용 답변 드렸는데 추가로 궁금하신 사항은 다시 질문 주시면 답변드리도록 할게요. 😉
혹시 제가 놓친 질문이 있다면 말씀주세요. 😋

다음 단계도 화이팅입니다!!

2021-01-13 20:09 UTC, merged