[yuni.code] 로또 미션 step2 PR입니다.
NewKrew2021/java-lotto-kakao pull request #48
Opened 2021-01-12 03:44 UTC by dsyun96

안녕하세요, yuni입니다.
로또 수동 기능을 추가로 구현하였습니다.

## 궁금한 점
- 로또 번호를 입력받고 나면 ", "로 split하고 Integer로 파싱해주는데, "1,2,3,4,5,6"처럼 붙여서 쓰는 경우도 고려해야 할까요?

2021-01-12 12:14 UTC, adeldel commented
한가지 아쉬운점이 `Result` (enum 상수집합)에서 로또등수에 따라 당첨금액과 함께 매치개수를 같이 관리하면 `mapResult` 메소드를 좀 개선해볼 수 있을것 같아요. 현재는 매치카운트 수를 조건절로 하여 `Result` 를 돌려주는데, 이 값도 상수값으로  관리하면 더 심플하게 변경가능 해 보입니다. 이와 함께 보너스 번호 포함여부도 갖을 수 있고요.
enum 클래스가 상수집합으로 잘 쓰이면 활용도가 더 높아질 것 같아요.
시도해보시다가, 잘 안풀리거나 시간 관계상 힘드시면 쿨하게 넘어가셔도 됩니다. 🙏 
참고해주세요~

2021-01-12 12:15 UTC, adeldel requested changes
안녕하세요 유니! 두번째 미션도 잘 수행해주셨습니다.
요구사항에 따라 잘 구현해주셨는데 아쉬운 점 몇가지가 보여 코멘트 남겨드렸어요.
확인해 보시고, 다시 리뷰요청 주시길 부탁드립니다. 
수고 많으셨어요! 👍 👍

2021-01-12 12:15 UTC, adeldel commented on src/main/java/lotto/view/InputView.java
>          } catch (IllegalArgumentException e) {
여기서 catch하는건 (IllegalArgumentException을 상속한) NumberFormatExcetion 일것 같아요. 
Exception의 상속구조를 보시면 도움이 되실 거예요. 보통은 하위의 Exception을 캐치해서 내가 정의한 exception이나 여기서처럼 IllegalArgumentException 같은 다른 exception으로 던지게 됩니다.
에러를 캐치해서 로깅만 하고 `throw e; ` 이렇게도 하구요. (아래처럼 수정은 안하고 참고만 하셔도 됩니다.)
```suggestion
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("금액 정보가 올바르지 않습니다.");
        }

2021-01-12 12:15 UTC, adeldel commented on src/main/java/lotto/LottoSimulationApp.java
>      public static void main(String[] args) {
main 함수에서는 로또게임을 수행해보기 위한 최소한의 로직만 남기고 컨트롤러를 생성해서 분리하는건 어떨까요? (요것도 필수는 아닙니다.)

2021-01-12 12:15 UTC, adeldel commented on src/main/java/lotto/domain/Lotto.java
> +        for (String number : text.split(", ")) {
Q. 로또 번호를 입력받고 나면 ", "로 split하고 Integer로 파싱해주는데, "1,2,3,4,5,6"처럼 붙여서 쓰는 경우도 고려해야 할까요?
A. 네 고려하는게 좋을것 같아요. 공백이 있든 없든 상관없이 처리되려면 여기서 split은 "," 로 변경하고 (String) number를 trim하면 어떨까요?

2021-01-12 12:15 UTC, adeldel commented on src/main/java/lotto/domain/Lottos.java
>      public static Lottos getInstance(int number) {
메소드명이 어색한것 같아요. 여기서는 의미가 나타나도록 `getAutoLottos` 같은 메소드명이 어떨까요?

2021-01-12 12:15 UTC, adeldel commented on src/main/java/lotto/view/OutputView.java
> +        System.out.println("수동으로 " + manualLottos.size() + "장, 자동으로 " + autoLottos.size() + "개를 구매했습니다.");
`manualLottos.size()  -> manualLottos.getLottos().size() `로 바꿀수 있을것 같습니다. size()메소드는 과하게 쪼갠거 아닌가 싶네요 😅

2021-01-12 12:15 UTC, adeldel commented on src/main/java/lotto/domain/Lottos.java
> +        List<Lotto> newLottos = new ArrayList<>(this.lottos);
lottos 를 미리 초기화 해두면 매번 arrayList로 생성하지 않아도 될것 같아요.

2021-01-13 08:35 UTC, dsyun96 commented
## 궁금한 점

- 3개 미만 매치의 경우 2, 1, 0개의 경우의 수가 있고 5개 매치 + 보너스 볼 일치가 아닌 경우는 보너스 볼이 일치 여부가 관계 없는 등 일관성 있는 규칙이 적용하기 어려워서 우선 Result enum 클래스에서 매치 개수만 인스턴스 변수로 추가하였습니다. 그 결과 mapResult 메서드도 깔끔하게 변경하지 못한 상황인데, 더 좋은 방법을 모르겠습니다 ㅜㅜ 어떻게 하면 좋을까요?
- 컨트롤러를 생성해서 분리하라는 말씀이 잘 이해가 가지 않습니다. 혹시 좀 더 자세히 알려주실 수 있나요?
- ```lottos 를 미리 초기화 해두면 매번 arrayList로 생성하지 않아도 될것 같아요.``` 라고 하셨는데, 이 부분도 잘 이해가 가지 않습니다. this가 가지고 있는 List<Lotto>와 인자로 받은 List<Lotto>를 합쳐서 새로운 Lottos 객체로 만들어주는게 목적인데, 더 좋은 방법이 있을까요? (지금은 static 메서드로 변경한 상태입니다)

2021-01-13 09:16 UTC, adeldel commented
질문 주신 내용 답변입니다.
- Q. 3개 미만 매치의 경우 2, 1, 0개의 경우의 수가 있고 5개 매치 + 보너스 볼 일치가 아닌 경우는 보너스 볼이 일치 여부가 관계 없는 등 일관성 있는 규칙이 적용하기 어려워서 우선 Result enum 클래스에서 매치 개수만 인스턴스 변수로 추가하였습니다. 그 결과 mapResult 메서드도 깔끔하게 변경하지 못한 상황인데, 더 좋은 방법을 모르겠습니다 ㅜㅜ 어떻게 하면 좋을까요?
- A. 요정도로도 충분할 것 같아요. enum 클래스는 상수집합이므로 좀더 활용했으면 하는 마음에 말씀드렸어요.
- Q. 컨트롤러를 생성해서 분리하라는 말씀이 잘 이해가 가지 않습니다. 혹시 좀 더 자세히 알려주실 수 있나요?
- A. Main함수는 input과 output을 출력하는 용도정도로만 쓰고 추후 API 로도 쓰일수 있도록 비즈니스 로직을 컨트롤러 클래스를 만들어 분리해보시면 좋을 것 같아 말씀드렸어요.  필수는 아니었어요.
- Q. lottos 를 미리 초기화 해두면 매번 arrayList로 생성하지 않아도 될것 같아요. 라고 하셨는데, 이 부분도 잘 이해가 가지 않습니다. this가 가지고 있는 List와 인자로 받은 List를 합쳐서 새로운 Lottos 객체로 만들어주는게 목적인데, 더 좋은 방법이 있을까요? (지금은 static 메서드로 변경한 상태입니다)
- A. lottos 멤버변수를 선언할때 미리 초기화해두면 다른 메소드에서 안해도 될거라는 얘기였어요.
 `private List<Lotto> lottos = new ArrayList<>();`

2021-01-13 09:21 UTC, adeldel approved these changes
안녕하세요 유니~ 로또미션 수행하느라 너무너무 고생많으셨습니다. 👏
step2는 여기서 머지할께요.
질문주신 사항은 댓글로 남겨드렸어요. 리뷰드린 내용이 도움이 되셨길 바랍니다.
남은 미션도 화이팅! 🎉

2021-01-13 09:21 UTC, merged