[mark.lim 임상진] 로또 step2 코드리뷰 요청드립니다.
NewKrew2021/java-lotto-kakao pull request #49
Opened 2021-01-12 04:10 UTC by limdef

안녕하세요 벨!

로또 step2 코드리뷰 요청드립니다.
이번에도 피드백 잘 부탁드리겠습니다.
감사합니다.

2021-01-12 10:12 UTC, limmmee-bonjour requested changes
안녕하세요 mark! 벨입니다 :)
2단계 미션도 잘 구현해주셨습니다 👍 👏 
잘 구현해주셔서 approve 해도 되겠지만, controller에서 관심사를 조금 더 분리해보는 연습을 해보면 좋을 것 같아 request change 드렸습니다! 궁금하신 사항이 있으시면 DM 주세요 :)

2021-01-12 10:12 UTC, limmmee-bonjour commented on src/main/java/controller/LottoController.java
> +        Amount amount = LottoInputView.inputAmount();
Amount를 리턴하도록 반영해주셨네요 👍

2021-01-12 10:12 UTC, limmmee-bonjour commented on src/main/java/controller/LottoController.java
> +        LottoTickets lottoTickets = manualTickets.concat(autoTickets);
[ 도전! ] Input 데이터를 의존성 주입받아 LottoTickets를 만드는 팩토리 클래스를 만들어보는 것은 어떨까요?
컨트롤러가 좀 더 심플해질 것 같고 관심사가 하나로 모아질 것 같습니다 :)
중간레이어의 데이터가 필요하다면 DTO를 만들어도 좋을 것 같고요!

2021-01-12 10:12 UTC, limmmee-bonjour commented on src/main/java/domain/Lotto.java
> +    private final Set<LottoNumber> numbers;
Set으로 잘 반영해주셨어요 👏

2021-01-12 10:12 UTC, limmmee-bonjour commented on src/main/java/view/LottoInputView.java
> +        System.out.println("수동으로 구매할 번호를 입력해주세요.");
수동 로또 번호에 중복데이터가 있다면 에러가 발생하는데 이것도 validation 처리하는것이 좋아보입니다 :)

2021-01-12 10:12 UTC, limmmee-bonjour commented on src/main/java/domain/LottoTicketCount.java
> +public class LottoTicketCount {
현재 이 도메인은 DTO로밖에 사용되어지고 있지 않은 것 같은데 의도를 좀 더 명확히 하면 좋을것 같습니다!
수동/자동 Count를 가지고 있거나 위 의견드린대로 팩토리를 위한 DTO로 용도를 변경해도 좋을 것 같아요 :)

2021-01-12 16:10 UTC, limdef commented on src/main/java/view/LottoInputView.java
> +        System.out.println("수동으로 구매할 번호를 입력해주세요.");
수동 로또 번호 입력을 마치면  Lotto.from을 통해 중복 번호가 있으면 에러가 발생합니다..!

2021-01-12 16:15 UTC, limdef commented
안녕하세요 벨! 

피드백 감사드립니다 :) 👍 
LottoTicketCount를 DTO 용도로 사용하고, LottoTicketsFactory 클래스를 만들어
controller를 좀 더 심플하게 해보았습니다!

2021-01-13 01:13 UTC, limmmee-bonjour approved these changes
안녕하세요 mark! 벨입니다 😄 
(제가 욕심을 좀 냈는데^^) 피드백 드린 부분 빠르게 잘 반영해주셨네요 👍 
코드가 처음보다 많이 좋아졌어요 💯  👏 👏 
이번 로또 미션 진행하시느라 고생 많으셨습니다!!
궁금하신점이 있으시면 언제든 DM 보내주세요! 다음 미션도 화이팅이예요 :)

2021-01-13 01:13 UTC, merged