[pavlo.v 최환] 로또 1단계 코드리뷰 부탁드립니다.
NewKrew2021/java-lotto-kakao pull request #5
Opened 2021-01-07 13:42 UTC by choihwan2

원시 값,문자열 포장, 일급콜렉션 그리고 등수에 따라 알맞은 출력을 위해서 많이 고민했던 것 같습니다.
`convertCountToRank` 라는 메소드를 리팩토링 하면서 어떻게 하면 한번의 for문에서 2등과 3등을 쉽게 구별할 수 있을까..? 하면서 TDD의 도움을 많이 받은 것 같습니다. 
메소드 내용을 변경하고 테스트를 계속해서 돌려가면서 한 경험이 값졌던 것 같습니다.

강한 피드백 부탁드립니다!

2021-01-07 19:48 UTC, Hue9010 requested changes
안녕하세요. 이번 리뷰를 맡은 휴입니다. 😄 
코드도 깔끔하고 객체 분리도 굉장히 잘해주셨네요. 거기다 커밋 로그까지 👍  
피드백 남겨드린 사항중 Enum은 꼭 적용해보시길 바랍니다!
궁금하신 사항 있으면 편히 문의주세요~!!

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/lotto/domain/LotteryNumber.java
> +            "로또 번호는 %d와 %d 사이의 수여야 합니다.", MIN_LOTTERYNUMBER, MAX_LOTTERYNUMBER);
`로또 번호는 1와 45 사이의 수여야 합니다.`라고 하면 될 것 같은데 약간 과도해 보입니다. 🤔

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/lotto/domain/LotteryNumber.java
> +            throw new IllegalArgumentException(MSG_WRONG_LOTTERYNUMBER_RANGE);
exception을 잘 사용해 주셨는데 한번 이 부분만 custom exception을 만들어 보세요.😉

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/lotto/ui/Main.java
> +        int profit = LotteryUtil.calculateProfitRate(lotteryCount, lotteryRank.getTotalIncome());
수익률 계산을 Util을 사용하지 않고 LotteryRank에서 할 수 있을 것 같네요. 게임 결과를 책임지는 객체로 Rank를 만든게 맞을까요? 그렇다면 결과에 대한 처리는 Rank가 가지게 해주세요.

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/lotto/domain/LotteryUtil.java
> +    };
[Enum 활용사례 3가지](https://jojoldu.tistory.com/137)
Line 51까지 포함해서 Enum을 활용 할 수 있을 것 같아요. 이줄 배열은 사용하기도 힘들고 보는사람도 괴로운 관계로 지양하는게 좋아요.  🙄

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/lotto/domain/LotteryUtil.java
> +    }
LottoNumber를 잘 만들어주셨는데 money 마찬가지로 Money를 만들어 보세요. 😉

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/lotto/ui/InputView.java
> +        return new LotteryNumber(lotteryNumber);
Exception이 발생하지 않았을 때만 도달할 수 있는 return 이라면 try안에 넣어주는게 좋습니다.

```java
        try {
            int lotteryNumber = Integer.parseInt(sc.nextLine().trim());
            return new LotteryNumber(lotteryNumber);
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("정상적인 정수 포맷을 입력하세요.");
        }
```
이렇게 되면 정상적인 입력일때만 LotteryNumber를 반환한다는 걸 알 수 있죠. 😉

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/lotto/domain/Lotteries.java
> +        List<Lottery> lotteryList = new ArrayList<>();
가능하면 변수명에 List, Set, Int, Float 등 타입을 넣지 않는게 좋습니다. 이후에 이름이나 타입을 바꾸기가 어려워 집니다. 나중에 List<Lottery>가 아닌 Set을 사용하게 되면 lotterySet으로 변경을 해줘야 합니다. 그렇다고 이름을 바꾸지 않으면 아래와 같은 혼종이 발생합니다. 😱
```java
Int phoneString;
```

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/lotto/domain/Lotteries.java
> +        }
Line 22 ~ 24의 반복문은 각 등수별 초기 값을 세팅하기 위해 존재하는게 맞을까요? 그렇다면 Map이 put, get 외에도 몇가지 유용한 기능이 있는데 한번 확인해보세요. 😉

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/lotto/domain/LotteryRank.java
> +    HashMap<Integer, Integer> lotteryRank;
Lotteries에선 List<Lotter>로 선언하셨는데 ArrayList가 아닌 List로 하신 이유가 뭘까요? 🤔 
그리고 접근 제어자가 빠졌습니다. 😉

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/lotto/domain/Lotteries.java
> +public class Lotteries {
LotteryNumber로 int를 직접 안쓰시는 것도 그렇고 일급 컬렉션까지 잘 사용하셨네요. 👍

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/lotto/domain/Lotteries.java
> +public class Lotteries {
한가지 질문! 파블로라고 부르면 될까요? 아니라면 알려주시면 좋을 것 같아요. 😋

2021-01-07 19:48 UTC, Hue9010 commented on README.txt
> +# 로또
md 파일과 txt 파일을 같이 관리하셨는데 따로 두신 이유가 있나요? 🤔

2021-01-07 19:48 UTC, Hue9010 commented on README.md
> +- [x] 0 로또 번호를 랩핑하는 LotteryNumber class 구현
체크 박스 👍

2021-01-07 19:48 UTC, Hue9010 commented on src/test/java/lotto/domain/LotteryAnswerTest.java
> +import lotto.domain.LotteryAnswer;
[[IntelliJ] intellij 유용한 단축키 정리](https://gmlwjd9405.github.io/2019/05/21/intellij-shortkey.html)
Import 정리하기 (Optimize Imports)
MacOS: Ctrl + Opt + o
Win/Linux: Ctrl + Alt + o
자동 설정: [Find Action] -> Optimize imports on 입력 -> “Auto import: …”

2021-01-07 19:48 UTC, Hue9010 commented on src/test/java/lotto/domain/LotteryAnswerTest.java
> +    }
정상 케이스 뿐만 아니라 잘못 된 입력이 들어올 때까지 꼼꼼히 테스트 해주셨네요. 👍

2021-01-07 19:48 UTC, Hue9010 commented on src/test/java/lotto/domain/LotteryNumberTest.java
> +    }
정상 값의 경계에서 테스트 👍👍

2021-01-07 19:48 UTC, Hue9010 commented on src/test/java/lotto/domain/LotteryTest.java
> +    void Lottery_당첨_6개일치_1등() {
참고로 @DisplayName을 사용하면`_` 없이 띄어 쓰기를 사용할 수 있답니다. 😉

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/lotto/domain/LotteryUtil.java
> +    public static final int FIRST_PRIZE = 2000000000;
[Underscores in Numeric Literals](https://docs.oracle.com/javase/8/docs/technotes/guides/language/underscores-literals.html)
의외로 자바7부터 추가된 기능입니다. 😉

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/lotto/domain/LotteryUtil.java
> +    };
Enum을 사용하면 계산부분이 꽤나 바뀔걸로 예상돼서 이번 피드백에서는 자세하게 다루지는 않을게요. 🙏

2021-01-08 03:28 UTC, choihwan2 commented on src/main/java/lotto/domain/LotteryNumber.java
> +            "로또 번호는 %d와 %d 사이의 수여야 합니다.", MIN_LOTTERYNUMBER, MAX_LOTTERYNUMBER);
후에 혹시 '로또번호가 1부터가 아니라 n부터 m까지 리팩토링 하기 복잡하겠지..?' 라고 생각하면서 작성했던 부분인데 '로또' 라는 게임이 정해져있기 때문에 과도한게 맞는것 같네요 수정하도록 하겠습니다!

2021-01-08 03:57 UTC, choihwan2 commented on src/main/java/lotto/domain/LotteryNumber.java
> +            throw new IllegalArgumentException(MSG_WRONG_LOTTERYNUMBER_RANGE);
커스텀 Exception을 만들어 적용해보았습니다! 적용하면서 발견하지 못했던 예외상황들도 좀 더 처리할 수 있었습니다.

2021-01-08 06:46 UTC, choihwan2 commented on src/main/java/lotto/domain/LotteryUtil.java
> +    };
가장 많이 고민했던 부분인데 enum을 활용해서 리팩토링 해보도록 하겠습니다!! 피드백 감사합니다

2021-01-08 06:49 UTC, choihwan2 commented on src/main/java/lotto/domain/LotteryUtil.java
> +    public static final int FIRST_PRIZE = 2000000000;
이런 방법도 있었군요.. 보기 더 좋아질것 같네요😊😊 감사합니다!!

2021-01-08 06:49 UTC, choihwan2 commented on src/test/java/lotto/domain/LotteryAnswerTest.java
> +import lotto.domain.LotteryAnswer;
매번 하나씩 찾아가면서 했었는데.. 감사합니다!!

2021-01-08 09:45 UTC, choihwan2 commented on src/main/java/lotto/ui/Main.java
> +        int profit = LotteryUtil.calculateProfitRate(lotteryCount, lotteryRank.getTotalIncome());
게임 결과를 전체를 책임지는 것 보다는 로또 순위들의 결과 값들을 HashMap으로 갖게 만들어보았는데 그걸 감싸고 있는 일급 콜렉션을 생각하면서 작성한게 LotteryRank 클래스 였습니다. 그래서 LotteryRank 안에 있는 HashMap 을 사용하는 메소드들만 갖게 하고싶어서 수익률 계산을 LotteryUtil 이 갖게 만든건데 제 생각이 잘못된 걸까요??

2021-01-08 09:53 UTC, choihwan2 commented on README.txt
> +# 로또
작성을 하면서 Code with me 에서 .md 파일을 확인할 수가 없어서 만들어서 서로 확인을 했었습니다!

2021-01-08 09:54 UTC, choihwan2 commented on src/main/java/lotto/domain/Lotteries.java
> +public class Lotteries {
파블로가 맞습니다!

2021-01-08 09:54 UTC, choihwan2 commented on src/main/java/lotto/domain/Lotteries.java
> +        List<Lottery> lotteryList = new ArrayList<>();
헙.. 이걸 확인을 못했었네요 좀 더 수정하도록 하겠습니다.

2021-01-08 10:24 UTC, choihwan2 commented on src/test/java/lotto/domain/LotteryTest.java
> +    void Lottery_당첨_6개일치_1등() {
@DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class) 요걸 활용해서 로그창에서 `_` 없이 띄어 쓰기로 보이도록 해보았습니다!

2021-01-08 16:58 UTC, Hue9010 approved these changes
피드백 반영 잘해주셨네요. 👍
이번 단계는 여기서 머지할게요. 질문에 대한 답변과 피드백 참고해서 다음 단계 진행해 주세요.
고생하셨어요! 👏

2021-01-08 16:58 UTC, Hue9010 commented on src/main/java/lotto/domain/LotteryRank.java
> +        return lotteryRank.getOrDefault(nthRank, 0);
getOrDefault 👍

2021-01-08 16:58 UTC, Hue9010 commented on src/main/java/lotto/domain/LotteryRank.java
> +    HashMap<LotteryPrize, Integer> lotteryRank;
접근 제어자가 빠졌네요!

2021-01-08 16:58 UTC, Hue9010 commented on src/main/java/lotto/domain/LotteryRank.java
> +            total += (long) prize.getRewardMoney() * getnthCount(prize);
rewardMoney에 대한 계산은 LotteryPrize한테 메시지를 보낼 수 있을 것 같네요. 😉

2021-01-08 16:58 UTC, Hue9010 commented on src/main/java/lotto/domain/LotteryPrize.java
> +    }
OutputView Line 19~23
```java
        Arrays.stream(LotteryPrize.values()).
                filter(lotteryPrize -> lotteryPrize != LotteryPrize.NONE).
                forEach(lotteryPrize -> System.out.println(lotteryPrize.makeLotteryPrizeMessage(lotteryPrize) +
                        lotteryRank.getnthCount(lotteryPrize) + "개"));
    }
```

사용되고 있는 곳을 봐도 prize를 받을 필요가 있을까요? 🤔

2021-01-08 16:58 UTC, Hue9010 commented on src/main/java/lotto/domain/Lottery.java
> +        return LotteryUtil.convertCountToRank(count, bonus);
LotteryPrize를 바로 사용하지 않고 LotteryUtil을 거치는 이유가 있나요? 🤔

2021-01-08 16:58 UTC, Hue9010 commented on src/main/java/lotto/ui/Main.java
> +        int profit = LotteryUtil.calculateProfitRate(lotteryCount, lotteryRank.getTotalIncome());
👌 Rank를 어떻게 정의하냐에 따라 다를 것 같네요. 제안드렸던 이유는 크게 두가지로 첫 번째로 저는 결과에 금액도 포함하여 생각하여 수익률 계산까지 충분히 가능하다고 생각했습니다. 이 부분은 누가 맞다/틀리자가 아니기 때문에 파블로가 생각해주신 것 처럼 LotteryRank에 없어도 될 것 같습니다. 👍

두번째는 저는 Util을 만들어 사용하는걸 지양하는 편입니다. 

[OOP Alternative to Utility Classes](https://www.yegor256.com/2014/05/05/oop-alternative-to-utility-classes.html)
[OOP Anti-Patterns: Utility or Helper Classes](https://ralin.io/blog/oop-anti-patterns-utility-or-helper-classes.html)
[Avoid Utility Classes](https://www.vojtechruzicka.com/avoid-utility-classes/)

위 아티클들은 내용이 많으니 개인적으로 선호하지 않는 단순한 사유를 말씀드리자면 **OOP Anti-Patterns: Utility or Helper Classes** 아티클 중간에 언급 된 `Why are utility classes so evil?`의  1, 2때문입니다. 
1. **They tend to become quite large quite quickly**
어디에 추가할 지 확실치 않은 기능이 생기면 Util 클래스에 몰기 시작하면서 생각보다 빠르게 방대해집니다.
2. **They group functions that are not related at all (low cohesion)**
그러면서 자연스럽게 서로 연관 없는 기능들이 한 클래스에 들어갑니다. 지금도 LotteryUtil라고 네이밍을 하셨는데 로또 프로젝트인걸 고려했을 때 만능 클래스로 프로젝트 내 아무 기능이나 이 클래스가 담당 할 수 있다는 의미입니다.

첫번째 pr을 보내기 전의 LotteryUtil을 봤을 때 위 상황대로 흘러가지 않았을까 생각 들었습니다. 따로 피드백을 드리지 않은 이유는 직접적으로 표현을 안했을 뿐 피드백이 Util에 몰려있었던걸 알 수 있습니다. 그리고 Enum을 적용하면 많이 해소될 걸로 보였고 실제로도 잘 해주셨습니다. 👍

그렇다고 Util을 사용하지 않는건 아닙니다. 어디까지나 직접 만들어 사용하지 않을 뿐 StringUtils 등등 잘 사용하고 있습니다. 😋 유틸을 만든다면 프로젝트 명과 동일하게 만들지말고 제공하려는 부수적인 기능에 맞춰 이름을 지어주세요.

유틸에 대한 생각은 아티클에도 있다시피 서로 의견이 다를 수 있는점은 참고해주세요.

2021-01-08 16:58 UTC, Hue9010 commented on src/main/java/lotto/ui/Main.java
> +        int profit = LotteryUtil.calculateProfitRate(lotteryCount, lotteryRank.getTotalIncome());
유틸에 대해서는 한번 생각해보고 수정이 필요할 부분이 있다싶으면 수정하고 아니라면 이런 의견이 있다고 참고만 해주셔도 될 것 같습니다. 😉

2021-01-08 16:58 UTC, Hue9010 commented on src/test/java/lotto/domain/LotteryTest.java
> +    void setUp() {
이제보니 테스트 쪽엔 접근 제어자가 누락되어 있네요.

2021-01-08 16:58 UTC, Hue9010 commented on src/test/java/lotto/domain/LotteryTest.java
> +    void Lottery_당첨_6개일치_1등() {
앗! 이건 저도 몰랐는데 덕분에 배워가네요. 👍

2021-01-08 16:58 UTC, Hue9010 commented on src/main/java/lotto/domain/LotteryPrize.java
> +    }
다형성을 가지게 개선 가능할 것 같네요.

2021-01-08 16:58 UTC, Hue9010 commented on src/main/java/lotto/domain/LotteryPrize.java
> +public enum LotteryPrize {
잘하셨습니다!! 💯 
예상보다 빠르게, 깔끔히 적용해주셨어요. 👍 

잠깐 어제의 이중배열을 다시한번 보죠. 비교해서 보면 어마어마하게 개선하신걸 눈치 채실 수 있을겁니다. 😉

```java
public class LotteryUtil {
    public static final int LOTTERY_PRICE = 1000;
    private static final int CHECK_BONUS = 1;
    private static final int NOT_CHECK_BONUS = 0;

    public static final int FIRST_PRIZE = 2000000000;
    public static final int SECOND_PRIZE = 30000000;
    public static final int THIRD_PRIZE = 1500000;
    public static final int FOURTH_PRIZE = 50000;
    public static final int FIFTH_PRIZE = 5000;

    public static final int[][] WINNING_TABLE = {
            {3, FIFTH_PRIZE, 5, NOT_CHECK_BONUS},
            {4, FOURTH_PRIZE, 4, NOT_CHECK_BONUS},
            {5, THIRD_PRIZE, 3, NOT_CHECK_BONUS},
            {5, SECOND_PRIZE, 2, CHECK_BONUS},
            {6, FIRST_PRIZE, 1, NOT_CHECK_BONUS}
    };

    public static final String[] WINNING_MSG = {
            WINNING_TABLE[0][0] + "개 일치 (" + WINNING_TABLE[0][1] + "원)-",
            WINNING_TABLE[1][0] + "개 일치 (" + WINNING_TABLE[1][1] + "원)-",
            WINNING_TABLE[2][0] + "개 일치 (" + WINNING_TABLE[2][1] + "원)-",
            WINNING_TABLE[3][0] + "개 일치, 보너스 볼 일치 (" + WINNING_TABLE[3][1] + "원)-",
            WINNING_TABLE[4][0] + "개 일치 (" + WINNING_TABLE[4][1] + "원)-"
    };

    public static int convertCountToRank(int count, boolean bonus) {
        for (int i = WINNING_TABLE.length - 1; i >= 0; i--) {
            if (WINNING_TABLE[i][0] == count && WINNING_TABLE[i][3] == CHECK_BONUS && bonus) {
                return WINNING_TABLE[i][2];
            }
            if (WINNING_TABLE[i][0] == count && WINNING_TABLE[i][3] == NOT_CHECK_BONUS) {
                return WINNING_TABLE[i][2];
            }
        }
        return Lottery.NONE;
    }
}

```

2021-01-08 16:58 UTC, merged

2021-01-08 17:02 UTC, Hue9010 commented on src/test/java/lotto/domain/LotteryAnswerTest.java
> +import lotto.domain.LotteryAnswer;
한가지 조심할게 자동 설정을 하면 프로젝트 전체에 적용이 되어 처음 킨 프로젝트는 어마무시하게 많은 파일이 변경되는 걸 볼 수 있답니다. 그리고 
```java
import java.util.Arrays;
import java.util.Map;
```

```java
import java.util.*;
```
위에서 아래로, 아래서 위로 바뀌면서 파일이 변경되기도 합니다. 😱
그래서 개인 작업 할때는 상관 없는데 팀 프로젝트 할 때는 살짝 유의해 주세요.

2021-01-11 06:11 UTC, choihwan2 commented on src/main/java/lotto/domain/Lottery.java
> +        return LotteryUtil.convertCountToRank(count, bonus);
리팩토링을 하면서 LotteryUtil 을 거치지 않더라도 가능한 형태가 되었네요! 수정하겠습니다!

2021-01-11 06:12 UTC, choihwan2 commented on src/main/java/lotto/domain/LotteryPrize.java
> +public enum LotteryPrize {
enum의 강력함을 알 수 있었던 것 같네요. 뭔가 보기에도 훨씬 깔끔해진 것 같습니다! 감사합니다

2021-01-11 06:20 UTC, choihwan2 commented on src/main/java/lotto/domain/LotteryRank.java
> +            total += (long) prize.getRewardMoney() * getnthCount(prize);
좀 더 객체지향적으로 코드를 작성할 수 있겠군요!

2021-01-11 06:21 UTC, choihwan2 commented on src/test/java/lotto/domain/LotteryTest.java
> +    void setUp() {
앗 수정하도록 하겠습니다.

2021-01-11 06:29 UTC, choihwan2 commented on src/main/java/lotto/ui/Main.java
> +        int profit = LotteryUtil.calculateProfitRate(lotteryCount, lotteryRank.getTotalIncome());
좋은 리뷰 너무너무 감사드립니다. 생각해보니 정말 맞는 말이네요 Util이라는 이름을 붙이고 정말 어떤 메소드라도 사용가능하게 하는 것은 후에 이 프로젝트가 커지거나 할 경우 정말 안좋은 습관이였던 것 같네요. StringUtils 처럼 어떤 역활을 한정적으로 수행하는 경우에만 사용하도록 하겠습니다! 다음 리뷰전에 유틸에 있는 기능을 가능하면 다른 클래스를 만들거나 위임하는 것이 더 좋다고 저도 생각이드네요. 감사합니다!!😊😊

2021-01-11 06:39 UTC, choihwan2 commented on src/main/java/lotto/domain/LotteryPrize.java
> +    }
놓칠수 있는 부분이였던 것 같은데 꼼꼼한 리뷰 감사드립니다.. 수정하였습니다!

2021-01-11 06:49 UTC, choihwan2 commented on src/test/java/lotto/domain/LotteryAnswerTest.java
> +import lotto.domain.LotteryAnswer;
사소한 팁 감사합니다!

2021-01-11 06:55 UTC, choihwan2 commented on src/main/java/lotto/domain/LotteryRank.java
> +    HashMap<Integer, Integer> lotteryRank;
자바에서 List에 관련된 컬렉션을 사용할때 List로 하게 되면 후에 ArrayList => LinkedList나 다른 리스트 형태로 리팩토링을 하게 되거나 하는 경우에 인터페이스 이기 때문에 더 편리하다고 들었던 것 같습니다. 그런데 이번같은 경우 한정적인 상황으로 ArrayList라도 딱 규정해놓는 것이 좋았을까요???

2021-01-11 06:56 UTC, choihwan2 commented
리뷰 너무너무 감사합니다. 후에 코드짤때도 많은 도움이 될 것 같네요. 특히나 Util 클래스에 대한 조언은 특히나 감사합니다!

2021-01-11 10:32 UTC, Hue9010 commented on src/main/java/lotto/domain/LotteryRank.java
> +    HashMap<Integer, Integer> lotteryRank;
넵, 특정 구현에 종속되지 않게 List로 사용해주시는게 좋습니다. 제가 질문을 살짝 잘못했네요. 😋 이 라인에서 코멘트를 단 이유는 lotteryRank는 Map이 아닌 HashMap으로 선언을 해주셔서 그렇습니다. 😉