[turner.lee] 로또 step2 리뷰 부탁드립니다.
NewKrew2021/java-lotto-kakao pull request #50
Opened 2021-01-12 05:22 UTC by sumniy

안녕하세요 휴 🤗
남겨주신 피드백 반영하고 step2 구현 완료했습니다. 
리뷰 잘 부탁드립니다!

2021-01-12 14:11 UTC, Hue9010 requested changes
잘해주셨네요. 👍
머지하기엔 몇가지 아쉬운 부분이 있어서 코멘트 남겼어요. 
확인하시고 궁금한 부분 있으면 질문주세요! 😉

2021-01-12 14:11 UTC, Hue9010 commented on src/main/java/domain/LottoNumber.java
> +  public static LottoNumber of(Integer number) {
of에다 기본 생성자는 private 👍

2021-01-12 14:11 UTC, Hue9010 commented on src/test/java/domain/LottoNumberTest.java
> +    assertThat(lottoNumber == LottoNumber.of(1)).isTrue();
캐싱 테스트까지 👍

2021-01-12 14:11 UTC, Hue9010 commented on src/main/java/domain/LottoTicket.java
> +    return of(Arrays.stream(Optional.ofNullable(lottoNumber)
발생시키는 Exception이 NPE이긴 하지만 Objects에 requireNonNull도 있답니다.
```java
Objects.requireNonNull(lottoNumber, "message");
```

2021-01-12 14:11 UTC, Hue9010 commented on src/main/java/controller/LottoController.java
>    }
LottoService의 역할을 어떻게 정하신건지 알 수 있을까요? 🤔
별도 메서드로 추출하신걸 보면 생각보다 많은 작업을 여기서 한다고 생각하셨다고 보네요. 그러면 View, Model을 연결해주는 Controller의 역할을 벗어난게 아닐지 생각해 볼 수 있을 것 같아요.

우선 LottoService가 없다는 가정하에 객체지향이 현실세계를 모방한다는 걸 생각하면 `수동으로 선택한 번호들`과 `자동 구매 갯수`, `구매 금액`을 주고 판매점에 로또를 구매하는 것 처럼 판매점의 역할을 할 객체를 만들어주면 어떨까요?

2021-01-12 14:11 UTC, Hue9010 commented on src/main/java/domain/LottoTickets.java
>  public class LottoTickets {
```java
  private int getRank(int matchedCount, boolean matchedBounus) {
    if (matchedCount == LottoTicket.LOTTO_NUMBERS_LENGTH) {
      return 1;
    }

    if (matchedCount == LottoTicket.LOTTO_NUMBERS_LENGTH - 1 && matchedBounus) {
      return 2;
    }

    if (matchedCount > 2) {
      return LottoTicket.LOTTO_NUMBERS_LENGTH - matchedCount + 2;
    }

    return 0;
  }
```

이 부분 숫자 값이아니라 LottoRank에서 matchedCount와 matchBounus를 통해 알맞은 LottoRank를 찾게 개선 할 수 있을 것 같네요.

2021-01-13 01:31 UTC, sumniy commented on src/main/java/controller/LottoController.java
>    }
Controller는 로또가 진행되는 흐름을 책임지게하고 거기서 로또 티켓을 생성하는 부분들을 Service로 분리했습니다. 
수동, 자동 로또 생성에 대한 로직을 따로 관리하려고 이렇게 했는데, 이게 Service의 역할에는 맞지 않는 것일까요?

2021-01-13 02:30 UTC, sumniy commented on src/main/java/controller/LottoController.java
>    }
다시 생각해보니 로또 티켓 생성은 Service로 생각하기보다는 컨트롤러가 가지거나 LottoTicketGenerator와 같이 관리하는게 맞는 것 같기도 합니다 🤔

2021-01-13 04:26 UTC, Hue9010 commented on src/main/java/controller/LottoController.java
>    }
사실 가장 큰 핵심은 Service의 명칭이 약간은 모호합니다. Spring의 Service layer를 의식한 네이밍이 아닐까 생각되네요. 그래서 Service가 로또의 생성에 대해서만 관리하는 걸 고려한건지 그 이상의 의미를 담고 있는지 문의 드렸던 겁니다. 의견 주신 것 처럼 LottoService보다는 LottoTicketGenerator가 좋을 것 같습니다. 👍 

제가 드린 예시의 상황은 Service에서 담당을 수행을 해주고 있으니 고려치 말아 주세요. 네이밍만 생각하면 될 것 같습니다.😭 🙏  `List<String> -> List<LottoNumber>`이 여기서 이뤄진다고 잘못 봤네요. 😱

2021-01-13 04:53 UTC, sumniy commented on src/main/java/controller/LottoController.java
>    }
아하 알겠습니다 🤗

2021-01-13 07:50 UTC, sumniy commented
피드백 반영했습니다. 리뷰 부탁드립니다. 🙇‍♂️

2021-01-13 11:41 UTC, Hue9010 approved these changes
피드백 잘 반영해주셨네요. 👍
이번 미션은 여기서 마무리하도록 할게요.
추가로 궁금한 사항 있으면 언제든 질문해주세요.
고생하셨습니다. 다음과제도 화이팅입니다!

2021-01-13 11:41 UTC, Hue9010 commented on src/main/java/domain/LottoRank.java
> +  private final int matchCount;
matchCount  👍

2021-01-13 11:41 UTC, merged

2021-01-14 03:45 UTC, sumniy commented
감사합니다!