[kuri.copper] 로또 step2 코드리뷰 요청드립니다.
NewKrew2021/java-lotto-kakao pull request #52
Opened 2021-01-12 06:19 UTC by D-kuri

이전에 해주셨던 피드백들과 예외처리, 수동 로또 기능 추가하였습니다.

지금까지의 작업을 하면서 궁금한점이 생겼습니다 !
지금까지 진행하면서 니오가 크게 언급해주셨던 LottoResults , LottoTickets 모두 단일 책임 원칙에 따라 생성하는 부분과 DTO와 같은 데이터를 전달하는 부분으로 나누기 위한 피드백을 주셨다고 생각합니다 : ) 객체를 다룬다는 관점에서 두개의 객체 모두 해당 객체들을 관리한다고 본다면 하나의 책임을 가지고 있다고 볼수 있지 않을까? 라는 생각이 들었는데 단일 책임 원칙을 적용할때 어느 정도의 레벨까지 적용해야 하는지 묻고 싶습니다 !

2021-01-12 06:37 UTC, sehan commented
@D-kuri conflicts 이 발생했네요. ^^  먼저 resolve 해주세요

2021-01-12 07:28 UTC, sehan commented
> 지금까지의 작업을 하면서 궁금한점이 생겼습니다 !
> 지금까지 진행하면서 니오가 크게 언급해주셨던 LottoResults , LottoTickets 모두 단일 책임 원칙에 따라 생성하는 부분과 DTO와 같은 데이터를 전달하는 부분으로 나누기 위한 피드백을 주셨다고 생각합니다 : ) 객체를 다룬다는 관점에서 두개의 객체 모두 해당 객체들을 관리한다고 본다면 하나의 책임을 가지고 있다고 볼수 있지 않을까? 라는 생각이 들었는데 단일 책임 원칙을 적용할때 어느 정도의 레벨까지 적용해야 하는지 묻고 싶습니다 !

우선 지금 진행하고 있는 미션은 훈련과정이기때문에 최대한 객체를 작게 만들고 책임을 나눌수 있다면 최대한 나누어서 새로운 객체로 책임을 분할하는것을 목표로 하고 있습니다. 우리가 이정도면 괜찮겠지 하고 생각하는 것 보다 더 적극적으로 나누고 있습니다.
 제가 객체에 SRP 를 적용하는 원칙은 해당 객체가 제공해야 하는 매소드인가?  매소드가 여러가지 기능을 하고 있는가? 를 중요하게 봅니다. 그에 따라 메소드를 다른 객체로 이동하거나 매소드의 일부기능을 다른객체에게 넘겨주거나 매소드를 분할 합니다. 
 그리고 단위테스트를 작성하다 보면 테스트가 복잡해지거나 테스트준비를 위해 많은 객체들을 준비시켜야 할때 해당 객체가 많은 책임을 가지고 있는지 확인하고 책임을 분리합니다. 
 적고 보니 원론적이네요. 딱 여기까지 입니다. 라고 말할 수 있는 명제는 없네요 : ( 
하지만, 이런 원칙으로 코드를 분할해 나가고 코드를 개선해 나가는 것이 SRP 라고 생각합니다. 한번에 모든책임을 완벽하게 분리하는것이 아니라 지속적으로 개선해 나가는 과정이 중요하다고 생각합니다. 
 정확한 해답은 아니지만 원하는 답을 찾는데 조금이나마 도움이 되었기를 바랍니다. 😄

2021-01-12 08:24 UTC, sehan requested changes
step2 미션을 빠르게 PR 주셨네요 😉
피드백도 잘 반영해주셨습니다. 👏👏👏


몇가지 보강할 사항이 있어서 Request changes 합니다.

* 다만, 단위테스트에 보강이 필요한 부분이 좀 있습니다. 
* 몇몇 메소드에는 기능에 맞게 네이밍을 다시 고민해 볼 필요가 있습니다.
* 수동로또 구매기능이 요구사항과 다른 부분이 있습니다. 
    * 구매금액 내에서 수동로또를 구매할 수 있고 구매후 남은 금액으로 자동로또를 구매해야 합니다. 
    * 현재 구현에서는 구매금액으로 자동로또를 모두 구매하고 수동로또는 무료(?) 로 구매하고 있습니다. 

관련 코멘트 확인 부탁드려요~ ☺️

2021-01-12 08:24 UTC, sehan commented on src/main/java/lotto/domain/CreateLottoResults.java
> +    public static Map<LottoRank, Integer> createLottoResults(List<LottoTicket> lottoTickets, WinningNumber winningNumber){
return 으로 LottoResults 객체가 돌려줘야 할거 같은 이름입니다. 😓
기능에 맞는 이름으로 이름을 변경해주세요

2021-01-12 08:24 UTC, sehan commented on src/test/java/lotto/CreateLottoResultsTest.java
> +public class CreateLottoResultsTest {
CreateLottoResults 는 로또순위별 당첨된로또수 Data 를 만들어 주는 static method 를 제공하고 있습니다.
LottoResults 객체가 생성되는 테스트는 LottoResultsTest 로 이동시켜 주세요 
그리고 여기에는 로또순위별 당첨된로또수 Data 가 잘 만들어 지는지 테스트코드를 작성해 주세요

2021-01-12 08:24 UTC, sehan commented on src/test/java/lotto/LottoResultsTest.java
> +    void getCountLottoRankTest(LottoRank rank, int matchNumber){
LottoResult.getCountLottoRank(rank) 시 Map<LottoRank, integer> 에 없는 LottoRank 를 넘겨줬을 때에 대한 단위테스트가 없습니다.  추가해주세요 👌

2021-01-12 08:24 UTC, sehan commented on src/test/java/lotto/LottoResultsTest.java
> +        results.put(rank, matchNumber);
results 에 대한 초기화가 계속 필요하다면 @BeforeEach 에서 단위테스트에 필요한 dataset 을 구성해 놓고 사용하면 좋습니다.

2021-01-12 08:24 UTC, sehan commented on src/main/java/lotto/view/InputView.java
> +    public static int[] inputPurchaseInfo(){
구입금액 입력과 수동로또번호 입력이 하나의 매소드에 있네요 분리해도 될거 같습니다.

2021-01-12 08:24 UTC, sehan commented on src/main/java/lotto/controller/LottoGame.java
> +                IntStream.rangeClosed(1, purchaseInfo[1])
수동로또 번호를 입력받는 로직은 view 로 이동시켜주는건 어떨까요?

2021-01-12 08:24 UTC, sehan commented on src/main/java/lotto/domain/CreateTicket.java
> +        lottoTickets.addAll(createHandTicket(handTicket));
수동로또를 생성하는 기능이 요구사항과 다릅니다.
수동로또를 구매하고 남은 금액으로 자동로또를 구매해야 합니다.

2021-01-12 12:33 UTC, sehan requested changes
피드백 잘 반영해 주셨습니다. 👍 

제가 1차 피드백에서 step2 에 추가된 프로그래밍 요구사항을 놓쳤네요 😓
사용자 입력값에 대한 예외처리와 단위테스트 보강이 필요한 부분이 있습니다.
그리고 실행결과가 요구사항과 다른부분이 있습니다.

코멘트 확인 부탁드려요~ 

다시한번 수정요청합니다.

2021-01-12 12:33 UTC, sehan commented on src/main/java/lotto/controller/LottoGame.java
> +        LottoTickets lottoTickets = new LottoTickets(CreateTicket.createTotalTicket(price, InputView.inputHandLotto()));
코드 가독성과 앞선 코드와의 일관성 측면에서 InputView.inputHandLott() 는 라인을 분리하는것이 좋겠습니다. 
```
int price = InputView.inputPurchasePrice();
List<String> handLottoNumbers = InputView.inputHandLotto();
LottoTickets lottoTickets = new LottoTickets(CreateTicket.createTotalTicket(price, handLottos));
```

2021-01-12 12:33 UTC, sehan commented on src/main/java/lotto/view/InputView.java
>  package lotto.view;
step2 에 추가된 프로그래밍 요구사항에 "사용자가 입력한 값에 대한 예외 처리를 철저히 한다."  가 있습니다. 
사용자에게 입력받은 값에 대한 예외처리가 전반적으로 되어 있지 않습니다.
사용자 입력에 대한 예외처리를 추가해 주세요.

2021-01-12 12:33 UTC, sehan commented on src/main/java/lotto/domain/CreateTicket.java
>  public class CreateTicket {
CreateTicket 에 대한 테스트가 작성되지 않았습니다. 테스트를 작성해 주세요

2021-01-12 12:33 UTC, sehan commented on src/main/java/lotto/view/ResultView.java
>  public class ResultView {
구입한 로또번호 출력시 아래와 같이 수동x개, 자동 x개 를 구매했습니다 메세지를 출력해 주세요

```
수동으로 3장, 자동으로 11개를 구매했습니다.
[8, 21, 23, 41, 42, 43]
[3, 5, 11, 16, 32, 38]
[7, 11, 16, 35, 36, 44]
[1, 8, 11, 31, 41, 42]
[13, 14, 16, 38, 42, 45]
[7, 11, 30, 40, 42, 43]
[2, 13, 22, 32, 38, 45]
[23, 25, 33, 36, 39, 41]
[1, 3, 5, 14, 22, 45]
[5, 9, 38, 41, 43, 44]
[2, 8, 9, 18, 19, 21]
[13, 14, 18, 21, 23, 35]
[17, 21, 29, 37, 42, 45]
[3, 8, 27, 30, 35, 44]
```

현재 코드에서는 구입금액을 입력하면 바로 로또구매수를 출력하고 있습니다.
```
구입 금액을 입력해주세요.
10000
10개를 구매했습니다.
```

2021-01-12 13:35 UTC, D-kuri commented
기본적인 요구사항 제대로 확인하지 않고 미션 진행한점 죄송합니다 ! ㅠ 
git을 많이 사용해보지 않아 자꾸 컨플릭트가 일어나는데 해당 부분에 대해서도 공부해보도록 하겠습니다 !!

2021-01-13 01:31 UTC, sehan requested changes
예외처리 추가 잘 해주셨습니다 ☺️

하지만 아쉽게도 TDD 가 아직 익숙치 않아 보이는 모습이 보입니다.
로직을 먼저 추가하다보니 단위테스트가 누락된 부분들이 곳곳에 보이네요
단위테스트를 보강해주세요 

다시한번 수정요청 드립니다.

2021-01-13 01:31 UTC, sehan commented on src/main/java/lotto/domain/CreateTicket.java
> -        if(price/1000 < handTicket.size()){
View 로 검증로직을 옮기고 Domain 에서는 검증로직을 제거 했네요 ☺️
view 와 domain 은 독립적인 부분으로 생각하는게 좋습니다.  마치 JavaScript 에서 사용자입력에 대한 검증코드가 있고 서버측에도 검증코드를 구현하는것과 같이 동일한 검증기능이기는 하지만 양측에서 체크해주는 것이 가장 좋습니다.
view 는 항상 변하는 코드이고 view 에서 검증에 문제가 발생하면 domain 에서 이를 막아주지 못하기 때문입니다.
domain 에도 검증코드를 유지시켜 주세요

2021-01-13 01:31 UTC, sehan commented on src/main/java/lotto/domain/WinningNumber.java
> +        if (Arrays.stream(winningNumber
생성자에서 winningNumber 문자열을 Set 으로 변환하는 코드랑 거의 중복되는 코드가 발생했네요 ☺️
WinningNumber 는 LottoTicket 을 상속했으니 bonusNumber 가 포함되어 있는지 여부는 contains() 로 확인할 수 있을거 같네요

2021-01-13 01:31 UTC, sehan commented on src/main/java/lotto/domain/WinningNumber.java
> +            throw new InvalidBonusNumber();
InvalidBonusNumber  발생에 대한 단위테스트가 없습니다. 작성해주세요

2021-01-13 01:31 UTC, sehan commented on src/main/java/lotto/domain/InvalidHandTicketSizeException.java
> +public class InvalidHandTicketSizeException extends RuntimeException{
현재 View 에서 만 수동 티켓구매수가 구입금액을 넘어서는 검증을 하고 있는데 도메인객체에서도 검증코드를 추가하고 단위테스트도 추가해주세요

2021-01-13 01:31 UTC, sehan commented on src/main/java/lotto/domain/LottoTicket.java
> +            throw new InvalidLottoTicketNumberException();
검증로직에 대한 단위테스트가 없습니다. 단위테스트 추가해주세요

2021-01-13 01:31 UTC, sehan commented on src/main/java/lotto/domain/InvalidPriceException.java
> +public class InvalidPriceException extends RuntimeException{
이 exception 도 view 에서 만 검증로직에 사용되고 있는데 도메인에도 검증로직을 추가하고 단위테스트 추가해주세요

2021-01-13 04:46 UTC, D-kuri commented on src/main/java/lotto/domain/CreateTicket.java
> -        if(price/1000 < handTicket.size()){
중복된 부분이 있어서 한곳에서만 검사하면 되지 않을까 생각하고 지웠는데 니오가 말씀해주신대로 앞으로 예외는 서버, 클라이언트 단에서 모두 체크하도록 하겠습니다 !!

2021-01-13 05:00 UTC, sehan approved these changes
단위테스트 작성 잘 해주셨습니다 💯 💯 💯 

로또미션 수행하느라 고생많으셨습니다. 👏👏👏
step2 PR merge 하겠습니다.

리뷰진행하는 동안 매소드분리, 객체역할 분담 그리고 단위테스트에 대한 피드백을 위주로 이야기를 하다보니  원시값 포장에 대한 이야기는 상대적으로 거의하지 못한것이 아쉽습니다. 
미션이 완료된 후에도 로또구입금액, 수동로또구입수, 로또수익율 과 같은 원시값 포장에 대해 한번더 생각해 보는 시간을 가져보기를 권합니다. 

끝까지 피드백 잘 따라와 주셔서 정말 감사드립니다.  🙏

2021-01-13 05:00 UTC, sehan commented on src/main/java/lotto/domain/CreateTicket.java
> +        if (price < 1000){
👍

2021-01-13 05:00 UTC, sehan commented on src/test/java/lotto/LottoTicketTest.java
> +    void invalidLottoTicketNumberCountTest(){
👍

2021-01-13 05:00 UTC, sehan commented on src/test/java/lotto/WinningNumberTest.java
> +    void invalidBonusNumberTest(){
👍

2021-01-13 05:00 UTC, merged

2021-01-13 05:01 UTC, sehan commented
@D-kuri 앗. 한가지 빼먹었군요 ^^

도메인객체에 대한 테스트는 도메인 객체와 동일한 패키지에 있어야 합니다. 
현재 lotto.domain 에 대한 테스트들이 lotto 패키지에 있습니다.