[sierra.s] 2단계 코드리뷰 요청드립니다.
NewKrew2021/java-lotto-kakao pull request #53
Opened 2021-01-12 06:36 UTC by 32sylee

jay 안녕하세요!!
지난번 피드백 감사했습니다😄
마지막에 적어주신 보완사항 수정과 2단계 추가 요구사항 구현을 마치고 2단계 코드리뷰 요청드립니다.

## 질문
LottoNumberGenerator 인터페이스를 활용해서 수동 번호를 생성할 수 있는 방법이 있을까요?
이 부분에 대해 고민해보았는데 수동 번호 생성이 view 하고 맞물려 있다보니 좋은 방법이 떠오르지 않습니다ㅠ.ㅠ

2021-01-12 10:22 UTC, parkjoos commented
질문에서 말씀 하신 것처럼 LottoNumberGenerator 를  구현하는 새로운 ManualNumberGenerator 를 만들어 볼 수도 있을것 같습니다.
ManualNumberGenerator 에 새로운 멤버변수로 inputString 을 받을 수 있을 것 같구요
Parser 의 사용을 ManualNumberGenerator 안으로 숨길수는 있을 것 같습니다.
그리고 generate 될때 그냥 사용자에게 입력받은 문자를 Set<LottoNumber> 로 변환해서 리턴 해주는 역할 정도일것 같네요

2021-01-12 10:29 UTC, parkjoos requested changes
안녕하세요 jay 입니다. 😁
1단계에서 구조를 잘 잡아 두었기 때문에 2단계 기능을 추가하는데에 크게 어려움이 있지는 않았을 것 같아요
이번 단계에서 시에라가 한가지 연습해 봤으면 하는게 있는데요
새로운 기능에 대해 코드를 추가/수정 하면서 기존 로직에 영향을 끼치지 않는지 알아보는 가장 좋은 방법은
기존에 작성된 테스트 코드를 전부다 돌려 보는 것 입니다.
2단계 PR 을 받아서 전체 테스트 코드를 돌려보니 실패하는 테스트가 몇개 있네요 
항상 코드를 작성하거나 새 테스트 케이스를 만들면 그 테스트 코드만 실행 해 보는것이 아니라
프로젝트의 전체 테스트 코드를 주기적으로 확인 해 보는것이 좋습니다. 
테스트 케이스는 만들어 놓기만 하면 되는게 아니라 항상 전부 통과가 되는지 확인이 되는것도 매우 중요합니다.
코멘트들 한번 확인 해보시고 
지금 실패하는 테스트 케이스들도 한번 확인해주세요

2021-01-12 10:29 UTC, parkjoos commented on src/main/java/lotto/util/LottoNumberParser.java
> +    public static final String SPLIT_DELIMITER = ", ";
정확히 ", " 로 되어 있어서 테스트로 돌려 볼때 생각보다 실패하는경우가 많이 나오는데요
공백이 있던 없던 상관 없이 작동하도록 구현해 보면 어떨까요?
delimiter 는 그냥  "," 로 하고 스플릿 된 결과를 trim 하면 원하는 결과가 나올것 같습니다.

2021-01-12 10:29 UTC, parkjoos commented on src/test/java/lotto/domain/MatchNumberTest.java
> +    }
이 테스트 케이스가 실패 하고 있습니다. 확인 한번 부탁드립니다.

2021-01-12 10:29 UTC, parkjoos commented on src/main/java/lotto/domain/Money.java
> +    public NumOfLotto howMany() {
로또 갯수를 wrapping 하셨는데요 MoneyTest 가 실패 하고 있습니다.
 한번 확인해 보세요.
 기존 로직을 수정후에 전체 테스트 케이스를 다 돌려서 확인해 봐야 
 내가 수정한 코드가 다른 부분에 사이드 이펙트를 주진 않는지 확인 할 수 있습니다.

2021-01-12 10:29 UTC, parkjoos commented on src/main/java/lotto/domain/WinningNumber.java
>      public Set<LottoNumber> getWinningNumber(){
이제 getter 는 더이상 사용하지 않는것 같네요 필요 없는 메소드는 삭제해도 좋을 것 같습니다.

2021-01-12 10:29 UTC, parkjoos commented on src/main/java/lotto/domain/NumOfLotto.java
> +    }
minus 검증 테스트가 있으면 좋겠네요

2021-01-12 10:29 UTC, parkjoos commented on src/main/java/lotto/domain/Lotto.java
>      }
이 세가지 메소드가 꼭 이 Lotto 도메인에 있어야 할 필요가 있을까요?
도메인 클래스내의 멤버함수는 그 객체를 조작하거나 객체 내부 데이터를 읽을 필요가 있을때에만 사용하도록 하고
이런 부분은 controller 나 util 성 클래스로 분리하는게 어떨까요?
아니면 이 함수들이 꼭 필요한 부분인지 다른 부분으로 합쳐서 더 간소화 할 방법은 없는지도 생각해 보면 좋을것 같습니다.

2021-01-12 10:29 UTC, parkjoos commented on src/main/java/lotto/controller/LottoController.java
> +            lottoList.add(Lotto.autoGenerate(lottoNumberGenerator));
```suggestion
            lottoList.add(new Lotto(lottoNumberGenerator.generate()));
```
또는 
```suggestion
            lottoList.add(Lotto.of(lottoNumberGenerator.generate()));
```

정도로만 하면 Lotto 내부의 로직도 정리되고 좀더 간결해지지 않을까요?

2021-01-12 12:02 UTC, 32sylee commented on src/main/java/lotto/util/LottoNumberParser.java
> +    public static final String SPLIT_DELIMITER = ", ";
trim을 하는 방법이 있었군요!! 수정하겠습니다:)

2021-01-12 12:07 UTC, 32sylee commented on src/test/java/lotto/domain/MatchNumberTest.java
> +    }
헉 예외가 발생하는 걸 검증해야 하는데 반대로 적었네요...ㅠㅠㅠ 수정했습니다!

2021-01-12 12:09 UTC, 32sylee commented on src/main/java/lotto/domain/Money.java
> +    public NumOfLotto howMany() {
PR을 하기 전에 테스트를 돌렸어야 했는데 그냥 PR을 해버렸군요ㅠㅠ
앞으로는 잊지 말고 전체 테스트 다 돌려보겠습니다! 해당 부분 수정했습니다:)

2021-01-12 12:09 UTC, 32sylee commented on src/main/java/lotto/domain/WinningNumber.java
>      public Set<LottoNumber> getWinningNumber(){
넵 메서드 삭제했습니다!

2021-01-12 13:04 UTC, 32sylee commented on src/main/java/lotto/domain/NumOfLotto.java
> +    }
넵! 테스트 추가하겠습니다

2021-01-12 13:09 UTC, 32sylee commented on src/main/java/lotto/controller/LottoController.java
> +            lottoList.add(Lotto.autoGenerate(lottoNumberGenerator));
생각해보니 불필요한 메서드 같네요..! ManualNumberGenerator 관련 답변주신 내용이랑 같이 고민해서 개선해보겠습니다:) 감사합니다!!

2021-01-12 13:56 UTC, 32sylee commented
jay 안녕하세요! 피드백 감사합니다😊
코멘트 주신대로 Lotto 클래스에서 generate하는 부분 제거하고 Ganerator 클래스로 통합했습니다.
그리고 기존에 LottoNumberGenerator 인터페이스를 구현받아 사용하던 부분은 지금 코드에서는 크게 필요가 없는 것 같아서
Generator 클래스들은 util성 클래스로 변경했습니다!

2021-01-13 01:23 UTC, parkjoos approved these changes
리뷰 반영 아주 잘 해 주셨습니다. 
간단하게 코멘트 드린건 있는데요 이번 미션은 머지 해도 될 것 같아요
다른 미션에서 코멘트 내용에 대해 연습해 보면 좋을 것 같습니다. 
그럼 로또 미션 정말 수고 하셨습니다. 👏 다음 미션도 화이팅 입니다.

2021-01-13 01:23 UTC, parkjoos commented on src/main/java/lotto/util/LottoNumberParser.java
>                  .collect(Collectors.toSet());
trim 에서 map 과 collect 를 다 한다음에 다시 map 과 collect 를 하고 있는데
이건 따로따로 순회를 두번한 거라 stream 을 사용한 이점이 없어진것 같아요
map 안에서 한번에 처리 할 수 있을것 같은데 다음 미션에서 이런 상황이 나오면 하나의 stream 에서 되도록 연습해 보세요

2021-01-13 01:23 UTC, merged

2021-01-13 05:08 UTC, 32sylee commented on src/main/java/lotto/util/LottoNumberParser.java
>                  .collect(Collectors.toSet());
하나의 stream에서 trim하고 split을 함께 처리할 수 있겠네요..!!
다음번 미션 할 때 기억해서 연습해보겠습니다. 코멘트 감사합니다:D