[teo.kkim 김태홍] 로또 미션 2단계 리뷰 요청 드립니다.
NewKrew2021/java-lotto-kakao pull request #54
Opened 2021-01-12 06:37 UTC by kth496

코드리뷰를 통해 많이 배우고 있습니다. 감사합니다 🙌

## 질문
1. 스트림 디버깅하는 팁이 있나요?? 디버거로 스트림을 살펴보니 복잡한 정보들이 많이 있어서, 이번 미션에서는 최종연산을 덧붙인 다음에 리턴값으로 디버깅을 했습니다. 일반적으로 최종 연산으로 리턴된 객체를 검사하는 식으로 스트림을 디버깅하나요? 리뷰어님은 어떻게 하시는지 궁금합니다!
2. 테스트코드에서 given when then 구조로 설명하기 어려운 부분이 있어서 고민입니다. 예를 들어, `LottoTest` 에 있는 `cannotOverSixNumbers` 테스트 코드는 람다식에서 발생하는 예외를 캐치하는 테스트입니다. 이런 경우에 given when then 구조로 작성하는 방법이 있을까요?
3. 1단계 피드백에서 말씀해주신 `@ParameterizedTest`를 사용해보았습니다. 이를 위해 `@CsvSource`등 값을 주입하는 여러 애너테이션이 있는 것도 알게 되었습니다. 제 코드는 `@MethodSource` 으로 `static` 메서드에서 데이터를 생성하도록 구현했습니다. 이 방법이 현재 적절한 테스트 작성 방법인지 궁금합니다!

2021-01-12 12:35 UTC, dongjoon1251 requested changes
먼저 질문에 대한 답변을 드리자면 아래와 같습니다.

1. stream은 디버깅하기 어렵습니다. 그래서 최대한 stream의 map이나 filter에 사용되는 메소드들을 분리해서 해당 메소드들을 테스트하는 방식을 사용합니다. 최종 연산으로 리턴된 객체를 테스트 하는 방식도 많이 사용됩니다. 원하는 값이 나오는지 중간에 map이나 forEach로 log를 찍거나 println하기도 합니다
2. 지금 작성해주신 대로 해주셔도 무방합니다 👍 
3. 잘 적용해주셨습니다 💯 

이전 피드백도 잘 반영해주셨네요 ㅎㅎ
추가로 몇가지 코멘트를 드렸습니다. 
모든 코드에 표시하지는 않았지만 getter를 통해서 list나 set을 리턴할 때 그냥 리턴하게 되면 어떤 위험성이 있을지 고민해보시면 좋을 것 같습니다.
그리고 성공하는 테스트들은 많이 작성되었지만 실패할 수 있는 케이스에 대해서도 테스트를 더 추가해보면 어떨까요?

2021-01-12 12:35 UTC, dongjoon1251 commented on src/main/java/mission/lotto/controller/LottoController.java
> +        LottoController lc = new LottoController();
LottoController 객체를 따로 만들지 않고 해당 클래스 내부에서 사용하는 메소드는 static으로 정의해서 사용해도 무방합니다.

2021-01-12 12:35 UTC, dongjoon1251 commented on src/main/java/mission/lotto/controller/LottoController.java
> +        UserMoney userMoney;
선언과 할당이 분리되어 있는데 합쳐도 괜찮을 것 같습니다.

2021-01-12 12:35 UTC, dongjoon1251 commented on src/main/java/mission/lotto/domain/Lottos.java
> +        int totalQuantity = lottoAmount(userMoney);
static 생성자를 잘 만들어 주셨네요 👍 
totalQuantity - manualCount 이부분으로 인해 예외가 빌생할 수 있을 것 같습니다. 검증 로직을 추가해보는게 어떨까요?

2021-01-12 12:35 UTC, dongjoon1251 commented on src/main/java/mission/lotto/domain/Lottos.java
>          Collections.sort(this.lottos);
생성자는 private 으로 바꿔서 내부에서만 접근하게 하고 생성은 static method로 모두 하도록 바꿔보면 어떨까요?
생성자에서는 할당만 하고 sort는 이전에 처리해서 넣어주면 어떨까요?

2021-01-12 12:35 UTC, dongjoon1251 commented on src/main/java/mission/lotto/domain/Lottos.java
> +        int totalQuantity = lottoAmount(userMoney);
해당 메소드에 대한 테스트 케이스도 추가해보는게 어떨까요?

2021-01-12 12:35 UTC, dongjoon1251 commented on src/main/java/mission/lotto/domain/Number.java
>              throw new IllegalArgumentException("숫자는 1~45 에 포함 되어야 합니다");
예외 클래스를 직접 만들어서 적용해보면 어떨까요?

2021-01-12 12:35 UTC, dongjoon1251 commented on src/main/java/mission/lotto/domain/Lotto.java
> +        if (checkNumbersLength(lottoNums)) {
사용된 메소드는 사용한 메소드 바로 아래에 두어서 가독성을 높여보면 어떨까요?

2021-01-12 12:35 UTC, dongjoon1251 commented on src/main/java/mission/lotto/view/OutputView.java
>          System.out.println("당첨 통계");
문자열은 모두 상수로 분리해보면 어떨까요?

2021-01-12 12:35 UTC, dongjoon1251 commented on src/main/java/mission/lotto/controller/LottoController.java
> +        userMoney = lc.registerUserMoney(InputView.enterUerMoney());
메소드로 분리하지 않고 바로 new UserMoney를 호출하게 하면 어떨까요?

2021-01-12 12:35 UTC, dongjoon1251 commented on src/main/java/mission/lotto/controller/LottoController.java
> +        LottoAnswer lottoAnswer = lc.makeLottoAnswer(
LottoAnswer를 생성하는 로직을  LottoAnswer 내부로 옮기고 여기도 new  LottoAnswer만으로 표현해보면 어떨까요?

2021-01-12 12:35 UTC, dongjoon1251 commented on src/main/java/mission/lotto/util/Statistics.java
> +
두 메소드 모드 Lottos, LottoAnswer를 파라미터로 받고 있네요. 생성자로 처음에 한번 받아서 필요한 Map<Rank, Integer> result 를 가지는 일급 컬렉션으로 리팩토링해보면 어떨까요? :)

2021-01-12 12:35 UTC, dongjoon1251 commented on src/main/java/mission/lotto/domain/Number.java
> +    public static final int MIN_NUMBER_VALUE = 1;
상수는 항상 맨 위에 정의해주세요 :)

2021-01-12 12:35 UTC, dongjoon1251 commented on src/main/java/mission/lotto/controller/LottoController.java
> -    private void buyLottos(NumGenerator numberGenerator) {
NumGenerator 인터페이스는 사용되는 부분이 없는데 삭제하면 어떨까요?

2021-01-12 12:35 UTC, dongjoon1251 commented on src/main/java/mission/lotto/domain/Rank.java
> +                .orElse(UNRANKED);
correctNo에 7이상의 값이 들어올 경우에도 UNRANKED로 간주하는게 좋을까요? 한번 고민해주시기 바랍니다.
그리고 변수명은 되도록 축약형은 지양해주시면 좋을 것 같습니다.

2021-01-12 12:35 UTC, dongjoon1251 commented on src/test/java/mission/lotto/domain/RankTest.java
> +    static Stream<Arguments> underThirdGenerator() {
ParameterizedTest 를 잘 적용해주셨네요 💯 
다만, 성공하는 테스트만 작성된 것으로 보입니다. 실패하는 케이스는 어떤 경우들이 있을까요?

2021-01-12 12:35 UTC, dongjoon1251 commented on src/main/java/mission/lotto/domain/LottoAnswer.java
>          }
getAnswerNumbers 를 통해서  set을 전달할 때 Collections.unmodifiableSet()로 한번 감싸서 리턴해주면 어떤 이점이 있을까요? :)

2021-01-12 13:58 UTC, kth496 commented on src/main/java/mission/lotto/domain/Lottos.java
> +        int totalQuantity = lottoAmount(userMoney);
테스트해보니 실제로 해당 로직에서 문제가 발생하네요 😭 코드를 수정하고 테스트 코드로 추가하겠습니다!

2021-01-12 14:30 UTC, kth496 commented on src/main/java/mission/lotto/domain/LottoAnswer.java
>          }
불변 컬렉션으로 변환하면서 얻을 수 있는 이점이 많다고 생각합니다. 도메인 객체 이외의 곳에서 변경을 시도했을 때 예외를 발생시키므로 이를 방지할 수 있을 것 같아요. :)

2021-01-12 15:09 UTC, kth496 commented on src/main/java/mission/lotto/util/Statistics.java
> +
생각지도 못했었네요.. 코드 중복을 많이 줄일 수 있는 방향이라고 생각합니다 😃

2021-01-12 15:11 UTC, kth496 commented on src/main/java/mission/lotto/view/OutputView.java
>          System.out.println("당첨 통계");
상수로 분리하는 과정에서 빼억은 것이 있었네요 😭 수정하겠습니다 :)

2021-01-12 15:13 UTC, kth496 commented on src/main/java/mission/lotto/controller/LottoController.java
> +        userMoney = lc.registerUserMoney(InputView.enterUerMoney());
과도하게 메서드 래핑을 했었네요.. 😭

2021-01-12 15:16 UTC, kth496 commented on src/main/java/mission/lotto/domain/Number.java
>              throw new IllegalArgumentException("숫자는 1~45 에 포함 되어야 합니다");
1단계에서 말씀해주신 부분인데 빼먹었네요 😭😭

2021-01-13 05:23 UTC, kth496 commented on src/main/java/mission/lotto/domain/Rank.java
> +                .orElse(UNRANKED);
`UNRANKED`를 아무 의미 없다는 표현으로 작성했습니다. `Lotto` 클래스의 생성자에서 중복없는 6개 숫자를 받아오기 때문에 7이상의 수가 들어오지 않는다고 생각했네요.. 문제가 될 수 있는 부분이 있을까요??

2021-01-13 05:25 UTC, kth496 commented on src/test/java/mission/lotto/domain/RankTest.java
> +    static Stream<Arguments> underThirdGenerator() {
실패하는 경우도 추가해보겠습니다!

2021-01-13 10:12 UTC, kth496 commented
안녕하세요! 코드 리뷰 해주신 내용을 바탕으로 리팩터링을 해 보았습니다. 말씀해주신 방향과 키워드를 바탕으로 고민하면서 몰랐던 자바 api도 알게되었습니다 😃 리뷰 중에서 `Rank`와 관련된 피드백은 제가 잘 이해하지 못해서 코멘트를 남겨두었으니 확인 부탁드립니다! 감사합니다 :)

2021-01-13 10:23 UTC, dongjoon1251 commented on src/main/java/mission/lotto/domain/Rank.java
> +                .orElse(UNRANKED);
현재 요구사항만 봤을 때는 문제가 없을 수 있고 구현해주신 방법으로 구현해도 무방합니다. 
다만, 해당 메소드가 public으로 구현되어 있어서 다른 동료가 작업할 때, 7 이상의 숫자를 입력해도 문제가 없는 것을 보고 잘못된 상황이 아니라고 인지할 가능성이 있습니다.

2021-01-13 10:34 UTC, dongjoon1251 approved these changes
피드백들을 잘 반영해주셨네요 👍 
이번 미션은 여기서 마무리하도록 하겠습니다. 
몇가지 추가로 코멘트를 남겨드렸는데 확인해보시고 궁금하신 점은 따로 DM을 주셔도 됩니다. 
고생하셨습니다.

2021-01-13 10:34 UTC, dongjoon1251 commented on src/main/java/mission/lotto/domain/Lotto.java
> +            throw new IllegalArgumentException("로또는 중복 없는 6자리만 가능합니다.");
직접 만든 예외클래스 적용을 코드 전체적으로 적용하는게 어떨까요?
공통 예외클래스인 LottoException을 사용하기 보다는 에러 종류별로 만들고 메시지는 해당 예외클래스 내부에서 관리해보면 어떨까요?

2021-01-13 10:34 UTC, dongjoon1251 commented on src/main/java/mission/lotto/domain/Lotto.java
> +        boolean hasBonusNo = isContainLottoNumber(bonus);
hasBonusNo 와 같은 축약어도 지양해주세요:)

2021-01-13 10:34 UTC, dongjoon1251 commented on src/main/java/mission/lotto/domain/Lotto.java
>          int correctNo = 12 - combine.size();
12는 어떤 의미가 있는 숫자인지 상수로 표현하면 어떨까요?

2021-01-13 10:34 UTC, dongjoon1251 commented on src/main/java/mission/lotto/domain/Lottos.java
> +        Stream<Lotto> manualLottos = IntStream.range(0, manualCount)
manaulLottos, autoLottos등을 생성하는 private 메소드로 분리해보면 어떨까요?

2021-01-13 10:34 UTC, dongjoon1251 commented on src/main/java/mission/lotto/domain/Number.java
>              throw new IllegalArgumentException("숫자는 1~45 에 포함 되어야 합니다");
"숫자는 1~45 에 포함 되어야 합니다" 메시지에 들어있는 숫자도 상수를 사용하면 어떨까요?

2021-01-13 10:34 UTC, dongjoon1251 commented on src/main/java/mission/lotto/util/Statistics.java
> +        for (Rank lotteryWinnings : Rank.values()) {
for문 대신 stream()을 사용해서 Map을 생성해보는 부분을 공부해보시면 좋을 것 같습니다 :)

2021-01-13 10:34 UTC, merged