[huey.j 전준호] 로또 Step2 리뷰 요청드립니다.
NewKrew2021/java-lotto-kakao pull request #57
Opened 2021-01-12 07:13 UTC by jh280722

2021-01-12 10:22 UTC, ljh131 requested changes
몇 가지 고민해 볼 수 있는 부분들 커멘트 드렸습니다. 어떻게 개선하면 좋을지 생각해보시고 수정 해보셨으면 좋겠습니다.

2021-01-12 10:22 UTC, friediceday commented on src/main/java/lotto/domain/LottoTicketCount.java
> +public class LottoTicketCount {
굳이 이런 클래스를 만든 이유가 있을까요? 수동으로 몇개를 사면 나머지로 자동을 몇개 살지만 계산하면 될 것 같은데요. 이 클래스를 추가함으로써 생기는 장점은 어떤걸까요?

2021-01-12 10:22 UTC, friediceday commented on src/main/java/lotto/domain/Lotto.java
> +    public static Lotto of(String lottoNumbers) {
팩토리 메서드가 하나 더 추가되었네요. 콜러가 스플릿해주는게 나을 것 같은데 굳이 따로 만든 이유가 있나요?
그리고 기존의 팩토리를 사용할 수 있을 것 같은데 중복해서 구현되었네요.

2021-01-12 10:22 UTC, ljh131 commented on src/main/java/lotto/domain/Lottos.java
> +    public void addRandomLottos(LottoTicketCount lottoTicketNumber) {
메서드들이 늘어나는 요구사항에 비례해서 점점 늘어나고 있습니다.
이 클래스가 자동과 수동을 따로 구분해서 알 필요가 있을까요?
만약에 나중에 반자동이라는 요구사항이 생기면 그때는 어떻게 해야할까요?

2021-01-12 10:22 UTC, ljh131 commented on src/main/java/lotto/domain/result/LottoResult.java
> +    public static List<LottoResult> notNothingValues() {
출력을 위해 사용하는 메서드인데, 이넘 선언 순서에 종속되지 않을까요?
선언 순서가 혹시 바뀌더래도 출력 순서를 보장할 수 있도록 할 수 없을까요?

2021-01-12 10:22 UTC, ljh131 commented on src/main/java/lotto/domain/result/LottoResults.java
> +        lottoResultsAndCount.remove(LottoResult.NOTHING);
굳이 안해도 되지 않을까요

2021-01-12 10:27 UTC, jh280722 commented on src/main/java/lotto/domain/result/LottoResults.java
> +        lottoResultsAndCount.remove(LottoResult.NOTHING);
아 이렇게 먼저 만들었다가 notNothingValues를 만들고 제거를 안해주었네요 감사합니다.

2021-01-12 10:32 UTC, jh280722 commented on src/main/java/lotto/domain/Lotto.java
> +    public static Lotto of(String lottoNumbers) {
중복 구현은 제거했습니다. 제 생각으론 Input에서 받은 문자열을 그대로 넘겨주고 Lotto 팩토리 메서드에서 처리를 해주면 편할 것 같아서 만들어봤는데요. 이런 방법은 별로인가요?

2021-01-12 10:37 UTC, jh280722 commented on src/main/java/lotto/domain/LottoTicketCount.java
> +public class LottoTicketCount {
예외를 처리하는 역할을 넘겨주었습니다. 수동으로 가능한 티켓보다 더 많은 수를 입력했을때와 문자를 입력했을 경우를 판단했습니다.
그러한 처리를 int로 설정하고 InputView에서 처리해주는 것이 좋을까요?

2021-01-12 10:37 UTC, ljh131 commented on src/main/java/lotto/domain/Lotto.java
> +    public static Lotto of(String lottoNumbers) {
편하죠. 그런데 편한 것 보다는 해당 클래스에 맞는 역할인지를 생각해보시면 좋겠습니다.

2021-01-12 10:39 UTC, ljh131 commented on src/main/java/lotto/domain/LottoTicketCount.java
> +public class LottoTicketCount {
인풋에서 로직을 처리하는 것은 좋아보이지 않습니다. 컨트롤러 역할을 하는 객체가 하면 어떨까요.

2021-01-12 11:45 UTC, jh280722 commented on src/main/java/lotto/domain/result/LottoResult.java
> +    public static List<LottoResult> notNothingValues() {
스트림에 sort를 추가하는건 어떨까요?

2021-01-12 13:28 UTC, jh280722 commented
controller를 만들고 enum sort를 찾아서 해봤는데 단순히 matchNumber로는 소트가 되지만
bonusCondition까지 고려해서 소트하는 방법은 영어로 구글링해도 찾지못했습니다. 소트가 아닌 다른 방법이 있을까요?

2021-01-13 09:12 UTC, ljh131 requested changes
전반적으로 개선되어가고 있는 것 같습니다. 조금 더 개선할 수 있는 부분은 커멘트 드렸습니다. 생각해보시고 적절히 수정해보시면 좋겠습니다.

2021-01-13 09:12 UTC, friediceday commented on src/main/java/lotto/domain/result/LottoResult.java
> +    private LottoResult a;
이건 뭔가요

2021-01-13 09:12 UTC, friediceday commented on src/main/java/lotto/domain/LottoSimulation.java
>  public class LottoSimulation {
이름을 보면 전체 과정을 담당하는 느낌인데 그에 비하면 하는일이 딱 하나네요. 이름을 바꾸는 것도 방법일 것 같고요. 그런데 그러다보면 이 클래스가 굳이 필요한가라는 의문이 들 것 같습니다.

2021-01-13 09:12 UTC, friediceday commented on src/main/java/lotto/domain/LottoSimulation.java
> +                StringUtils.convertToIntegerList(winningLottoText.split(",")), bonusBall);
여기 스플릿도 밖에서 해주는게 역할 분리에 좋을 것 같네요

2021-01-13 09:12 UTC, friediceday commented on src/main/java/lotto/domain/result/LottoResult.java
> +    public static List<LottoResult> notNothingValues() {
이넘값에 등수를 넣고, 출력시 이걸로 소팅하면 어떤가요?

2021-01-13 09:12 UTC, ljh131 commented on src/main/java/lotto/domain/result/LottoResult.java
> +    public static List<LottoResult> notNothingValues() {
이름도 get이라는게 명확히 들어가고 어떤걸 리턴하는건지 알 수 있으면 좋을 것 같네요.

2021-01-13 10:23 UTC, jh280722 commented on src/main/java/lotto/domain/LottoSimulation.java
>  public class LottoSimulation {
컨트롤러가 담당하게 되니 클래스가 필요없게 되었네요.
역할 자체를 컨트롤러가 모두 가질 수 있을것 같아 제거를 하였습니다.

2021-01-13 10:30 UTC, jh280722 commented
enum에 필드 하나를 추가하면 되는걸 괜히 그대로 정렬해야한다는 생각에 매몰되어 계속 고민했던 것 같습니다. 감사합니다.
피드백을 거의 반영했지만 의문점이 들어서 질문드립니다.
enum에서 .values()를 통해 배열을 가져올 수 있는데요. 저는 LottoResult.values()라는 자체에서 결과들의 값들 이라는 표시가 되어있는 것이라 생각해서 LottoResult.notNothingValues라 명명했는데요. 그래도 메소드 자체에 좀 더 이름을 명확히 하는 것이 나을까요?

2021-01-13 11:18 UTC, ljh131 approved these changes
수고하셨습니다. 이번 미션은 여기서 머지하겠습니다. 
추가로 소소하게 고민해볼 수 있는 부분과 질문하신 내용 답변은 커멘트 드렸습니다.

2021-01-13 11:18 UTC, friediceday commented on src/main/java/lotto/view/OutputView.java
> +    private static List<LottoResult> getReversedLottoResult() {
여기서 목록을 정렬하고, 랭크도 갖고오고 할 필요 없이 LottoResult가 해주면 더 좋을 것 같아요.

2021-01-13 11:18 UTC, friediceday commented on src/main/java/lotto/domain/result/LottoResult.java
> +    FIFTH(5,3, DONT_CARE, 5_000L, "3개 일치 (5000원)-"),
일부러 순서가 바뀌는 상황을 가정한거였으니 원래 순서로 해도 될 것 같네요.

2021-01-13 11:18 UTC, ljh131 commented on src/main/java/lotto/domain/result/LottoResult.java
> +    public static List<LottoResult> getNotNothingLottoResults() {
네이밍에 관해 질문 하셨는데요,

예를 들어 getLottoResultsExceptNothing 뭐 이런식이라고 하면, 클라이언트 입장에서는 저게 뭘까라는 생각이 들지 않을까 싶어요. nothing이라는게 뭔지, 왜 빼고 주는지. 그럼 결국 구현을 봐야되고요. 외부 입장에서는 nothing이라는게 내부에 있는지 알 필요도 없고, 등수 목록만 정확히 주면 될텐데요. 예를 들면 저 같으면 간단하게 LottoPrize.getPrizes 라고 할 것 같습니다. prize면 등수에 못든게 포함 안되는건 당연하다고 생각할 것 같고요.

2021-01-13 11:18 UTC, merged

2021-01-13 11:20 UTC, jh280722 commented on src/main/java/lotto/domain/result/LottoResult.java
> +    public static List<LottoResult> getNotNothingLottoResults() {
아하 딱 바로 이해가 되는 예시네요. 굳이 외부에 필요없는 정보는 공개하지않고 필요한 정보만 공개하는거군요. 감사합니다.
계속 이상한 코드 봐주시느라 수고하셨습니다. 세세한 리뷰 감사드립니다.