[ellie.klm 김예지] 로또 미션 step2 리뷰요청 드립니다.
NewKrew2021/java-lotto-kakao pull request #58
Opened 2021-01-12 07:20 UTC by Ye-Ji-Kim

이번 단계에서는 수동으로 구매할 로또의 개수와 수동 로또 번호를 입력받게 하였습니다.
따라서 입력받은 개수만큼은 수동으로, 나머지는 자동으로 로또를 구매하여 통계를 구하는 기능을 추가하였습니다.

2021-01-12 10:49 UTC, parkjoos requested changes
안녕하세요. jay 입니다. 😁
지난 단계를 잘 마무리 하셔서 2단계는 아주 간단하고 쉽게 구현이 되었네요 
새롭게 기능을 추가하고 요구사항이 변경이 되었는데요 
1단계에서 추가해 두었던 기능 목록이 업데이트가 되어 있지 않는것 같습니다. 
기능이 추가 되거나 수정되면서 프로젝트내에 정리한 문서나 주석, method 이름등도 그 변화에 맞게 업데이트가 되어야
이후 이 프로젝트를 수정하게 될 동료들이 더 쉽게 코드를 이해 할수 있게 됩니다. 
(본인이 될 수 도 있어요. 이상하게 자기가 만든 코드인데 금방 기억이 안나요 )
이부분 확인 부탁드립니다.

2021-01-12 10:49 UTC, parkjoos commented on src/main/java/lotto/domain/LottoGame.java
>              tickets.add(generateLottoTicket(numbers));
수동 티켓을 모두 만든 마음에 자동 티켓을 만드는 과정인데요
수동/자동이 다 가능한 상황이기 때문에  generateLottoTicket 라는 이름을 그대로 사용하게 되면 한번에 어떤 의미인지 이해하기 어려울 것 같습니다. 
좀더 정확하고 명확한 이름으로 바꿔보는게 어떨까요?

2021-01-14 01:37 UTC, Ye-Ji-Kim commented
리뷰 감사합니다!ㅎㅎ
코드 구현 뿐만 아니라 이를 문서로 정리하는 부분에도 주의가 필요한 것 같네요. 좋은 지적 감사합니다! 😊

2021-01-14 05:13 UTC, parkjoos approved these changes
엘리 미션 수고 많으셨습니다. 👍
바로 머지 하면 될것 같아요
리뷰 내용에 대해 수정 반영 후에 next step 에서 리뷰 요청 버튼을 다시 눌러 주시거나 
git 에서 리뷰 재 요청을 해 주셔야 리뷰가 가능한 상태인지 확인이 가능합니다. 
![image](https://user-images.githubusercontent.com/61861989/104547736-99b57a80-5672-11eb-8d93-70cff7594025.png)
(지금 제가 self 로 재요청을 해서 버튼이 없는데 요기에 재요청 할 수 있게 버튼이 있어요)

다음 미션 하실때 참고해서 진행해 주세요
로또 미션 수고 많으셔습니다. 다음 미션도 화이팅 입니다.

2021-01-14 05:14 UTC, merged