[jayk.yang] 로또 Step2 리뷰 요청드립니다.
NewKrew2021/java-lotto-kakao pull request #59
Opened 2021-01-12 07:26 UTC by tttuer

지금은 message를 받아서 처리하고 있는데, 오류를 더 자세히 표현하는 예외 클래스들로 더 세분화해서 나눠보면 어떨까요?
이 부분을 잘 모르겠습니다. 각 클래스에 맞는 예외 클래스들을 따로 만들어서 하라고 하신 말씀일까요?

== 보다는 equals를 사용하는게 어떨까요?
이부분도 잘 모르겠습니다. equals로 비교를 하게 되면 winnings에 대한 값이 필요할텐데 그 부분을 받아올 방법을 잘 모르겠습니다.

리뷰 및 피드백 감사합니다!

2021-01-12 13:05 UTC, dongjoon1251 requested changes
피드백을 많이 반영해주셨네요 :)
질문주신 부분에 대해서는 추가로 남긴 코멘트에 포함되어 있습니다.
몇가지 코드상에 남기지 못한 코멘트를 아래에 남깁니다. 확인 부탁드립니다.
- 상수로 선언한 부분은 항상 클래스 맨 위에 오게 맞춰주세요.
- toString() 메소드를 사용하지 않고, 출력에 관련된 로직은 출력을 담당하는 클래스로 모아주세요.
- List나 Map 생성시에 stream()을 통해서 생성되도록 리팩토링해보세요.
- 실패하는 테스트들도 추가해주시고 @ParameterizedTest를 통해서 다양한 값에 대해서 테스트가 수행되도록 추가해주세요 :)
- assert구문은 최대한 테스트 메소드 하나당 하나만 사용하도록 맞춰주세요.

2021-01-12 13:05 UTC, dongjoon1251 commented on src/main/java/view/LottoSimulatorView.java
>  public class LottoSimulatorView {
해당 클래스를 결과를 출력하는 View와 입력을 받기위해 필요한 View로 역할을 분리해보면 어떨까요?

2021-01-12 13:05 UTC, dongjoon1251 commented on src/main/java/view/Message.java
> +    public static final String ASK_MANUAL_LOTTO_NUMBERS = "수동으로 구매할 번호를 입력해 주세요.";
필요한 상수를 따로 선언해주는 것도 좋지만 클래스 내에서 사용하도록 수정해보면 어떨까요? 
해당 상수들이 view말고 다른 곳에서 사용되는 곳이 없다면 따로 클래스로 나누지 않는게 어떨까요?

2021-01-12 13:05 UTC, dongjoon1251 commented on src/main/java/domain/Money.java
> +            throw new LottoException("금액이 부족합니다.");
제가 의도했던 부분은 LottoException으로 오류를 한가지로 통일해서 표현하기 보다 지금 입력된 에러 메시지에 따라서 구분해보면 어떨지 말씀드린 거였습니다. 위의 경우에는 InvalidMoneyException 과 같이 표현할 수 있을 것 같습니다.

2021-01-12 13:05 UTC, dongjoon1251 commented on src/main/java/domain/LottoStatus.java
>      }
matchedLottoNumberCount == LottoStatus.SECOND.matchedLottoNumberCount 는 matchedLottoNumberCount를   Integer 타입으로 받으면 equals로 표현할 수 있는데요. 굳이 그렇게 하지 않아도 될 것 같습니다. 
그리고 이전에 코멘트 드렸듯이  isBonusNumberMatched도 enum의 필드로 추가해보면 어떨까요?
findStatus 메소드 내부의 stream 메소드는 한 줄에 포인트 하나씩 나오도록 맞춰주세요 :)
예시) stream()
.filter()
.findFirst()...

matchedLottoNumberCount 에 잘못된 값이 들어온 경우 무조건 NONE으로 리턴해주는 것이 맞을지 다시 고민해주시기 바랍니다.

2021-01-12 13:05 UTC, dongjoon1251 commented on src/main/java/domain/LottoStatus.java
>      }
해당 enum내에서 사용되는 변수명이 너무 길어서 가독성이 떨어지는 것 같습니다. 더 적은 단어로 표현해보면 어떨까요?

2021-01-12 13:05 UTC, dongjoon1251 commented on src/main/java/domain/LottoStatus.java
>      private final int winngs;
오타인것 같습니다 :)

2021-01-12 13:05 UTC, dongjoon1251 commented on src/main/java/domain/ManualLottoGenerateStrategy.java
> +public class ManualLottoGenerateStrategy implements LottoGenerateStrategy{
LottoGenerateStrategy 로 인터페이스를 분리했지만 의도한 대로 잘 분리되진 않은 것 같습니다. 실제로 입력받는 로직도 다른 부분에 있구요. 인터페이스로 분리하지 않고 따로따로 생각해보면 어떨까요? Random한 값을 가져오는 부분은 Util로 보고 해당 클래스와 인터페이스는 삭제해도 되지 않을까요?

2021-01-12 13:05 UTC, dongjoon1251 commented on src/main/java/controller/LottoController.java
> -        buyAutoLotto();
이 메소드를 바로 main 메소드로 사용하는게 어떨까요?
사용되는 메소드들은 static으로 선언해도 괜찮습니다.

2021-01-12 13:05 UTC, dongjoon1251 commented on src/main/java/controller/LottoController.java
> +        Lottos manualLottos = buyManualLotto();
manualLottos, autoLottos 를 생성하는 로직을 모두 Lottos 생성자에서 처리하도록 리팩토링해보면 어떨까요?

2021-01-12 13:05 UTC, dongjoon1251 commented on src/main/java/controller/LottoController.java
> +        for (int i = 0; i < manualLottoCount; i++) {
리스트를 생성하는 부분을 IntStream(0, manualLottoCount)와 같은 stream을 통해 생성되도록 리팩토링해보면 어떨까요?

2021-01-12 13:05 UTC, dongjoon1251 commented on src/main/java/controller/LottoController.java
> +        if (manualLottoCount == 0) {
0이면 generateManualLottos 메소드를 통해서 빈리스트가 나오지 않을까요? 따로 구분하지 않아도 무방해보입니다.

2021-01-12 13:05 UTC, dongjoon1251 commented on src/main/java/controller/LottoController.java
> +
아래 메소드들은 분리되면서 오히려 가독성이 떨어지는 것 같습니다. LottoResult를 메소드 내의 로컬변수로 두고 필요한 메소드를 호출해서 사용하도록 리팩토링해보면 어떨까요?

2021-01-12 13:05 UTC, dongjoon1251 commented on src/main/java/controller/LottoController.java
> +        List<Integer> lotto = StringUtils.splitText(inputTexts).stream()
AnswerLotto를 생성하는 로직을 생성자 내부로 옮겨볼 수 있을까요?

2021-01-13 10:16 UTC, dongjoon1251 requested changes
제가 드렸던 코멘트들이 일부 잘 반영되지 않은 것 같습니다. 
코멘트들이 중간에 생략 표시로 바로 확인이 안되어서 못 보신 부분이 있으셨던 걸로 예상됩니다.
코멘트가 잘 이해가지 않거나 리뷰이분께서 생각하시는 방향과 다르다면 의견 주시면 좋을 것 습니다.

2021-01-13 10:48 UTC, tttuer commented
> * toString() 메소드를 사용하지 않고, 출력에 관련된 로직은 출력을 담당하는 클래스로 모아주세요.

LottoGenerateStrategy 인터페이스는 삭제를 하고 다시 올렸습니다!
궁금한 점이 toString() 메소드를 사용하지 않았을때 각 클래스들에서 getter로 값을 가져와서 출력 부분에 사용해야 할 것이라 생각됩니다. 그런데 getter는 안쓰는 편이 좋다고 강의 중에 들었는데 어떻게 getter를 쓰지 않으면서 toString을 없앨 수 있을까요?

2021-01-13 10:54 UTC, dongjoon1251 commented
> > * toString() 메소드를 사용하지 않고, 출력에 관련된 로직은 출력을 담당하는 클래스로 모아주세요.
> 
> LottoGenerateStrategy 인터페이스는 삭제를 하고 다시 올렸습니다!
> 궁금한 점이 toString() 메소드를 사용하지 않았을때 각 클래스들에서 getter로 값을 가져와서 출력 부분에 사용해야 할 것이라 생각됩니다. 그런데 getter는 안쓰는 편이 좋다고 강의 중에 들었는데 어떻게 getter를 쓰지 않으면서 toString을 없앨 수 있을까요?

setter는 아예 없앨 수 있지만 getter를 아예 사용하지 않는 것은 사실 거의 불가능합니다. 대신 외부에서 필요한 필드들만 추려서 dto로 변환해서 전달하거나 외부에서 수정이 불가하도록 컬렉션을 immutable 한 컬랙션으로 래핑해서 전달할 수 있습니다. 그러면 getter로 전달받은 객체를 외부에서 수정할 수 없거나 수정해도 문제가 없을 수 있습니다. getter 사용을 지양하는 이유는 최대한 외부에서 클래스 내부의 값들을 변경하지 못하도록 막기 위해서 입니다. 답변이 도움이 되었으면 좋겠네요 :) 더 궁금하신점은 DM으로 바로바로 질문주셔도 됩니다!

2021-01-15 03:32 UTC, dongjoon1251 approved these changes
피드백을 잘 반영해주셨네요. 
아직 java8 stream 라이브러리에 익숙하지 않으신 것 같아서 참고하실만한 코멘트를 몇개 추가했습니다.
다른 코멘트들도 다른 미션 수행에 도움이 될것으로 생각되어 같이 남겼습니다.
이번 미션은 여기에서 마무리하도록 하겠습니다.
고생하셨습니다.

2021-01-15 03:32 UTC, dongjoon1251 commented on src/main/java/controller/LottoController.java
> +        return inputs;
아래와 같은 형식으로 리팩토링해볼 수 있을 것 같습니다. 꼭 Stream으로 바꿔야한다는 규칙은 없지만 for 문을 stream으로 바꿔보고 가독성이 더 좋은 방향으로 앞으로 적용해보시면 좋을 것 같습니다.

return IntStream.range(0, manualLottoCount)
                .mapToObj(i-> LottoInputView.inputManualLotto())
                .collect(Collectors.toList())

2021-01-15 03:32 UTC, dongjoon1251 commented on src/main/java/controller/LottoController.java
> +        money.checkCanBuy(manualLottoCount);
money를 가지고 로또를 제대로 살수 있는지 검증하는 부분도 Lottos 내부로 이동이 가능해보입니다.

2021-01-15 03:32 UTC, dongjoon1251 commented on src/main/java/controller/LottoController.java
> +    private static void printBuyLottos(Lottos lottos) {
따로 메소드로 분리하지 않아도 무방해보입니다.

2021-01-15 03:32 UTC, dongjoon1251 commented on src/main/java/controller/LottoController.java
> +        String answerLottoNumbers = LottoInputView.askLottoNumberToAnswerLotto();
이 메소드도 따로 분리하지 않아도 무방해보입니다.

2021-01-15 03:32 UTC, dongjoon1251 commented on src/main/java/domain/AnswerLotto.java
>      }
이부분은 아래와 같이 표현이 가능합니다.

return (int) lotto.stream()
                .filter(answerLotto::contains)
                .count();

2021-01-15 03:32 UTC, dongjoon1251 commented on src/main/java/domain/LottoResult.java
> +                .forEach(lottoStatus -> result.put(lottoStatus, 0));
아래와 같이 초기화가 가능합니다.
Map<LottoStatus, Integer> result = Arrays.stream(LottoStatus.values())
                .collect(Collectors.toMap(Function.identity(), lottoStatus -> 0));

2021-01-15 03:32 UTC, dongjoon1251 commented on src/main/java/domain/LottoResult.java
> +                .forEach(lotto -> result.put(answerLotto.getResult(lotto), result.get(answerLotto.getResult(lotto)) + 1));
이부분은 for문으로 표현하는것이 더 좋을수도 있고, 위의 Map 생성 스트림을 참고하셔서 리팩토링해보셔도 좋습니다.

2021-01-15 03:32 UTC, dongjoon1251 commented on src/main/java/domain/Lottos.java
> +    }
아래와 같이 바꾸고 list를 합치거나 stream을 합치는 연산을 통해서 this.lottos에 할당해주는 것도 가능합니다.

private List<Lotto> generateManualLottos(List<String> inputs) {
        return inputs.stream()
                .map(StringUtils::splitText)
                .map(lotto -> new Lotto(generateManualLotto(lotto)))
                .collect(Collectors.toList());
    }

2021-01-15 03:32 UTC, dongjoon1251 commented on src/main/java/domain/LottoStatus.java
> +    private final boolean isBonusNumberMatched;
필드가 사용되지 않는데 findStatus부분에서 사용해보면 어떨까요?

2021-01-15 03:32 UTC, dongjoon1251 commented on src/main/java/domain/LottoStatus.java
secondOrThird 와 같이 enum에 사용된 상수명을 이용한 함수명은 지양해주시기 바랍니다. SECOND, THIRD의 의미가 달라질 경우에 문제가 생긴것을 파악하기 힘듭니다.

2021-01-15 03:32 UTC, dongjoon1251 commented on src/main/java/domain/LottoStatus.java
>                  .orElse(NONE);
해당하는 matchCount, isBonusNumberMatched 가 없을때 NONE으로 맞추는 것이 좋을지 에러를 내는것이 더 나은 상황은 없을지 고민해보시기 바랍니다.

2021-01-15 03:32 UTC, dongjoon1251 commented on src/main/java/domain/AnswerLotto.java
> +            throw new InvalidLottoException("로또번호에 보너스가 포함되어있습니다.");
예외 클래스 내부에 에러 메시지를 상수로 정의해서 사용하면 어떨까요?

2021-01-15 03:32 UTC, dongjoon1251 commented on src/main/java/view/LottoOutputView.java
> +        System.out.println("당첨 통계\n-----------");
해당 문자열들도 상수로 분리해주면 어떨까요?

2021-01-15 03:32 UTC, dongjoon1251 commented on src/test/java/domain/MoneyTest.java
> +    void 로또_개수() {
한글로 메소드명을 작성해주셔도 괜찮지만 @DisplayName으로 모두 통일해보면 어떨까요?

2021-01-15 03:32 UTC, merged

2021-01-15 03:36 UTC, tttuer commented on src/main/java/controller/LottoController.java
> +        return inputs;
컨트롤러에도 for문이 있는지는 제가 신경을 잘 못썼네요. 피드백 감사합니다