[echo.ohce 김환석] lotto 미션 step2 리뷰 부탁드립니다!
NewKrew2021/java-lotto-kakao pull request #60
Opened 2021-01-12 08:55 UTC by 10000sukk

안녕하세요 에코입니다!
먼저 저번에 너무나도 섬세히 리뷰 주셔서 정말 감사의 인사를 전합니다. 객체가 어려워서 많이 헤멧었네요...ㅎㅎ 
저번에 피드백 주신 사항을 따라서 controller 를 삭제하고 main 에서 객체들을 사용하니 더 분리하기도 쉽고 깔금해 진듯합니다.
여기서 궁금한점이 있는데 그러면 main 이 controller 같은 역할을 해주니 controller는 여기서 main 이다! 라고 말할 수도 잇는 건가요?

매운맛 피드백 부탁드립니다!

2021-01-12 09:16 UTC, 10000sukk commented
한가지 더 의문점이 드는데 모델이(LottoGame)이 자신의 상태를 가지고 있지 않아도 (Lotto의 정보나, 정답 정보, 입력 금액정보) 이것을 모델이라고 봐도 괜찮은 건가요?

2021-01-13 05:05 UTC, sehan commented
@10000sukk PR 올라온걸 지금 확인했습니다. slack 알림에 누락이 있었나 봅니다.
리뷰가 안올라와서 많이 기다렸을거 같네요. 빨리 리뷰진행 할께요 조금만 기다려 주세요 ^^

2021-01-13 05:14 UTC, sehan commented
> 안녕하세요 에코입니다!
> 먼저 저번에 너무나도 섬세히 리뷰 주셔서 정말 감사의 인사를 전합니다. 객체가 어려워서 많이 헤멧었네요...ㅎㅎ
> 저번에 피드백 주신 사항을 따라서 controller 를 삭제하고 main 에서 객체들을 사용하니 더 분리하기도 쉽고 깔금해 진듯합니다.
> 여기서 궁금한점이 있는데 그러면 main 이 controller 같은 역할을 해주니 controller는 여기서 main 이다! 라고 말할 수도 잇는 건가요?
> 
> 매운맛 피드백 부탁드립니다!

매운맛 나갑니다. 🤣
controller 삭제 후 변경된 코드를 보니 피드백을 잘 이해하신거 같아서 아주 기쁘네요 😄
controller 는 domain (model) 과 view 를 사용해서 application 이 동작하도록 하는 역할을 해주고 있으니 main 에 구현된 코드가 바로 controller 입니다. 기대와는 다르게 매운맛 1단계 정도 밖에 안되는거 같네요 ㅎㅎ. 좀 허무하죠?

이런 미션처럼 간단한 application 같은 경우는 main() 에 1회성의 미션 시나리오를 실행하고 종료되다 보니 별도의 Controller 역할을 분리할 필요가 없는거 같네요

2021-01-13 06:21 UTC, sehan requested changes
1차 피드백을 아주 잘 반영해주셨습니다. 👍 👍 👍 

몇가지 아쉬운 부분이 있어서 코멘트 남겼습니다.
단위테스트가 작성되지 않은곳이 좀 있고 객체의 역할을 나누었으면 하는 부분이 있습니다. 
그리고 step2 에 프로그래밍 요구사항으로 아래 2가지 항목이 추가되었습니다. 
* 예외가 발생하는 부분에 대해 자바 Exception을 적용해 예외처리한다.
* 사용자가 입력한 값에 대한 예외 처리를 철저히 한다.

위 2가지 부분도 체크해서 반영해주시기 바랍니다. 

수정요청 드리겠습니다.

2021-01-13 06:21 UTC, sehan commented on src/main/java/lottomission/Main.java
> +    public static void main(String[] args) {
main() 코드 가독성이 아주 좋아졌습니다.  로또미션이 무엇 이었는지 문서를 보지 않고도 알수 있겠습니다. 👍 
피드백을 아주 잘 이해하고 반영해 주셨네요

2021-01-13 06:21 UTC, sehan commented on src/main/java/lottomission/domain/LottoGame.java
> -
Lottos , LottoAnswer 를 멤버에서 제거함 으로써 LottoGame 은 1회용 로또구매용 객체가 아니라 계속 살아 숨쉬며 구입금액에 해당하는 로또를 발급해주고 발급된 로또의 결과를 체크해주는 멋진 객체가 되었습니다.

2021-01-13 06:21 UTC, sehan commented on src/main/java/lottomission/domain/LottoNumbers.java
> -        combineSet.addAll(lottoNumbers.getNumbers());
객체 상태를 꺼내는 부분을 잘 제거해 주셨습니다. 👍

2021-01-13 06:21 UTC, sehan commented on src/main/java/lottomission/view/OutputView.java
> +    public static void autoBoughtView(Lottos lottos) {
출력에 필요한 인자들만 받아서 처리하니 매소드의 역할이 한결 명확해 졌습니다. 👍

2021-01-13 06:21 UTC, sehan commented on src/main/java/lottomission/domain/Lottos.java
> +    public Lottos combineLottos(Lottos lottos){
수동로또와 자동로또 번호를 하나로 합치기위해 작성된 매소드인 걸로 보입니다.
수동로또와 자동로또는 Lotto 객체로 만들기 전에 합쳐서 Lottos 를 한번에 만들면 이 매소드가 필요 없어 보입니다.

2021-01-13 06:21 UTC, sehan commented on src/main/java/lottomission/domain/UserMoney.java
> +    public UserMoney getLeftUserMoney(int lottoCount){
자동로또 구입수를 구하기 위해 lottoCount 를 구입하고 남은 금액을 계산하는 매소드를 추가한 걸로 보입니다. 
대신에 구입금액으로 구입할수 있는 로또수에서 수동입력한 로또수를 빼면 되지 않을까요? 
그러면 위 메소드를 제거할 수 있을거 같네요

2021-01-13 06:21 UTC, sehan commented on src/main/java/lottomission/domain/LottoResult.java
> +        if(userMoney.isUserMoneyZero()){
수익율을 계산하기 위해 구입금액을 입력 받고 있습니다. 
이 부분을 좀 생각해보니 LottoResult 에서 수익율 계산하는 부분을 분리하는건 어떨까? 하는 생각이듭니다. 
수익율을 계산해주는 계산기?? 같은 객체를 만들어 주면 LottoResult 에서 총 수익금(getSumAllWinngingMoney()) 을 얻어내고 구입금액 두가지만 알면 수익율을 계산해주는 객체를 만들어 주면 어떨가요? 

그리고 단위테스트가 없습니다. 추가해주세요

2021-01-13 06:21 UTC, sehan commented on src/main/java/lottomission/domain/Lottos.java
>      public List<List<Integer>> getLottosNumberList() {
단위테스트가 없습니다. 추가해주세요

2021-01-13 06:21 UTC, sehan commented on src/main/java/lottomission/domain/UserMoney.java
> +            throw new IllegalArgumentException("구입금액은 음수가 될 수 없습니다.");
단위테스트가 없습니다. 추가해주세요

2021-01-13 14:05 UTC, sehan approved these changes
피드백 잘 반영해 주셨습니다 👍 👍 👍 

객체에서 매소드들고 정리하고 나니 객체크기도 작아지고 더 명확해 졌네요.
몇번의 피드백에도 지치지 않고 끝까지 잘 마무리 해주셔서 감사합니다. 고생 하셨습니다. 
PR 은 여기서 merge 하도록 하겠습니다. 

코드에 코멘트가 없으면 정 없을까봐 매운맛으로 1단계로 하나 남겨놨습니다. 화이팅~~~

2021-01-13 14:05 UTC, sehan commented on src/main/java/lottomission/util/CalculatorForLotto.java
> +public class CalculatorForLotto {
수익률계산기를 만들어서 역할을 잘 분리 했네요 👍 
이 객체는 유틸성격이 강해서 rateOfProfit() 매소드를 static 으로 만드는것도 괜찮아 보입니다.
그리고 userdMoney 를 int 가 아닌 UserMoney 객체로 받고 
earnedMoney 도 int 가 포장객체를 생성해서 처리하면 isNotPositive() 나 isNegative() 같은 검증매소드 들도 제거 할 수 있을거 같습니다.

2021-01-13 14:08 UTC, sehan commented
혹, 코드의 테스트 커버리지 ( 단위테스트가 적용된 정도?? ) 가 궁금하다면 인텔리제이에서 쉽게 확인할 수 있습니다. 
test 를 실행하실때 그냥 Run 하지 마시고 "Run ..... with Coverage" 라는 실행메뉴가 있습니다. 한번 사용해 보세요 : )

2021-01-13 14:10 UTC, merged

2021-01-13 15:04 UTC, 10000sukk commented
감사합니다! 제 코드 보기가 쉽지 않았을 텐데...세심하게 피드백 해주셔서 정말 감사드립니다...😭😭 이런 매운맛이라면 언제 먹어도 질리지 않을거 같아요 ㅎㅎ 피드백을 니오한테 받아서 정말 기쁩니다...ㅎㅎ 정말 감사했습니다..😄