[pharrell.mp3 민필규] 로또 수동(step2)에 대해 PR 요청드립니다.
NewKrew2021/java-lotto-kakao pull request #66
Opened 2021-01-12 15:52 UTC by pilgyumin

안녕하세요! pharrell_(퍼렐,민필규)입니다.

로또 자동에 대한 피드백을 성심성의껏 작성해주셔서 정말 감사드립니다.
step1에 관한 피드백중에 해결되지 않은 점과 궁금한 점에 대해서는
코멘트로 질문하였습니다. 해당 부분 파악 부탁드리겠습니다.

이번 로또 수동(step2)에 대해서는 입력값에 대한 예외 상황이 날 수 있는 상황을
고민하였고, 그 고민을 바탕으로 예외 처리를 구현하였습니다.

또한, 사용자 정의 Exception을 구현하여, 예외 상황을 명확하게 전달하려고
노력하였습니다.

그리고 개인적으로 느낀 점은 step1때는 프로젝트 설계가 잘못되었다는 것을 느꼈습니다.
처음부터 다시하고 싶은 생각이 들었지만, 잘못된 설계가 된 코드를 리팩토링하는 능력을
키우기 위해 늦은 시간까지 진행하였고 이를 통해 뿌듯함을 얻었던 것 같습니다.

step2때도 리뷰어님이 주신 피드백을 바탕으로 좀 더 개선된 모습 보여드리겠습니다.

이번 피드백도 잘 부탁드리겠습니다.

감사합니다.

2021-01-13 09:17 UTC, ljh131 requested changes
안녕하세요. 몇 가지 개선할 수 있을 부분들 커멘트 드렸습니다. 한번 생각해보시고 수정해보시면 좋겠습니다. 
그리고 답변이 너무 늦어지는 것 같으면 제가 놓쳤을 수도 있으니 슬랙 dm으로 알려주시면 감사하겠습니다. 일단 이전 pr 질문은 해당 pr에 답변 드렸습니다.

2021-01-13 09:17 UTC, friediceday commented on src/main/java/domain/LottoRank.java
>              return LottoRank.SECOND;
이 부분은 이전 pr에 댓글로 설명드렸습니다. 참고해보시면 좋겠습니다.

2021-01-13 09:17 UTC, friediceday commented on src/main/java/domain/Lottos.java
> +    public List<Lotto> getAutoLottos() {
자동과 수동을 분리하셨는데요. 요구사항상 굳이 필요는 없어보이네요.
이렇게 두 리스트로 분리해놓으면 모든 메서드에서 둘 다 신경써야 하니까 좋진 않아보입니다.

만약 꼭 분리하고 싶다면 리스트를 나누는 것도 방법이지만, 로또 객체만 가지고 자동인지 수동인지 구분해볼 수 있겠습니다.
아니면 또 다른 방법으로 리스트는 2개를 유지하되 각각 직접 접근하지 않고 합친걸 리턴하는 메서드를 거치도록 할 수도 있고요.

2021-01-13 09:17 UTC, friediceday commented on src/main/java/domain/Lottos.java
> +        this.autoLottos = lottos;
이 생성자는 자동만 넣어주고 위 생성자는 자동을 생성하고 수동을 넣어주고 있네요.
둘다 같은 생성자인데 동작이 이렇게 다르면 좋지 않을 것 같습니다.

2021-01-13 09:17 UTC, friediceday commented on src/main/java/domain/Ball.java
> +    public Ball(String number) {
볼이 스트링을 직접 다루기보다는.. 외부에서 처리해주는게 좋지 않을까요?

2021-01-13 09:17 UTC, friediceday commented on src/test/java/domain/LottoTest.java
> +            new Lotto(Arrays.asList(new Ball(1), new Ball(7), new Ball(8),
이렇게 매번 생성하기엔 코드가 너무 복잡해지기 때문에 숫자 6개 받아서 리스트 만드는 헬퍼 메서드를 만드는것도 고려해볼만 합니다.

2021-01-13 09:17 UTC, friediceday commented on src/main/java/domain/Lottos.java
> +        for (Lotto lotto : autoLottos) {
두개를 분리해서 처리하게되면서 코드가 중복되네요.

2021-01-13 09:17 UTC, friediceday commented on src/main/java/MainApplication.java
> +        } catch (Exception e){
익셉션 열심히 처리하셨는데요, 사실 좋은 방법이라고 생각하지 않습니다. 처리할 수 없는 익셉션이면 던지는게 좋을 것 같아요.
지금 처리는 스택트레이스도 출력하지 않고 간단한 메시지만 출력하고 특별히 처리하는 것도 없네요.

2021-01-13 09:17 UTC, friediceday commented on src/main/java/controller/LottoProgram.java
> +            manualLottos.add(new Lotto(getBalls(lottoProgramView.getManualLottoForUser())));
수동 로또는 여기서 직접 생성해주고 있네요, 근데 자동 로또는 Lottos에서 생성하고요. 
비슷한 일을 한 객체가 담당하면 좋지 않을까요?

2021-01-13 09:17 UTC, friediceday commented on src/main/java/domain/Lotto.java
> +        this(RandomBallPool.getLottoBallList(LOTTO_COUNT));
이 객체도 생성자가 각각 하는일이 다른데요. 하나는 수동 입력받고 하나는 자기 스스로 자동을 생성하네요.
특히 자동 생성같은 경우 이 객체에서 하는게 과연 적절한지 생각해보시면 좋겠습니다.

2021-01-13 09:17 UTC, ljh131 commented on src/main/java/MainApplication.java
> +        try{
`키워드+공백+중괄호` 컨벤션을 일관성있게 해보면 좋겠습니다.

2021-01-13 14:57 UTC, pilgyumin commented on src/main/java/domain/LottoRank.java
>              return LottoRank.SECOND;
해당 부분에 대해 다시 질문 남겼습니다. 확인 부탁드리겠습니다!

2021-01-13 16:16 UTC, pilgyumin commented on src/main/java/domain/Lottos.java
> +        this.autoLottos = lottos;
네 두 로또를 같은 리스트로 통합하겠습니다!

2021-01-13 16:16 UTC, pilgyumin commented on src/main/java/domain/Lottos.java
> +        for (Lotto lotto : autoLottos) {
넵 lottos로 통합하겠습니다.

2021-01-13 16:18 UTC, pilgyumin commented on src/main/java/controller/LottoProgram.java
> +            manualLottos.add(new Lotto(getBalls(lottoProgramView.getManualLottoForUser())));
넵 LottoProgram에서 나온 수동 로또는 Lottos에 추가하는 방식으로 구현하겠습니다.

2021-01-13 16:26 UTC, pilgyumin commented on src/main/java/domain/Ball.java
> +    public Ball(String number) {
볼이 스트링을 다루는 이유는 아래와 같이 입력값 배열을 바로 List<Ball>로 바꾸기 위해서 구현하였습니다.
입력값 배열을 int[]로 바꾸고, int[]로 List<Ball>로 변환하는 것이 복잡하다고 생각이 들어서
아래와 같은 방식으로 구현하였습니다.
혹시 int[]을 파라미터로 받는 것이 더 좋다는 말씀이실까요???

`
public static List<Ball> getBalls(String[] numbers){
        return Arrays.stream(numbers)
                .map(Ball::new)
                .collect(Collectors.toList());
    }
`

2021-01-13 16:27 UTC, pilgyumin commented on src/main/java/domain/Lottos.java
> +    public List<Lotto> getAutoLottos() {
넵 해당 부분은 수동 로또와 자동 로또를 통합하여 관리하는 방식으로 개선하겠습니다!

2021-01-13 16:36 UTC, pilgyumin commented on src/main/java/MainApplication.java
> +        } catch (Exception e){
넵 해당 부분 수정하겠습니다!

2021-01-13 17:03 UTC, pilgyumin commented on src/main/java/domain/Lotto.java
> +        this(RandomBallPool.getLottoBallList(LOTTO_COUNT));
네 해당 부분 고려해서 수정하겠습니다.

2021-01-13 17:03 UTC, pilgyumin commented on src/main/java/MainApplication.java
> +        try{
넵 코드 포멧팅 하겠습니다,

2021-01-13 17:28 UTC, pilgyumin commented on src/test/java/domain/LottoTest.java
> +            new Lotto(Arrays.asList(new Ball(1), new Ball(7), new Ball(8),
넵 해당 부분 구현하겠습니다.

2021-01-14 03:03 UTC, ljh131 requested changes
점차 개선되고 있는 것 같습니다. 추가적으로 고민해볼 부분들은 커멘트 드렸으니 생각해보시고 수정해보시면 좋겠습니다.

2021-01-14 03:03 UTC, friediceday commented on src/main/java/domain/Ball.java
> +    public static Ball map(String number) {
그런데 이건 왜 필요한가요?

2021-01-14 03:03 UTC, friediceday commented on src/main/java/controller/LottoProgram.java
> +            lottos.addLotto(Lotto.makeLotto(Ball.getBalls(lottoProgramView.getManualLottoForUser())));
아래에서 설명하겠습니다만, 저는 여기서 문자열을 `List<Integer>`로 바꾸던지, 아니면 인풋이 애초에 리스트를 넘겨주던지 하는게 적절할 것 같아요.

2021-01-14 03:03 UTC, friediceday commented on src/main/java/domain/Ball.java
> +    public Ball(String number) {
볼이 스트링을 직접 처리하기 위해 여러개의 생성자와 메서드를 두는게 더 복잡할 것 같습니다.
가공된 데이터를 주고받는게 더 직관적이고 편하지 않을까요? 가공되지 않은 데이터를 여러 메서드를 거치면서 처리해 나가는 것 보다는요. 
그리고 뭐가 들어있는지도 모르는 데이터를 로직 안쪽까지 갖고 들어온다면 위험하지 않을까요. 그러면 위험을 없애기 위해 비지니스 로직만 수행하면 될 객체가 밸리데이션 체크도 해야되고요. (그럼 여기서 숫자가 1~45범위에 있는지 체크하는 건 뭐냐고 할 수 있는데, 이건 비지니스 로직의 요구사항에 가깝죠.)

2021-01-14 03:03 UTC, friediceday commented on src/main/java/utils/RandomBallPool.java
> +        for (int lottoNum = Ball.LOTTO_MIN; lottoNum <= Ball.LOTTO_MAX; ++lottoNum) {
유틸에 있는데 비지니스 로직이 연관되어있네요. 유틸이라면 로직에 얽히지 않고 general해야될 것 같습니다. 
아니면 유틸이 아닌 비지니스 로직으로 옮기던지요.

2021-01-14 03:03 UTC, friediceday commented on src/main/java/domain/Lotto.java
> +        while (balls.size() != LOTTO_COUNT) {
여기서 숫자 6개 뽑는것고 그렇게 뽑은 숫자로 객체 생성하는 두가지 일을 하고 있는데요. 분리하면 어떨까요?
더 구체적으로 얘기하면, 랜덤볼풀 클래스의 역할을 더 넓혀서 숫자 6개 뽑는것도 같이 해주는거죠.

그리고 이 객체는 로또 번호만 가지고 있으니, 랜덤 숫자를 뽑기는 컨트롤러 역할인 외부에서 해주는게 좋을 것 같아요.

2021-01-14 03:03 UTC, friediceday commented on src/main/java/domain/LottoRank.java
> +        if (sameCount(count, SECOND) && matchBonusBall) {
여기서 알려드리겠습니다.
아래와 같이 했을때 어떻게 로직을 만들어야 하는지 물어보신 것 같은데요.
```
SECOND(5, 30000000, true,"5개 일치, 보너스 볼 일치(30000000원)- "),
THIRD(5, 1500000, false,"5개 일치 (1500000원)- "),
```

이렇게 받은 3번째 인자를 checkBonusBall 이라고 하고, 아래 스트림 필터에 조건을 추가하면 되지 않을까요?

```
                .filter(lottoRank -> sameCount(count, lottoRank))
->
                .filter(lottoRank -> sameCount(count, lottoRank) && lottoRank.checkBonusBall ? matchBonusBall : true
```

2021-01-14 03:03 UTC, friediceday commented on src/main/java/domain/Lottos.java
> +    public Lottos(int autoCount) {
여기 생성자 2개가 서로 하는 일이 다릅니다. 이건 자동으로 알아서 생성해주는거고 밑에 생성자는 외부에서 생성한걸 넣어주네요.
메서드, 생성자가 같은 이름인데 하는일이 다르면 혼란스럽지 않을까요?

2021-01-14 03:03 UTC, friediceday commented on src/main/java/utils/RandomBallPool.java
> +        Collections.shuffle(randomPool);
1개만 넘겨주면 되는데 모든 배열을 셔플하는건 효율적이진 않아보이네요.

2021-01-14 03:04 UTC, ljh131 commented on src/main/java/domain/LottoRank.java
>              return LottoRank.SECOND;
이 pr에 답변 남겼습니다.

2021-01-14 14:29 UTC, pilgyumin commented on src/main/java/domain/Ball.java
> +    public Ball(String number) {
넵 알겠습니다 ball 생성자 파라미터이 가공된 데이터만 들어오게 수정하겠습니다!

2021-01-14 14:32 UTC, pilgyumin commented on src/main/java/domain/Ball.java
> +    public static Ball map(String number) {
아 이 부분을 생성자로 처리해도 되었는데, 그 부분을 고려하지 못하고 작성하였던 것 같습니다. 이 메소드는 ball의 생성자 파라미터를 int형태로 가공하여 들어오게 수정하여서 삭제하였습니다!

2021-01-14 14:42 UTC, pilgyumin commented on src/main/java/controller/LottoProgram.java
> +            lottos.addLotto(Lotto.makeLotto(Ball.getBalls(lottoProgramView.getManualLottoForUser())));
네 인풋이 리스트를 넘겨주는 방향으로 수정하였습니다!

2021-01-14 14:55 UTC, pilgyumin commented on src/main/java/utils/RandomBallPool.java
> +        for (int lottoNum = Ball.LOTTO_MIN; lottoNum <= Ball.LOTTO_MAX; ++lottoNum) {
네 RandomBallPool을 domain으로 옮기는 것이 적당할 것 같습니다. 반영하겠습니다!

2021-01-14 15:39 UTC, pilgyumin commented on src/main/java/domain/Lotto.java
> +        while (balls.size() != LOTTO_COUNT) {
넵 이해했습니다 객체의 역할을 분리하겠습니다!

2021-01-14 15:42 UTC, pilgyumin commented on src/main/java/utils/RandomBallPool.java
> +        Collections.shuffle(randomPool);
넵 수정하겠습니다!

2021-01-14 15:43 UTC, pilgyumin commented on src/main/java/domain/Lottos.java
> +    public Lottos(int autoCount) {
Lottos에 숫자를 파라미터로 받는 생성자를 제거하고, List형태로만 받을 수 있도록 수정하였습니다.

2021-01-14 16:24 UTC, pilgyumin commented on src/main/java/domain/LottoRank.java
> +        if (sameCount(count, SECOND) && matchBonusBall) {
.filter(lottoRank -> sameCount(count, lottoRank) && lottoRank.checkBonusBall ? matchBonusBall : true)

위에 작성해주신 식은 이해하였고, 저도 해당 로직을 생각했었습니다.
위의 필터에 대한 로직은

 [1번 케이스]

      FIRST(6, 2000000000, false,"6개 일치 (2000000000원)- "),
      SECOND(5, 30000000, true,"5개 일치, 보너스 볼 일치(30000000원)- "),
      THIRD(5, 1500000, false,"5개 일치 (1500000원)- "),
      FOURTH(4, 50000, false, "4개 일치 (50000원)- "),
      FIFTH(3, 5000, false,"3개 일치 (5000원)- "),
      NONE(2, 0, false,"0~2개 일치 (0원)- "),

이렇게 enum 클래스를 선언하였을 때, 정상적으로 작동합니다.

  [2번 케이스]

      NONE(2, 0, false,"0~2개 일치 (0원)- "),
      FIFTH(3, 5000, false,"3개 일치 (5000원)- "),
      FOURTH(4, 50000, false, "4개 일치 (50000원)- "),
      THIRD(5, 1500000, false,"5개 일치 (1500000원)- "),
      SECOND(5, 30000000, true,"5개 일치, 보너스 볼 일치(30000000원)- "),
      FIRST(6, 2000000000, false,"6개 일치 (2000000000원)- ");

하지만 이렇게 enum 클래스를 선언하였을 때는 SECOND일 경우에도 THIRD로 출력하는 현상이 발생합니다.

enum 클래스를 [1번 케이스]로 작성하고 filter를 피드백 주신 조건문으로 판단하는 방식으로 구현을 한다면, 어느 경우에도 정상 작동할 수 있다고 판단할 수 있을 지 궁금합니다!

2021-01-15 02:23 UTC, ljh131 reviewed
수고하셨습니다. 이번 미션은 여기에서 마무리하겠습니다.
몇 가지 커멘트 드렸으니 참고해보시면 좋겠습니다.

2021-01-15 02:23 UTC, friediceday commented on src/main/java/domain/LottoStatistics.java
> +        List<LottoRank> printRanks = Arrays.stream(LottoRank.values())
이렇게 하면 이넘 선언 순서대로 출력하게되는데, 선언 순서가 바뀌어도 출력 순서에 영향이 없으려면 어떻게 해야할까요?

2021-01-15 02:23 UTC, friediceday commented on src/main/java/domain/LottoRank.java
> +        if (sameCount(count, SECOND) && matchBonusBall) {
말씀하신대로 enum선언 순서에 관계없이 코드 상에서 보장해주는게 좋습니다.

가장 간단한 방법은, enum에 명시적으로 등수를 넣고 아래 당첨 판별 스트림에서 해당 등수로 sort를 하면 되지 않을까요?
다른 커멘트에서 제시한 출력 순서 문제도 그렇게 해결할 수 있고요.

2021-01-15 02:23 UTC, merged