[turner.lee] 로또 Step1 리뷰 부탁드립니다.
NewKrew2021/java-lotto-kakao pull request #7
Opened 2021-01-07 15:48 UTC by sumniy

안녕하세요 리뷰어님.
이번 미션은 클래스와 메서드를 분리하는게 굉장히 어려웠네요.
최대한 노력은 했지만 코드를 읽는데 불편함이 있으실 수도 있습니다. 😭
리뷰 잘 부탁드립니다. 🙇‍♂️

# 질문
* `InputView`를 사용했고, View 클래스는 입력에 대한 책임만 있어야 한다고 생각해서 입력받은 데이터만 넘겨주고, 실제 데이터를 이용한 객체 생성은 컨트롤러가 담당하게 했습니다. 그러다보니 컨트롤러의 코드가 지저분해졌는데, 가독성을 높이게 하기 위해서 `InputView` 클래스에 객체를 생성해서 반환하는 책임을 가지게 하는 방법은 클린 코드에 적합하지 않은 방법일까요?
* `List<LottoTicket>`에 대한 일급 컬렉션으로 `LottoTickets`를 만들어서 사용하는데, 이 `LottoTickets`에 대한 정보를 전달할 때에도 따로 객체를 만들어서 전달해줘야 할까요? (예를들어 `LottoTicketsDto`) 현재 `LottoTickets`은 데이터를 가공해서 정보를 추출해주는 책임만 가지고 있습니다.

2021-01-07 19:48 UTC, Hue9010 requested changes
안녕하세요. 이번 리뷰를 맡은 휴입니다. 😄 
객체 분리도 잘하셨고 전반적으로 군더더기 없이 깔끔히 잘 짜주셨네요. 👍 
질문 주신 사항 답변과 피드백 남겼는데 확인하시고 궁금하신 사항 있으면 문의해주세요.

2021-01-07 19:48 UTC, Hue9010 commented on src/test/java/domain/LottoNumberTest.java
> +    @ValueSource(ints = {1, 45})
ParameterizedTest , ValueSource 😮 👍

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/domain/LottoNumber.java
> +    }
Override 메서드 사이에 직접 작성한 메서드를 넣지 말아주세요.

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/domain/exceptions/InvalidLottoNumberException.java
> +public class InvalidLottoNumberException extends RuntimeException{
👍👍👍👍👍

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/domain/LottoTicket.java
> +    }
of 네이밍을 사용하는 정적 팩토리 메서드 명에 타입은 넣을 필요 없다고 봅니다. of 네이밍이 겹쳐도 자동적으로 오버로딩 되어 사용되고 시그니처를 통해 어떤 타입이 필요한지 알 수 있어 불필요하다고 생각됩니다.
실제 흔히 사용하는 Integer도 valueOf(int i), valueOf(String s)로 타입을 명시하진 않습니다. 다만, 이런 컨벤션은 개인/팀마다 조금씩 다를 수 있는점은 감안해주세요. 😉

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/domain/LottoTicket.java
> +        return numbers.stream().map(LottoNumber::getNumber).collect(Collectors.toList());
스트림에 보통 아래 처럼 연산마다 줄바꿈을 해주는 편입니다.
```java
        return numbers.stream()
                .map(LottoNumber::getNumber)
                .collect(Collectors.toList());
```

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/domain/LottoTicket.java
> +    }
List<LottoNumber>를 외부에 드러내지 않고 캡슐화 시켰군요. 💯

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/domain/WinningInfo.java
> +    private final List<Integer> info;
PRIZE와 info 둘 다 리스트 순서에 의존하고 있네요. PRIZE를 Enum으로 바꿔주고 info는 List로 순서에 의존하지 말고 Map<Prize, Integer> info로 관리해보세요.  😉
Enum은 [Enum 활용사례 3가지](https://jojoldu.tistory.com/137)를 참고하면 좋을 것 같아요.

위 두가지를 적용하면 계산 과정이 크게 바뀔걸로 예상돼서 이번 피드백에서는 계산은 크게 다루지 않은점 참고부탁드려요. 🙏

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/view/LottoOutputView.java
> +        System.out.println(String.format("총 수익률은 %.2f입니다.", yield));
String.format 은근히 아시는 분이 적은데 😮 👍 

String을 잘 다루시는걸 보니 이미 아실 것 같지만 간단한 문자열 더하기 연산은 자동으로 최적화가 됩니다. 
[jdk1.5에서 String 더하기의 컴파일시의 최적화](https://gist.github.com/benelog/b81b4434fb8f2220cd0e900be1634753)

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/domain/Amount.java
> +    }
단순 getter인 getAmount는 테스트가 필요없지만 getCount는 단순 getter가 아니기 때문에 테스트를 작성해주세요.
참고로 getter를 테스트하는 것에 대한 의견은 사람마다 다를 수 있습니다.

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/domain/Amount.java
> +    public static final int LOTTO_PRICE = 1000;
private!

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/domain/LottoNumber.java
> +        if (number < 1 || number > 45) {
1, 45를 상수화 하는 것에 대해서는 반반인 입장인데 LottoService에서는 LOWER/UPPER_BOUND를 사용 중이네요. 그렇다면 로또 번호 상 제약이니 LottoNumber 에서 관리하는게 좋아 보입니다.

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/domain/LottoTicket.java
> +                .collect(Collectors.toList());
Optional 👏

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/domain/LottoTicket.java
> +        Set<LottoNumber> numbersSet = new HashSet<>(numbers);
Set을 이용한 중복 제거 💯

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/domain/LottoController.java
> +        LottoOutputView.printYield(amount, winningInfo.getSumPrize());
printYield를 보면 총 상금을 사용하지 않는데 winningInfo를 통해 수익률을 계산할 수 있을 것 같네요. 🤔

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/domain/LottoTickets.java
> +public class LottoTickets {
> List<LottoTicket>에 대한 일급 컬렉션으로 LottoTickets를 만들어서 사용하는데, 이 LottoTickets에 대한 정보를 전달할 때에도 따로 객체를 만들어서 전달해줘야 할까요? (예를들어 LottoTicketsDto) 현재 LottoTickets은 데이터를 가공해서 정보를 추출해주는 책임만 가지고 있습니다.

`LottoTickets에 대한 정보를 전달할 때`가 View를 말씀 하시는 거라면 만들어줘야 합니다. 정확히는 LottoTickets의 List<LottoTicket>도 Dto 만들어야 합니다.

```java
public class LottoTicketsDto {
    private List<LottoTicketsDto> lottoTickets;
```

이번 미션처럼 콘솔이 아니라 웹이였다면 아래와 같은 네이밍의 DTO를 만들었을 것 같네요.

```java
public class LottoTicketsResponse {
    private List<LottoTicketsResponse> lottoTickets;
```

DTO는 Data Transfer Object 뜻 그대로 데이터 전달만을 목적으로 하는 객체인데 터너(이렇게 부르는게 맞나요? 😋 )도 말씀하신 것 처럼 LottoTickets는 Lotto List의 관리를 하고 있습니다. 이미 DTO의 정의를 벗어 났습니다. 그래서 질문 의도에 맞춰 답변 드리면 DTO를 만드는게 맞습니다.
그러면 이번에 DTO를 만들어야 하냐면 No입니다. 우선 DTO를 만들어 얻을 수 있는 이점이 없고 그에 비해 지나치게 프로젝트가 복잡해지기 때문입니다.

워낙 옛날 글이라 요즘은 다른 견해를 가지고 계실 수도 있는데 [혹시 DTO(VO) 작성하시나요?](https://www.slipp.net/questions/22)라는 글에서 익숙하신 분이 보이네요. 🙄

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/domain/LottoController.java
> +    }
> InputView를 사용했고, View 클래스는 입력에 대한 책임만 있어야 한다고 생각해서 입력받은 데이터만 넘겨주고, 실제 데이터를 이용한 객체 생성은 컨트롤러가 담당하게 했습니다. 그러다보니 컨트롤러의 코드가 지저분해졌는데, 가독성을 높이게 하기 위해서 InputView 클래스에 객체를 생성해서 반환하는 책임을 가지게 하는 방법은 클린 코드에 적합하지 않은 방법일까요?

[🚀 2단계 - 자동차 경주 리팩토링](https://edu.nextstep.camp/s/bb4PXLji/ls/W1LFM86E)에 있는 그림을 다시 한번 보죠!

![mvc](https://firebasestorage.googleapis.com/v0/b/nextstep-real.appspot.com/o/lesson-attachments%2F-L9D5L4Xj_6xjTfOTRks%2Fdomain.PNG?alt=media&token=5083069f-e922-4f0e-95a4-d3fb9fb95224)

클린코드는 넓은 의미를 가지니 범위를 좁혀 얘기하면 MVC 패턴에 맞지 않습니다. MVC 패턴을 적용했지만 MVC 패턴을 제대로 적용하지 못한 점에서 클린 하지 못하다고 볼 수 있겠네요.

위 그림 위에
> MVC 패턴 기반으로 리팩토링해 view 패키지의 객체가 domain 패키지 객체에 의존할 수 있지만, domain 패키지의 객체는 view 패키지 객체에 의존하지 않도록 구현한다

라는 언급이 있는데 이는 패키지 의존성에 한정 된 얘기입니다.(View에서 Model을 화면에 출력해야하니까 허용)

 View가 지금의 자바 환경이 아닌 웹 페이지로 생각해보시면 조금 더 이해가 빠를 수도 있을 것 같네요. 😉 View에서 객체 생성을 하게 되면 View를 콘솔이 아닌 웹페이지로 변환이 가능할까요?

2021-01-07 19:48 UTC, Hue9010 commented on src/main/java/domain/LottoController.java
> +    }
Controller가 domain 패키지에 위치하고 있네요. 알맞은 패키지를 만들어서 옮겨주세요. 😉

2021-01-07 19:48 UTC, Hue9010 commented on src/test/java/domain/LottoTicketTest.java
> +    }
예외가 발생하고 있는 케이스까지 꼼꼼하게 잘 해주셨네요. 👍

2021-01-08 07:09 UTC, sumniy commented on src/main/java/domain/LottoTicket.java
> +    }
말씀 듣고 다시 보니 확실히 넘겨주는 타입으로 알 수 있다는 생각이 드네요. 알려주셔서 감사합니다 🤗

2021-01-08 07:10 UTC, sumniy commented on src/main/java/domain/LottoTicket.java
> +        return numbers.stream().map(LottoNumber::getNumber).collect(Collectors.toList());
앗 ㅎㅎ 감사합니다

2021-01-08 07:12 UTC, sumniy commented on src/main/java/domain/WinningInfo.java
> +    private final List<Integer> info;
거의 하드코딩에 가까운 방법이어서 고민하고 있던 부분인데, 좋은 방법 알려주셔서 감사합니다! 훨씬 관리하기 편해지고 가독성이 좋아질 것 같네요!

2021-01-08 07:12 UTC, sumniy commented on src/main/java/view/LottoOutputView.java
> +        System.out.println(String.format("총 수익률은 %.2f입니다.", yield));
헉 그 부분은 모르고 있었네요 🙇‍♂️

2021-01-08 07:17 UTC, sumniy commented on src/main/java/domain/LottoController.java
> +        LottoOutputView.printYield(amount, winningInfo.getSumPrize());
그렇게 하는편이 뷰에서 연산하는 로직도 뺄 수 있겠네요

2021-01-08 07:19 UTC, sumniy commented on src/main/java/domain/LottoTickets.java
> +public class LottoTickets {
Dto에 대한 개념이 잘 잡힌 것 같습니다 감사합니다! (터너 맞습니다 👌)

2021-01-08 07:23 UTC, sumniy commented on src/main/java/domain/LottoController.java
> +    }
웹 페이지로 생각해보니 바로 이해가 갔습니다 ㅎㅎ 감사합니다 😀

2021-01-11 06:55 UTC, sumniy commented
피드백 반영했습니다. 리뷰 부탁드립니다!

2021-01-11 11:11 UTC, Hue9010 approved these changes
안녕하세요. 터너~!! 피드백 반영 잘해주셨네요. 👍
추가 피드백을 남겼는데 다음 단계를 진행하면서 같이 반영해 주시면 될것 같아요. 😉
궁금한 사항은 언제든 질문주세요.
고생하셨습니다!

2021-01-11 11:11 UTC, Hue9010 commented on src/main/java/domain/LottoNumber.java
> +  }
LottoTicket에서 null 체크를 해주긴 하지만 LottoNumber도 스스로 null에 대한 처리를 해야합니다. 지금은 validateRange의 if문에서 예외가 발생할것 같네요.

2021-01-11 11:11 UTC, Hue9010 commented on src/main/java/domain/LottoNumber.java
> +public class LottoNumber implements Comparable<LottoNumber> {
캐싱을 적용해 인스턴스 생성을 최소화 할 수 있을 것 같아요. 캐싱에 대해서는 너무 어렵게 생각하실 필요는 없습니다.

간단한 퀴즈를 하나 드려볼게요.
```java
Integer a = 127; 
Integer b = 127;
```
> a == b (true? false?)

a == b 의 답은 뭘까요?

[[Java] Integer.valueOf(127) == Integer.valueOf(127) 는 참일까요?](https://meetup.toast.com/posts/185)
이런 퀴즈와 포스팅을 공유 드린점에서 답을 유추할 수도 있지만 한번 곰곰히 생각해보신 다음 보시길 바랄게요. 😉

2021-01-11 11:11 UTC, Hue9010 commented on src/main/java/domain/LottoRank.java
> +  }
getPrize라는 이름은 단순위 Rank의 상금만을 주는 메서드로 오인 할 여지가 있네요.

2021-01-11 11:11 UTC, Hue9010 commented on src/main/java/domain/LottoRank.java
> +  private final Function<Long, Long> expression;
Function 인터페이스는 기본 타입을 반환하는 변형이 존재하는데 그중 int를 받아 long을 반환하는 인터페이스는 IntToLongFunction랍니다. 😉 

이번 내용과 직접적인 연관은 없지만 관련된 내용을 다뤘을 때 참고하면 아무래도 기억에 좀더 오래 남으니 볼만한 포스팅 추천드려요.
이펙티브 자바 3판 [[Effective Java] Item 44. 표준 함수형 인터페이스를 사용하라](https://icarus8050.tistory.com/94)

2021-01-11 11:11 UTC, Hue9010 commented on src/main/java/domain/LottoTickets.java
> +      LottoRank rank = LottoRank.of(getRank(matchedCount, matchedBounus));
두가지를 개선 할 수 있을 것 같네요.
우선 꽝인 경우에 대한 LottoRank를 추가하면 숫자가 하나도 일치하지 않을 때 skip하는 로직을 제거할 수 있지 않을까요? (들여쓰기도 두번 이뤄졌습니다!)

matchedCount, matchedBounus 값에 따라 어떤 등수가 되는지는 LottoRank한테 위임할 수 있지 않을까요?

2021-01-11 11:11 UTC, Hue9010 commented on src/main/java/domain/LottoTickets.java
> +      LottoRank rank = LottoRank.of(getRank(matchedCount, matchedBounus));
List의 인덱스 값으로 등수를 관리하던 이전 코드를 보면 엄청나게 개선 하신 걸 알 수 있죠. 👍 💯

```java
    public static final int MIN_MATCH_COUNT = 3;

    public WinningInfo getWinningInfo(LottoWinningNumber lottoWinningNumber) {
        List<Integer> winningInfo = new ArrayList<>(Arrays.asList(0, 0, 0, 0, 0));
        for (LottoTicket lottoTicket : lottoTickets) {
            checkLottoTicket(lottoWinningNumber, winningInfo, lottoTicket);
        }

        return new WinningInfo(winningInfo);
    }

    private void checkLottoTicket(LottoWinningNumber lottoWinningNumber, List<Integer> winningInfo,
        LottoTicket lottoTicket) {
        int winningInfoIndex = 0;
        int matchedCount = lottoWinningNumber.getMatchedCount(lottoTicket);

        if (matchedCount < MIN_MATCH_COUNT)
            return;

        if (isSecond(lottoWinningNumber, lottoTicket, matchedCount) || isFirst(matchedCount)) {
            winningInfoIndex = 1;
        }
        updateWinningInfo(winningInfo, winningInfoIndex, matchedCount);
    }

    private void updateWinningInfo(List<Integer> winningInfo, int winningInfoIndex, int matchedCount) {
        winningInfoIndex += matchedCount - MIN_MATCH_COUNT;
        winningInfo.set(winningInfoIndex, winningInfo.get(winningInfoIndex) + 1);
    }

    private boolean isFirst(int matchedCount) {
        return matchedCount == LottoTicket.LOTTO_NUMBERS_LENGTH;
    }

    private boolean isSecond(LottoWinningNumber lottoWinningNumber, LottoTicket lottoTicket,
        int matchedCount) {
        return matchedCount == LottoTicket.LOTTO_NUMBERS_LENGTH - 1 && lottoWinningNumber.isContainsBounusNumber(lottoTicket);
    }
```

사실 List일 땐 첫번째 요소가 일등일지 꽝일지부터 파악하고 로직 분석을 했네요. 😋

2021-01-11 11:11 UTC, merged

2021-01-11 12:39 UTC, sumniy commented
꿀같은 정보들 알려주셔서 감사합니다!! 👍👍👍 다음 단계에 적용해보겠습니다!