[eli.nabro(일라이, 오영민)] 로또 step2 코드리뷰 요청드립니다.
NewKrew2021/java-lotto-kakao pull request #70
Opened 2021-01-13 16:53 UTC by maireneu

안녕하세요! 일라이입니다.
늦어서 죄송합니다. 로또 수동 step2 를 구현했습니다.

## File 목록
### controller
- LottoGame : 로또 게임 flow 제어

### domain
- LottoNo : 로또 번호 객체
- LottoTicket : 로또 티켓 객체
- PurchaseList : 구입목록 객체
- StatisticsResult : 매칭 결과 객체
- WinningLottoNos : 당첨 로또 티켓 객체
- StatisticsType : 로또 당첨 Ranking enum
- Validation : 예외 처리 class 

#### strategy
- AutoBuyingStrategy : 로또 자동 구입 객체
- ManualBuyingStrategy : 로또 수동 구입 객체
- BuyingStrategy : 로또 구입 전략패턴 인터페이스

### Service
- LottoLogic : 로또 구입, 당첨로또와 매칭

### view
- LottoInputView : Input UI view
- LottoOutputView : Output UI view

### 기타
- LottoGameMain : main 함수

질문이 두가지 있습니다.
1. 전략패턴에서 인터페이스에 생성자를 처리 못한 부분이 약간 아쉽던데.. 이 경우에는 상속과 추상메서드로 구현하는게 더 나을까요?
2. LottoInputView 에서 input 처리부분은 엄밀히 말하면 컨트롤러에 속하는게 맞을까요...? 간단한 콘솔 프로그램이라선지 다른 분들도  view에 넣는거 같아서 일단 view에 넣었어요.

항상 감사합니다!

2021-01-14 14:12 UTC, limmmee-bonjour requested changes
안녕하세요 Eli! 벨입니다 😄 
이전 리뷰에 요청드린 부분을 잘 반영해주셨어요 👍 
다만 질문 주신 전략패턴에 대해 조금 더 고민해 보면 좋을 것 같은 부분이 있어 코멘트 남겨 두었습니다!
질문 사항이 있으시다면 언제든지 DM 주셔요 :)

2021-01-14 14:12 UTC, limmmee-bonjour commented on src/main/java/lotto/controller/LottoGame.java
> +    private static final String MANUAL_LOTTO_INPUT_TEXT = "수동으로 구매할 번호를 입력해 주세요.";
이 Text는 LottoInputView의 관심사 일 것 같은데요 :) 어떻게 생각하시나요?

2021-01-14 14:12 UTC, limmmee-bonjour commented on src/main/java/lotto/controller/LottoGame.java
> +    private PurchaseList createPurchaseList() {
요 부분도 LottoGame에서 알기 위한 관심사라기보다는 LottoInputView에서 알아야할 관심사 인 것 같습니다.
단순 금액을 받고, 수동 로또 카운트를 받고 수동 로또 번호를 받는 것 이니까요!

[ 도전! ] LottoGame과  LottoInputView의 경계를 좀 더 확실히 나누어주세요 :) 
입출력에 관련된 부분은 입출력으로 옮기고 DTO를 통해서만 데이터가 왔다갔다 할 수 있도록 합시다 !

2021-01-14 14:12 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/LottoNo.java
> +            throw new IllegalArgumentException("잘못된 로또 번호 입니다.");
Exception에 메세지를 잘 적어주셨습니다 👍

2021-01-14 14:12 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/LottoNo.java
> +    }
1부터 45까지의 수를 미리 캐싱해서 정적 팩토리 메서드에서 사용하는 get하여 사용하는 이유가 있을까요..?
int 를 LottoNo 으로 만들때 lottoNumberBasket, lottoNoCache 필요한 이유를 알고 싶어요 :)!

2021-01-14 14:12 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/Validation.java
> +public class Validation {
Validation은 domain 위치보다는 utils 와 같은 패키지를 만들어서 그 하위에 위치시켜주는게 좋습니다 :)

2021-01-14 14:12 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/StatisticsType.java
> +    }
하나의 메소드로 만들어주셨네요 👍 💯

2021-01-14 14:12 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/strategy/AutoBuyingStrategy.java
> +public class AutoBuyingStrategy implements BuyingStrategy{
Q. 전략패턴에서 인터페이스에 생성자를 처리 못한 부분이 약간 아쉽던데.. 이 경우에는 상속과 추상메서드로 구현하는게 더 나을까요?
A. 전략패턴에 대해 질문을 주셨으니, 전략 패턴에 대해 얘기해보겠습니다 :)

BuyingStrategy 는 "로또 만드는 방법"에 대해서 알고 싶은거겠죠?
그렇다면, 해당 인터페이스를 구현한 AutoBuyingStrategy, ManualBuyingStrategy 에서 
PurchaseList 를 멤버 변수로 가지는 이유가 있을까요?
단지 로또 만드는 방법은 buyTicket()을 호출하면, Set<Integer>(혹은 Set<LottoNo>)와 같이 6개의 로또 번호만 리턴하면되는 것이지, 몇개를 만들어야할지 어디에 저장해야할지와 같은 세부사항을 알 필요가 있을까요?
이런 로직은 해당 전략이 아닌 다른 비즈니스 로직에서 해주어야할 것 같습니다.
(예를들어 해당 전략을 주입받은 LottoTicket 생성자를 만들수 있겠죠? 그리고 해당 생성자에서는 주입받은 전략을 실행시켜 로또 번호만 받아올 수 있겠죠. 관심사를 분리시켜 줍시다!)

ManualBuyingStrategy 뿐 아니라, scanner를 통해서 입력을 받는 전략 또한 만들 수 있지 않을까요? (물론 여기에는 for 문이나, while 문은 없을 것입니다.) 왜냐하면 몇개를 만들지는 이 전략패턴의 관심사가 아니거든요!
이 전략패턴은 단지 로또1장을 만드는 법이니까요 :)

이처럼 현재 전략패턴에는 너무 많은 요구 사항이 담겨져있고 많은 비즈니스 로직이 추가되어있습니다.
그렇게 되면 전략패턴을 쓰더라도 복잡해져서 자꾸 해당 전략이 커지게 됩니다.
추후 공부하시게 되면 "단일 책임 원칙"에 대해 많이 고민하게 될 것 같은데요. 해당 인터페이스도 변경의 이유는 딱 하나여야합니다.
로또를 어떻게 만들것인가이죠. 몇개를 만들지, 어디에 저장해야할지는 이 전략의 관심사가 아닙니다.

또한 말씀해주신대로 상속과 추상메서드는 인터페이스와 달리 확장이나 의존성에 대한 결합도가 큽니다.
따라서 현 상황에서는 상속과 추상메서드 보다는 전략패턴을 단 하나의 관심사만 갖도록 분리해주시는게 좋을 것 같습니다 :)

[ 도전! ] 자, 그럼 전략패턴이 단 하나의 관심사만 갖고, 나머지는 다른 로직에서 처리할 수 있도록 디벨롭해볼까요?

2021-01-14 14:12 UTC, limmmee-bonjour commented on src/main/java/lotto/service/LottoLogic.java
> +public class LottoLogic {
Servie 레이어에 비즈니스 로직을 위치 시키기 보다는 각 객체에서 해당 작업을 할 수 있도록 하는 방법도 고민해보아요 :) 
각 도메인에 해당하는 행동을 올바른 위치로 변경하거나, DTO 또는 일급컬렉션을 만드는 것도 방법이 될 수 있답니다 !

2021-01-14 14:12 UTC, limmmee-bonjour commented on src/main/java/lotto/view/LottoInputView.java
> +        } while(!validateMoney(money));
네이밍 변경 👍 👏

2021-01-14 14:12 UTC, limmmee-bonjour commented on src/test/java/lotto/domain/PurchaseListTest.java
> +public class PurchaseListTest {
Test가 각각 어떤일을 하고 있는지 한눈에 알 수 없네요 :)
[ 도전! ] @DisplayName 어노테이션으로 해당 테스트의 목적을 나타내주세요

2021-01-14 14:12 UTC, limmmee-bonjour commented on src/test/java/lotto/domain/ValidationTest.java
> +    )
로또번호, 보너스번호를 테스트하고 싶으신걸까요~?
아래와 같이 좀 더 가독성있게 테스트케이스를 작성하실 수 있습니다.

```suggestion
@CsvSource(value = {
            "1,2,3,4,5,6 | 3",
            "1,2,3,4,5,6 | 0",
            "1,2,3,4,5,6 | 46",
            "1,2,3,4,5,5 | 0",
            "1,2,3,4,5,6 | 7"
    }, delimiter = '|')
```

2021-01-14 14:12 UTC, limmmee-bonjour commented on src/main/java/lotto/view/LottoInputView.java
>          do {
Q. LottoInputView 에서 input 처리부분은 엄밀히 말하면 컨트롤러에 속하는게 맞을까요...?
 간단한 콘솔 프로그램이라선지 다른 분들도 view에 넣는거 같아서 일단 view에 넣었어요.

A. 여기가 위치가 아닌 것 같지만^^; 이 질문에 대한 답은 여기서 드릴게요!
제가 정확하게 질문을 이해 못한 것 같아 혹시 원하는 답이 아니라면 DM 주세요 :)

보통 입출력은 도메인과 영향이 없도록 Controller에서 정의하고 해당 데이터를 DTO로 한번 변환한 후 해당 DTO를 서비스, 도메인으로 넘겨줍니다. 그렇다고 해서 입출력이 컨트롤러에 속한다는 말은 조금 어울리지 않는 것 같습니다.
입출력은 입출력으로 독립적으로 만들어져야 하고, 생성자 혹은 static하게 데이터를 가져올때만 (DTO를 가져올때만 Controller에서 정의합니다.)

가장 이상적인 방법은 아래와 같은 소스 코드 한줄이 컨트롤러에 정의되는 것 입니다.
(입력과 관련된 부분은 모두 LottoInputView에 있어야겠죠?)
```
PurchaseList puchaseList = LottoInputView.input();
```

2021-01-17 16:07 UTC, maireneu commented on src/main/java/lotto/controller/LottoGame.java
> +    private static final String MANUAL_LOTTO_INPUT_TEXT = "수동으로 구매할 번호를 입력해 주세요.";
해당부분을 LottoInputView로 이동하였습니다!

2021-01-17 16:33 UTC, maireneu commented on src/main/java/lotto/controller/LottoGame.java
> +    private static final String MANUAL_LOTTO_INPUT_TEXT = "수동으로 구매할 번호를 입력해 주세요.";
해당부분을 모두 LottoGame으로 이동하였습니다!

2021-01-17 17:30 UTC, maireneu commented on src/main/java/lotto/controller/LottoGame.java
> +    private PurchaseList createPurchaseList() {
제가 아는 DTO 에 대한 지식을 최대한 활용해서, service와 view가 DTO에 의해서 데이터를 전달하거나 받고, controller 에서는 DTO 생성만 하되 관심없는 데이터가 노출되지 않도록 수정하였습니다.

제가 컨트롤러, 뷰, 서비스, DTO 등 각 객체의 역할에 대해서 이론적 지식만 약간 알고, 제대로 구현해본적이 없어서 적절하게 사용했는지 잘 모르겠습니다..

2021-01-17 17:30 UTC, maireneu commented on src/main/java/lotto/domain/LottoNo.java
> +            throw new IllegalArgumentException("잘못된 로또 번호 입니다.");
감사합니다!

2021-01-17 17:36 UTC, maireneu commented on src/main/java/lotto/domain/LottoNo.java
> +    }
우선 1부터 45 lottonumber를 캐싱하는 이유는, 티켓을 무척 많이 구입했을때 lotto number의 객체가 무척 많이 생성되는 문제를 방지하기 위함입니다.

10만개의 티켓을 구입하면 로또 번호는 60만개의 객체를 생성해야하나, 1부터 45까지 객체만 미리 만들어두고 static으로 사용하면 45개의 객체만 사용해도 된다고 강의에서 배웠는데요.. 
제가 혹시 잘못 이해한 부분이 있을까요?

lottoNumberBasket은 자동으로 로또 구매시, 45개 번호가 담긴 List<LottoNos> LottoNumberBasket을 collection.shuffle을 통해서 랜덤 정렬하고, 6개를 꺼내는 작업을 하기 위함입니다.

랜덤을 만드는 다른 방법도 많을것 같은데, 과제 요구사항에 collection.shuffle을 사용하라고 언급이 있어서 위 처럼 구현하였습니다.

2021-01-17 17:36 UTC, maireneu commented on src/main/java/lotto/domain/Validation.java
> +public class Validation {
util 패키지를 만들고 해당 부분으로 이동하였습니다! 감사합니다.

2021-01-17 17:36 UTC, maireneu commented on src/main/java/lotto/domain/StatisticsType.java
> +    }
감사합니다.

2021-01-17 17:40 UTC, maireneu commented on src/main/java/lotto/service/LottoLogic.java
> +public class LottoLogic {
LottoLogic을 LottoService로 변경하고, DTO애 객체를 생성하는 작업들로 변경하였습니다!

2021-01-17 17:40 UTC, maireneu commented on src/main/java/lotto/view/LottoInputView.java
> +        } while(!validateMoney(money));
감사합니다!

2021-01-17 17:42 UTC, maireneu commented on src/main/java/lotto/view/LottoInputView.java
>          do {
자세한 설명 정말 감사드립니다! 말씀하신대로 DTO를 이용해서 입출력의 정보를 저장하도록 변경하였습니다.
DTO와 입출력View는 Controller에서 생성하도록 변경하였습니다.

이렇게 하는게 맞을까요?

2021-01-17 17:55 UTC, maireneu commented on src/test/java/lotto/domain/PurchaseListTest.java
> +public class PurchaseListTest {
모든 테스트에 대해서 @DisplayName을 적용하였습니다!

2021-01-17 18:01 UTC, maireneu commented on src/test/java/lotto/domain/ValidationTest.java
> +    )
정말 감사합니다! 이걸 몰라서 노가다로 다 적어주고 있었네요 ㅠㅠ...

2021-01-17 18:39 UTC, maireneu commented on src/main/java/lotto/domain/strategy/AutoBuyingStrategy.java
> +public class AutoBuyingStrategy implements BuyingStrategy{
전략패턴에 대한 자세한 설명 정말 감사드립니다! 전략패턴에서 PurchaseList 를 제거하고, LottoTicket 한장을 생성해서 반환하도록 변경하였습니다. 다만 ManualBuyingStrategy의 경우, 수동 로또 번호가 필요하여 DTO를 확인하도록  하였습니다.

2021-01-18 09:38 UTC, limmmee-bonjour requested changes
안녕하세요 Eli! 벨입니다 :)
제가 드린 코멘트에 대해 잘 반영해주셨어요 👍 👏 
다만 DTO 관련 + 소소한 부분 의견을 조금 드렸습니다 :)
approve해도 되지만 조금 더 완성도 높은 코드를 위해 한 번 더 달려볼까요?
궁금하신점이 있으시면 언제든지 DM 주시기 바랍니다. 화이팅입니다!

2021-01-18 09:38 UTC, limmmee-bonjour commented on src/main/java/lotto/controller/LottoGame.java
> +        lottoOutputView = new LottoOutputView(lottoDto);
DTO에 대해 고민 많으해주셨네요 👍 
그런데, LottoGame을 만들때마다 LottoDto를 만들어서 Service, InputView, OuputView를 만들 때 생성자 주입을 해준다면, 현재 로직에서는 문제가 없지만 "동시성"이 있는 시스템인 경우는 어떻게될까요? 누군가 lottoDto를 사용하고 있는데, 누군가는 그걸 바꿔버리면..? 
Dto는 보통 생성자에 셋팅해주는 것보다는, param으로 이동하는것이 좋습니다.

```
LottoDto lottoDto = lottoInputView.inputMoney();  
lottoService.makePurchaseList(lottoDto);
```

2021-01-18 09:38 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/LottoDto.java
> +    private int bonusNumber;
LottoDto에 너무 많은 관심사가 담겨있어요!
DTO는 보통 레이어 간의 데이터를 이동(?) 시켜주는 중간 단계 계층이라고 할수 있어요!
DTO를 쪼개는 것을 추천드려요 !

- 입력 <-> 도메인 : 입력을위한DTO
    - 또한 입력을 위한 DTO는 한개만 있는 것이 아니라 상황에 따라 여러개가 존재할 수 있습니다!
- 도메인 <-> 출력 : 출력을위한DTO

[도전! ] DTO를 입력 (or 출력) 에 맞게 나누고 생성자로 주입하지 말고 param으로 이동할 수 있게 수정해주세요
[해당글](https://velog.io/@gillog/Entity-DTO-VO-%EB%B0%94%EB%A1%9C-%EC%95%8C%EA%B8%B0) (해당 글에 연관된 글도 함께 읽어보면 좋아요!)을 읽어보면 도움이 될거예요 :)

2021-01-18 09:38 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/LottoNo.java
> +    }
제가 질문을 드렸던 이유는 이 로직이 여기에 있는게 맞을까? 하는 의문이 있었어요!

lottoNumberBasket을 정의해서 미리 만들어 놓는 것은 좋은 아이디어 입니다 👍  
(당연히 매번 만드는게 아니라 미리 만들어져 있어야겠지요?)
그런데 basket은 랜덤으로 로또를 만들때만 있으면 될 것 같은데, AutoBuyingStrategy 전략에 위치하는건 어때요?
게다가 LottoNo 정적 팩토리 메서드에서 굳이 캐싱한 값을 넘겨줘야할까요?
그냥 new LottoNo(number) 로 만들어주면 안될까요?~

2021-01-18 09:38 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/PurchaseList.java
> +            throw new IllegalArgumentException("잘못된 금액을 입력하셨습니다.");
동일한 에러메세지는 상수화 시켜주시는게 좋겠죠~? 😉 
추가로 1000원도 상수화 시켜 의도를 나타내 보아요 ^^!

2021-01-18 09:38 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/StatisticsType.java
> +    SIX (6, 2000000000, false );
일반적으로 금액은 천 단위로 _ 를 포함시켜 가독성을 높이는 것이 좋습니다! :)
ex) 2_000_000_000

2021-01-18 09:38 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/WinningLottoNos.java
> +import lotto.util.Validation;
패키지 옮겨주셨네요 💯

2021-01-18 09:38 UTC, limmmee-bonjour commented on src/main/java/lotto/view/LottoInputView.java
> +    private static final String WRONG_NUMBER = "잘못된 수를 입력하셨습니다.";
잘 옮겨주셨습니다 👍  👏

2021-01-18 09:38 UTC, limmmee-bonjour commented on src/test/java/lotto/domain/LottoTicketTest.java
> +    @DisplayName("티켓에 번호가 포함되어있는지 여부 확인 true 반환 테스트")
DisplayName 잘 적용해주셨어요! 테스트 의도가 잘 드러나네요! 👍  💯  👏

2021-01-18 09:38 UTC, limmmee-bonjour commented on src/test/java/lotto/domain/PurchaseListTest.java
> +//                    .isEqualTo(manualTickets.get(manualTicketCount - i - 1));
불필요한 주석은 지워주는게 좋습니다 :)

2021-01-20 10:55 UTC, maireneu commented on src/main/java/lotto/controller/LottoGame.java
> +        lottoOutputView = new LottoOutputView(lottoDto);
그런 문제가 있었네요!  DTO를 필요할때 객체로 선언하는 방식으로 변경하였습니다.

2021-01-20 10:56 UTC, maireneu commented on src/main/java/lotto/domain/LottoDto.java
> +    private int bonusNumber;
DTO를 필요 요구사항에 따라 나누었습니다! 감사합니다.

2021-01-20 11:01 UTC, maireneu commented on src/main/java/lotto/domain/PurchaseList.java
> +            throw new IllegalArgumentException("잘못된 금액을 입력하셨습니다.");
해당부분에 대한 상수를 수정하였습니다!

2021-01-20 11:01 UTC, maireneu commented on src/main/java/lotto/domain/StatisticsType.java
> +    SIX (6, 2000000000, false );
쉼표가 안되어서 아쉬웠는데, 이런방법이 있었네요! 감사합니다.

2021-01-20 11:04 UTC, maireneu commented on src/main/java/lotto/domain/WinningLottoNos.java
> +import lotto.util.Validation;
DTO 또한 패키지를 변경하였습니다.

2021-01-20 11:04 UTC, maireneu commented on src/test/java/lotto/domain/LottoTicketTest.java
> +    @DisplayName("티켓에 번호가 포함되어있는지 여부 확인 true 반환 테스트")
감사합니다!

2021-01-20 11:04 UTC, maireneu commented on src/test/java/lotto/domain/PurchaseListTest.java
> +//                    .isEqualTo(manualTickets.get(manualTicketCount - i - 1));
불필요한 주석을 삭제하였습니다!

2021-01-20 14:46 UTC, limmmee-bonjour approved these changes
안녕하세요 Eli! 벨입니다 😄 
DTO 수정사항 잘 반영해주셨어요! 💯 
이전보다 코드가 깔끔해지고 관심사도 분리되고 구조도 좋습니다 👍 👏 
로또 미션하시느라 정말 고생 많이하셨어요! 몇가지 소소한 의견 드렸는데 다음 프로젝트에도 잊지 않으셨으면 좋겠어요 :)
궁금하신 점이 있으시면 언제든지 주저말고 DM 주셔요! 
고생 많으셨고 다음 프로젝트도 화이팅입니다!! 💪

2021-01-20 14:46 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/LottoDto.java
>  public class LottoDto {
LottoDto와 BuyingListDto 쪼개주셨네요 :) 👍 💯  
훨씬 더 깔끔해지고 관심사가 분리되었어요!

2021-01-20 14:46 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/LottoDto.java
> +    private WinningLottoNos WinningLottoNos;
멤버변수의 첫글자는 소문자로 맞춰주시는게 좋을 것 같아요~ 😉

2021-01-20 14:46 UTC, limmmee-bonjour commented on src/main/java/lotto/controller/LottoGame.java
> +        BuyingListDto buyingListDto = inputMoneyAndTicketCount();                       // 로또 티켓 구입 실행
Dto를 전역변수에서 멤버변수로! 좋습니다 👍 💯 👏

2021-01-20 14:46 UTC, limmmee-bonjour commented on src/main/java/lotto/domain/StatisticsType.java
> +    SIX (6, 2_000_000_000, false );
가독성이 높아졌어요 👏 👏

2021-01-20 14:46 UTC, limmmee-bonjour commented on src/main/java/lotto/exception/WrongMoneyInputException.java
> +public class WrongMoneyInputException extends RuntimeException {
오 Exception도 새로 정의해주셨네요!! 👍

2021-01-20 14:46 UTC, limmmee-bonjour commented on src/main/java/lotto/dto/LottoDto.java
> +    private lotto.domain.WinningLottoNos WinningLottoNos;
lotto.domain (패키지명)을 따로 적어주신 이유가 있을까요? 🤔

2021-01-20 14:47 UTC, merged