[bmo.adventure 이원우] 로또 step2  pr요청드립니다.
NewKrew2021/java-lotto-kakao pull request #72
Opened 2021-01-14 18:54 UTC by dddfff22

자세한 설명 감사합니다 ㅠㅠ
이번 step2로 오면서 LottoGeneratorService를 제거하고 권한을 Lotto로 위임했습니다.
Amount에 수동구매 개수필드를 추가하면서 setter와 비슷한 역활을 하는 메서드를 추가했는데 이부분은 괜찮을까요?

2021-01-15 10:49 UTC, findstar requested changes
안녕하세요, 제임스 입니다. 
코드가 점점 개선되고 있습니다. 💯 질문 주신것과 같이
수동 구매 수량과, 자동 구매 수량을 획득하는 부분에 대해서 코멘트 남겼습니다. 
두개의 Lottos 를 하나로 만드는 부분에 대해서 고민해봐주세요. 
그럼 계속 화이팅입니다.

덧) 코드 스타일링을 주의해주세요. Intellij 의 reformat 기능을 참고해주세요 😄 
https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html

2021-01-15 10:49 UTC, findstar commented on src/main/java/lotto/domain/Amount.java
> +        this.autoAmount=this.autoAmount-manualAmount;
코드 스타일은 계속 신경써주세요 auto reformat 만 해도 충분히 스타일이 좋아집니다 😄

2021-01-15 10:49 UTC, findstar commented on src/main/java/lotto/domain/Amount.java
> +    public void buyManualLotto(int manualAmount){
별도로 수동 구매 수량을 전달하는 부분이 고민이라면,
로또 구입금액 입력 데이터와 수동 구매 수량 입력 데이터를 가지는 클래스로 Amount 를 역할을 변경해 볼수도 있겠네요.

2021-01-15 10:49 UTC, findstar commented on src/main/java/lotto/controller/LottoController.java
> +    public Lottos buyAutoLotto(Amount amount,Lottos lottos) {
수동 구매 Lotts 와 자동 구매 Lottos 를 합칠 수 있는 메서드를 추가해보면 어떨까요?

2021-01-15 10:49 UTC, findstar commented on src/main/java/lotto/domain/LottoNumber.java
> +    public static List<LottoNumber> generateLottoNumbers(int amount) {
LottoNumber 에서 Lotto 에 의존하는 부분이 개선되었네요 💯

2021-01-16 12:42 UTC, dddfff22 commented on src/main/java/lotto/controller/LottoController.java
> +    public Lottos buyAutoLotto(Amount amount,Lottos lottos) {
이 부분을 작성할때 Lottos에서 private final List<Lotto> lottos;를 합치려면 get를 이용해서 가져와야한다고 생각했는데, 수동 구매와 자동구매 모두 Lottos 클래스이니 .lottos를 이용해서 가져올수 있다는 생각을 못했습니다 ㅠㅠ

2021-01-16 12:44 UTC, dddfff22 commented
바쁘실텐데도 항상 많은 코멘트 남겨주셔서 감사합니다 ㅠㅠ
로또를 합치는 로직을 구현하면서 자바에 대한 이해도가 부족함을 느꼈네요, 둘다 Lottos.class여서 상대방에게 객체를 넘겨주고  .lottos를 이용해서 접근가능하다는 생각을 못했었어요ㅠㅠ

2021-01-18 01:11 UTC, findstar approved these changes
안녕하세요 피드백 잘 반영해주셨네요. 
수고 많으셨습니다. 
아직 자바가 익숙하지 않으셨다고 했는데요
앞서 알려드린 부분들을 계속 연습하다 보면 
다른 미션에서도 충분히 좋은 코드를 작성하실 수 있습니다 👍 
로또 미션 진행하시느라 수고 많으셨습니다. 
PR 은 머지하겠습니다. 
다른 궁금한 점이 있다면 언제든지 DM 으로 연락해주세요.

2021-01-18 01:11 UTC, findstar commented on src/main/java/lotto/domain/Amount.java
> +    public void buyManualLotto(int manualAmount) {
내부에서만 사용되는 메서드는 private 으로 지정해야 합니다 😄

2021-01-18 01:11 UTC, findstar commented on src/main/java/lotto/domain/Amount.java
> +    public Amount(int money, int manualAmount) {
구입금액과 수동 수량을 입력받는 클래스로 변경되었군요.

2021-01-18 01:11 UTC, findstar commented on src/main/java/lotto/domain/Amount.java
> +        return autoAmount;
수동 구매 수량을 기준으로 자동 구매 수량을 얻는 방법 좋습니다 💯

2021-01-18 01:11 UTC, findstar commented on src/main/java/lotto/domain/Lottos.java
> +    public void appendLottos(Lottos newLottos) {
두개의 Lottos 를 합칠 수 있도록 개선되었네요. 💯

2021-01-18 01:11 UTC, merged