[pharrell.mp3 민필규] 로또 자동에 대해 PR 요청드립니다.
NewKrew2021/java-lotto-kakao pull request #9
Opened 2021-01-07 17:07 UTC by pilgyumin

안녕하세요! pharrell_(퍼렐,민필규)입니다.

로또 자동(1차)에 대해 개발한 코드에 대해 PR 요청드리겠습니다.

이번 프로젝트는 자동차 경주때 받은 피드백을 바탕으로 더 좋은 코드를 짜기 
위해 노력하였습니다.

기존에 잘 사용하지 않던 스트림도 사용해보았고, 최대한 TDD 방식을 지키려고 노력하였습니다.

이번에 TDD방식으로 개발하면서 이슈라고 생각했던 점은 해당 방식으로 진행했을 때 나중에 사용하지
않는 메소드가 발생한 점이었습니다.

사용하지 않는 메소드가 구현되지 않는 리뷰어분의 팁이 있다면 노티 부탁드리겠습니다.

감사합니다.

2021-01-08 03:20 UTC, ljh131 requested changes
남긴 커멘트들을 참고해서 객체들의 역할이 명확하고 많은 일을 하지 않도록 잘 생각해보시고 수정해보시면 좋겠습니다.
질문에 대한 답변은 별도로 달겠습니다.

2021-01-08 03:20 UTC, friediceday commented on src/main/java/domain/LottoRank.java
> +    FIFTH(Arrays.asList(3), Arrays.asList(true, false), new BigDecimal("5000"), "3개 일치 (5000원)- "),
BigDecimal에 스트링을 넘기는 이유가 있나요?

2021-01-08 03:20 UTC, friediceday commented on src/main/java/domain/LottoRank.java
> +    // 선언 순서 중요
선언순서가 중요하지 않도록 만들어보면 좋겠습니다. 주석으로 남긴다고 이런 제약사항이 보장되지 않으니까요. 코드에서 보장할 수 있도록 해야합니다.

2021-01-08 03:20 UTC, friediceday commented on src/main/java/domain/Lotto.java
> +    private int bonusBall;
이러면 클래스가 사실상  - 보너스볼이 있는 경우 / 없는 경우 - 두 가지 역할을 하게되는데요. 보너스볼이 없는 구매한 번호와 보너스볼이 있는 추첨번호만 비교하게 되어있는 것도 아니고요. 이런 부분에 대한 고려가 필요하지 않을까요?

2021-01-08 03:20 UTC, friediceday commented on src/main/java/domain/Lotto.java
> +        randomPool = new ArrayList<>();
로또번호가 스스로 번호를 생성하는건 너무 많은 일을 하고 있는 것 같아요. 좋은 방법을 고민해보면 좋겠습니다.

2021-01-08 03:20 UTC, friediceday commented on src/main/java/domain/Lotto.java
> +    private List<Integer> lottoBalls;
요구사항 `규칙 3: 모든 원시값과 문자열을 포장한다.`가 그냥 Integer나 BigDecimal을 쓰라는 얘기가 아닐 것입니다.
로또 번호라는 특성을 잘 나타낼 수 있는 역할을 만드는게 어떤가요?

2021-01-08 03:20 UTC, friediceday commented on src/main/java/view/LottoProgramView.java
> +    public Lotto getWinningLotto() {
뷰에서 직접 생성하기보단, 뷰는 raw한 입력만 담당하고 도메인 로직을 담당하는 누군가가 생성 해주면 좋을 것 같아요.

2021-01-08 03:20 UTC, friediceday commented on src/main/java/domain/Lotto.java
> +        bonusBall = randomPool.get(LOTTO_COUNT + 1);
구매한 로또에서는 보너스볼이 없지 않나요?

2021-01-08 03:20 UTC, friediceday commented on src/main/java/domain/LottoRank.java
> +    FIFTH(Arrays.asList(3), Arrays.asList(true, false), new BigDecimal("5000"), "3개 일치 (5000원)- "),
그리고 보너스볼 여부를 true, false 이렇게 두개 넣어야 한다는건 직관적이지 않아보여요.

2021-01-08 03:20 UTC, friediceday commented on src/main/java/domain/Lottos.java
> +                String.valueOf(
이런 과정은 불필요할 것 같아요. 그런데 BigDecimal을 꼭 써야하는지도 궁금하고요.

2021-01-08 03:20 UTC, friediceday commented on src/main/java/domain/LottoRank.java
> +    FIFTH(Arrays.asList(3), Arrays.asList(true, false), new BigDecimal("5000"), "3개 일치 (5000원)- "),
rightCounts도 꼭 리스트로 받아야 하나요?

2021-01-08 03:20 UTC, ljh131 commented on src/main/java/domain/Lottos.java
> +    public Lottos(int totalCount) {
테스트용으로는 다른 생성자를 쓰는데, 실제로는 이걸 써요.
테스트되는 코드가 실제로도 실행되는게 좋지 않을까요?

2021-01-08 04:09 UTC, ljh131 commented
```
이번에 TDD방식으로 개발하면서 이슈라고 생각했던 점은 해당 방식으로 진행했을 때 나중에 사용하지
않는 메소드가 발생한 점이었습니다.

사용하지 않는 메소드가 구현되지 않는 리뷰어분의 팁이 있다면 노티 부탁드리겠습니다.
```
-> 왜 그런일이 발생했을까요? 테스트용 따로, 실행용 따로인게 가장 크지 않을까 싶습니다. 테스트하는 코드가 실제 동작하는 코드가 되어야 합니다. 물론 100% 가능한 것은 아닙니다. 랜덤, 입력 등등이 그렇죠. 그럼 이런 부분은 분리해서 테스트할 수 있어야 합니다. 그렇게 되면 실제 동작하는 코드와 다를바 없습니다.
유닛 테스트에서는 일부 세세한 부분을 테스트하기 위해 중간 결과 등을 가져오고 싶을때도 있습니다. 그런 검증이 필수라면 테스트 전용 메서드가 들어가도 좋다고 생각합니다.

2021-01-11 06:25 UTC, pilgyumin commented on src/main/java/domain/LottoRank.java
> +    FIFTH(Arrays.asList(3), Arrays.asList(true, false), new BigDecimal("5000"), "3개 일치 (5000원)- "),
1. BigDecimal에 스트링을 넘기는 이유가 있나요?
=> BigDecimal로 선언한 이유는 사용자가 구매하려는 금액이 정수의 범위를 넘어갈 수도 있다는 생각을 하여서 사용하였습니다. 그래서 Rank에 BigDecimal에 스트링으로 선언한 객체를 할당하여 사용하였습니다.
이번 스텝은 BigDecimal이 아닌 다른 형태로 구현하겠습니다,

2. 그리고 보너스볼 여부를 true, false 이렇게 두개 넣어야 한다는건 직관적이지 않아보여요.
=> 넵 리팩토링하겠습니다.

3. rightCounts도 꼭 리스트로 받아야 하나요?
=> 해당 부분은 기존에 아무것도 없을 때를 가정한 NONE이라는 부분도 enum에 구현되어 있었는데, 그때 rightCounts를 {0,1,2}로 정의하려고 리스트에 선언하였습니다. 이 부분은 리팩토링 진행하겠습니다.

2021-01-11 07:39 UTC, ljh131 commented on src/main/java/domain/LottoRank.java
> +    FIFTH(Arrays.asList(3), Arrays.asList(true, false), new BigDecimal("5000"), "3개 일치 (5000원)- "),
BigDecimal에 스트링을 넘기는 이유가 있나요?
-> 이 부분은 해당 라인이 new BigDecimal(5000)이어도 될 것 같은데 굳이 스트링으로 넣고있어서(다른 부분도 마찬가지) 질문드린 것이었습니다.

그리고 참고로 다른 커멘트에서도 Integer나 BigDecimal을 직접적으로 사용하기보다는 다른 객체로 래핑해서 쓰는게 좋겠다는 의미입니다.

2021-01-11 16:51 UTC, pilgyumin commented on src/main/java/domain/LottoRank.java
> +    // 선언 순서 중요
넵 해당 부분도 반영하겠습니다.

2021-01-11 17:04 UTC, pilgyumin commented on src/main/java/domain/Lotto.java
> +    private int bonusBall;
해당 부분을 구분하기 위해 당첨 로또와 구매 로또와 클래스를 분리하겠습니다.

2021-01-11 17:05 UTC, pilgyumin commented on src/main/java/domain/Lotto.java
> +        randomPool = new ArrayList<>();
로또번호를 랜덤으로 번호를 생성해주는 풀에서 할당 받는 방법으로 구현하겠습니다.

2021-01-11 17:06 UTC, pilgyumin commented on src/main/java/domain/Lottos.java
> +                String.valueOf(
넵 리팩토링하겠습니다!

2021-01-11 17:07 UTC, pilgyumin commented on src/main/java/domain/Lotto.java
> +        bonusBall = randomPool.get(LOTTO_COUNT + 1);
넵 구매 로또와 당첨 로또 클래스를 분리하겠습니다.

2021-01-11 17:26 UTC, pilgyumin commented on src/main/java/view/LottoProgramView.java
> +    public Lotto getWinningLotto() {
넵 분리해서 구현하겠습니다.

2021-01-11 17:31 UTC, pilgyumin commented on src/main/java/domain/Lottos.java
> +    public Lottos(int totalCount) {
네 실제 사용되는 생성자를 테스트에서도 사용하도록 구현하겠습니다,

2021-01-11 17:36 UTC, pilgyumin commented on src/main/java/domain/Lottos.java
> +    public Lottos(int totalCount) {
네 테스트 코드의 생성자와 프로덕션 코드의 생성자를 최대한 매칭시키겠습니다.

2021-01-11 17:56 UTC, pilgyumin commented on src/main/java/domain/Lotto.java
> +    private List<Integer> lottoBalls;
넵 로또 번호를 하나의 공으로 생각하여 Ball로 래핑하겠습니다,

2021-01-12 03:44 UTC, ljh131 reviewed
많이 개선된 것 같습니다. 이번 단계는 머지하겠습니다.
커멘트 드린 부분들은 생각해보시고 다음 단계에 반영해보시면 좋겠습니다.

2021-01-12 03:44 UTC, ljh131 commented on src/main/java/controller/LottoProgram.java
> +        if(buyAmount < 1000){
상수로 만들면 좋겠습니다

2021-01-12 03:44 UTC, ljh131 commented on src/main/java/domain/LottoRank.java
> +        if(sameCount(count,SECOND) && matchBonusBall){
enum값에 보너스볼 여부를 선언하고, enum 값에 따라서 처리할 수 있으면 더 좋지 않을까요?

2021-01-12 03:44 UTC, ljh131 commented on src/main/java/domain/LottoStatistics.java
> +                    statisticsResult.append(lottoRank.getResultPrefix());
functional 에 side effect가 있으면 안좋을 것 같습니다. 사이드 이펙트가 없도록 수정하면 어떨까요?

2021-01-12 03:44 UTC, ljh131 commented on src/main/java/domain/RandomBallPool.java
> +        Collections.shuffle(randomPool);
스레드 세이프는 항상 유의하면 좋겠습니다.

2021-01-12 03:44 UTC, ljh131 commented on src/main/java/domain/LottoRank.java
> +        if(sameCount(count,FIRST)){
혹시 FIRST는 특별히 처리해야되는 이유가 있나요?

2021-01-12 03:44 UTC, ljh131 commented on src/main/java/domain/LottoRank.java
> +    NONE(2,  0, "3개 일치 (5000원)- "),
이름은 NONE인데 2는 뭐고 3개 일치는 뭔가요?

2021-01-12 03:44 UTC, merged

2021-01-12 04:53 UTC, pilgyumin commented on src/main/java/controller/LottoProgram.java
> +        if(buyAmount < 1000){
넵 상수 처리하겠습니다!

2021-01-12 05:11 UTC, pilgyumin commented on src/main/java/domain/LottoRank.java
> +        if(sameCount(count,FIRST)){
THIRD를 작성한다는 것이 잘못 작성하였습니다. 수정하겠습니다!

2021-01-12 05:17 UTC, pilgyumin commented on src/main/java/domain/LottoRank.java
> +    NONE(2,  0, "3개 일치 (5000원)- "),
NONE일 경우 0~2개 일치라고 작성해야 하는데 해당 부분을 실수로 변경하지 못하였습니다. 수정하겠습니다!

2021-01-12 05:20 UTC, pilgyumin commented on src/main/java/domain/RandomBallPool.java
> +        Collections.shuffle(randomPool);
넵 유의해서 사용하겠습니다.

2021-01-12 06:35 UTC, pilgyumin commented on src/main/java/domain/LottoStatistics.java
> +                    statisticsResult.append(lottoRank.getResultPrefix());
해당 부분으로 작성하였을 때 어떤 side effect가 나타날 수 있을까요??

2021-01-12 10:24 UTC, ljh131 commented on src/main/java/domain/LottoStatistics.java
> +                    statisticsResult.append(lottoRank.getResultPrefix());
펑셔널 프로그래밍에 대한 내용입니다.
https://livebook.manning.com/book/functional-programming-in-scala/chapter-1/

2021-01-12 15:42 UTC, pilgyumin commented on src/main/java/domain/LottoRank.java
> +        if(sameCount(count,SECOND) && matchBonusBall){
해당 피드백에 대해서 좋은 아이디어가 떠오르지 않는데, 혹시 어떤 방향으로 피드백 주신 거신지 알 수 있을까요??

2021-01-13 07:39 UTC, ljh131 commented on src/main/java/domain/LottoRank.java
> +        if(sameCount(count,SECOND) && matchBonusBall){
```
    FIFTH(3,  5000, "3개 일치 (5000원)- "),
```

예를들어 지금 위와 같이 선언되어있는데요, 각각 일치 개수, 상금, 결과 문자열입니다. 여기에 보너스볼 여부를 추가하면 SECOND 라는걸 메서드에서 알 필요 없이 enum 값 선언만 가지고 할 수 있다는 말이었습니다.

2021-01-13 14:27 UTC, pilgyumin commented on src/main/java/domain/LottoRank.java
> +        if(sameCount(count,SECOND) && matchBonusBall){
`SECOND(5,  30000000, true,"5개 일치, 보너스 볼 일치(30000000원)- "),`
`THIRD(5, 1500000, false,"5개 일치 (1500000원)- "),`

이렇게 보너스볼 여부를 boolean값으로 추가하였을 때 저 보너스볼 여부를 통해서 어떻게 로직을 사용할 지에 대한 아이디어가
떠오르지 않은 상황입니다!

혹시 생각하신 구현 방법을 코드나 설명으로 알 수 있을까요??